Repository Tencent/bk-cmdb, pull requests merged in 2018-11, with the labels that each got.

#1294 finished topo server related association refactor.
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apimachinery/objcontroller/association/api.go
  src/apimachinery/objcontroller/association/association.go
  src/apimachinery/objcontroller/objcontroller.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/association.go
  src/common/metadata/attribute.go
  src/common/metadata/object.go
  src/common/metadata/struct_tags.go
  src/common/util/valid.go
  src/scene_server/topo_server/core/inst/association.go
  src/scene_server/topo_server/core/inst/inst.go
  src/scene_server/topo_server/core/model/association.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/graphics.go
  src/scene_server/topo_server/core/operation/import_asst.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/types.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/graphics.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/object_association.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/objectcontroller/service/association_action.go
  src/source_controller/objectcontroller/service/common.go
  src/source_controller/objectcontroller/service/inst_action.go
  src/source_controller/objectcontroller/service/objectasst_action.go
Labels: demand, inner

#1311 delete is_pre check in the mainline topo operation.
  src/common/definitions.go
  src/scene_server/topo_server/core/model/object.go
Labels: inner, optimization

#1309 fix: instance validator
  scripts/Makefile
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/admin_server/upgrader/x18.10.10.01/pkg.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/validator/valid_basic.go
Labels: bug, inner

#1316 fix: update association upgrader
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: inner, optimization

#1319 topo 关联关系verb和字段调整。
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: inner, optimization

#1318 web server import object error, http reply multip json
  src/apimachinery/apiserver/api.go
  src/web_server/service/object.go
Labels: bug, inner

#1321 解决upgrader的default关联类型
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#1322 fix: upgrader update association type descriptions
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#1324 bugfix: fix a bug when update mainline object association
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apimachinery/rest/request.go
  src/common/definitions.go
  src/common/errInfo.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/source_controller/hostcontroller/service/host.go
Labels: bug, inner

#1330 association refactor, instance association export to excel
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  resources/language/default/import_instance.json
  resources/language/en/import_instance.json
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/common/condition/field.go
  src/common/definitions.go
  src/common/metadata/association.go
  src/common/metadata/common.go
  src/common/metadata/object.go
  src/common/metadata/page.go
  src/common/metadata/webserver.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/web_server/logics/association.go
  src/web_server/logics/excel.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/fields.go
  src/web_server/service/host.go
  src/web_server/service/inst.go
Labels: demand, inner

#1333 修改关联关系的BUG
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/graphics.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/object_association.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: bug, inner

#1334 support superadmin query
  src/common/definitions.go
  src/scene_server/topo_server/service/inst_business.go
Labels: demand, inner

#1336 fix: export instance bug issue #1335
  src/web_server/logics/excel.go
  src/web_server/logics/inst.go
  src/web_server/service/service.go
Labels: bug, inner

#1339 bugfix: fix a bug when delete mainline object association
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
Labels: bug, inner

#1340 import association
  src/common/condition/condition.go
  src/common/condition/condition_test.go
  src/common/condition/field.go
  src/common/condition/or.go
  src/common/condition/or_test.go
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/service/service.go
  src/web_server/logics/excel.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/fields.go
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
  src/web_server/service/host.go
  src/web_server/service/inst.go
Labels: demand, inner, optimization

#1341 cherry-pick from 3.1.1
  scripts/Makefile
  src/common/condition/field.go
  src/common/condition/types.go
  src/common/definitions.go
  src/common/metadata/association.go
  src/scene_server/admin_server/command/getter.go
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/validator/valid_basic.go
Labels: inner, optimization

#1344 bugfix: fix object controller instance association lost a field
  src/common/errInfo.go
  src/common/metadata/association.go
  src/source_controller/objectcontroller/service/instasst_action.go
Labels: bug, inner

#1332 解决导入拓扑时没删掉不含default字段的模块问题
  src/common/condition/field.go
  src/common/condition/types.go
  src/common/definitions.go
  src/scene_server/admin_server/command/getter.go
  src/scene_server/admin_server/command/import.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst_business.go
Labels: bug, inner

#1352 新增wiki文档
  docs/wiki/blueking-golang-code-conduct.pdf
  docs/wiki/community-link.md
  docs/wiki/community.md
  docs/wiki/container-support.md
  docs/wiki/contribute.md
  docs/wiki/faq.md
  docs/wiki/feature-plan.md
  docs/wiki/feature.md
  docs/wiki/img/contribute-flow.png
  docs/wiki/img/feature-flow.png
  docs/wiki/img/fork.png
  docs/wiki/img/image-check.png
  docs/wiki/img/pr-create.png
  docs/wiki/img/pr-finish.png
  docs/wiki/img/pr-submmit.png
  docs/wiki/issue.md
  docs/wiki/version-guidline.md
  src/common/condition/types.go
  src/scene_server/topo_server/core/operation/association.go
Labels: demand, inner

#1354 add wiki doc
  docs/CONTRIBUTING.md
  docs/wiki/blueking-golang-code-conduct.pdf
  docs/wiki/community-link.md
  docs/wiki/community.md
  docs/wiki/container-support.md
  docs/wiki/contribute.md
  docs/wiki/faq.md
  docs/wiki/feature-plan.md
  docs/wiki/feature.md
  docs/wiki/img/contribute-flow.png
  docs/wiki/img/feature-flow.png
  docs/wiki/img/fork.png
  docs/wiki/img/image-check.png
  docs/wiki/img/pr-create.png
  docs/wiki/img/pr-finish.png
  docs/wiki/img/pr-submmit.png
  docs/wiki/issue.md
  docs/wiki/version-guidline.md
Labels: demand, inner

#1357 optimize wiki doc about container support
  docs/wiki/container-support.md
Labels: inner, optimization

#1368 新增wiki首页用图片
  docs/wiki/img/cmdb_environment.png
  docs/wiki/img/cmdb_feature.png
  docs/wiki/img/cmdb_system.png
  docs/wiki/img/git_cmdb.png
  docs/wiki/img/join_us.png
Labels: inner, optimization

#1349 feature: 导入导出业务拓扑的关联改造
  src/scene_server/admin_server/command/export.go
  src/scene_server/admin_server/command/getter.go
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/command/types.go
Labels: inner, optimization

#1370 前端BUG修复及优化
  src/ui/config/index.js
  src/ui/src/assets/json/static-navigation.json
  src/ui/src/components/hosts/table/_quick-search.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/components/ui/form/associate-input.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/components/ui/selector/selector.vue
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/utils/tools.js
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/eventpush/pop.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/topology/index.vue
Labels: bug, demand, inner

#1371 mainline topo optimize
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
Labels: inner, optimization

#1372 POST method in createobject should put obj in body
  src/apimachinery/toposerver/object/obj.go
Labels: bug, outer

#1374 add two wiki's picture
  docs/wiki/img/Experience_mode.png
  docs/wiki/img/cmdb_architecture.png
Labels: demand, inner

#1375 change experience file name.
  docs/wiki/img/way_to_experience.png
Labels: demand, inner

#1377 修复前端实例查询部分参数错误的问题
  src/ui/src/components/hosts/table/_quick-search.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/topology/index.vue
Labels: bug, inner

#1392 code optimize
  src/common/metadata/association.go
  src/common/metadata/graphic.go
  src/framework/api/input.go
  src/framework/core/input/input_private.go
  src/framework/core/output/module/client/v3/inst.go
  src/framework/core/output/module/inst/iterator_inst.go
  src/framework/core/output/module/model/type.go
  src/scene_server/common/util/fields.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/graphics.go
  src/scene_server/topo_server/core/operation/inst_fields.go
Labels: inner, optimization

#1395 add IsPre field in association kind.
  src/common/metadata/association.go
Labels: demand, inner

#1398 feature: pre-defined association kind can not be deleted.
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/association.go
Labels: demand, inner

#1362 apiserver 目录结构调整
  src/api_server/app/server.go
  src/api_server/logics/v2/common/converter/converter.go
  src/api_server/logics/v2/common/defs/defs.go
  src/api_server/logics/v2/common/utils/utils.go
  src/api_server/logics/v2/common/utils/utils_test.go
  src/api_server/logics/v2/fileds.go
  src/api_server/logics/v2/logics.go
  src/api_server/logics/v2/search.go
  src/api_server/logics/v2/topo.go
  src/api_server/logics/v2/userapi.go
  src/api_server/service/import.go
  src/api_server/service/v2/addhost.go
  src/api_server/service/v2/application.go
  src/api_server/service/v2/gse.go
  src/api_server/service/v2/host.go
  src/api_server/service/v2/module.go
  src/api_server/service/v2/plat.go
  src/api_server/service/v2/process.go
  src/api_server/service/v2/property.go
  src/api_server/service/v2/search.go
  src/api_server/service/v2/searchext.go
  src/api_server/service/v2/service.go
  src/api_server/service/v2/set.go
  src/api_server/service/v2/userapi.go
Labels: inner, optimization

#1402 add ForeignKeyType
  src/common/definitions.go
  src/common/util/conv.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/validator/valid_basic.go
Labels: demand, inner

#1397 fix commit so support #1394
  src/web_server/app/server.go
  src/web_server/middleware/login.go
  src/web_server/middleware/user/public.go
  src/web_server/middleware/user/user.go
  src/web_server/service/login.go
  src/web_server/service/service.go
  src/web_server/service/user.go
Labels: demand, inner

#1409 refactor:[v3.3.x]host hand over the business module to resource pool tips
  src/common/mapstr/mapstr.go
  src/common/mapstr/mapstr_test.go
  src/scene_server/host_server/service/module.go
Labels: inner, optimization

#1414 模型拓扑图样式调整
  src/ui/src/views/model-manage/topo.vue
Labels: inner, optimization

#1415 模型拓扑图样式调整
  src/ui/src/views/model-manage/topo.vue
Labels: inner, optimization

#1424 feature:webserver session use cluster issue #1422
  src/web_server/logics/httpheader.go
  src/web_server/middleware/auth/auth_util.go
Labels: demand, inner

#1425 feature:webserver session use cluster issue #1422
  src/web_server/logics/httpheader.go
  src/web_server/middleware/auth/auth_util.go
Labels: demand, inner

#1426 update preset object association
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/storage/dal/mongo/mgo_mongo.go
Labels: bug, inner

#1430 V3.3.x 修复hostsearch 排序字段失效及云区域适配问题
  src/api_server/logics/v2/common/converter/converter.go
  src/scene_server/host_server/logics/hostsearch.go
Labels: bug, inner

#1429 V3.2.x 问题修复
  src/api_server/logics/v2/common/converter/converter.go
  src/common/mapstr/mapstr.go
  src/common/mapstr/mapstr_test.go
  src/scene_server/host_server/logics/hostsearch.go
Labels: bug, inner

#1431 bugfix: can not create new instance for a 1:1 association.
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/association.go
Labels: bug, inner

#1432 feature: an associated object can not be deleted。
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/object.go
Labels: demand, inner

#1433 add two new check ruels about association.
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/object.go
Labels: bug, demand, inner

#1438 解决业务拓扑被异常转移到其他业务问题 to 3.1.0 #1437
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
Labels: bug, inner

#1434 a predefined object association can not be updated or deleted.
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/association.go
Labels: inner, optimization

#1442 导航风格调整与关联关系问题修复
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.eot
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/assets/images/logo.svg
  src/ui/src/assets/json/icon-hex-map.json
  src/ui/src/assets/json/static-navigation.json
  src/ui/src/assets/scss/model-manage.scss
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/store/modules/api/user-custom.js
  src/ui/src/store/modules/global.js
  src/ui/src/utils/tools.js
  src/ui/src/views/index/children/classify-item.vue
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/model-manage/_business-topo.vue
  src/ui/src/views/model-manage/children/_property-group.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/group.vue
  src/ui/src/views/model-manage/relation-type/index.vue
  src/ui/src/views/model-manage/relation.vue
  src/ui/src/views/model-manage/topo-detail/display.vue
  src/ui/src/views/model-manage/topo-detail/relation-detail.vue
  src/ui/src/views/model-manage/topo-detail/relation.vue
  src/ui/src/views/model-manage/topo.vue
  src/ui/src/views/permission/business.vue
  src/ui/src/views/permission/role.vue
  src/ui/static/svg/cc-nav-audit.svg
  src/ui/static/svg/cc-nav-authority.svg
  src/ui/static/svg/cc-nav-collection.svg
  src/ui/static/svg/cc-nav-detective.svg
  src/ui/static/svg/cc-nav-model.svg
  src/ui/static/svg/cc-nav-resource.svg
Labels: bug, demand, inner, optimization

#1440 解决业务拓扑被异常转移到其他业务问题 to master #1437
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
Labels: bug, inner

#1444 导航风格调整及关联关系优化与问题修复
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/storage/dal/mongo/mgo_mongo.go
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.eot
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/assets/images/logo.svg
  src/ui/src/assets/json/icon-hex-map.json
  src/ui/src/assets/json/static-navigation.json
  src/ui/src/assets/scss/model-manage.scss
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/store/modules/api/user-custom.js
  src/ui/src/store/modules/global.js
  src/ui/src/utils/tools.js
  src/ui/src/views/index/children/classify-item.vue
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/model-manage/_business-topo.vue
  src/ui/src/views/model-manage/children/_property-group.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/group.vue
  src/ui/src/views/model-manage/relation-type/index.vue
  src/ui/src/views/model-manage/relation.vue
  src/ui/src/views/model-manage/topo-detail/display.vue
  src/ui/src/views/model-manage/topo-detail/relation-detail.vue
  src/ui/src/views/model-manage/topo-detail/relation.vue
  src/ui/src/views/model-manage/topo.vue
  src/ui/src/views/permission/business.vue
  src/ui/src/views/permission/role.vue
  src/ui/static/svg/cc-nav-audit.svg
  src/ui/static/svg/cc-nav-authority.svg
  src/ui/static/svg/cc-nav-collection.svg
  src/ui/static/svg/cc-nav-detective.svg
  src/ui/static/svg/cc-nav-model.svg
  src/ui/static/svg/cc-nav-resource.svg
Labels: bug, demand, inner, optimization

#1447 minor: 样式调整
  src/ui/src/assets/scss/model-manage.scss
  src/ui/src/views/model-manage/topo.vue
Labels: demand, inner

#1455 Apiserver apimchiney supplier
  src/api_server/logics/v2/common/converter/converter.go
  src/api_server/logics/v2/common/utils/utils.go
  src/api_server/service/v2/host.go
  src/api_server/service/v2/module.go
  src/api_server/service/v2/process.go
  src/api_server/service/v2/search.go
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/apimachinery/procserver/openapi/api.go
  src/apimachinery/procserver/openapi/openapi.go
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/module.go
  src/apimachinery/toposerver/inst/set.go
  src/apimachinery/toposerver/openapi/api.go
  src/apimachinery/toposerver/openapi/openapi.go
  src/common/util/ownerutil.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/logics/plat.go
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/operation/object.go
  src/source_controller/objectcontroller/service/inst_action.go
Labels: inner, optimization

#1463 Master cherry pick v3.2.x to master
  src/scene_server/topo_server/core/operation/import_association.go
  src/web_server/middleware/login.go
Labels: bug, demand, inner

#1461 V3.2.x 关联关系导入调整
  src/scene_server/topo_server/core/operation/import_association.go
  src/web_server/middleware/login.go
Labels: bug, demand, inner

#1456 mege master
  scripts/Makefile
  src/api_server/logics/v2/common/converter/converter.go
  src/api_server/logics/v2/common/utils/utils.go
  src/api_server/service/v2/host.go
  src/api_server/service/v2/module.go
  src/api_server/service/v2/process.go
  src/api_server/service/v2/search.go
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/apimachinery/procserver/openapi/api.go
  src/apimachinery/procserver/openapi/openapi.go
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/module.go
  src/apimachinery/toposerver/inst/set.go
  src/apimachinery/toposerver/openapi/api.go
  src/apimachinery/toposerver/openapi/openapi.go
  src/common/util/ownerutil.go
  src/common/version/version.go
  src/scene_server/admin_server/upgrader/x08.09.13.01/addOperationLogIndex.go
  src/scene_server/admin_server/upgrader/x08.09.13.01/pkg.go
  src/scene_server/admin_server/upgrader/x08.09.13.01/reconcileGroupPrivilege.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/logics/plat.go
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/operation/object.go
  src/source_controller/objectcontroller/service/inst_action.go
Labels: inner

#1467 模型拓扑交互更新
  src/ui/build/webpack.base.conf.js
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.eot
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/assets/json/icon-hex-map.json
  src/ui/src/components/model-manage/_choose-icon.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/model-association/_detail.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/group.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/model-topology/index.vue
  src/ui/static/svg/cc-line.svg
Labels: inner, optimization

#1470 导航样式微调
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/components/layout/header.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/mixins/classify.js
  src/ui/src/router/index.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/group.vue
  src/ui/src/views/model-topology/index.vue
  src/ui/src/views/permission/business.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/topology/index.vue
  src/ui/static/svg/cc-nav-toggle.svg
Labels: inner, optimization

#1469 前端BUG修复
  src/ui/src/components/import/import.vue
  src/ui/src/components/ui/form/enum.vue
Labels: bug, inner

#1471 模型字段增加导入功能
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/model-manage/children/field-detail/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/index.vue
Labels: demand, inner

#1457 新增模型分组唯一
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apimachinery/objcontroller/objcontroller.go
  src/apimachinery/objcontroller/unique/api.go
  src/apimachinery/objcontroller/unique/unique.go
  src/common/blog/blog.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/eventserver.go
  src/common/metadata/time.go
  src/common/metadata/unique.go
  src/common/tablenames.go
  src/common/util/http.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/v3.0.8/addDefauleApp.go
  src/scene_server/admin_server/upgrader/v3.0.8/addPresetObjects.go
  src/scene_server/admin_server/upgrader/v3.0.8/objAttDescData.go
  src/scene_server/admin_server/upgrader/v3.1.0-alpha.2/addBkStartParamRegex.go
  src/scene_server/admin_server/upgrader/x18.11.19.01/pkg.go
  src/scene_server/admin_server/upgrader/x18.11.19.01/reconcilAsstID.go
  src/scene_server/admin_server/upgrader/x18.11.19.01/reconcilUnique.go
  src/scene_server/event_server/service/subscription.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/unique.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/scene_server/topo_server/service/unique.go
  src/scene_server/validator/type.go
  src/scene_server/validator/valid_basic.go
  src/scene_server/validator/valid_unique.go
  src/source_controller/objectcontroller/service/object_unique.go
  src/source_controller/objectcontroller/service/objectatt_action.go
  src/source_controller/objectcontroller/service/service.go
Labels: demand, inner

#1476 fix: should query common association type
  src/source_controller/objectcontroller/service/association_action.go
Labels: bug, inner

#1477 V3.3.x 登录，业务新加supplier_id字段
  resources/language/default/property.json
  resources/language/en/property.json
  src/common/definitions.go
  src/common/metadata/hostlock.go
  src/common/metadata/webserver.go
  src/common/util/lib.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.10.30.02/biz_supplier_id.go
  src/scene_server/admin_server/upgrader/x18.10.30.02/pkg.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/source_controller/hostcontroller/app/server.go
  src/source_controller/hostcontroller/logics/hostlock.go
  src/web_server/logics/httpheader.go
  src/web_server/middleware/login.go
  src/web_server/middleware/user/plugins/method/self/userinfo.go
  src/web_server/middleware/user/public.go
  src/web_server/service/user.go
Labels: demand, inner

#1464 fix: should query common association type
  src/source_controller/objectcontroller/service/association_action.go
Labels: bug, inner

#1480 模型管理更新
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/index.vue
Labels: bug, inner

#1479 bugfix:修复删除最近浏览记录导致所有记录被清空的问题
  src/ui/src/views/index/children/recently.vue
Labels: bug, inner
