Repository Tencent/bk-cmdb, pull requests merged in 2018-12, with the labels that each got.

#1490 fix: getInstDataByID should return not found error if the id not exists
  src/scene_server/validator/valid_unique.go
Labels: bug, inner

#1492 长短字符支持输入@和#号
  src/ui/src/setup/validate.js
Labels: demand, inner

#1493 增加coreservice 框架代码
  src/common/metadata/common.go
  src/common/metadata/core_service.go
  src/common/metadata/create.go
  src/common/metadata/delete.go
  src/common/metadata/query.go
  src/common/metadata/result.go
  src/common/metadata/update.go
  src/common/types/serverInfo.go
  src/common/universalsql/field.go
  src/common/universalsql/mongo/condition.go
  src/common/universalsql/mongo/create_statement.go
  src/common/universalsql/mongo/delete_statement.go
  src/common/universalsql/mongo/element.go
  src/common/universalsql/mongo/result.go
  src/common/universalsql/mongo/select_statement.go
  src/common/universalsql/mongo/statement.go
  src/common/universalsql/mongo/table.go
  src/common/universalsql/mongo/update_statement.go
  src/common/universalsql/type.go
  src/common/universalsql/universalsql.go
  src/common/universalsql/universalsql_test.go
  src/source_controller/coreservice/Makefile
  src/source_controller/coreservice/app/options/options.go
  src/source_controller/coreservice/app/options/options_test.go
  src/source_controller/coreservice/app/server.go
  src/source_controller/coreservice/core/association/association.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/association/kind.go
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/type.go
  src/source_controller/coreservice/main.go
  src/source_controller/coreservice/readme.md
  src/source_controller/coreservice/service/association.go
  src/source_controller/coreservice/service/health.go
  src/source_controller/coreservice/service/instances.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/coreservice/service/types.go
Labels: demand, inner

#1489 doc: update gopath desc
  docs/overview/source_compile.md
Labels: inner, optimization

#1505 V3.2.x duplicate index 修复主机克隆的时候，asset_id重复
  src/scene_server/host_server/logics/phpapi.go
Labels: demand, inner

#1507 修改返回结构，增加主流程调用逻辑与输入参数解析
  src/common/metadata/core_service.go
  src/common/metadata/create.go
  src/common/metadata/delete.go
  src/common/metadata/result.go
  src/common/metadata/update.go
  src/common/universalsql/mongo/condition.go
  src/common/universalsql/mongo/create_statement.go
  src/common/universalsql/mongo/delete_statement.go
  src/common/universalsql/mongo/element.go
  src/common/universalsql/mongo/result.go
  src/common/universalsql/mongo/select_statement.go
  src/common/universalsql/mongo/statement.go
  src/common/universalsql/mongo/table.go
  src/common/universalsql/mongo/update_statement.go
  src/common/universalsql/type.go
  src/common/universalsql/universalsql.go
  src/common/universalsql/universalsql_test.go
  src/source_controller/coreservice/core/association/association.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/association/kind.go
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/type.go
  src/source_controller/coreservice/service/association.go
  src/source_controller/coreservice/service/instances.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/service.go
Labels: demand, inner

#1516 V3.2.x bug修复
  src/api_server/logics/v2/common/converter/converter.go
  src/api_server/logics/v2/topo.go
  src/api_server/service/v2/application.go
  src/api_server/service/v2/host.go
  src/api_server/service/v2/module.go
  src/api_server/service/v2/plat.go
  src/api_server/service/v2/set.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
  src/web_server/service/host.go
  src/web_server/service/inst.go
Labels: bug, inner

#1518 fefector: 更新日志级别
  src/api_server/logics/v2/common/converter/converter.go
  src/api_server/logics/v2/fileds.go
  src/api_server/logics/v2/topo.go
  src/api_server/service/v2/application.go
  src/api_server/service/v2/module.go
  src/api_server/service/v2/plat.go
  src/api_server/service/v2/set.go
  src/api_server/service/v3/service.go
  src/apimachinery/discovery/server.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/logics/phpapi_gse.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/logics/phpapi_searchhost.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/proc_server/logics/host.go
  src/scene_server/proc_server/logics/topo.go
  src/scene_server/proc_server/proc_service/service/openapi.go
  src/scene_server/proc_server/proc_service/service/procdetail.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/topo_server/app/server.go
  src/source_controller/hostcontroller/logics/hostlock.go
  src/source_controller/hostcontroller/service/favourite.go
  src/source_controller/hostcontroller/service/user.go
  src/source_controller/proccontroller/service/module.go
  src/source_controller/proccontroller/service/procinstance.go
  src/source_controller/proccontroller/service/template.go
  src/web_server/logics/host.go
  src/web_server/logics/privilege.go
  src/web_server/middleware/user/owner.go
  src/web_server/middleware/user/plugins/method/self/userinfo.go
Labels: inner, optimization

#1519 V3.2.x 修复登录供应商ID使用错误的问题
  src/web_server/middleware/login.go
Labels: bug, inner

#1512 MapStr and struct interconvert
  src/common/mapstr/mapstr.go
  src/common/mapstr/struct_tags.go
  src/common/metadata/association.go
  src/common/metadata/attribute.go
  src/common/metadata/classification.go
  src/common/metadata/group.go
  src/common/metadata/object.go
  src/common/metadata/privilege.go
  src/scene_server/topo_server/core/model/association.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/classification.go
  src/scene_server/topo_server/core/model/group.go
  src/scene_server/topo_server/core/model/object.go
Labels: demand, inner, optimization

#1522 实现新建模型分类的接口 #1495
  src/common/metadata/result.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/type.go
Labels: demand, inner

#1527 修改条件入参 #1503
  src/common/metadata/query.go
  src/common/universalsql/mongo/condition.go
Labels: inner, optimization

#1521 网络发现bugfix
  src/ui/src/views/network-config/collect.vue
  src/ui/src/views/network-discovery/confirm.vue
  src/ui/src/views/network-discovery/details.vue
Labels: bug, inner

#1529 feature: 普通用户导航视图
  src/ui/src/components/hosts/filter/_filter-field-operator.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/router/index.js
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/store/modules/api/user-authority.js
  src/ui/src/store/modules/api/user-privilege.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/_property-group.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.vue
  src/ui/src/views/permission/business.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/process/module.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/topology/index.vue
Labels: demand, inner

#1532 bugfix: bad code 导航计算属性循环引用
  src/ui/src/components/layout/nav.vue
Labels: bug, inner

#1536 完善universalsql 支持从复杂条件结构解析生成 universal 定义的条件对象 # 1499
  src/common/mapstr/mapstr.go
  src/common/universalsql/mongo/condition.go
  src/common/universalsql/mongo/condition_private.go
  src/common/universalsql/mongo/condition_test.go
  src/common/universalsql/type.go
Labels: inner, optimization

#1534 coreservice 常量定义和apimachinery封装
  src/apimachinery/coreservice/association/api.go
  src/apimachinery/coreservice/association/association.go
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/instance/api.go
  src/apimachinery/coreservice/instance/instance.go
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/model/model.go
  src/common/metadata/core_service.go
  src/common/metadata/create.go
  src/common/metadata/query.go
  src/common/metadata/result.go
  src/common/metadata/update.go
Labels: demand, inner, optimization

#1540 模型拓扑bugfix
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/model-topology/index.vue
Labels: bug, inner

#1542 minor: add get privilege authority to get associatioin kind info.
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/types/types.go
Labels: demand, inner

#1543 fix: 修改分组唯一时要重算存量模型实例唯一性
  src/common/blog/blog.go
  src/common/definitions.go
  src/scene_server/topo_server/core/model/unique.go
  src/source_controller/objectcontroller/service/object_unique.go
  src/storage/dal/mongo/mgo_mongo.go
  src/storage/dal/mongo/mock_mongo.go
  src/storage/dal/mongo/rpc_mongo.go
  src/storage/dal/rdb.go
Labels: bug, inner

#1544 fix: check unique should include bk_obj_id
  src/source_controller/objectcontroller/service/object_unique.go
Labels: bug, inner

#1546 新增普通用户的模型查询权限
  src/scene_server/topo_server/service/service_initfunc.go
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/types/types.go
Labels: demand, inner

#1547 minor: delete mistake code
  src/scene_server/topo_server/service/service_initfunc.go
Labels: inner, optimization

#1549 bugfix: fix a config bug about business topo max value.
  src/scene_server/topo_server/app/server.go
Labels: bug, inner

#1541 finish code about model management logic #1494
  src/common/metadata/query.go
  src/common/metadata/result.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/classification_crud.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/dependences.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_crud.go
  src/source_controller/coreservice/service/service.go
Labels: demand, inner, optimization

#1552 3.1.0 bugfix
  src/ui/src/pages/hosts/hosts.vue
  src/ui/src/pages/organization/object.vue
Labels: bug, inner

#1551 V3.1.0 bugfix
  src/ui/src/common/json/timezone.json
  src/ui/src/common/scss/common.scss
  src/ui/src/components/filter/screening.vue
  src/ui/src/components/history/details.vue
  src/ui/src/pages/eventpush/eventpush.vue
  src/ui/src/pages/hosts/hosts.vue
  src/ui/src/pages/topology/topology.vue
Labels: bug, inner

#1554 bugfix-3.1.0:修复无业务权限时可以刷新查询主机信息的问题
  src/ui/src/pages/hosts/hosts.vue
Labels: bug, inner

#1548 coreservice apimachinery mock and test case.
  src/apimachinery/clientset.go
  src/apimachinery/clientset_coreservice_inst_test.go
  src/apimachinery/clientset_coreservice_model_test.go
  src/apimachinery/coreservice/association/api.go
  src/apimachinery/coreservice/association/association.go
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/instance/api.go
  src/apimachinery/coreservice/instance/instance.go
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/model/model.go
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/discovery_mock.go
  src/common/metadata/create.go
Labels: demand, inner

#1553 bugfix: 事件推送推送测试参数错误
  src/ui/src/views/eventpush/pop.vue
Labels: bug, inner

#1557 feature:change count type int64=>uint64
  src/source_controller/coreservice/core/association/dependences.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/association/kind.go
Labels: optimization

#1561 bugfix: fix create association with invalid id problem.
  src/common/metadata/object_controller.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/service/object_association.go
Labels: bug, inner

#1563 fix: 新建主线模型时，主线拓扑实例中缺少默认的实例字段属性 #1562
  src/scene_server/topo_server/core/operation/association_mainline_object.go
Labels: bug, inner

#1566 fix： fix bug in issue #1565, topo graph missing fields lead to panic
  src/common/metadata/graphic.go
  src/common/metadata/graphic_test.go
  src/scene_server/topo_server/core/operation/graphics.go
Labels: bug, inner

#1567 fix: v2 getHostAppByCompanyId api get host panic issue #1564
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/logics/phpapi_searchhost.go
  src/scene_server/host_server/service/phpapi.go
Labels: inner, optimization

#1550 bugfix: 修复模块可以在不同业务下可重复问题
  scripts/init.py
  src/apimachinery/rest/request.go
  src/common/tablenames.go
  src/scene_server/admin_server/upgrader/x18.11.19.01/reconcil_unique.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/web_server/middleware/login.go
Labels: bug, inner

#1572 bugfix: 批量导入模型实例时，实例名称相同会被覆盖。
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/common/metadata/graphic.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst.go
  src/source_controller/objectcontroller/service/topographics.go
Labels: inner, optimization

#1575 fix: topo graphics update and search with wrong data.
  src/common/metadata/graphic.go
  src/source_controller/objectcontroller/service/topographics.go
Labels: bug, inner

#1576 refactor: 模型拓扑交互更新
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/object-association.js
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/model-topology/index.vue
Labels: inner, optimization

#1570 :optimize the implementation of basic operation methods , add logs for all model management logic
  src/common/metadata/classification.go
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/association/model_crud.go
  src/source_controller/coreservice/core/association/model_private.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/attribute_private.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/classification_crud.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_crud.go
  src/source_controller/coreservice/core/model/model_private.go
Labels: optimization

#1582 optimize: 关联关系删除保护， 实例拓扑新增字段
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/common/metadata/association.go
  src/scene_server/topo_server/core/inst/association.go
  src/scene_server/topo_server/core/inst/inst.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/types.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/object_association.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: demand, inner, optimization

#1583 test:add unit testcase for model classifications issue #1495
  src/common/errors/error.go
  src/common/metadata/core_service.go
  src/common/universalsql/mongo/condition_private.go
  src/common/universalsql/mongo/element.go
  src/common/universalsql/type.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/classification_crud.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/classification_test.go
  src/source_controller/coreservice/core/model/mock_test.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_crud.go
  src/source_controller/coreservice/core/model/model_private.go
  src/source_controller/coreservice/core/model/model_test.go
Labels: inner, optimization

#1587 fix： add privilege for common user, optimize association instance response.
  src/Makefile
  src/apimachinery/objcontroller/association/api.go
  src/apimachinery/objcontroller/association/association.go
  src/apimachinery/toposerver/association/apis.go
  src/apimachinery/toposerver/association/association.go
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/objectcontroller/service/instasst_action.go
  src/source_controller/objectcontroller/service/service.go
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/types/types.go
Labels: bug, inner, optimization

#1588 3.2.x UI fix & update
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/relation/_topology.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/store/modules/api/object-association.js
  src/ui/src/utils/tools.js
Labels: bug, demand, inner, optimization

#1589 fix: 模型管理bugfix
  src/ui/src/components/ui/selector/selector.vue
  src/ui/src/views/model-manage/children/field-detail/index.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation-detail/form-selector.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
Labels: bug, inner, optimization

#1590 3.2.x ui fix & update
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/topology/index.vue
Labels: bug, inner, optimization

#1593 optimize: optimize the search object instance association api.
  src/scene_server/topo_server/core/inst/association.go
  src/scene_server/topo_server/core/inst/inst.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/model/types.go
Labels: inner, optimization

#1597 optimize: add privilege for export object excel api.
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/types/types.go
Labels: demand, inner

#1598 optimize: add privilege for search inst association api for common user
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/types/types.go
Labels: inner, optimization

#1602 fix:ui:修复部分页面未重置页面标题的问题
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/status/403.vue
  src/ui/src/views/status/404.vue
  src/ui/src/views/status/error.vue
  src/ui/src/views/status/require-business.vue
Labels: inner, optimization

#1603 optimize: add privilege for common user with create inst association api.
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/types/types.go
Labels: inner, optimization

#1606 optimize: add delete inst association api privilege for common user.
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/types/types.go
Labels: inner, optimization

#1578 Feature: cmdb object add float support
  .gitignore
  docs/apidoc/object_model_property.md
  resources/language/default/fieldtype.json
  resources/language/en/fieldtype.json
  src/common/definitions.go
  src/common/errInfo.go
  src/common/util/conv.go
  src/framework/core/output/module/model/type.go
  src/scene_server/admin_server/upgrader/v3.0.8/objAttDescData.go
  src/scene_server/admin_server/upgrader/v3.0.9-beta.3/fixes_port_pattern.go
  src/scene_server/admin_server/upgrader/x08.09.04.01/updateSystemProperty.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/validator/type.go
  src/scene_server/validator/util.go
  src/scene_server/validator/valid_basic.go
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/ui/form/float.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/index.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/model-manage/children/field-detail/config.vue
  src/ui/src/views/model-manage/children/field-detail/float.vue
  src/ui/src/views/model-manage/children/field-detail/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model/details/field.vue
  src/ui/src/views/model/details/model-field/config.vue
  src/ui/src/views/model/details/model-field/float.vue
  src/ui/src/views/model/details/model-field/index.vue
  src/web_server/logics/excel_util.go
  src/web_server/logics/fields.go
Labels: demand, outer

#1614 fix: 修复错误信息判断错误的问题
  src/scene_server/host_server/logics/import.go
Labels: bug, inner

#1619 Compatible with older versions of mongodb equal syntax issue
  src/common/universalsql/mongo/condition_private.go
  src/common/universalsql/mongo/condition_test.go
  src/common/universalsql/mongo/element.go
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/association/model_private.go
  src/source_controller/coreservice/core/association/model_test.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/mock_test.go
  src/source_controller/coreservice/service/model_dependencs.go
Labels: inner, optimization

#1620 fix: 模型拓扑箭头未按照关联类型正确展示 to v3.2.x
  src/ui/src/views/model-topology/index.vue
Labels: bug, inner

#1605 datacollection coreservice 改造
  src/scene_server/datacollection/datacollection/handler.go
  src/scene_server/datacollection/datacollection/netdevice.go
Labels: demand, inner, optimization

#1623 Regression: v3.2.0 iteration.
  resources/errors/common/default/common.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/service/unique.go
  src/scene_server/validator/valid_unique.go
Labels: inner, optimization

#1624 修复用户类型字段未校验问题
  src/scene_server/admin_server/upgrader/x18.11.19.01/pkg.go
  src/scene_server/admin_server/upgrader/x18.11.19.01/reconcil_unique.go
  src/scene_server/validator/valid_basic.go
Labels: bug, demand, inner

#1622 3.2.x bugfix
  src/ui/src/components/relation/_topology.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/components/ui/form/date.vue
  src/ui/src/components/ui/form/time.vue
  src/ui/src/utils/tools.js
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/index.vue
Labels: bug, inner, optimization

#1627 3.2.x bugfix
  src/ui/src/components/relation/_topology.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.vue
Labels: bug, inner, optimization

#1626 feature:Supports conversion between anonymous structures and MapStr i…
  src/common/mapstr/mapstr.go
  src/common/mapstr/mapstr_test.go
  src/common/mapstr/struct_tags.go
  src/common/mapstr/struct_tags_private.go
  src/common/metadata/attribute.go
  src/common/metadata/classification.go
  src/common/metadata/common.go
  src/common/metadata/graphic.go
  src/common/metadata/group.go
  src/common/metadata/metadata.go
  src/common/metadata/object.go
  src/source_controller/coreservice/core/model/attribute_test.go
Labels: demand, inner

#1628 fix: 补充国际化翻译内容
  src/ui/src/i18n/lang/en.json
Labels: demand, inner

#1631 补充前端翻译
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/eventpush/push-detail.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/model-manage/children/_property-group.vue
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/index.vue
  src/ui/src/views/permission/authority.vue
  src/ui/src/views/process/index.vue
Labels: inner, optimization

#1630 feature: add translation for association kind
  resources/language/default/association.json
  resources/language/en/association.json
  src/source_controller/objectcontroller/service/association_action.go
  src/source_controller/objectcontroller/service/common.go
Labels: demand, inner

#1632 optimize: change label type and add new receivers.
  src/common/metadata/metadata.go
Labels: demand, inner

#1636 add unit test case for model association and add model attribute groups
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/result.go
  src/source_controller/coreservice/core/association/mock_test.go
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/association/model_crud.go
  src/source_controller/coreservice/core/association/model_test.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/mock_test.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_attribute_group.go
  src/source_controller/coreservice/core/model/model_attribute_group_crud.go
  src/source_controller/coreservice/core/model/model_attribute_group_private.go
  src/source_controller/coreservice/core/model/model_attribute_group_test.go
  src/source_controller/coreservice/core/model/model_test.go
  src/source_controller/coreservice/service/instances.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/coreservice/service/translate.go
Labels: demand, inner

#1643 optimize: toposerver object ,instance, group, attribute revise
  src/scene_server/topo_server/core/inst/association.go
  src/scene_server/topo_server/core/inst/inst.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/classification.go
  src/scene_server/topo_server/core/model/factory.go
  src/scene_server/topo_server/core/model/group.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/model/types.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/graphics.go
  src/scene_server/topo_server/core/operation/group.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/topo_server/core/operation/supplementary_validator.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/object.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: inner, optimization

#1645 test: add service api test case framework issue #1644
  src/common/backbone/backbone.go
  src/common/backbone/backbone_mock.go
  src/source_controller/coreservice/app/options/options_test.go
  src/source_controller/coreservice/service/model_test.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_test.go
Labels: demand, inner

#1635 fix: solve dail mongodb forever problem
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/command/command.go
  src/scene_server/datacollection/datacollection/datacollection.go
  src/scene_server/event_server/app/server.go
  src/source_controller/auditcontroller/app/server.go
  src/source_controller/hostcontroller/app/server.go
  src/source_controller/objectcontroller/app/server.go
  src/source_controller/proccontroller/app/server.go
  src/storage/dal/mongo/mgo_mongo.go
Labels: inner, optimization

#1648 增加mongo条件查询函数嵌入式表达方式
  src/common/mapstr/mapstr.go
  src/common/universalsql/mongo/condition.go
  src/common/universalsql/mongo/condition_test.go
  src/common/universalsql/mongo/create_statement.go
  src/common/universalsql/mongo/element.go
  src/common/universalsql/mongo/field.go
  src/common/universalsql/mongo/field_test.go
  src/common/universalsql/mongo/statement.go
  src/common/universalsql/mongo/table.go
  src/common/universalsql/type.go
  src/common/universalsql/universalsql.go
  src/common/universalsql/universalsql_test.go
  version.md
Labels: inner, optimization

#1651 fix: solve init.py for coreservice
  scripts/init.py
  src/scene_server/admin_server/upgrader/x18.12.05.01/addswitchAssociation.go
  src/scene_server/admin_server/upgrader/x18.12.05.01/pkg.go
Labels: demand, inner

#1650 fix: find all result should use pointer
  src/source_controller/objectcontroller/service/identifier.go
Labels: bug, inner

#1657 fix: multip-supplier method, assign to app issue #1656
  src/scene_server/host_server/logics/app.go
Labels: bug, inner

#1659 V3.2.1 regression
  resources/language/default/enum.json
  resources/language/default/property.json
  resources/language/en/enum.json
  resources/language/en/property.json
  src/common/metadata/graphic.go
  src/scene_server/topo_server/core/model/classification.go
  src/scene_server/topo_server/core/model/factory.go
  src/scene_server/topo_server/core/model/types.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/graphics.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: bug, inner

#1654 3.2.x bugfix
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/columns-config/columns-config.vue
  src/ui/src/components/hosts/filter/_collection.vue
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/hosts/table/_quick-search.vue
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/i18n/index.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/src/bk-magic-ui/src/bk.scss
  src/ui/src/magicbox/src/bk-magic-ui/src/pagination.scss
  src/ui/src/magicbox/src/bk-magic-ui/src/paging.scss
  src/ui/src/magicbox/src/bk-magic-ui/src/tree.scss
  src/ui/src/magicbox/src/components/button/button.vue
  src/ui/src/magicbox/src/components/date-picker/date-picker.vue
  src/ui/src/magicbox/src/components/date-range/date-picker.vue
  src/ui/src/magicbox/src/components/date-range/date-range.vue
  src/ui/src/magicbox/src/components/dialog/dialog.vue
  src/ui/src/magicbox/src/components/pagination/index.js
  src/ui/src/magicbox/src/components/pagination/pagination.vue
  src/ui/src/magicbox/src/components/paging/paging.vue
  src/ui/src/magicbox/src/components/tag-input/tag-input.vue
  src/ui/src/magicbox/src/components/timeline/timeline.vue
  src/ui/src/magicbox/src/components/tree/tree-item.vue
  src/ui/src/magicbox/src/components/tree/tree.vue
  src/ui/src/magicbox/src/index.js
  src/ui/src/store/modules/api/object-model.js
  src/ui/src/views/eventpush/push-detail.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/_property-group.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/status/require-business.vue
Labels: bug, inner, optimization
