Repository Tencent/bk-cmdb, pull requests merged in 2018-10, with the labels that each got.

#1241 modify net device api
  resources/errors/common/default/datacollection.json
  resources/errors/english/en/datacollection.json
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/datacollection.go
  src/scene_server/datacollection/logics/device.go
  src/scene_server/datacollection/logics/property.go
  src/scene_server/datacollection/service/device.go
  src/scene_server/datacollection/service/property.go
  src/scene_server/datacollection/service/service.go
  src/web_server/application/controllers/netdevice.go
  src/web_server/application/controllers/netproperty.go
  src/web_server/application/logics/netproperty.go
Labels: demand, inner

#1243 网络发现功能更新
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/src/bk-magic-ui/src/member-selector.scss
  src/ui/src/magicbox/src/components/dialog/dialog.vue
  src/ui/src/store/modules/api/net-collect-device.js
  src/ui/src/store/modules/api/net-collect-property.js
  src/ui/src/views/network-config/collect.vue
  src/ui/src/views/network-config/device.vue
  src/ui/src/views/network-config/property.vue
  src/ui/src/views/network-discovery/details.vue
  src/ui/src/views/network-discovery/history.vue
Labels: demand, in progress, inner

#1236 feature: 实例关联关系拓扑图增加关联描述
  src/ui/src/components/relation/_topology.vue
Labels: demand, inner

#1242 bugfix: 测试推送没有post数据
  src/ui/src/assets/json/event-push-example.json
  src/ui/src/views/eventpush/pop.vue
Labels: bug, inner, resolved

#1245 属性管理修改接口
  resources/errors/common/default/datacollection.json
  resources/errors/english/en/datacollection.json
  src/common/errInfo.go
  src/common/metadata/datacollection.go
  src/common/metadata/netdevice.go
  src/scene_server/datacollection/logics/common.go
  src/scene_server/datacollection/logics/device.go
  src/scene_server/datacollection/logics/property.go
  src/scene_server/datacollection/service/device.go
  src/scene_server/datacollection/service/property.go
  src/scene_server/datacollection/service/service.go
  src/web_server/application/controllers/netproperty.go
Labels: demand, inner

#1253 关联关系toposerver http 调用方式修改
  src/apimachinery/rest/request.go
  src/apimachinery/toposerver/association/apis.go
  src/apimachinery/toposerver/association/association.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: inner, optimization

#1254 minor: 网络发现接口参数调整
  src/ui/src/views/network-config/collect.vue
  src/ui/src/views/network-config/device.vue
  src/ui/src/views/network-config/property.vue
  src/ui/src/views/network-discovery/confirm.vue
  src/ui/src/views/network-discovery/details.vue
Labels: demand, inner

#1249 关联查询，对or查询条件的转换 #1149
  src/common/metadata/association.go
  src/source_controller/objectcontroller/service/instasst_action.go
  src/source_controller/objectcontroller/service/objectasst_action.go
Labels: inner, optimization

#1258 关联关系处理，插入实例关联关系时写入模型id #1149
  src/common/metadata/association.go
  src/source_controller/objectcontroller/service/instasst_action.go
Labels: bug, inner

#1267 增加默认设置SupplierAccount的逻辑 #1264
  src/scene_server/topo_server/core/model/association.go
  src/scene_server/topo_server/core/model/classification.go
  src/scene_server/topo_server/core/model/factory.go
Labels: inner, optimization

#1252 解决推送主机身份缺少进程信息问题
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/command/types.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/compatiblev2.go
Labels: bug, inner

#1250 解决推送主机身份缺少进程信息问题
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/command/types.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/topo_server/core/operation/inst_business.go
Labels: bug, inner

#1270 fix https login url
  src/web_server/app/options/options.go
  src/web_server/app/server.go
  src/web_server/middleware/login.go
  src/web_server/middleware/user/public.go
  src/web_server/middleware/user/user.go
  src/web_server/service/login.go
  src/web_server/service/service.go
  src/web_server/service/user.go
Labels: bug, inner

#1275 修复根据IP获取进程信息时， 业务下多个进程。只展示一个进程的问题
  src/scene_server/proc_server/proc_service/service/openapi.go
Labels: bug, inner

#1281 minor: 修改文案
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/network-config/property.vue
Labels: inner, optimization

#1283 修改 BKINnerObjIDObject 名字到 BKInnerObjIDObject
  src/common/definitions.go
  src/common/mapping.go
  src/common/metadata/object.go
  src/common/metadata/object_test.go
  src/common/tablenames.go
  src/common/tablenames_test.go
  src/framework/core/output/module/types/type.go
  src/scene_server/event_server/distribution/handle_event.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/import_asst.go
  src/scene_server/host_server/logics/instance.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/proc_server/proc_service/service/procdetail.go
  src/scene_server/topo_server/core/operation/import_asst.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/validator/valid_unique.go
  src/source_controller/hostcontroller/logics/object.go
  src/source_controller/objectcontroller/service/common.go
  src/source_controller/objectcontroller/service/inst_action.go
  src/web_server/logics/excel.go
  src/web_server/logics/fields.go
Labels: inner, optimization

#1287 修改SetValueToStructByTags 的实现，增加float 类型数据到 int 默认转换 #1286
  src/common/metadata/struct_tags.go
Labels: inner, optimization

#1279 getProcessPortByIP 当业务下有多个进程，只显示其中一个
  src/scene_server/proc_server/proc_service/service/openapi.go
Labels: bug, inner

#1291 【关联关系】主机查询接口改造
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/logics/instance.go
Labels: inner, optimization

#1278 事件推送接入关联改造
  src/common/definitions.go
  src/common/metadata/association.go
  src/common/metadata/eventserver.go
  src/common/version/version.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/v3.0.8/addPresetObjects.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/pkg.go
  src/scene_server/event_server/identifier/identifier.go
  src/source_controller/objectcontroller/service/identifier.go
  src/source_controller/objectcontroller/service/instasst_action.go
Labels: demand, inner

#1289 请求头兼容supplier id和supplier account
  src/common/definitions.go
  src/common/rdapi/rdfunc.go
  src/common/util/lib.go
  src/web_server/app/server.go
Labels: inner, optimization
