Repository Tencent/bk-cmdb, pull requests merged in 2019-10, with the labels that each got.

#3238 code optimize
  src/apimachinery/rest/request.go
  src/common/backbone/register.go
  src/common/metadata/common.go
Labels: optimization

#3225 update:ui: 回归优化
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/resource/index.vue
Labels: optimization

#3230 Feature ui association list web
  src/common/metadata/object.go
  src/common/universalsql/mongo/condition_private.go
  src/common/universalsql/mongo/condition_test.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: bug, demand, inner, optimization

#3242 修复host集成测试用例
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/common/errInfo.go
  src/scene_server/host_server/service/host.go
  src/test/host_server/host_abnormal_test.go
Labels: demand

#3168 feature-ui 集成测试问题修复
  docs/apidoc/v3.2/host_favorites.md
  src/apimachinery/toposerver/object/api.go
  src/apimachinery/toposerver/object/unique.go
  src/auth/extensions/attributegroup.go
  src/common/definitions.go
  src/common/universalsql/mongo/condition_private.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
  src/scene_server/host_server/service/favourite.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/topo_server/core/inst/inst.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/model/valid.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/group.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/object_group.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator_attr.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/model_attribute_group.go
  src/source_controller/coreservice/core/model/model_attribute_group_private.go
  src/test/event_server/event_server_suite_test.go
  src/test/healthz/healthz_suite_test.go
  src/test/host_server/user_test.go
  src/test/proc_server/no_service_template_test.go
  src/test/proc_server/service_template_test.go
  src/test/reporter/html_reporter.go
  src/test/reporter/template.go
  src/test/topo_server/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/object_test.go
  src/test/topo_server/topo_server_suite_test.go
Labels: demand

#3245 fix: topo server test suite
  src/test/topo_server/object_test.go
Labels: optimization

#3243 update:ui: 优化代码兼容性
  src/ui/src/filters/formatter.js
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
Labels: optimization

#3248 UI: 集群模板功能与实例关联关系显示优化
  src/ui/package.json
  src/ui/src/App.vue
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/assets/images/latest-data.png
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/components/relation/_topology.new.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/other/tips.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/meta.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/object-relation.js
  src/ui/src/store/modules/api/object-set.js
  src/ui/src/store/modules/api/service-classification.js
  src/ui/src/store/modules/api/set-sync.js
  src/ui/src/store/modules/api/set-template.js
  src/ui/src/store/modules/view/set-features.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-set.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/custom-fields/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/model-topology/index.new.vue
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/set-sync/router.config.js
  src/ui/src/views/set-sync/set-instance.vue
  src/ui/src/views/set-sync/sync-index.vue
  src/ui/src/views/set-sync/view-sync.vue
  src/ui/src/views/set-template/children/service-template-info.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
  src/ui/src/views/set-template/children/template-config.vue
  src/ui/src/views/set-template/children/template-info.vue
  src/ui/src/views/set-template/children/template-intance.vue
  src/ui/src/views/set-template/children/template-tree.vue
  src/ui/src/views/set-template/create.vue
  src/ui/src/views/set-template/index.vue
  src/ui/src/views/set-template/router.config.js
  src/ui/src/views/set-template/template.vue
Labels: demand, inner, optimization

#3251 集群模板功能
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/set-sync/set-instance.vue
  src/ui/src/views/set-sync/sync-index.vue
  src/ui/src/views/set-template/children/template-intance.vue
  src/ui/src/views/set-template/index.vue
  src/ui/src/views/set-template/router.config.js
  src/ui/src/views/set-template/sync-history.vue
Labels: demand

#3263 35bugfix&optimize
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.09.03.08/pkg.go
  src/scene_server/admin_server/upgrader/x19.09.03.08/update_process_property.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/model.go
Labels: demand

#3262 fix service instance panic issue
  src/common/mapstr/convert.go
  src/common/metadata/metadata.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/service/association.go
Labels: bug

#3260 ui: 回归优化
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/host-details/index.vue
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/index.vue
Labels: optimization

#3264 search inst. 有特殊字符的，实例查询不出来
  src/scene_server/topo_server/core/operation/inst.go
Labels: demand, outer

#3265 fix: 操作审计，根据时间查询日志，由于UTC时区问题，导致查询结果错误
  src/common/metadata/common.go
Labels: bug

#3250 feature: optimized exception handling issue #2614
  src/storage/tmserver/core/core.go
  src/storage/tmserver/core/session/manager.go
  src/storage/tmserver/service/service.go
Labels: inner, optimization

#3235 鉴权优化：业务/集群/模块/主机新增业务私有自定义属性应申请业务下的权限
  src/apiserver/service/url.go
  src/auth/authcenter/perm_biz.go
  src/auth/extensions/model.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/auth/parser/util.go
  src/scene_server/admin_server/authsynchronizer/handler/model.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: demand

#3271 update:ui: 删除metadata参数
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association-list.vue
Labels: optimization

#3270 fix: cmdb_ctl related problem and makefile
  src/Makefile
  src/common/backbone/http.go
  src/common/backbone/notice.go
Labels: optimization

#3275 按业务区分收藏条件
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
Labels: demand

#3279 update:ui: 操作审计取参调整及路由高亮设置
  src/ui/src/components/audit-history/details.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/views/business/router.config.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/history/index.vue
  src/ui/src/views/history/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/resource/router.config.js
Labels: inner, optimization

#3269 服务模板移除metadata合入3.6后集群模板测试用例调整
  src/common/metadata/set_template_request.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/test/topo_server/set_template_test.go
Labels: demand

#3280 主机查询条件收藏支持按业务隔离
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/common/metadata/hostcontroller.go
  src/common/metadata/querycondition.go
  src/scene_server/host_server/service/favourite.go
  src/scene_server/host_server/service/findhost.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/service/processtemplate.go
  src/source_controller/coreservice/service/hostfavourite.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand, optimization

#3281 optimize: fix search host multilike search issue.
  src/common/paraparse/app.go
Labels: optimization

#3285 限制通用模型实例接口可操作模型范围
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/object.go
Labels: optimization

#3283 查询实例关联关系API
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: demand, inner

#3266 3.6功能开发及优化调整
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/servicecategory.go
  src/auth/extensions/settemplate.go
  src/auth/meta/resource.go
  src/auth/parser/framework.go
  src/auth/parser/settemplate.go
  src/auth/parser/topolatest.go
  src/common/metadata/inst.go
  src/common/metadata/set_template.go
  src/common/metadata/set_template_request.go
  src/scene_server/admin_server/authsynchronizer/handler/settemplate.go
  src/scene_server/admin_server/authsynchronizer/meta/types.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/authsynchronizer/worker.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/service/inst_set.go
  src/scene_server/topo_server/service/set_template.go
  src/test/topo_server/inst_test.go
Labels: demand

#3293 移除 DeleteModelClassificationCascade
  src/apimachinery/clientset_coreservice_model_test.go
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/model/model.go
  src/auth/extensions/model.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/object.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/model/attribute_private.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/classification_crud.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_attribute_group.go
  src/source_controller/coreservice/core/model/model_attribute_group_crud.go
  src/source_controller/coreservice/core/model/model_attribute_group_private.go
  src/source_controller/coreservice/core/model/model_crud.go
  src/source_controller/coreservice/core/model/model_private.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: optimization

#3301 UI: 全文检索展示问题 / 样式调整
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/model-manage/index.vue
Labels: inner, optimization

#3287 fix: 修复tmserver的bug和更新相应的事务测试用例 issue #3286
  src/storage/dal/mongo/remote/mongo_test.go
  src/storage/dal/mongo/remote/pool.go
  src/storage/dal/mongo/remote/transaction_test.go
  src/storage/rpc/server.go
Labels: bug

#3313 update:ui: 去掉同步提示框
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/set-sync/sync-index.vue
Labels: inner, optimization

#3318 UI： 翻译补充及UI异常处理
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/ui/form/associate-input.vue
  src/ui/src/components/ui/form/bool-input.vue
  src/ui/src/components/ui/form/date.vue
  src/ui/src/components/ui/form/enum.vue
  src/ui/src/components/ui/form/float.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/int.vue
  src/ui/src/components/ui/form/longchar.vue
  src/ui/src/components/ui/form/search-input.vue
  src/ui/src/components/ui/form/singlechar.vue
  src/ui/src/components/ui/form/time.vue
  src/ui/src/components/ui/form/timezone.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/host-search.js
  src/ui/src/utils/tools.js
  src/ui/src/views/model-manage/children/verification-detail/index.vue
  src/ui/src/views/model-manage/children/verification.vue
Labels: bug, inner

#3317 内置业务、模块、集群国际化
  src/source_controller/objectcontroller/service/common.go
Labels: bug, inner

#3316 v3.2.x: 主机多匹配及国际化翻译相关优化
  resources/language/default/property_group.json
  resources/language/en/enum.json
  resources/language/en/property_group.json
  src/common/paraparse/app.go
Labels: bug, optimization

#3315 内置业务、模块、集群国际化
  src/source_controller/coreservice/service/instances.go
Labels: demand, inner

#3305 集群模板体验优化及bug修复
  resources/errors/common/default/common.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/topo_server.json
  src/auth/extensions/base.go
  src/auth/extensions/module.go
  src/common/errInfo.go
  src/common/errors/errorIf.go
  src/common/http/rest/contexts.go
  src/common/metadata/association.go
  src/common/metadata/inst.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/upgrader/x19.10.09.01/settemplate_sync_status.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/scene_server/topo_server/core/settemplate/worker.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/internal_task.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/validator_unique.go
  src/test/topo_server/object_test.go
  src/test/topo_server/set_template_test.go
Labels: optimization

#3310 response 返回值生成Error
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/label/api.go
  src/apimachinery/coreservice/process/api.go
  src/common/errors/defaultError.go
  src/common/errors/errorIf.go
  src/common/errors/error_test.go
  src/common/errors/factory.go
  src/common/metadata/result.go
  src/common/metadata/result_test.go
  src/scene_server/proc_server/logics/processinstance.go
Labels: inner, optimization

#3302 feature: instance association object instance info issue #3282
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/permit/permit.go
  src/auth/parser/topolatest.go
Labels: demand, inner

#3300 feature:auth add operation statistics resource, verify api issue #3299
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_sys.go
  src/auth/authcenter/permit/permit.go
  src/auth/meta/resource.go
  src/auth/parser/framework.go
  src/auth/parser/operationstatistics.go
  src/auth/parser/process.go
Labels: demand, inner

#3294 cmdb_ctl tool添加zk操作和回显服务器小工具
  src/tools/cmdb_ctl/app/app.go
  src/tools/cmdb_ctl/cmd/echo.go
  src/tools/cmdb_ctl/cmd/zk.go
  src/tools/cmdb_ctl/readme.md
Labels: demand

#3326 optimize:ui: 调整业务列表ID列宽
  src/ui/src/views/business/index.vue
Labels: optimization

#3332 fix: 预设模型运营状态翻译不全
  resources/language/default/enum.json
  resources/language/en/enum.json
Labels: optimization

#3330 fix: 预设模型运营状态翻译不全
  resources/language/default/enum.json
  resources/language/en/enum.json
Labels: optimization

#3329 feature:ui: 下线权限转换拦截
  src/ui/src/api/middleware/index.js
  src/ui/src/store/modules/api/auth.js
Labels: demand, inner

#3325 进程升级到3.5时进程实例supplier account与服务实例保持一致
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/proc_server/service/serviceinstance.go
Labels: bug, demand

#3323 fix: 修改cpu频率的英文字段名和单位 issue #3321
  resources/language/en/property.json
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.10.22.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.10.22.01/update_cpu_unit.go
Labels: bug

#3322 fix: 修改cpu频率的英文字段名和单位 issue #3321
  resources/language/en/property.json
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.12.12.08/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.08/update_cpu_unit.go
Labels: optimization

#3331 code refactor: rename
  resources/language/default/import_instance.json
  resources/language/en/import_instance.json
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/service/host.go
Labels: optimization

#3324 支持将进程属性字段设置成null
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/metadata/process.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/processtemplate.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/service/process_template.go
  src/test/proc_server/no_service_template_test.go
Labels: demand

#3333 fix: 主机详情变更记录排序传参错误
  src/ui/src/views/host-details/children/history.vue
Labels: bug

#3289 fix: excel import enum field fail
  src/source_controller/validator/util.go
  src/source_controller/validator/valid_basic.go
Labels: bug

#3348 update:ui: 模块节点信息展示调整
  src/ui/src/views/business-topology/children/service-node-info.vue
Labels: optimization

#3351 fix: fix get biz host list api bug.
  src/auth/parser/host.go
  src/common/metadata/hostserver.go
Labels: bug

#3339 内置权限管理下线
  resources/language/default/property_group.json
  resources/language/en/property_group.json
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/privilege/api.go
  src/apimachinery/coreservice/privilege/privilege.go
  src/apimachinery/toposerver/privilege/api.go
  src/apimachinery/toposerver/privilege/privilege.go
  src/apimachinery/toposerver/toposerver.go
  src/auth/parser/topology.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/privilege.go
  src/common/paraparse/privilege.go
  src/common/tablenames.go
  src/scene_server/admin_server/upgrader/v3.0.8/createtable.go
  src/scene_server/admin_server/upgrader/v3.0.9-beta.1/fixes_supplier_account.go
  src/scene_server/admin_server/upgrader/x08.09.13.01/pkg.go
  src/scene_server/admin_server/upgrader/x08.09.13.01/reconcileGroupPrivilege.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/privilege.go
  src/scene_server/topo_server/core/privilege/group.go
  src/scene_server/topo_server/core/privilege/privilege.go
  src/scene_server/topo_server/core/privilege/role.go
  src/scene_server/topo_server/service/privilege.go
  src/scene_server/topo_server/service/privilege_group.go
  src/scene_server/topo_server/service/privilege_role.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/coreservice/service/privilege_role.go
  src/source_controller/coreservice/service/privilege_usergroup.go
  src/source_controller/coreservice/service/privilege_usergroup_detail.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/coreservice/service/system_action.go
  src/test/business/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/privilege_test.go
  src/web_server/logics/privilege.go
  src/web_server/middleware/auth/auth.go
  src/web_server/middleware/auth/auth_test.go
  src/web_server/middleware/auth/auth_util.go
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/login.go
  src/web_server/middleware/privilege/privilege.go
  src/web_server/middleware/privilege/privilege_test.go
  src/web_server/middleware/types/types.go
  src/web_server/service/index.go
Labels: demand

#3337 服务实例查询支持按主机IDs查询
  src/common/metadata/core_service.go
  src/common/metadata/hostserver.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/service/service_settemplate_initfunc.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/test/topo_server/set_template_test.go
  src/test/topo_server/topo_server_suite_test.go
Labels: optimization

#3356 新增主机相关的权限校验
  src/auth/parser/host.go
  src/auth/parser/topology.go
  src/test/topo_server/inst_test.go
Labels: demand

#3358 fix: 运营统计，定时器没触发bug
  src/scene_server/operation_server/app/options/options.go
  src/scene_server/operation_server/logics/logics.go
Labels: bug

#3360 3.2.x 优化
  src/ui/package.json
  src/ui/src/views/audit/index.vue
  src/ui/src/views/model-manage/children/field-detail/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification-detail/index.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
Labels: optimization

#3363 fix: 查看主机删除历史页面查看不到被删除的主机记录
  src/scene_server/host_server/service/host.go
Labels: bug
