Repository Tencent/bk-cmdb, pull requests merged in 2019-11, with the labels that each got.

#3377 表格展示优化
  src/ui/src/api/index.js
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/table-stuff/table-stuff.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/mixins/permission.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/history.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-template/children/template-intance.vue
  src/ui/src/views/set-template/index.vue
  src/ui/src/views/set-template/sync-history.vue
Labels: inner, optimization

#3378 业务内置模块拓扑树节点返回default字段
  src/common/metadata/inst.go
  src/common/metadata/object.go
  src/scene_server/topo_server/core/operation/inst_business.go
Labels: demand

#3355 主机&服务实例管理页面合并相关接口
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/auth/parser/framework.go
  src/auth/parser/host.go
  src/auth/parser/operationstatistics.go
  src/auth/parser/processinstance.go
  src/auth/parser/processtemplate.go
  src/auth/parser/servicecategory.go
  src/auth/parser/serviceinstance.go
  src/auth/parser/servicetemplate.go
  src/auth/parser/settemplate.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/hostserver.go
  src/common/metadata/process.go
  src/common/metadata/process_request.go
  src/scene_server/host_server/logics/cloud_synctask.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/source_controller/coreservice/service/service_template.go
Labels: demand

#3374 新增：云区域更新接口 #3373
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/auth/parser/topology.go
  src/common/errInfo.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/service.go
  src/scene_server/topo_server/service/inst.go
Labels: demand

#3365 fix:UI 页面模糊查询不受特殊字符影响 close #3364
  src/common/paraparse/app.go
  src/common/paraparse/host.go
  src/common/paraparse/paraparse_test.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: bug, inner

#3369 fix:UI 页面模糊查询不受特殊字符影响 close #3368
  src/common/paraparse/app.go
  src/common/paraparse/paraparse_test.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: bug, inner

#3382 允许给主机添加自定义唯一约束
  src/scene_server/topo_server/service/unique.go
Labels: demand

#3383 fix: 判断主线模型时未包括业务
  src/scene_server/topo_server/core/operation/association.go
Labels: demand

#3385 optimize: read supplier account from header when create cloud area.
  src/auth/parser/topology.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/phpapi.go
Labels: demand

#3381 UI: 添加sideslider关闭提示
  src/ui/src/views/model-association/_detail.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/verification.vue
Labels: optimization

#3386 add supporting for operating special model instance with common instance interface by white list
  src/scene_server/topo_server/service/inst.go
Labels: demand

#3384 支持设置主机移除后默认转移的内置模块
  src/common/metadata/hostserver.go
  src/scene_server/host_server/service/transfer.go
Labels: demand, optimization

#3390 删除集群时同步清理集群同步状态
  src/apimachinery/coreservice/settemplate/api.go
  src/apimachinery/coreservice/settemplate/settemplate.go
  src/common/metadata/set_template_request.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/settemplate/sync_status.go
  src/source_controller/coreservice/service/service_set_template_initfunc.go
  src/source_controller/coreservice/service/set_template.go
Labels: demand

#3376 fix：导入主机与实例关联失败 && 字段有英文符号“,;”时报错
  src/common/definitions.go
  src/scene_server/topo_server/core/operation/import_association.go
Labels: bug

#3392 update:ui: 新建/编辑进程模板权限调整
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process.vue
Labels: bug

#3393 云区域查询条件和使用icon-cool
  src/ui/package.json
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/selector/cloud.vue
  src/ui/src/main.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/cloudarea.js
  src/ui/src/views/custom-query/define.vue
Labels: demand

#3398 fix get topo panic bug when a topo is not correct.
  src/auth/extensions/instance.go
  src/source_controller/coreservice/core/mainline/instance.go
  src/source_controller/coreservice/core/mainline/manager.go
Labels: bug

#3399 update: ui调整 / 多IP搜索
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/store/modules/view/hosts.js
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/operation/index.vue
  src/ui/src/views/resource/index.vue
Labels: demand, inner

#3402 fix: fix sync model instance auth bug.
  src/scene_server/admin_server/authsynchronizer/handler/core.go
  src/scene_server/admin_server/authsynchronizer/handler/module.go
  src/scene_server/admin_server/authsynchronizer/handler/plat.go
  src/scene_server/admin_server/authsynchronizer/handler/set.go
Labels: bug

#3404 删除自定义层级时没有级联删除集群和模块bugfix
  src/common/metadata/process.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: optimization

#3405 fix: update object property group iam issue.
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
Labels: bug

#3407 optimize: rollback model attribute group auth logic.
  src/auth/parser/topology.go
Labels: optimization

#3403 update:ui: 3.5回归优化
  src/ui/src/components/relation/_update.vue
  src/ui/src/views/business-topology/children/service-instance-empty.vue
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
Labels: bug, optimization

#3394 添加查询主机和拓扑信息的接口
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/auth/parser/host.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/service/findhost.go
  src/scene_server/host_server/service/service.go
  src/source_controller/coreservice/core/host/transfer/transfer.go
  src/test/host_server/host_test.go
Labels: demand

#3401 add: hosts/property/batch api
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/auth/parser/host.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/service.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_test.go
Labels: demand

#3413 fix: /api/v3/findmany/modulehost 权限URL错误
  src/auth/parser/host.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/findhost.go
Labels: bug

#3395 fix: 导入实例关联，报解析授权信息失败
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/scene_server/topo_server/core/operation/import_association.go
Labels: bug

#3371 fix：运营统计，定时统计图表数据bug
  src/common/metadata/operation.go
  src/scene_server/operation_server/logics/logics.go
  src/source_controller/coreservice/core/operation/inner_chart.go
  src/source_controller/coreservice/service/operation.go
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/operation/index.vue
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/chain.go
  vendor/github.com/robfig/cron/chain_test.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/cron_test.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/go.mod
  vendor/github.com/robfig/cron/logger.go
  vendor/github.com/robfig/cron/option.go
  vendor/github.com/robfig/cron/option_test.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/parser_test.go
  vendor/github.com/robfig/cron/spec.go
  vendor/github.com/robfig/cron/spec_test.go
Labels: bug

#3416 批量编辑成功关闭侧滑 / 字段删除界面显示异常
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/views/general-model/index.vue
Labels: bug

#3415 demand: revise object instance unique check rules with new demand.
  src/scene_server/validator/util.go
  src/scene_server/validator/valid_basic.go
  src/source_controller/coreservice/core/instances/validator_unique.go
  src/source_controller/coreservice/core/model/unique.md
  src/source_controller/coreservice/core/model/unique_crud.go
Labels: demand

#3408 主机新增 云区域+内网IP 唯一校验；将主机云区域属性采用单独接口修改
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/apiserver/service/url.go
  src/auth/parser/host.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/hostserver.go
  src/common/metadata/process.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.10.22.02/add_host_index.go
  src/scene_server/admin_server/upgrader/x19.10.22.02/pkg.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/service.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/cloudarea.go
  src/source_controller/coreservice/service/cloudarea.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand

#3412 update:ui: 主线模型不可创建必填字段 / 首页搜索UI调整
  src/ui/src/components/model-manage/field-group/field-detail/config.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/auth/auth-queue.js
  src/ui/src/components/ui/auth/auth.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
Labels: demand, optimization

#3422 主机属性复制 / 拓扑路径显示不正确
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology-new/host/host-list-options.vue
  src/ui/src/views/business-topology-new/host/host-list.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/set-template/children/template-intance.vue
  src/ui/src/views/set-template/sync-history.vue
Labels: bug, inner

#3421 添加auth小工具
  src/scene_server/topo_server/service/inst.go
  src/tools/cmdb_ctl/cmd/auth.go
  src/tools/cmdb_ctl/cmd/snapshot.go
  src/tools/cmdb_ctl/cmd/zk.go
  src/tools/cmdb_ctl/readme.md
Labels: demand

#3418 升级migration版本号方案
  src/auth/parser/operationstatistics.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/compare.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/admin_server/upgrader/x19.08.19.01/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201909062359/add_module_property.go
  src/scene_server/admin_server/upgrader/y3.6.201909062359/add_set_property.go
  src/scene_server/admin_server/upgrader/y3.6.201909062359/create_table.go
  src/scene_server/admin_server/upgrader/y3.6.201909062359/initialize_set_template_field.go
  src/scene_server/admin_server/upgrader/y3.6.201909062359/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201909272359/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201909272359/task.go
  src/scene_server/admin_server/upgrader/y3.6.201910091234/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201910091234/settemplate_sync_status.go
Labels: optimization

#3389 主机转移接口优化
  resources/errors/common/default/common.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/topo_server.json
  src/apiserver/service/url.go
  src/auth/parser/topolatest.go
  src/common/errInfo.go
  src/common/mapstruct/decode.go
  src/common/metadata/association.go
  src/common/metadata/core_service.go
  src/common/metadata/hostserver.go
  src/common/metadata/process.go
  src/common/metadata/result.go
  src/common/metadata/time.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/proc_server/logics/logic.go
  src/scene_server/proc_server/logics/logics.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/test/proc_server/no_service_template_test.go
Labels: demand

#3424 主页搜索框样式优化 / 鉴权组件调整
  src/ui/src/components/ui/auth/auth.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/index/children/search-input.vue
Labels: inner, optimization

#3420 新增标签,搜索无法选中标签
  src/ui/src/views/business-topology/children/service-instances.vue
Labels: demand

#3429 UI: 重命名业务拓扑目录
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-topology/children/batch-edit-label.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/business-topology/children/create-set.vue
  src/ui/src/views/business-topology/children/edit-label.vue
  src/ui/src/views/business-topology/children/service-instance-empty.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/edit-multiple-host.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/host/host-selector-custom.vue
  src/ui/src/views/business-topology/host/host-selector-topology.vue
  src/ui/src/views/business-topology/host/host-selector.vue
  src/ui/src/views/business-topology/host/module-selector.vue
  src/ui/src/views/business-topology/host/move-to-resource-confirm.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/index.js
  src/ui/src/views/service-instance/children/clone-to-other.vue
  src/ui/src/views/service-instance/create.vue
Labels: inner

#3425 fix: 导入实例关联时鉴权错误
  src/auth/extensions/instance.go
  src/scene_server/topo_server/core/operation/import_association.go
Labels: bug

#3426 add: topo check tool
  src/tools/cmdb_ctl/app/config/config.go
  src/tools/cmdb_ctl/cmd/log.go
  src/tools/cmdb_ctl/cmd/snapshot.go
  src/tools/cmdb_ctl/cmd/topo.go
  src/tools/cmdb_ctl/cmd/zk.go
  src/tools/cmdb_ctl/readme.md
Labels: demand

#3430 demand: 支持内外网IP的多IP搜索功能。
  src/common/paraparse/host.go
  src/scene_server/host_server/logics/hostsearch.go
Labels: demand

#3353 移除查询模型属性时多余的查询模型分组操作
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/inst_business.go
Labels: optimization

#3435 V3.6.x后端bugfix
  src/auth/authcenter/perm_initial.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/operation_server/app/server.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/source_controller/coreservice/core/mainline/manager.go
Labels: bug

#3433 3.6回归优化
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/components/ui/auth/auth.vue
  src/ui/src/components/ui/form/enum.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/service-instance-empty.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/model-topology/index.new.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
  src/ui/src/views/set-template/index.vue
Labels: optimization

#3442 optimize: revise cmdb tool echo server
  src/tools/cmdb_ctl/cmd/echo.go
Labels: optimization

#3441 3.6 回归优化
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/set-sync/set-instance.vue
  src/ui/src/views/set-template/children/template-tree.vue
Labels: bug, optimization

#3448 fix: 查询实例关联拓扑apiserver parser正则重复
  src/auth/parser/topology.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: bug

#3447 coreservice validator 性能优化
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator_unique.go
  src/source_controller/coreservice/core/instances/validator_util.go
Labels: optimization

#3446 optimize: revise cmdb tool auth command
  src/tools/cmdb_ctl/cmd/auth.go
  src/tools/cmdb_ctl/cmd/util.go
Labels: optimization

#3444 update:ui: 表格无权限优化 / 运营统计交互调整
  src/ui/src/components/ui/form/enum.vue
  src/ui/src/components/ui/table-empty/table-empty.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/operation/index.vue
Labels: inner, optimization

#3453 optimize:ui: 3.6 交互体验优化
  src/ui/src/components/ui/form/objuser.vue
  src/ui/src/dictionary/menu.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/index.js
  src/ui/src/setup/permission.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/service-template/children/process-form.vue
Labels: inner, optimization

#3451 optimize: add preData in host identifier event.
  src/scene_server/event_server/identifier/identifier.go
  src/tools/cmdb_ctl/cmd/auth.go
Labels: optimization

#3437 添加待回收模块
  resources/errors/common/default/core_service.json
  resources/language/default/inst.json
  resources/language/default/oplogdesc.json
  resources/language/en/inst.json
  resources/language/en/oplogdesc.json
  src/apimachinery/coreservice/process/api.go
  src/apiserver/core/compatiblev2/service/host.go
  src/auth/authcenter/adaptor.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/auth/parser/host.go
  src/common/definitions.go
  src/common/metadata/common.go
  src/common/metadata/core_service.go
  src/common/util/array.go
  src/scene_server/admin_server/command/getter.go
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/admin_server/upgrader/v3.0.8/upgradeBKBiz.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/admin_server/upgrader/y3.6.201911121930/add_recycle_module.go
  src/scene_server/admin_server/upgrader/y3.6.201911121930/pkg.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/synchronize_server/logics/inst.go
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/inst_set.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/host/transfer/transfer.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/translate.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_test.go
  src/test/host_server/user_test.go
  src/test/topo_server/object_test.go
Labels: demand

#3449 移除集群和模块实例的metadata字段
  src/auth/parser/framework.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/admin_server/upgrader/y3.6.201910091234/settemplate_sync_status.go
  src/scene_server/admin_server/upgrader/y3.6.201911141015/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201911141015/remove_metadata.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
Labels: demand

#3440 添加移除主线模型自定义字段必填属性的upgrader
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.10.22.03/pkg.go
  src/scene_server/admin_server/upgrader/x19.10.22.03/remove_mainline_property_required.go
Labels: demand

#3462 fix：更新实例旧接口权限资源解析错误
  src/auth/parser/topology.go
Labels: bug

#3463 auth 小工具添加输入json文件的功能
  src/tools/cmdb_ctl/cmd/auth.go
  src/tools/cmdb_ctl/readme.md
Labels: demand

#3457 fix：模型之间可以创建不同关联类型的多个关联
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/association/model_private.go
Labels: demand

#3472 模型拓扑交互优化
  src/ui/src/views/model-topology/index.new.vue
Labels: inner, optimization

#3475 fix: querybuilder 嵌套深度
  src/common/querybuilder/types.go
Labels: demand

#3476 通过模板同步进程实例属性时，进程实例属性bind_ip原始值nil时同步的bind_ip没有转换成ip地址bugfix(模板中的值为1, 2)
  src/common/metadata/process.go
Labels: bug

#3464 fix: validator 判断数字允许字符串
  src/common/util/conv.go
  src/source_controller/coreservice/core/instances/validator_attr.go
Labels: demand

#3460 实例导入，根据ID区分是新建，更新
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst.go
Labels: demand, inner

#3445 fix: excel导入导出，把必填字段放最前面
  src/web_server/logics/excel.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/netdevice.go
  src/web_server/logics/netproperty.go
Labels: demand

#3478 3.6回归优化
  src/ui/package.json
  src/ui/src/assets/json/model-icon.json
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/table-empty/table-empty.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/business-topology/children/create-set.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/custom-fields/router.config.js
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/eventpush/push-detail.vue
  src/ui/src/views/host-operation/children/create-service-instance.vue
  src/ui/src/views/host-operation/children/move-to-idle-host.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-manage/children/verification-detail/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-sync/set-instance.vue
  src/ui/src/views/set-sync/sync-index.vue
  src/ui/src/views/set-template/children/template-config.vue
  src/ui/src/views/set-template/template.vue
Labels: optimization

#3455 集群模板与集群实例对比接口：新增返回模块主机数信息 #3024
  src/apimachinery/toposerver/settemplate/apis.go
  src/apimachinery/toposerver/settemplate/settemplate.go
  src/auth/parser/topology.go
  src/common/metadata/page.go
  src/common/metadata/set_template_request.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/scene_server/topo_server/service/set_template.go
  src/test/topo_server/set_template_test.go
Labels: demand

#3436 feature: 统计报表从zk读取定时的时间，时间格式: 00:00 - 23:59
  src/common/definitions.go
  src/scene_server/operation_server/app/options/options.go
  src/scene_server/operation_server/app/server.go
  src/scene_server/operation_server/logics/core.go
  src/scene_server/operation_server/logics/logics.go
  src/scene_server/operation_server/service/service.go
  src/source_controller/coreservice/core/operation/inner_chart.go
  src/source_controller/coreservice/core/operation/operation.go
  src/source_controller/coreservice/service/operation.go
Labels: demand

#3452 feature: 新加列表(list)字段类型
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  resources/language/default/property.json
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/process.go
  src/common/util/valid.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.6.201911141516/obj_host_add_field_type_list.go
  src/scene_server/admin_server/upgrader/y3.6.201911141516/pkg.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/validator/valid_basic.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator_attr.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/translate.go
  src/tools/cmdb_ctl/cmd/snapshot.go
  src/tools/cmdb_ctl/cmd/topo.go
Labels: demand

#3485 fix：新增列表字段，规范错误码，输出错误日志
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/errInfo.go
  src/scene_server/validator/valid_basic.go
Labels: optimization

#3483 refactor:delete v2 compatible api code issue #3482
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/apimachinery/toposerver/openapi/api.go
  src/apimachinery/toposerver/openapi/openapi.go
  src/apimachinery/toposerver/toposerver.go
  src/apiserver/core/compatiblev2/common/converter/converter.go
  src/apiserver/core/compatiblev2/common/defs/defs.go
  src/apiserver/core/compatiblev2/common/utils/utils.go
  src/apiserver/core/compatiblev2/common/utils/utils_test.go
  src/apiserver/core/compatiblev2/logic/fileds.go
  src/apiserver/core/compatiblev2/logic/logic.go
  src/apiserver/core/compatiblev2/logic/search.go
  src/apiserver/core/compatiblev2/logic/topo.go
  src/apiserver/core/compatiblev2/logic/userapi.go
  src/apiserver/core/compatiblev2/service/addhost.go
  src/apiserver/core/compatiblev2/service/application.go
  src/apiserver/core/compatiblev2/service/host.go
  src/apiserver/core/compatiblev2/service/module.go
  src/apiserver/core/compatiblev2/service/plat.go
  src/apiserver/core/compatiblev2/service/property.go
  src/apiserver/core/compatiblev2/service/search.go
  src/apiserver/core/compatiblev2/service/searchext.go
  src/apiserver/core/compatiblev2/service/service.go
  src/apiserver/core/compatiblev2/service/set.go
  src/apiserver/core/compatiblev2/service/userapi.go
  src/apiserver/core/core.go
  src/apiserver/service/service.go
  src/common/definitions.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/logics/phpapi_searchhost.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/service.go
  src/scene_server/topo_server/service/compatiblev2.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/test/host_server/host_test.go
Labels: demand

#3486 update:ui: 模型新增list（列表）字段
  src/ui/src/components/model-manage/field-group/field-detail/config.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/field-detail/list.vue
  src/ui/src/components/model-manage/field-group/field-view.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/list.vue
  src/ui/src/components/ui/index.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
Labels: demand

#3487 UI： 服务模板配置页面改造
  src/ui/package.json
  src/ui/src/App.vue
  src/ui/src/assets/scss/_vars.scss
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/columns-config/columns-config.vue
  src/ui/src/components/feature-tips/index.vue
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/components/model-manage/choose-icon/_choose-icon.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/components/ui/dialog/dialog.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/store/modules/api/object-main-line-module.js
  src/ui/src/store/modules/api/service-template.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-synchronous/router.config.js
  src/ui/src/views/business-topology/children/service-instance-empty.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/host/host-selector-topology.vue
  src/ui/src/views/business-topology/host/host-selector.vue
  src/ui/src/views/business-topology/host/module-selector.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/cloud-confirm/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/operation/router.config.js
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-instance/children/clone-to-other.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/children/process.vue
  src/ui/src/views/service-template/children/template-instance.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/service-template/router.config.js
  src/ui/src/views/service-template/template.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
  src/ui/src/views/set-template/children/template-config.vue
  src/ui/src/views/set-template/children/template-intance.vue
  src/ui/src/views/set-template/index.vue
  src/ui/src/views/set-template/sync-history.vue
  src/ui/src/views/set-template/template.vue
Labels: demand, inner, optimization

#3480 主机身份bugfix
  src/common/metadata/inst.go
  src/scene_server/event_server/identifier/hostcache.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/event_server/service/subscription.go
  src/source_controller/coreservice/core/host/identifier/identifier.go
Labels: bug, optimization

#3488 remove validator related redundant code.
  src/common/definitions.go
  src/common/util/conv.go
  src/scene_server/admin_server/upgrader/v3.0.8/addDefauleApp.go
  src/scene_server/admin_server/upgrader/v3.0.8/objAttDescData.go
  src/scene_server/admin_server/upgrader/v3.0.9-beta.3/fixes_port_pattern.go
  src/scene_server/admin_server/upgrader/x08.09.04.01/updateSystemProperty.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.12.12.01/add_aix_property.go
  src/scene_server/admin_server/upgrader/x18.12.12.01/set_tcp_default.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/supplementary.go
  src/scene_server/topo_server/core/operation/supplementary_auth.go
  src/scene_server/topo_server/core/operation/supplementary_validator.go
  src/scene_server/validator/type.go
  src/scene_server/validator/util.go
  src/scene_server/validator/valid_basic.go
  src/scene_server/validator/valid_unique.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator_attr.go
  src/source_controller/coreservice/core/instances/validator_util.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/test/host_server/host_abnormal_test.go
  src/web_server/logics/fields.go
  src/web_server/middleware/user/owner.go
Labels: demand, optimization

#3493 修复 create_object_attribute 接口权限解析无layer信息
  src/auth/parser/topology.go
Labels: bug

#3502 修复metrics不同请求参数生成多个handler记录
  src/common/metrics/gauge.go
  src/common/metrics/metrics.go
Labels: bug

#3504 集成测试失败时提示信息添加http返回
  src/test/event_server/event_server_suite_test.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_server_suite_test.go
  src/test/host_server/host_test.go
  src/test/host_server/user_test.go
  src/test/proc_server/no_service_template_test.go
  src/test/proc_server/proc_server_suite_test.go
  src/test/proc_server/service_template_test.go
  src/test/test.go
  src/test/topo_server/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/object_test.go
  src/test/topo_server/topo_server_suite_test.go
  src/test/util/fail.go
Labels: demand

#3500 初始化脚本里增加对eventserver的授权认证使用控制
  scripts/init.py
Labels: demand

#3509 feature:ui: 小窗登陆
  src/ui/package.json
  src/ui/src/App.vue
  src/ui/src/api/index.js
  src/ui/src/router/index.js
  src/ui/static/login_success.html
Labels: demand, inner

#3513 optimize: 查询业务相关接口优化
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/app.go
  src/common/metadata/toposerver.go
  src/common/paraparse/app.go
  src/common/universalsql/mongo/condition_private.go
  src/common/universalsql/mongo/element.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/inst_business.go
  src/web_server/middleware/user/owner.go
Labels: optimization

#3512 修复auth在blog的flag没有赋值完成的时候调用导致blog的部分flag不生效
  src/common/auth/auth.go
  src/common/util/flags.go
Labels: optimization

#3508 修复模型拓扑默认图标缩放太小和鼠标滚轮缩放比例太大问题
  src/ui/src/views/model-topology/index.new.vue
Labels: optimization

#3496 添加进程关系变化的主机身份事件推送
  src/scene_server/event_server/distribution/callback.go
  src/scene_server/event_server/distribution/distribution.go
  src/scene_server/event_server/distribution/handle_event.go
  src/scene_server/event_server/identifier/identifier.go
  src/source_controller/coreservice/core/process/base.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/service/service.go
Labels: demand

#3506 权限同步流控优化
  scripts/init.py
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/type.go
  src/scene_server/admin_server/authsynchronizer/handler/core.go
  src/scene_server/admin_server/authsynchronizer/meta/types.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/authsynchronizer/synchronizer.go
  src/scene_server/admin_server/authsynchronizer/worker.go
Labels: optimization

#3517 fix: test util package conflict
  src/test/topo_server/object_test.go
Labels: demand

#3516 fix:ui: 修复动态分组预览表格limit定位偏移的问题
  src/ui/src/views/custom-query/preview.vue
Labels: bug, inner

#3518 fix: 运营统计定时配置，配置解析失败，设置默认时间
  scripts/init.py
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/init_chart.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/upgrader.go
  src/scene_server/operation_server/service/service.go
  src/ui/src/views/operation/index.vue
Labels: bug

#3515 新增拓扑节点主机数查询接口
  src/auth/parser/host.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/service/findhost.go
  src/scene_server/host_server/service/service.go
Labels: demand

#3519 fix: import upgrade y3.6.201911261109
  src/scene_server/admin_server/imports.go
Labels: demand

#3523 fix: update/operation/chart/position auth parser missing
  src/auth/parser/operationstatistics.go
Labels: bug

#3525 UI: Bugfix
  src/ui/src/components/hosts/filter/_filter-field-operator.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/host-operation/children/create-service-instance.vue
  src/ui/src/views/host-operation/index.vue
Labels: bug, inner

#3527 update:ui: 体验优化
  src/ui/src/components/columns-config/columns-config.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/store/modules/api/set-template.js
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/host/move-to-resource-confirm.vue
  src/ui/src/views/custom-fields/index.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/resource-manage/index.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/template-instance.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
  src/ui/src/views/set-template/children/template-tree.vue
  src/ui/src/views/set-template/index.vue
Labels: inner, optimization

#3531 UI: 添加离开确认组件
  src/ui/src/components/ui/dialog/confirm-store.js
  src/ui/src/components/ui/dialog/leave-confirm.vue
  src/ui/src/components/ui/index.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/host-temp/apply-status.vue
Labels: demand, inner

#3526 update:ui: 切换查询业务列表的接口
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/views/business-topology/host/host-selector.vue
Labels: demand, inner

#3529 fix: biz attribute unique check missing biz info
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/attribute_private.go
Labels: bug
