Repository Tencent/bk-cmdb, pull requests merged in 2019-01, with the labels that each got.

#1664 add 3 pictures
  docs/wiki/img/bk_cmdb.png
  docs/wiki/img/flow_all.png
  docs/wiki/img/flow_cmdb.png
Labels: demand, inner

#1642 feature: 实例校验支持metadata label维度的数据校验
  resources/configures/coreservice.conf
  src/common/definitions.go
  src/common/metadata/metadata.go
  src/common/universalsql/mongo/condition_private.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator.go
  src/source_controller/coreservice/core/instances/validator_unique.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/readme.md
Labels: demand, inner

#1667 fix: ModuleNamePropertyGroup
  src/scene_server/admin_server/upgrader/x18.12.12.02/pkg.go
Labels: bug, inner

#1670 fix: 内置模型修复多语言支持问题
  resources/language/default/description.json
  resources/language/default/placeholder.json
  resources/language/default/property_group.json
  resources/language/en/description.json
  resources/language/en/placeholder.json
  resources/language/en/property.json
  resources/language/en/property_group.json
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/object.go
  src/scene_server/validator/valid_basic.go
  src/scene_server/validator/valid_unique.go
  src/source_controller/objectcontroller/service/common.go
  src/source_controller/objectcontroller/service/objectatt_action.go
Labels: bug, inner

#1680 Update readme.md
  readme.md
Labels: demand, inner

#1683 refactor: proc log use http request id issue #1682
  src/common/rdapi/rdfunc.go
  src/common/util/lib.go
  src/scene_server/host_server/logics/hostlock.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/logics/appinstance.go
  src/scene_server/proc_server/logics/backgroup.go
  src/scene_server/proc_server/logics/gsehandle.go
  src/scene_server/proc_server/logics/host.go
  src/scene_server/proc_server/logics/instance.go
  src/scene_server/proc_server/logics/instanceconst.go
  src/scene_server/proc_server/logics/instanceutil.go
  src/scene_server/proc_server/logics/log.go
  src/scene_server/proc_server/logics/logics.go
  src/scene_server/proc_server/logics/matchprocinstance.go
  src/scene_server/proc_server/logics/process.go
  src/scene_server/proc_server/logics/task.go
  src/scene_server/proc_server/logics/template.go
  src/scene_server/proc_server/logics/topo.go
  src/scene_server/proc_server/logics/variables.go
  src/scene_server/proc_server/proc_service/service/init_func.go
  src/scene_server/proc_server/proc_service/service/openapi.go
  src/scene_server/proc_server/proc_service/service/proc2module.go
  src/scene_server/proc_server/proc_service/service/procdetail.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/proc_server/proc_service/service/procinstance.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/proc_server/proc_service/service/template.go
  src/scene_server/proc_server/proc_service/service/templatefile.go
  src/scene_server/proc_server/proc_service/service/templateversion.go
Labels: demand, inner, optimization

#1676 change switch type to reflect and rebuild the query condition by the metadata
  src/common/mapstr/export_functions.go
  src/common/mapstr/export_private_functions.go
  src/common/mapstr/mapstr_test.go
  src/common/universalsql/mongo/condition_private.go
  src/common/universalsql/mongo/condition_test.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/attribute_private.go
  src/source_controller/coreservice/core/model/attribute_test.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/classification_test.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_test.go
Labels: demand, inner

#1686 optimize: UI优化
  src/ui/src/assets/json/static-navigation.json
  src/ui/src/components/hosts/table/_host-topo.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
Labels: inner, optimization

#1688 refactor: 隐藏模型子网区域、进程
  src/ui/src/assets/scss/model-manage.scss
  src/ui/src/router/index.js
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/field-detail/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification-detail/index.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
Labels: inner, optimization

#1687 update coreservice testcase #1685
  src/common/metadata/core_service.go
  src/common/metadata/result.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/mock_test.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_attribute_group.go
  src/source_controller/coreservice/core/model/model_test.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/model_classification_test.go
  src/source_controller/coreservice/service/model_test.go
  src/source_controller/coreservice/service/service_test.go
Labels: inner, optimization

#1692 feature:Mapstr supports parsing pointer fields within structs
  src/common/mapstr/export_functions.go
  src/common/mapstr/export_private_functions.go
  src/common/mapstr/mapstr_test.go
  src/common/mapstr/struct_tags.go
  src/common/mapstr/struct_tags_private.go
  src/common/mapstr/struct_tags_test.go
Labels: bug, inner

#1694 fix: enterIP add host info, ostype field value error issue #1693
  src/api_server/service/v2/addhost.go
Labels: bug, inner

#1697 optimize : delete biz id in topo graphic.
  src/common/metadata/graphic.go
  src/scene_server/topo_server/core/operation/graphics.go
Labels: inner, optimization

#1699 fix: Support for conversion to multi-type maps for MapStr #1625
  src/common/mapstr/mapstr_test.go
  src/common/mapstr/struct_tags_private.go
  src/common/mapstr/to_value.go
  src/source_controller/coreservice/service/model_test.go
Labels: bug, inner

#1701 feature: add synchronize api for framework
  src/apimachinery/util/client.go
  src/common/http/httpclient/client.go
  src/common/metadata/graphic.go
  src/common/ssl/ssl.go
  src/framework/api/api.go
  src/framework/api/output_host.go
  src/framework/api/wrapper_host.go
  src/framework/clientset/business/api.go
  src/framework/clientset/business/business.go
  src/framework/clientset/clientset.go
  src/framework/clientset/discovery/discovery.go
  src/framework/clientset/host/api.go
  src/framework/clientset/host/host.go
  src/framework/clientset/model/api.go
  src/framework/clientset/model/attribute.go
  src/framework/clientset/model/instance.go
  src/framework/clientset/model/model.go
  src/framework/clientset/model/moudle.go
  src/framework/clientset/model/set.go
  src/framework/clientset/types/attribute.go
  src/framework/clientset/types/business.go
  src/framework/clientset/types/error.go
  src/framework/clientset/types/host.go
  src/framework/clientset/types/instance.go
  src/framework/clientset/types/model.go
  src/framework/clientset/types/moudle.go
  src/framework/clientset/types/set.go
  src/framework/clientset/types/types.go
  src/framework/common/http/client.go
  src/framework/common/http/server.go
  src/framework/common/http/type.go
  src/framework/common/rest/request.go
  src/framework/common/rest/rest.go
  src/framework/common/rest/type.go
  src/framework/common/struct_tags.go
  src/framework/core/discovery/rdiscover.go
  src/framework/core/input/input.go
  src/framework/core/input/input_private.go
  src/framework/core/input/type.go
  src/framework/core/input/wrapper.go
  src/framework/core/manager/event.go
  src/framework/core/manager/event_business.go
  src/framework/core/manager/factory.go
  src/framework/core/manager/manager.go
  src/framework/core/output/module/client/v3/client.go
  src/framework/core/output/module/client/v3/inst_host.go
  src/framework/core/output/module/client/v3/model.go
  src/framework/core/output/module/client/v3/module.go
  src/framework/core/output/module/inst/inst_host.go
  src/framework/core/output/module/inst/inst_module.go
  src/framework/core/output/module/model/model.go
  src/framework/core/output/output_model.go
  src/framework/core/output/type.go
  src/framework/core/types/mapstr.go
  src/framework/main.go
  src/framework/plugins/sync/sync.go
  src/scene_server/topo_server/core/operation/graphics.go
Labels: demand, inner

#1698 feature:[v3.2.x] http filter 功能
  src/api_server/service/v2/service.go
  src/api_server/service/v3/service.go
  src/common/rdapi/rdfunc.go
  src/scene_server/admin_server/service/service.go
  src/scene_server/datacollection/service/service.go
  src/scene_server/event_server/service/service.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/auditcontroller/service/service.go
  src/source_controller/hostcontroller/service/service.go
  src/source_controller/objectcontroller/service/service.go
  src/source_controller/proccontroller/service/service.go
Labels: demand, inner, optimization

#1696 feature:[v3.3.x]toposerver,coreservice add http request filter issue …
  src/common/rdapi/rdfunc.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/service/service.go
Labels: demand, inner, optimization

#1703 test:add attribute group testcase, issue #1644
  src/common/mapstr/mapstr_test.go
  src/source_controller/coreservice/core/model/model_attribute_group.go
  src/source_controller/coreservice/core/model/model_attribute_group_crud.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/model_attribute_group_test.go
  src/source_controller/coreservice/service/model_attribute_test.go
Labels: bug, inner

#1704 fix: fix a panic in attribute query api.
  src/scene_server/topo_server/core/model/attribute.go
Labels: bug, inner

#1705 fix:Model ID unassigned bug, issue #1494
  src/source_controller/coreservice/core/model/model_crud.go
Labels: bug, inner

#1706 修复coreservice属性相关问题
  scripts/start.sh
  scripts/stop.sh
  scripts/template.sh.stop
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/rest/request.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/operation/group.go
  src/scene_server/topo_server/core/operation/object.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/model_crud.go
  vendor/github.com/golang/glog/glog.go
Labels: bug, inner

#1712 fix:set model association id, issue #1710
  src/source_controller/coreservice/core/association/model_crud.go
Labels: bug, inner

#1718 test:add some testcase for model association, issue #1644
  src/common/metadata/association.go
  src/common/metadata/time.go
  src/source_controller/coreservice/core/association/model_private.go
  src/source_controller/coreservice/service/model_association_test.go
Labels: inner, optimization

#1721 test:add testcase for time, issue #1720
  src/common/metadata/association_test.go
  src/common/metadata/attribute_test.go
  src/common/metadata/classification_test.go
  src/common/metadata/common_test.go
  src/common/metadata/eventserver_test.go
  src/common/metadata/graphic_test.go
  src/common/metadata/group_test.go
  src/common/metadata/inst_test.go
  src/common/metadata/log_test.go
  src/common/metadata/metadata_test.go
  src/common/metadata/privilege_test.go
  src/common/metadata/query_test.go
  src/common/metadata/querycondition_test.go
  src/common/metadata/time_test.go
Labels: inner, optimization

#1726 test:replace the time parser by the 'github.com/coccyx/timeparser'
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/server.go
  src/common/backbone/register.go
  src/common/identification.go
  src/common/identification_test.go
  src/common/metadata/attribute.go
  src/common/metadata/classification.go
  src/common/metadata/group.go
  src/common/metadata/object.go
  src/common/metadata/object_controller.go
  src/common/metadata/privilege.go
  src/common/metadata/time.go
  src/common/registerdiscover/interface.go
  src/common/registerdiscover/registerdiscover.go
  src/common/registerdiscover/zkregdiscv.go
  src/framework/core/discovery/rdiscover.go
  src/source_controller/coreservice/service/model_test.go
  src/web_server/app/rdiscover/rdiscover.go
Labels: bug, inner

#1731 refactor: fix import attribute
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/factory.go
  src/scene_server/topo_server/core/model/object.go
Labels: bug, inner

#1734 refactor: replace the update owner way in a condition , issue #1727
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_attribute_group.go
  src/source_controller/coreservice/service/model_classification_test.go
Labels: inner, optimization

#1741 fix:if the value in mapstr is nil, then to convert nil to array object for $in and $nin operator, issue #1738
  src/common/universalsql/mongo/condition_test.go
  src/common/universalsql/mongo/element.go
Labels: inner, optimization

#1743 feature:clean the right control code, issue #1737
  src/api_server/main.go
  src/api_server/middleware/auth.go
  src/api_server/middleware/router.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/privilege.go
  src/scene_server/topo_server/core/privilege/group.go
  src/scene_server/topo_server/core/privilege/privilege.go
  src/scene_server/topo_server/core/privilege/role.go
  src/scene_server/topo_server/service/privilege.go
  src/scene_server/topo_server/service/privilege_group.go
  src/scene_server/topo_server/service/privilege_role.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/objectcontroller/service/privilege_action.go
  src/source_controller/objectcontroller/service/role_action.go
  src/source_controller/objectcontroller/service/service.go
  src/web_server/app/server.go
  src/web_server/main.go
Labels: demand, inner

#1747 fix: should return modified value
  src/common/util/ownerutil.go
  src/common/util/ownerutil_test.go
  src/common/util/valid_test.go
Labels: bug, inner

#1757 refactor: fix not delete association when delete instance
  src/scene_server/topo_server/core/operation/inst.go
Labels: bug, inner

#1763 feature: add url parse chain filters. issue #1746
  src/auth/parser/chain.go
  src/auth/parser/parser.go
  src/auth/type.go
Labels: demand, inner

#1754 fix: 克隆主机。主机有已经被删除的字段，克隆失败
  src/scene_server/host_server/logics/phpapi.go
Labels: bug, inner

#1748 fix:ui: 修复转移主机时模块过多UI溢出的问题
  src/ui/src/components/hosts/transfer/index.vue
Labels: bug, inner, optimization

#1769 [refactor]更新excel 用户须知
  resources/language/default/import_comment_sheet.json
  resources/language/en/import_comment_sheet.json
  src/web_server/logics/excel_util.go
Labels: demand, inner

#1777 feature:add rest api with blueking auth center. issue #1771
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/type.go
  src/auth/type.go
Labels: demand, inner

#1765 fix: modify the reflect.Value validation checks for MapStr, issue #1727
  src/common/mapstr/deal_types.go
  src/common/mapstr/struct.go
Labels: bug, inner

#1779 create mainline测试用例运行失败处理：新增 bk_classification_id 为空的校验
  src/scene_server/topo_server/core/operation/association_mainline_object.go
Labels: inner, optimization

#1785 UI：修复主线自定义层级关联关系可以被删除的问题
  src/ui/src/views/model-manage/children/relation.vue
Labels: bug, inner
