Repository Tencent/bk-cmdb, pull requests merged in 2019-04, with the labels that each got.

#1965 调整代码检查告警
  src/api_server/app/server.go
  src/api_server/logics/v2/common/converter/converter.go
  src/api_server/logics/v2/fileds.go
  src/api_server/service/v2/userapi.go
  src/common/RegisterDiscover/zkregdiscv.go
  src/common/confregdiscover/zkregdiscover.go
  src/common/metric/api.go
  src/common/metric/go-metric.go
  src/common/metric/plugin/counter.go
  src/common/metric/type.go
  src/common/ssl/ssl.go
  src/common/util/flags.go
  src/common/util/struti.go
  src/scene_server/admin_server/command/command.go
  src/scene_server/admin_server/command/getter.go
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/command/types.go
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/admin_server/upgrader/doc.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/admin_server/upgrader/v3.0.8/addDefauleApp.go
  src/scene_server/admin_server/upgrader/v3.0.8/upgradeBKBiz.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.11.19.01/reconcil_asst_id.go
  src/scene_server/datacollection/datacollection/hostsnap.go
  src/scene_server/event_server/distribution/handle_event.go
  src/scene_server/event_server/distribution/reconclier.go
  src/scene_server/event_server/distribution/start.go
  src/scene_server/event_server/distribution/transaction.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/event_server/service/subscription.go
  src/scene_server/host_server/app/server.go
  src/scene_server/host_server/service/favourite.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/unique.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/validator/valid_unique.go
  src/source_controller/hostcontroller/service/favourite.go
  src/source_controller/hostcontroller/service/host.go
  src/source_controller/objectcontroller/service/identifier.go
  src/source_controller/objectcontroller/service/inst_action.go
  src/source_controller/objectcontroller/service/object_action.go
  src/source_controller/objectcontroller/service/object_unique.go
  src/source_controller/objectcontroller/service/objectasst_action.go
  src/source_controller/objectcontroller/service/objectatt_action.go
  src/source_controller/objectcontroller/service/objectatt_group_action.go
  src/source_controller/objectcontroller/service/objectcls_action.go
  src/storage/rpc/client.go
  src/storage/rpc/types.go
  src/storage/server/manager/txn_manager.go
  src/storage/types/types.go
  src/web_server/logics/excel.go
  src/web_server/logics/host.go
  src/web_server/middleware/login.go
  src/web_server/service/host.go
Labels: inner, optimization

#1974 Codereview adminserver
  src/scene_server/admin_server/command/getter.go
  src/scene_server/admin_server/common/definitions.go
  src/scene_server/admin_server/comparer/compare.go
Labels: inner, optimization

#1972 UI: 导航高亮与业务模式视图权限
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/components/layout/header.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/dictionary/menu.js
  src/ui/src/main.js
  src/ui/src/mixins/authority.js
  src/ui/src/router/index.bak.js
  src/ui/src/router/index.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/menu.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/business-model/router.config.js
  src/ui/src/views/business/router.config.js
  src/ui/src/views/custom-query/router.config.js
  src/ui/src/views/eventpush/router.config.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/index/children/classify-item.vue
  src/ui/src/views/index/router.config.js
  src/ui/src/views/model-association/router.config.js
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/permission/authority.vue
  src/ui/src/views/permission/business.vue
  src/ui/src/views/permission/index.vue
  src/ui/src/views/permission/role-form.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/process/router.config.js
  src/ui/src/views/resource/router.config.js
  src/ui/src/views/topology/router.config.js
  src/ui/static/svg/cc-resource.svg
Labels: demand, inner

#1979 fix:host transfer default module ,can has other module issue #1978
  src/source_controller/hostcontroller/logics/logics.go
Labels: bug, inner

#1980 修复v3.2.x分支中codecc扫描结果
  src/api_server/logics/v2/topo.go
  src/api_server/service/v2/userapi.go
  src/apimachinery/apiserver/api.go
  src/scene_server/host_server/service/host.go
  src/web_server/service/index.go
Labels: inner, optimization

#1990 V3.3.x
  src/common/definitions.go
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
Labels: demand, inner

#1989 V3.2.x
  src/common/definitions.go
  src/scene_server/datacollection/datacollection/hostsnap.go
Labels: demand, inner

#1988 V3.1.0
  src/common/definitions.go
  src/scene_server/datacollection/datacollection/hostsnap.go
Labels: demand, inner

#1976 修改权限中心模型
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_sys.go
  src/auth/meta/meta.go
  src/auth/parser/process.go
Labels: demand, inner

#1993 feature: coreservice get config after, run service issue #1992
  src/source_controller/coreservice/app/server.go
  src/source_controller/coreservice/service/service.go
Labels: inner, optimization

#1996 fix not delete association when delete instance
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: bug, inner

#1994 fix not delete association when delete instance
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: inner, optimization

#1975 optimize: 权限中心对接调试优化
  resources/errors/common/default/apiserver.json
  resources/errors/english/en/apiserver.json
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/discovery_mock.go
  src/apiserver/service/auth.go
  src/apiserver/service/service.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/type.go
  src/common/errInfo.go
  src/common/pidfile.go
  src/scene_server/host_server/host.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/web_server/middleware/login.go
Labels: inner, optimization

#1991 fix:host transfer default module ,can has other module issue #1978
  src/source_controller/hostcontroller/logics/logics.go
Labels: bug, inner

#1973 支持选择性开启事务
  src/api_server/logics/v2/fileds.go
  src/scene_server/event_server/app/server.go
  src/scene_server/event_server/distribution/start.go
  src/scene_server/topo_server/core/operation/association.go
Labels: demand, inner

#2006 v2接口查询到不同业务下的同名称模块下的进程 #2003
  src/scene_server/proc_server/proc_service/service/openapi.go
Labels: bug, inner

#2005 v2接口查询到不同业务下的同名称模块下的进程 #2003
  src/scene_server/proc_server/proc_service/service/openapi.go
Labels: bug, inner

#2004 v2接口查询到不同业务下的同名称模块下的进程
  src/scene_server/proc_server/proc_service/service/openapi.go
Labels: bug, inner

#2002 feature:run proc sync data issue #1780
  src/scene_server/synchronize_server/logics/synchronize.go
Labels: demand, inner

#2008 feature: add system base
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/id.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
Labels: demand, inner

#2012 feature: add OperationLog
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_sys.go
Labels: demand, inner

#2010 register association type to iam bugfix
  src/auth/extensions/association.go
  src/auth/extensions/classification.go
  src/auth/extensions/instance.go
  src/scene_server/topo_server/core/operation/association.go
Labels: bug, inner

#2015 UI: 业务模式鉴权
  src/ui/src/components/hosts/filter/_filter-config.vue
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/main.js
  src/ui/src/mixins/auth.js
  src/ui/src/mixins/classify.js
  src/ui/src/router/index.js
  src/ui/src/router/meta.js
  src/ui/src/setup/afterload.js
  src/ui/src/setup/preload.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/store/modules/api/user-privilege.js
  src/ui/src/store/modules/global.js
  src/ui/src/store/modules/menu.js
  src/ui/src/utils/tools.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/business/router.config.js
  src/ui/src/views/eventpush/push-detail.vue
  src/ui/src/views/eventpush/router.config.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/history/router.config.js
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/index/children/classify-item.vue
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/topology/index.vue
  src/ui/src/views/topology/router.config.js
Labels: demand, inner

#2017 ui: 无业务权限用户的伪鉴权
  src/ui/src/dictionary/auth.js
  src/ui/src/router/index.js
  src/ui/src/setup/afterload.js
  src/ui/src/setup/preload.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/custom-query/router.config.js
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/permission/role-form.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/process/router.config.js
  src/ui/src/views/resource/router.config.js
  src/ui/src/views/topology/router.config.js
Labels: demand, inner

#2019 create tomcat instance failed, as coreservice doesn't allow f…
  src/source_controller/coreservice/core/instances/instance_validate.go
Labels: inner, optimization

#2021 修复coreservice中数据缺少开发商的问题
  src/apimachinery/rest/request.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/association/kind_crud.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/service/instances.go
Labels: demand, inner

#2023 fix:ui: 修复后台模式判断错误的问题
  src/ui/src/setup/afterload.js
  src/ui/src/store/modules/global.js
Labels: bug, inner

#2022 权限中心调试问题修复
  src/auth/extensions/association.go
  src/auth/extensions/attribute.go
  src/auth/extensions/attributegroup.go
  src/auth/extensions/classification.go
  src/auth/extensions/host.go
  src/auth/extensions/modelunique.go
  src/auth/extensions/set.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/service/object_classification.go
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/login.go
Labels: demand, inner

#2026 fixes translate placeholder branch v3.2
  src/source_controller/objectcontroller/service/common.go
  src/source_controller/objectcontroller/service/objectatt_action.go
Labels: bug, inner

#2030 权限中心调试 bugfix
  src/auth/authcenter/client.go
  src/auth/extensions/attributegroup.go
  src/auth/extensions/business.go
  src/auth/extensions/instance.go
  src/auth/extensions/model.go
  src/auth/extensions/modelunique.go
  src/auth/extensions/types.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/unique.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/web_server/middleware/login.go
Labels: bug, inner, optimization

#2033 feature: add gitignore file. issue #2032
  .gitignore
Labels: demand, inner

#2035 optimize: association type and ignore file
  .gitignore
  scripts/Makefile
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/association.go
  src/auth/extensions/instance.go
  src/auth/meta/meta.go
  src/auth/parser/chain.go
  src/auth/parser/topology.go
Labels: inner, optimization

#2036 fix: fix create mainline object problem.
  src/auth/extensions/types.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/association.go
Labels: inner, optimization

#2038 ui: 模型管理页面操作鉴权
  src/ui/src/store/modules/menu.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/business/router.config.js
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/resource/router.config.js
Labels: bug, inner

#2042 optimize: 权限中心对接问题优化
  resources/errors/common/default/apiserver.json
  resources/errors/english/en/apiserver.json
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/permit/permit.go
  src/auth/meta/meta.go
  src/auth/parser/host.go
  src/auth/parser/parser.go
  src/auth/parser/topology.go
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/unique.go
  src/scene_server/topo_server/service/unique.go
  src/source_controller/coreservice/core/model/unique.go
  src/web_server/logics/inst.go
  src/web_server/service/inst.go
Labels: demand, inner, optimization

#2043 update gitignore file.
  .gitignore
Labels: inner, optimization

#2046 优化模型拓扑、视图、属性权限
  src/auth/extensions/model.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/graphics.go
  src/scene_server/topo_server/core/operation/object.go
Labels: inner, optimization

#2047 authorization on process sync and dynamic group
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/id.go
  src/auth/extensions/audit.go
  src/auth/extensions/dynamicgroup.go
  src/auth/extensions/model.go
  src/auth/extensions/process.go
  src/auth/extensions/types.go
  src/auth/meta/meta.go
  src/common/definitions.go
  src/common/tablenames.go
  src/scene_server/admin_server/synchronizer/handler/core.go
  src/scene_server/admin_server/synchronizer/handler/dynamicgroup.go
  src/scene_server/admin_server/synchronizer/handler/process.go
  src/scene_server/admin_server/synchronizer/meta/types.go
  src/scene_server/admin_server/synchronizer/producer.go
  src/scene_server/admin_server/synchronizer/worker.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/topo_server/core/operation/object.go
Labels: inner, optimization

#2048 fix:ui: 修复模型实例鉴权参数缺失parent_layers的问题
  src/ui/src/router/index.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/model-manage/router.config.js
Labels: bug, inner

#2051 修复 coreservice 创建模型唯一校验存在的问题
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/model/model.go
  src/common/metadata/core_service.go
  src/common/metadata/unique.go
  src/scene_server/topo_server/core/operation/unique.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/model/unique.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/objectcontroller/service/object_unique.go
  src/storage/dal/mongo/remote/mongo.go
Labels: demand, inner

#2049 将process注册迁移到extension模块
  src/scene_server/admin_server/synchronizer/handler/process.go
  src/scene_server/admin_server/synchronizer/producer.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/logics/logics.go
  src/scene_server/proc_server/logics/util.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/proc_server/proc_service/service/service.go
Labels: inner, optimization

#2052 进程保存按钮和模型删除按钮鉴权修改，模型页面数据刷新
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/process/index.vue
Labels: inner, optimization

#2031 添加资源池
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/perm_sys.go
  src/auth/extensions/instance.go
  src/auth/extensions/types.go
  src/auth/parser/topolatest.go
  src/web_server/middleware/login.go
Labels: demand, inner

#2059 完善审计日志鉴权
  src/auth/authcenter/authcenter.go
  src/auth/extensions/attributegroup.go
  src/auth/extensions/audit.go
  src/auth/extensions/modelunique.go
  src/scene_server/admin_server/synchronizer/handler/audit.go
  src/scene_server/admin_server/synchronizer/handler/core.go
  src/scene_server/admin_server/synchronizer/producer.go
  src/scene_server/topo_server/service/auditlog.go
  src/source_controller/auditcontroller/logics/audit.go
Labels: demand, inner

#2058 UI： 鉴权修复、路由跳转优化
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/ui/form/bool.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/router/StatusError.js
  src/ui/src/router/index.js
  src/ui/src/store/modules/api/operation-audit.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/history/router.config.js
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/process/module.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/resource/router.config.js
  src/ui/src/views/topology/index.vue
Labels: bug, inner, optimization

#2050 模型与实例权限优化，webserver新增权限中心配置
  src/auth/authcenter/id.go
  src/scene_server/topo_server/core/operation/unique.go
  src/scene_server/topo_server/service/unique.go
  src/web_server/app/options/options.go
  src/web_server/app/server.go
  src/web_server/service/index.go
Labels: inner, optimization

#2055 update:增加Aix操作系统类型支持
  src/api_server/logics/v2/common/converter/converter.go
Labels: demand, inner

#2056 update:增加Aix操作系统类型支持
  src/api_server/logics/v2/common/converter/converter.go
Labels: demand, inner

#2057 update:增加Aix操作系统类型支持
  src/api_server/ccapi/logics/v2/common/converter/converter.go
Labels: demand, inner

#2062 ui: 修复preload中metadata注入失败的问题
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/views/model-manage/index.vue
Labels: inner, optimization

#2065 fix: remove unused file
  src/scene_server/datacollection/datacollection/hostsnap.go
  src/scene_server/datacollection/datacollection/type.go
Labels: inner, optimization

#2077 v3.4.x 4/9 体验修复
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/perm_sys.go
  src/auth/extensions/business.go
  src/auth/parser/topolatest.go
  src/auth/parser/util.go
  src/common/definitions.go
  src/common/metadata/object.go
Labels: inner, optimization

#2079 业务查询优化
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/server.go
  src/apiserver/service/auth.go
  src/common/metadata/query.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst_business.go
Labels: inner, optimization

#2084 v3.4.x 体验优化
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/id.go
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/audit.go
  src/auth/extensions/instance.go
  src/auth/extensions/module.go
  src/auth/extensions/process.go
  src/auth/extensions/set.go
  src/auth/extensions/types.go
  src/auth/meta/meta.go
  src/auth/parser/host.go
  src/auth/parser/topolatest.go
  src/scene_server/admin_server/synchronizer/handler/audit.go
  src/scene_server/admin_server/synchronizer/handler/business.go
  src/scene_server/admin_server/synchronizer/handler/core.go
  src/scene_server/admin_server/synchronizer/handler/dynamicgroup.go
  src/scene_server/admin_server/synchronizer/handler/host.go
  src/scene_server/admin_server/synchronizer/handler/instance.go
  src/scene_server/admin_server/synchronizer/handler/model.go
  src/scene_server/admin_server/synchronizer/handler/module.go
  src/scene_server/admin_server/synchronizer/handler/process.go
  src/scene_server/admin_server/synchronizer/handler/set.go
  src/scene_server/admin_server/synchronizer/producer.go
  src/scene_server/host_server/service/module.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/auditcontroller/logics/audit.go
Labels: inner, optimization

#2089 UI: 修复自测问题
  src/ui/index.html
  src/ui/src/components/layout/header.vue
  src/ui/src/store/modules/api/object-model-property.js
  src/ui/src/utils/tools.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/group.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/resource/index.vue
  src/ui/src/views/status/require-business.vue
Labels: bug, demand, inner

#2090 style:fix codecc warning issue #1949
  src/common/metadata/webserver.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/logics/phpapi_searchhost.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/proc_server/logics/gsehandle.go
  src/scene_server/proc_server/proc_service/service/openapi.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/proc_server/proc_service/service/template.go
  src/web_server/logics/excel.go
  src/web_server/middleware/user/plugins/method/self/userinfo.go
Labels: inner, optimization

#2092 模型唯一约束权限控制调整 #2091
  src/auth/extensions/model.go
  src/auth/extensions/modelunique.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/unique.go
Labels: inner, optimization

#2087 update:ui: 优化3.4.x前端显示
  src/ui/src/components/layout/header.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/status/require-business.vue
Labels: inner, optimization

#2094 UI：添加权限中心配置
  src/ui/config/index.js
Labels: demand, inner

#2102 optimize: 模型分组、主机、set相关优化调整
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/base.go
  src/auth/extensions/classification.go
  src/auth/parser/host.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/scene_server/topo_server/core/operation/classification.go
  src/source_controller/coreservice/service/instances.go
  src/web_server/application/controllers/netdevice.go
  src/web_server/application/controllers/netproperty.go
  src/web_server/logics/host.go
  src/web_server/service/host.go
  src/web_server/service/object.go
Labels: inner, optimization

#2104 去掉公有云版体验相关描述
  docs/overview/experience.md
Labels: inner, optimization

#2108 模型拓扑与主机转移更新优化
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/business.go
  src/source_controller/objectcontroller/service/topographics.go
Labels: inner, optimization

#2101 支持本地权限控制
  src/apiserver/app/server.go
  src/apiserver/middleware/auth.go
  src/apiserver/middleware/router.go
  src/apiserver/service/service.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/privilege.go
  src/scene_server/topo_server/core/privilege/group.go
  src/scene_server/topo_server/core/privilege/privilege.go
  src/scene_server/topo_server/core/privilege/role.go
  src/scene_server/topo_server/service/privilege.go
  src/scene_server/topo_server/service/privilege_group.go
  src/scene_server/topo_server/service/privilege_role.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/objectcontroller/service/privilege_action.go
  src/source_controller/objectcontroller/service/role_action.go
  src/source_controller/objectcontroller/service/service.go
  src/web_server/app/server.go
  src/web_server/ui.go
Labels: demand, inner

#2109 object id可重复问题处理 issue #2088
  src/auth/extensions/attribute.go
  src/auth/extensions/attributegroup.go
  src/auth/extensions/instance.go
  src/auth/extensions/model.go
  src/auth/extensions/modelunique.go
  src/auth/extensions/types.go
  src/common/metadata/metadata.go
  src/common/metadata/metadata_test.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/unique.go
  src/source_controller/coreservice/core/model/unique_crud.go
Labels: demand, inner

#2110 支持选择性启用权限中心相关功能
  src/auth/authcenter/authcenter.go
  src/scene_server/host_server/app/server.go
  src/web_server/service/index.go
Labels: demand, inner

#2113 UI: 添加cmdb内置权限控制
  src/ui/.gitignore
  src/ui/config/index.js
  src/ui/index.html
  src/ui/src/api/index.js
  src/ui/src/api/middleware/auth.js
  src/ui/src/api/middleware/business.js
  src/ui/src/api/middleware/index.js
  src/ui/src/api/middleware/util.js
  src/ui/src/dictionary/menu.js
  src/ui/src/router/index.js
  src/ui/src/setup/preload.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/user-privilege.js
  src/ui/src/store/modules/menu.js
  src/ui/src/views/permission/authority.vue
  src/ui/src/views/permission/business.vue
  src/ui/src/views/permission/index.vue
  src/ui/src/views/permission/role-form.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/permission/router.config.js
Labels: demand, inner

#2114 导航鉴权问题
  src/ui/src/store/modules/menu.js
Labels: inner, optimization

#2115 ui: 资源池、操作审计、事件推送权限映射
  src/ui/src/api/middleware/auth.js
  src/ui/src/api/middleware/business.js
  src/ui/src/api/middleware/util.js
  src/ui/src/setup/preload.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/permission/authority.vue
Labels: demand, inner

#2117 解决权限更新只更新一部分的问题
  src/common/mapstr/struct.go
  src/web_server/app/options/options.go
  src/web_server/middleware/login.go
Labels: inner, optimization

#2120 codecc代码扫描优化
  src/apiserver/core/compatiblev2/logic/topo.go
  src/apiserver/core/compatiblev2/service/host.go
  src/apiserver/core/compatiblev2/service/search.go
  src/apiserver/core/compatiblev2/service/set.go
  src/common/metadata/core_service_synchronize.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/logics/phpapi_searchhost.go
  src/scene_server/host_server/service/favourite.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/proc_server/logics/instanceutil.go
  src/scene_server/proc_server/logics/process.go
  src/scene_server/proc_server/logics/topo.go
  src/scene_server/proc_server/proc_service/service/openapi.go
  src/scene_server/proc_server/proc_service/service/proc2template.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/proc_server/proc_service/service/template.go
  src/source_controller/coreservice/core/datasynchronize/association.go
  src/source_controller/coreservice/core/datasynchronize/instance.go
  src/source_controller/coreservice/core/datasynchronize/model.go
  src/web_server/logics/excel.go
  src/web_server/middleware/user/plugins/method/self/userinfo.go
Labels: inner, optimization

#2093 ui: 模型显示配置交互修改，支持模型隐藏
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/global-models.js
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/index.vue
Labels: demand, inner

#2125 V3.4.x hostimport 导入主机失败
  src/scene_server/host_server/logics/import.go
Labels: inner, optimization

#2126 feature-v3.4.0 object instance import, mapstr related optimize
  src/auth/extensions/host.go
  src/common/metadata/classification.go
  src/common/metadata/metadata.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/privilege/privilege.go
  src/scene_server/topo_server/service/identifier.go
  src/scene_server/topo_server/service/service.go
  src/web_server/logics/association.go
  src/web_server/logics/excel.go
  src/web_server/logics/fields.go
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
  src/web_server/service/host.go
  src/web_server/service/index.go
  src/web_server/service/inst.go
  src/web_server/service/object.go
  src/web_server/service/service.go
  src/web_server/service/util.go
Labels: inner, optimization

#2127 主机导出数据缺失修复 issue #2118
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/business.go
  src/auth/extensions/host.go
  src/auth/extensions/instance.go
  src/auth/extensions/model.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/scene_server/admin_server/synchronizer/handler/host.go
  src/scene_server/admin_server/synchronizer/handler/instance.go
  src/scene_server/topo_server/core/operation/object.go
  src/web_server/app/server.go
  src/web_server/logics/fields.go
  src/web_server/logics/host.go
  src/web_server/service/host.go
  src/web_server/service/object.go
Labels: inner, optimization

#2184 UI: 3.4.0 迭代回归
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/int.vue
  src/ui/src/components/ui/form/time.vue
  src/ui/src/components/ui/slider/slider.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/src/components/date-picker/date-picker.vue
  src/ui/src/mixins/form.js
  src/ui/src/store/modules/api/global-models.js
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/model-manage/children/group.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/permission/business.vue
  src/ui/src/views/permission/role-form.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/topology/index.vue
Labels: bug, inner, optimization

#2183 feature-3.4.0 前端问题回归优化
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/model-association/_detail.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/topology/index.vue
Labels: bug, inner

#2192 修复3.4关联问题
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.12.12.04/fix_bk_obj_asst_id.go
  src/scene_server/admin_server/upgrader/x18.12.12.04/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
  src/source_controller/coreservice/core/instances/validator_unique.go
  src/web_server/logics/association.go
  src/web_server/logics/excel.go
  src/web_server/logics/fields.go
  src/web_server/logics/object.go
  src/web_server/middleware/login.go
Labels: inner, optimization

#2186 修复3.2关联问题
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.12.12.04/fix_bk_obj_asst_id.go
  src/scene_server/admin_server/upgrader/x18.12.12.04/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: inner, optimization

#2116 时间组件添加按钮/更新样式/修复主机导出和收藏界面
  src/ui/src/assets/scss/admin-view.scss
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/ui/form/date-range.vue
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/host-batch.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/resource/index.vue
Labels: inner, optimization

#2195 fix: 关联关系设置页面，分辨率小的时候，看不到下面的分页栏
  src/ui/src/components/relation/_update.vue
Labels: optimization, outer

#2211 V3.4.x toposerver requestid
  src/scene_server/topo_server/core/types/types.go
  src/scene_server/topo_server/service/service.go
Labels: inner, optimization

#2204 3.2.x 回归调整
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/ui/form/float.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/int.vue
  src/ui/src/components/ui/slider/slider.vue
  src/ui/src/setup/validate.js
  src/ui/src/store/modules/api/global-models.js
  src/ui/src/store/modules/api/user-custom.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/model-association/_detail.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/index.vue
  src/ui/src/views/permission/role-form.vue
Labels: bug, inner, optimization

#2205 3.2.x 优化回归
  src/ui/src/api/index.js
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/ui/slider/slider.vue
  src/ui/src/magicbox/src/bk-magic-ui/src/dialog.scss
  src/ui/src/mixins/form.js
  src/ui/src/store/modules/api/global-models.js
  src/ui/src/utils/tools.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-topology/index.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/topology/index.vue
Labels: bug, inner, optimization

#2207 调整业务与关联类型搜索代码 / 修复业务变更记录搜索问题
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/model-association/index.vue
Labels: inner, optimization

#2208 UI: 3.4.0 缺陷修复
  src/ui/src/components/ui/form/float.vue
  src/ui/src/utils/tools.js
  src/ui/src/views/model-topology/index.old.vue
Labels: bug, inner

#2209 v3.2.x 导入相关优化
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/service/object_association.go
Labels: inner, optimization

#2217 fix: multip-tenant use superadmin not return all data issue #2216
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
Labels: bug, inner

#2218 v3.4.x 导入相关优化
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/service/object_association.go
Labels: inner, optimization

#2220 fixes warning
  src/common/mapstr/mapstr.go
  src/common/metadata/netdevice.go
  src/common/metric/api.go
  src/common/metric/client.go
  src/common/metric/floatOrStr.go
  src/common/metric/go-metric.go
  src/common/metric/plugin/counter.go
  src/common/metric/plugin/integer.go
  src/common/metric/type.go
  src/common/util/lib.go
  src/scene_server/admin_server/command/command.go
  src/scene_server/datacollection/datacollection/porter.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/service/privilege_role.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/web_server/service/index.go
Labels: inner, optimization

#2222 V3.4.x fix hosttoinnermodule
  src/source_controller/coreservice/core/host/modulehost/transfer.go
Labels: inner, optimization

#2197 Feature v3.4.0
  src/apimachinery/auditcontroller/api.go
  src/apimachinery/auditcontroller/auditcontroller.go
  src/apimachinery/coreservice/mainline/api.go
  src/auth/authcenter/authcenter.go
  src/auth/parser/topology.go
  src/common/auditoplog/operationlog.go
  src/common/mapping.go
  src/common/metadata/audit.go
  src/common/metadata/core_service.go
  src/scene_server/admin_server/command/types.go
  src/scene_server/admin_server/synchronizer/handler/instance.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/audit.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/inst_module.go
  src/source_controller/auditcontroller/service/service.go
  src/source_controller/auditcontroller/service/topology.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/mainline/instance.go
  src/source_controller/coreservice/core/mainline/manager.go
  src/web_server/service/host.go
Labels: inner, optimization

#2223 add join-bk-community doc
  docs/wiki/img/join_blueking_opensource_community.png
  docs/wiki/join-bk-community.md
Labels: demand, inner

#2226 解析metadata bugfix
  src/auth/parser/host.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/association.go
Labels: inner, optimization

#2228 optimize: code check and optimize.
  docs/overview/experience.md
  docs/overview/installation.md
  docs/wiki/img/join_blueking_opensource_community.png
  docs/wiki/join-bk-community.md
  src/common/metadata/hostserver.go
  src/common/metadata/toposerver.go
  src/common/util/mapbuilder.go
  src/common/util/mapbuilder_test.go
  src/framework/clientset/model/instance.go
  src/framework/common/rest/request.go
  src/framework/core/output/output_model.go
  src/scene_server/admin_server/upgrader/x18.11.07.01/pkg.go
  src/scene_server/admin_server/upgrader/x18.11.07.01/upgrader.go
  src/scene_server/datacollection/logics/property.go
  src/scene_server/host_server/service/host.go
  src/scene_server/topo_server/core/operation/group.go
  src/scene_server/topo_server/service/graphics.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_private.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_attribute_group.go
  src/source_controller/objectcontroller/service/inst_action.go
Labels: inner, optimization

#2225 UI: 首页改版与权限中心启用判断
  src/ui/config/index.js
  src/ui/index.html
  src/ui/src/api/middleware/index.js
  src/ui/src/components/layout/nav.vue
  src/ui/src/router/index.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/menu.js
  src/ui/src/store/modules/view/index.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/classify-item.vue
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/index/children/search.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/resource/index.vue
Labels: demand, inner

#2231 fix: NewConditionFromMapStr support boolean, slice, struct close #2229
  src/common/universalsql/mongo/condition_private.go
  src/common/universalsql/mongo/condition_test.go
Labels: inner, optimization

#2237 feature:ui: 默认使用内置权限
  src/ui/index.html
Labels: inner, optimization

#2239 UI: 首页优化
  src/ui/config/index.js
  src/ui/index.html
  src/ui/src/api/middleware/index.js
  src/ui/src/store/modules/menu.js
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/index/index.vue
Labels: bug, inner, optimization

#2243 update webserver config
  src/web_server/app/options/options.go
  src/web_server/app/server.go
  src/web_server/middleware/login.go
  src/web_server/service/index.go
Labels: inner, optimization

#2238 Solve 3.2.7
  src/apimachinery/rest/request.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.12.12.06/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
  src/scene_server/topo_server/core/operation/association.go
  src/web_server/logics/fields.go
  src/web_server/service/inst.go
  src/web_server/service/service.go
  vendor/github.com/golang/glog/glog.go
Labels: bug, inner

#2245 init.py代码规范及配置生成支持auth相关配置项
  scripts/init.py
Labels: demand, inner

#2246 主线拓扑实例可以通过重命名达到名称重复效果
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/validator/valid_unique.go
Labels: demand, inner

#2112 V3.4.x coreservice 主机转移逻辑下沉及hostserver 替换
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  resources/language/default/import_instance.json
  resources/language/en/import_instance.json
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/core_service_test.go
  src/common/util/lib.go
  src/scene_server/host_server/logics/app.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/logics/phpapi_searchhost.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/service.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/hostmoduleconfig.go
  src/source_controller/coreservice/core/host/modulehost/hostmodule.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
  src/source_controller/coreservice/service/host.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/hostcontroller/service/host.go
Labels: inner, optimization

#2249 optimize: rollback auth config for iam in webserver.
  src/web_server/app/options/options.go
  src/web_server/app/server.go
  src/web_server/service/index.go
Labels: demand, inner

#2248 修复codecc告警
  src/apimachinery/apiserver/api.go
  src/apiserver/core/compatiblev2/service/userapi.go
Labels: inner, optimization

#2254 fix:ui: 修复桌面版切换app失败的问题
  src/ui/src/views/resource/index.vue
  src/ui/src/views/status/require-business.vue
Labels: bug, inner

#2252 补充使用iam时本地鉴权跳过逻辑
  src/web_server/service/index.go
Labels: demand, inner

#2253 设置关联字段参数处理逻辑问题
  src/scene_server/topo_server/core/operation/inst.go
Labels: bug, inner

#2251 object controller中get privilege接口在没有权限数据时返回格式与有权限时格式不一致 #2250
  src/source_controller/objectcontroller/service/role_action.go
Labels: inner, optimization

#2255 optimize: rollback json package to encoding/json.
  src/apimachinery/clientset_coreservice_inst_test.go
  src/apimachinery/clientset_coreservice_model_test.go
  src/apimachinery/discovery/server.go
  src/apimachinery/rest/request.go
  src/apiserver/core/compatiblev2/common/utils/utils.go
  src/apiserver/core/compatiblev2/logic/topo.go
  src/apiserver/core/compatiblev2/service/host.go
  src/apiserver/core/compatiblev2/service/set.go
  src/auth/parser/host.go
  src/auth/parser/parser.go
  src/common/backbone/configcenter/cc.go
  src/common/core/cc/api/api_resource.go
  src/common/metadata/classification.go
  src/scene_server/topo_server/service/service.go
  src/web_server/service/util.go
Labels: inner, optimization

#2259 日志中打印redis等明文密码 不安全 #1986
  vendor/github.com/boj/redistore/redistore.go
Labels: inner, optimization

#2260 日志中打印redis等明文密码 不安全 #1986
  vendor/github.com/boj/redistore/redistore.go
Labels: inner, optimization

#2258 增强服务注册逻辑健壮性
  src/apimachinery/discovery/discovery.go
  src/common/backbone/backbone.go
  src/common/backbone/configcenter/parse.go
  src/common/backbone/http.go
  src/common/backbone/register.go
  src/common/backbone/service_mange/zk/zk.go
  src/common/registerdiscover/interface.go
  src/common/registerdiscover/registerdiscover.go
  src/common/registerdiscover/zkregdiscv.go
  src/scene_server/host_server/app/server.go
Labels: inner, optimization
