Repository Tencent/bk-cmdb, pull requests merged in 2019-05, with the labels that each got.

#2267 update make file
  scripts/Makefile
Labels: inner, optimization

#2270 查询业务模型属性时报解析授权信息失败 #2269
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/auth/authcenter/authcenter.go
  src/auth/parser/host.go
  src/auth/parser/topolatest.go
  src/common/errInfo.go
  src/scene_server/topo_server/core/inst/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/association.go
Labels: inner, optimization

#2265 feature: sync data between multiple bk-cmdb
  src/apimachinery/discovery/server.go
  src/common/definitions.go
  src/common/types/serverInfo.go
  src/scene_server/synchronize_server/app/options/options.go
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/synchronize_server/logics/background_synchronize.go
  src/scene_server/synchronize_server/logics/synchronize.go
  src/source_controller/coreservice/core/datasynchronize/find.go
  src/source_controller/coreservice/core/datasynchronize/model.go
  src/source_controller/coreservice/core/datasynchronize/util.go
  src/source_controller/coreservice/service/data_synchronize.go
Labels: demand, inner

#2280 demand: skip supplier strict, update makefile
  scripts/Makefile
  src/apiserver/service/service.go
  src/auth/authcenter/authcenter.go
Labels: demand, inner

#2286 配置生成脚本redis host中去掉端口号 #2283
  scripts/init.py
Labels: inner, optimization

#2282 fix:ui: 修复主机表格可能出现无表头字段的问题
  src/ui/src/components/hosts/table/index.vue
Labels: bug, inner

#2288 fix: clone host tips host not found issue #2287
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/host.go
Labels: bug, inner

#2285 id字段转换换成GetInt64ByInterface
  src/apimachinery/hostserver/apis.go
  src/auth/extensions/host.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/phpapi.go
Labels: inner, optimization

#2278 实例查询没有按path参数指定的类型过滤 #2166
  src/scene_server/topo_server/core/operation/inst.go
Labels: bug, inner

#2291 fix:ui: 修复导入文件对响应的处理配置不正确的问题
  src/ui/src/components/import/import.vue
  src/ui/src/views/model-manage/children/index.vue
Labels: bug, inner

#2290 修复官方bson库导致的解析enum失败问题 #2289
  src/scene_server/admin_server/upgrader/x19.04.16.02/updateFranceName.go
  src/source_controller/coreservice/core/instances/validator_attr.go
  src/source_controller/coreservice/core/instances/validator_util.go
  src/source_controller/coreservice/service/translate.go
Labels: inner, optimization

#2298 fix:a blan column appears when exporting the host in administrator mo…
  src/web_server/logics/fields.go
Labels: inner

#2296 V3.4.x 测试用例问题修复
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/apiserver/core/compatiblev2/service/plat.go
  src/scene_server/host_server/logics/app.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/phpapi.go
Labels: inner

#2302 主机，主线模型权限优化修复
  scripts/init.py
  src/auth/authcenter/adaptor.go
  src/auth/extensions/classification.go
  src/auth/extensions/instance.go
  src/auth/parser/host.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/common/metadata/metadata.go
  src/scene_server/admin_server/synchronizer/handler/classification.go
  src/scene_server/admin_server/synchronizer/meta/types.go
  src/scene_server/admin_server/synchronizer/producer.go
  src/scene_server/admin_server/synchronizer/worker.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst.go
Labels: bug, inner, optimization

#2299 UI: 部分删除接口metadata
  src/ui/src/assets/images/map.svg
  src/ui/src/components/hosts/filter/_collection.vue
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/store/modules/api/auth.js
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/index/children/map.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/model-manage/children/group.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/resource/index.vue
Labels: inner

#2300 补充18.12.12.06
  src/common/mapping.go
  src/common/metadata/core_service.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.12.12.06/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
  src/scene_server/topo_server/core/operation/object.go
  src/source_controller/coreservice/service/model.go
Labels: demand, inner

#2305 fix export object instance nil map issue
  src/web_server/service/inst.go
Labels: bug, inner

#2256 V3.2.x，模型关联1:n，实际是n:n。添加1：n校验。
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/admin_server/upgrader/v3.0.8/createtable.go
  src/scene_server/topo_server/core/operation/association.go
Labels: optimization, outer

#2308 禁止删除内置模型
  src/common/mapping.go
  src/scene_server/topo_server/core/operation/object.go
Labels: inner, optimization

#2313 UI: 修复导出文件无法打开的问题
  src/ui/src/api/index.js
Labels: bug, inner

#2315 V3.4.x 下载模型导入模版支持改为POST方法。支持业务模式
  src/web_server/service/service.go
Labels: demand, inner

#2310 独立配置项控制是否开启权限同步，默认不开启
  scripts/init.py
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/type.go
  src/scene_server/admin_server/app/server.go
Labels: inner, optimization

#2312 UI: 修复导出文件无法打开的问题
  src/ui/src/api/index.js
Labels: bug, inner

#2316 fix:ui: 下载模板get => post
  src/ui/src/api/index.js
  src/ui/src/components/import/import.vue
Labels: demand, inner

#2317 optimize get business topology auth
  src/auth/authcenter/permit/permit.go
Labels: demand, inner

#2318 业务拓扑查询主机接口优化
  src/common/metadata/core_service.go
  src/source_controller/coreservice/core/mainline/class.go
  src/source_controller/coreservice/core/mainline/manager.go
Labels: inner, optimization

#2321 demand: add host instance auth.
  src/auth/authcenter/id.go
Labels: inner, optimization

#2323 主机身份查询不再做鉴权
  resources/errors/common/default/host_server.json
  src/auth/parser/host.go
Labels: inner, optimization

#2324 optimize: code optimize
  src/apiserver/service/http.go
  src/apiserver/service/service.go
  src/auth/authcenter/id.go
  src/auth/parser/host.go
  src/auth/parser/process.go
  src/common/rdapi/rdfunc.go
Labels: inner, optimization

#2334 解决3.4回归问题
  src/apimachinery/clientset_coreservice_model_test.go
  src/common/definitions.go
  src/common/mapstr/mapstr.go
  src/common/metadata/time.go
  src/framework/clientset/types/attribute.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/v3.0.8/objAttDescData.go
  src/scene_server/admin_server/upgrader/v3.1.0-alpha.2/addBkStartParamRegex.go
  src/scene_server/admin_server/upgrader/x18.10.30.02/biz_supplier_id.go
  src/scene_server/admin_server/upgrader/x18.11.19.01/reconcil_unique.go
  src/scene_server/admin_server/upgrader/x18.12.12.01/add_aix_property.go
  src/scene_server/admin_server/upgrader/x19.04.16.03/pkg.go
  src/scene_server/admin_server/upgrader/x19.04.16.03/updateAttributeCreateTime.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/valid.go
  src/scene_server/topo_server/core/operation/inst.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
Labels: demand, inner, optimization

#2333 服务出现异常后，不返回代码调用的堆栈信息到用户
  resources/errors/common/default/common.json
  resources/errors/common/default/host_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/host_server.json
  src/common/errInfo.go
  src/common/paraparse/app.go
  src/common/rdapi/rdfunc.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/host_server/service/host.go
Labels: inner, optimization

#2332 V3.2.x 服务出现异常后，不返回代码调用的堆栈信息到用户
  resources/errors/common/default/common.json
  resources/errors/common/default/host_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/host_server.json
  src/common/errInfo.go
  src/common/paraparse/app.go
  src/common/rdapi/rdfunc.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/host_server/service/host.go
Labels: inner, optimization

#2232 fix: 模型关联1:n，实际是n:n修复。添加1:n校验
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/cloud_synctask.go
  src/scene_server/host_server/service/cloudtask.go
  src/scene_server/topo_server/core/operation/association.go
  src/ui/src/assets/json/static-navigation.json
  src/ui/src/dictionary/auth.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/cloud-confirm/history.vue
  src/ui/src/views/cloud-confirm/index.vue
  src/ui/src/views/cloud-confirm/router.config.js
  src/ui/src/views/cloud-discover/create.vue
  src/ui/src/views/cloud-discover/index.vue
  src/ui/src/views/cloud-discover/router.config.js
  src/ui/src/views/cloud-discover/task-details.vue
  src/ui/src/views/cloud-discover/update.vue
Labels: bug, outer

#2343 解决集成测试问题
  src/common/mapstr/struct.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst_business.go
Labels: inner, optimization

#2331 文档：用开源CMDB替换社区版
  docs/overview/upgrade-from-ce.md
  readme.md
Labels: demand, inner

#2274 操作审计代码迁移至coreservice
  src/apimachinery/auditcontroller/api.go
  src/apimachinery/auditcontroller/auditcontroller.go
  src/apimachinery/clientset.go
  src/apimachinery/coreservice/auditlog/api.go
  src/apimachinery/coreservice/auditlog/auditlog.go
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/discovery/discovery.go
  src/apimachinery/healthz/healthz.go
  src/auth/extensions/audit.go
  src/common/metadata/audit.go
  src/common/metadata/common.go
  src/common/types/serverInfo.go
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/logics/log.go
  src/scene_server/proc_server/proc_service/service/proc2module.go
  src/scene_server/proc_server/proc_service/service/proc2template.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/proc_server/proc_service/service/template.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/audit.go
  src/scene_server/topo_server/core/operation/health.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/topo_server/service/auditlog.go
  src/source_controller/auditcontroller/Makefile
  src/source_controller/auditcontroller/app/options/options.go
  src/source_controller/auditcontroller/app/server.go
  src/source_controller/auditcontroller/audit.go
  src/source_controller/auditcontroller/logics/audit.go
  src/source_controller/auditcontroller/readme.md
  src/source_controller/auditcontroller/service/host.go
  src/source_controller/auditcontroller/service/object.go
  src/source_controller/auditcontroller/service/search.go
  src/source_controller/auditcontroller/service/service.go
  src/source_controller/auditcontroller/service/topology.go
  src/source_controller/coreservice/core/auditlog/audit.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/service/auditlog.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/coreservice/service/service_test.go
  src/source_controller/objectcontroller/app/server.go
Labels: demand, inner

#2346 metadata data structure for process
  src/common/metadata/process.go
Labels: demand, inner

#2347 add tags for process's structure.
  src/auth/parser/topology.go
  src/common/metadata/process.go
Labels: demand, inner

#2350 update document
  docs/overview/upgrade-from-ce.md
  readme.md
Labels: inner, optimization

#2351 update readme
  docs/resource/img/jiawei-logo.png
  docs/resource/img/youole-logo.jpg
  docs/resource/img/yuanding-logo.png
  readme.md
Labels: inner, optimization

#2353 update readme
  docs/resource/img/youole-logo.jpg
  readme.md
Labels: inner, optimization

#2354 修复framework编译不通过的问题
  src/framework/core/config/configcenter.go
  src/framework/core/config/factory.go
  src/framework/core/discovery/rdiscover.go
  src/framework/main.go
Labels: inner, optimization

#2349 define enum type for socket bind type and protocol type
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
Labels: demand, inner

#2359 feature: mongo update support operator issue #1780 #2357 #2340
  src/storage/dal/db.go
  src/storage/dal/mongo/local/mock_mongo.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/remote/collection.go
Labels: demand, inner

#2348 add proc fresh auth.
  src/auth/parser/topology.go
Labels: demand, inner

#2365 update process template structure in proc server
  src/common/metadata/process.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/service/init_func.go
  src/scene_server/proc_server/service/openapi.go
  src/scene_server/proc_server/service/proc2module.go
  src/scene_server/proc_server/service/proc2template.go
  src/scene_server/proc_server/service/procdetail.go
  src/scene_server/proc_server/service/process.go
  src/scene_server/proc_server/service/procinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/template.go
  src/scene_server/proc_server/service/templatefile.go
  src/scene_server/proc_server/service/templateversion.go
Labels: demand, inner

#2367 demand: proc server新增服务分类处理功能
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/blog/blog.go
  src/common/errInfo.go
  src/common/http/rest/contexts.go
  src/common/http/rest/rest.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/service/category.go
  src/scene_server/proc_server/service/service.go
Labels: demand, inner

#2363 调整apiserver上操作审计鉴权 #2362
  src/auth/parser/topology.go
Labels: demand, inner

#2379 optimize: update reademe with add front-page demo picture.
  docs/resource/img/frontpage.png
  docs/resource/img/frontpage_en.png
  readme.md
  readme_en.md
Labels: inner, optimization

#2372 coreservice ServiceTemplate CRUD #2361
  resources/errors/common/default/common.json
  resources/errors/common/default/core_service.json
  resources/errors/english/en/common.json
  resources/errors/english/en/core_service.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/common/metadata/query.go
  src/common/tablenames.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/process.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/process_instance_relation.go
  src/source_controller/coreservice/service/process_template.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/source_controller/coreservice/service/service_template.go
Labels: demand, inner

#2399 feature: process server add new features like service template etc.
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/definitions.go
  src/common/http/rest/contexts.go
  src/common/http/rest/rest.go
  src/common/mapstr/struct.go
  src/common/metadata/metadata.go
  src/common/metadata/process.go
  src/scene_server/proc_server/logics/logic.go
  src/scene_server/proc_server/logics/process.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/category.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
Labels: demand, inner

#2403 feature: procserver新增根据服务模板对比进程实例差异的能力。
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/common/universalsql/universalsql.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
Labels: demand, inner

#2339 ui: 功能指引提示 / 样式优化
  src/ui/src/App.vue
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.eot
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/assets/images/no-authority.png
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/feature-tips/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/operation-audit.js
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business-model/router.config.js
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/status/require-business.vue
  src/ui/static/svg/cc-exclamation-tips.svg
  src/ui/static/svg/cc-no-authority.svg
  src/ui/static/svg/cc-tips-close.svg
Labels: demand, inner

#2389 optimize:ui: 业务模式下拓扑视图中不允许删除公有模型的位置
  src/ui/src/views/model-topology/index.old.vue
Labels: inner, optimization

#2411 feature: 全文检索
  src/ui/src/assets/images/full-text-search.png
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/full-text-search.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/full-text-pagination.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/index/router.config.js
Labels: inner

#2381 feature: synchronize data baseed on identifier issue #1780
  src/apimachinery/synchronize/synchronizeserver/syncrhonize.go
  src/common/definitions.go
  src/common/util/lib.go
  src/framework/core/discovery/rdiscover.go
  src/scene_server/synchronize_server/app/options/options.go
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/synchronize_server/logics/assocation.go
  src/scene_server/synchronize_server/logics/background_synchronize.go
  src/scene_server/synchronize_server/logics/inst.go
  src/scene_server/synchronize_server/logics/model.go
  src/scene_server/synchronize_server/logics/synchronize.go
  src/source_controller/coreservice/core/datasynchronize/data_clear.go
  src/source_controller/coreservice/core/datasynchronize/identifier.go
  src/source_controller/coreservice/core/datasynchronize/util.go
Labels: demand, inner

#2420 feature: add inner association kind to auth center when the authcent is initialized.
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/auth/authcenter/perm_initial.go
  src/auth/meta/meta.go
  src/common/errInfo.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/admin_server/service/service.go
Labels: demand, inner

#2412 进程相关接口实现调整
  src/apimachinery/coreservice/process/api.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/processtemplate.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/service/process_instance_relation.go
  src/source_controller/coreservice/service/process_template.go
  src/source_controller/coreservice/service/service_category.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_template.go
Labels: inner

#2407 refactor:clear procserver code issue #2046
  src/scene_server/proc_server/logics/appinstance.go
  src/scene_server/proc_server/logics/backgroup.go
  src/scene_server/proc_server/logics/gsehandle.go
  src/scene_server/proc_server/logics/instance.go
  src/scene_server/proc_server/logics/instanceconst.go
  src/scene_server/proc_server/logics/instanceutil.go
  src/scene_server/proc_server/logics/log.go
  src/scene_server/proc_server/logics/logics.go
  src/scene_server/proc_server/logics/matchprocinstance.go
  src/scene_server/proc_server/logics/scopematchutil_test.go
  src/scene_server/proc_server/logics/scopemathutil.go
  src/scene_server/proc_server/logics/task.go
  src/scene_server/proc_server/logics/template.go
  src/scene_server/proc_server/logics/topo.go
  src/scene_server/proc_server/logics/variables.go
  src/scene_server/proc_server/service/init_func.go
  src/scene_server/proc_server/service/proc2module.go
  src/scene_server/proc_server/service/proc2template.go
  src/scene_server/proc_server/service/procinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/template.go
  src/scene_server/proc_server/service/templatefile.go
  src/scene_server/proc_server/service/templateversion.go
Labels: inner, optimization

#2424 update:ui: 操作审计过滤条件选中清空问题
  src/ui/src/views/audit/index.vue
Labels: demand, inner

#2410 feature: add force sync service template to service instance feature
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  src/common/condition/condition.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/serviceinstance.go
Labels: demand, inner

#2428 UI： 主机沉浸式查看详情页
  src/ui/src/api/_request-queue.js
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.eot
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/components/ui/form/bool.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/view/host-details.js
  src/ui/src/utils/tools.js
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/association-graphics.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association-list.vue
  src/ui/src/views/host-details/children/association-property-filter.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/history.vue
  src/ui/src/views/host-details/children/info.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/status.vue
  src/ui/src/views/host-details/index.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/static/svg/cc-arrow.svg
  src/ui/static/svg/cc-edit.svg
Labels: demand, inner

#2380 调整apiserver上操作审计鉴权 #2362
  src/apimachinery/rest/request.go
  src/apiserver/service/auth.go
  src/apiserver/service/filter.go
  src/auth/authcenter/authcenter.go
  src/auth/extensions/association.go
  src/auth/extensions/attribute.go
  src/auth/extensions/attributegroup.go
  src/auth/extensions/audit.go
  src/auth/extensions/base.go
  src/auth/extensions/business.go
  src/auth/extensions/classification.go
  src/auth/extensions/dynamicgroup.go
  src/auth/extensions/host.go
  src/auth/extensions/instance.go
  src/auth/extensions/model.go
  src/auth/extensions/modelunique.go
  src/auth/extensions/module.go
  src/auth/extensions/plat.go
  src/auth/extensions/process.go
  src/auth/extensions/set.go
  src/auth/parser/topology.go
  src/common/definitions.go
  src/common/rdapi/rdfunc.go
  src/common/util/lib.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/core/instances/dependences.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator.go
  src/source_controller/coreservice/service/instances_dependence.go
  src/source_controller/coreservice/service/service.go
Labels: inner, optimization

#2427 fix: fix update object name but not update to iam problem
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/scene_server/topo_server/core/operation/object.go
  src/web_server/service/inst.go
Labels: inner, optimization

#2430 主机查询失败 #2328
  src/scene_server/host_server/logics/object.go
  src/source_controller/coreservice/core/instances/instance.go
Labels: bug, inner

#2437 optimize: add proce server api to apiserver router.
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/apiserver/service/url.go
  src/common/http/rest/contexts.go
  src/common/http/rest/rest.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/service/service.go
Labels: demand, inner

#2434 代码规范
  src/common/rdapi/rdfunc.go
  src/common/registerdiscover/zkregdiscv.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/proc_server/app/options/options.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/logics/host.go
  src/scene_server/proc_server/logics/logics.go
  src/scene_server/proc_server/logics/process.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/logics/topo.go
  src/scene_server/proc_server/service/category.go
  src/scene_server/proc_server/service/init_func.go
  src/scene_server/proc_server/service/openapi.go
  src/scene_server/proc_server/service/procdetail.go
  src/scene_server/proc_server/service/process.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
Labels: inner, optimization

#2440 coreservice中进程模块metadata采用结构体替换mapstr #2439
  src/common/mapstr/convert.go
  src/common/metadata/metadata.go
  src/common/metadata/process.go
  src/source_controller/coreservice/core/process/process.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
Labels: inner, optimization

#2441 回滚：coreservice中进程模块metadata采用结构体替换mapstr #2439
  src/common/metadata/metadata.go
  src/common/metadata/process.go
  src/source_controller/coreservice/core/process/process.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
Labels: inner, optimization

#2445 bugfix 处理ExtractRequestIDFromContext空指针问题
  src/common/util/lib.go
Labels: bug, inner

#2447 修复自定义模型通过导入方式修改后，字段的页面操作（编辑，删除）灰掉问题
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/types.go
Labels: inner, optimization

#2438 V3.4.x 实例删除，更新，新加新加事件处理
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/logics/phpapi_host.go
  src/source_controller/coreservice/core/instances/event.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/service/service.go
Labels: demand, inner

#2456 proc server api optimize
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  src/apimachinery/coreservice/process/api.go
  src/common/errInfo.go
  src/common/http/rest/contexts.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/servicetemplate.go
Labels: demand, inner

#2393 进程模板升级
  resources/language/default/property.json
  resources/language/en/property.json
  src/common/metadata/inst.go
  src/common/metadata/process.go
  src/common/tablenames.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/add_default_category.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/change_process_name.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/create_table.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
Labels: demand, inner

#2451 主机释放前置条件检查：关联服务实例的主机不能释放 #2450
  resources/errors/common/default/common.json
  resources/errors/common/default/core_service.json
  resources/errors/english/en/common.json
  resources/errors/english/en/core_service.json
  src/apimachinery/coreservice/process/api.go
  src/common/errInfo.go
  src/common/metadata/process.go
  src/source_controller/coreservice/app/server.go
  src/source_controller/coreservice/core/host/modulehost/hostmodule.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
Labels: demand, inner

#2460 optimize: fix url wrapper, metadata parse issue and association id
  src/apimachinery/rest/client.go
  src/apimachinery/rest/request.go
  src/common/metadata/metadata.go
  src/scene_server/topo_server/core/operation/association.go
Labels: inner, optimization

#2469 服务实例/进程相关接口调整
  src/apimachinery/coreservice/process/api.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/validator/valid_basic.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator_attr.go
  src/source_controller/coreservice/core/process/process.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/service_category.go
Labels: inner, optimization

#2463 主机查询支持按id查询 #2461
  src/scene_server/host_server/logics/hostsearch.go
Labels: demand, inner

#2422 V3.5.x host identifier 相关调整
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/common/metadata/inst.go
  src/common/metadata/process.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/topo_server/core/operation/identifier.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/identifier.go
  src/source_controller/coreservice/service/host.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand, inner

#2462 UI: 主机详情优化与bug修复
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/user-custom.js
  src/ui/src/store/modules/menu.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association-list.vue
  src/ui/src/views/host-details/children/association-property-filter.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/graphics-association.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/topology/index.vue
Labels: bug, inner, optimization

#2474 UI: 主机详情优化
  src/ui/src/components/ui/form/float.vue
  src/ui/src/components/ui/form/int.vue
  src/ui/src/components/ui/form/longchar.vue
  src/ui/src/components/ui/form/objuser.vue
  src/ui/src/components/ui/form/singlechar.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/association-property-filter.vue
  src/ui/src/views/host-details/children/history.vue
  src/ui/src/views/host-details/children/info.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/index.vue
Labels: inner, optimization

#2475 UI: 主机详情关联表格全部展开
  src/ui/src/components/ui/form/bool.vue
  src/ui/src/router/index.js
  src/ui/src/store/modules/view/host-details.js
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/index.vue
Labels: demand, inner

#2473 删除web_server&framework无用的代码
  src/framework/clientset/discovery/discovery.go
  src/web_server/app/rdiscover/rdiscover.go
Labels: inner, optimization

#2471 optimize: add new and optimize proc api
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/condition/condition.go
  src/common/condition/condition_test.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/http/rest/contexts.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/category.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
Labels: demand, inner, optimization
