Repository Tencent/bk-cmdb, pull requests merged in 2019-03, with the labels that each got.

#1838 refacor: rename and resolve misspell
  src/scene_server/admin_server/readme.md
  src/scene_server/admin_server/service/clear.go
  src/scene_server/admin_server/service/flag.go
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/service/service.go
  src/scene_server/admin_server/upgrader/register.go
Labels: inner, optimization

#1845 fix: fix lost time package error in storage dal.
  src/storage/dal/mongo/remote/mongo.go
Labels: bug, inner

#1846 feature: 权限中心对接中策略，接口，资源定义优化。
  src/auth/attribute.go
  src/auth/auth.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/id.go
  src/auth/authcenter/type.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/auth/parser/chain.go
  src/auth/parser/host.go
  src/auth/parser/netcollector.go
  src/auth/parser/parser.go
  src/auth/parser/process.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/auth/permit/permit.go
  src/scene_server/topo_server/core/operation/supplementary_auth.go
  src/scene_server/topo_server/core/wrapper/auth.go
  src/scene_server/topo_server/service/service.go
Labels: demand, inner, optimization

#1848 update makefile with supports for branch/tag/pr at building #1847
  scripts/Makefile
Labels: inner, optimization

#1849 bugfix: makefile extract branch/version/tag
  scripts/Makefile
Labels: inner, optimization

#1836 fix: ignore duplicated error
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/event_server/distribution/start.go
Labels: inner, optimization

#1837 fix wrong condition for upgrade inst association
  src/scene_server/admin_server/fixes_inst_association.js
  src/scene_server/admin_server/fixes_topo.js
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#1853 解决replaceALL问题
  src/scene_server/event_server/service/subscription.go
Labels: bug, outer

#1863 V3.2.x fix issue
  src/common/metadata/common.go
  src/source_controller/objectcontroller/service/inst_action.go
  src/web_server/logics/excel_commet_sheet.go
Labels: inner, optimization

#1856 fix: waitGroup should add before start the goroutine #1854
  src/scene_server/event_server/distribution/transaction.go
Labels: optimization, outer

#1852 V3.2.x 400 move idle
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/apimachinery/hostcontroller/module/api.go
  src/apimachinery/hostcontroller/module/module.go
  src/common/metadata/hostcontroller.go
  src/scene_server/host_server/logics/app.go
  src/scene_server/host_server/service/module.go
  src/source_controller/hostcontroller/app/server.go
  src/source_controller/hostcontroller/logics/logics.go
  src/source_controller/hostcontroller/service/host.go
  src/source_controller/hostcontroller/service/service.go
Labels: bug, inner

#1870 fix:error handle nil error
  src/source_controller/coreservice/core/model/model_attribute_group.go
Labels: bug

#1869 [v3.2.x] nil pointer error at framework,hostserver,procserver when d…
  src/framework/core/config/factory.go
  src/scene_server/host_server/logics/plat.go
  src/scene_server/host_server/service/host.go
  src/scene_server/proc_server/logics/gsehandle.go
  src/scene_server/proc_server/proc_service/service/openapi.go
Labels: bug, inner

#1868 fix: fix err panics in toposerver . issue #1862
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/compatiblev2/set.go
  src/scene_server/topo_server/core/model/group.go
  src/scene_server/topo_server/core/model/unique.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
Labels: bug, inner

#1867 fix: fix nil pointer error at apiserver,hostserver,procserver
  src/api_server/logics/v2/fileds.go
  src/api_server/service/v2/process.go
  src/api_server/service/v2/searchext.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/plat.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/proc_server/logics/gsehandle.go
  src/scene_server/proc_server/proc_service/service/openapi.go
Labels: bug, inner

#1866 fixes nil pointer error at adminserver when dealing error. #1862
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#1865 feature: adaptor cmdb and auth center's policy and resource actions.
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/type.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/auth/parser/host.go
  src/auth/parser/topolatest.go
Labels: demand, inner

#1819 Data sync
  resources/errors/common/default/synchronize.json
  resources/errors/english/en/synchronize.json
  scripts/init.py
  scripts/start.sh
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/synchronize/api.go
  src/apimachinery/coreservice/synchronize/synchronize.go
  src/apimachinery/synchronize/synchronize.go
  src/apimachinery/synchronize/synchronizeserver/apis.go
  src/apimachinery/synchronize/synchronizeserver/syncrhonize.go
  src/apimachinery/synchronize/util/discovery.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/common.go
  src/common/metadata/core_service_synchronize.go
  src/common/rdapi/rdfunc.go
  src/common/types/serverInfo.go
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/synchronize_server/Makefile
  src/scene_server/synchronize_server/app/options/options.go
  src/scene_server/synchronize_server/app/options/options_test.go
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/synchronize_server/logics/assocation.go
  src/scene_server/synchronize_server/logics/background_synchronize.go
  src/scene_server/synchronize_server/logics/exception/file/exception.go
  src/scene_server/synchronize_server/logics/find.go
  src/scene_server/synchronize_server/logics/inst.go
  src/scene_server/synchronize_server/logics/logics.go
  src/scene_server/synchronize_server/logics/model.go
  src/scene_server/synchronize_server/logics/statistics.go
  src/scene_server/synchronize_server/logics/synchronize.go
  src/scene_server/synchronize_server/service/service.go
  src/scene_server/synchronize_server/service/synchronize.go
  src/scene_server/synchronize_server/synchronize.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/datasynchronize/association.go
  src/source_controller/coreservice/core/datasynchronize/data_clear.go
  src/source_controller/coreservice/core/datasynchronize/dependences.go
  src/source_controller/coreservice/core/datasynchronize/find.go
  src/source_controller/coreservice/core/datasynchronize/instance.go
  src/source_controller/coreservice/core/datasynchronize/model.go
  src/source_controller/coreservice/core/datasynchronize/synchronize.go
  src/source_controller/coreservice/core/datasynchronize/util.go
  src/source_controller/coreservice/service/data_synchronize.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_datasync_initfunc.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand, inner

#1872 ui optimize
  src/ui/src/components/hosts/status/status.vue
  src/ui/src/components/ui/collapse/collapse.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/index.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/process/index.vue
Labels: inner, optimization

#1873 merge v3.2.x
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  scripts/Makefile
  src/apimachinery/coreservice/association/api.go
  src/apimachinery/coreservice/association/association.go
  src/apimachinery/objcontroller/meta/api.go
  src/apimachinery/objcontroller/meta/meta.go
  src/common/errInfo.go
  src/scene_server/admin_server/command/command.go
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/command/types.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/service.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/service/association.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/objectcontroller/service/association_action.go
  src/source_controller/objectcontroller/service/instasst_action.go
  src/source_controller/objectcontroller/service/objectasst_action.go
  src/source_controller/objectcontroller/service/service.go
Labels: demand, inner

#1822 feature: add authorize to process create
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/type.go
  src/auth/initial/biz_perm.go
  src/auth/initial/initial.go
  src/auth/initial/sys_perm.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/common/errInfo.go
  src/common/util/mapbuilder.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/topo_server/core/operation/inst_business.go
Labels: demand, inner

#1876 新增根据模块ID查询主机接口
  src/api_server/service/v3/uri.go
  src/common/metadata/hostserver.go
  src/common/metadata/metadata.go
  src/scene_server/host_server/logics/findhost.go
  src/scene_server/host_server/service/findhost.go
  src/scene_server/host_server/service/service.go
Labels: demand, inner

#1878 cmdb实例导出excel拿不到属性字段
  src/web_server/logics/fields.go
Labels: bug, inner

#1882 fixes miss change muti associate to single when upgrade to 3.2
  src/common/metadata/attribute.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#1887 初始化权限中心资源
  resources/errors/common/default/migrate.json
  resources/errors/english/en/migrate.json
  src/apiserver/app/server.go
  src/auth/auth.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/perm_sys.go
  src/auth/authcenter/type.go
  src/auth/meta/meta.go
  src/common/errInfo.go
  src/scene_server/admin_server/app/options/options.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/admin_server/service/service.go
Labels: bug, inner

#1889 V3.3.x backbone
  src/api_server/app/server.go
  src/api_server/service/v3/service.go
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/discovery_mock.go
  src/apimachinery/discovery/server.go
  src/common/backbone/backbone.go
  src/common/backbone/backbone_mock.go
  src/common/backbone/configcenter/cc.go
  src/common/backbone/register.go
  src/common/backbone/service_mange/zk/zk.go
  src/common/backbone/type.go
  src/common/confregdiscover/confregdiscover.go
  src/common/confregdiscover/regdiscoverIf.go
  src/common/confregdiscover/zkregdiscover.go
  src/common/identification.go
  src/common/registerdiscover/interface.go
  src/common/registerdiscover/registerdiscover.go
  src/common/registerdiscover/zkregdiscv.go
  src/common/types/serverInfo.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/event_server/app/server.go
  src/scene_server/host_server/app/server.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/auditcontroller/app/server.go
  src/source_controller/auditcontroller/audit.go
  src/source_controller/coreservice/app/server.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/hostcontroller/app/server.go
  src/source_controller/objectcontroller/app/server.go
  src/source_controller/proccontroller/app/server.go
  src/storage/tmserver/app/run.go
  src/web_server/app/config/conf.go
  src/web_server/app/server.go
  src/web_server/middleware/login.go
  src/web_server/service/login.go
  src/web_server/service/service.go
  src/web_server/service/user.go
Labels: inner, optimization

#1894 feature:support master-slave issue #1780
  src/common/mapstr/mapstr.go
  src/common/types/serverInfo.go
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/synchronize_server/logics/synchronize.go
  src/scene_server/synchronize_server/synchronize.go
  src/source_controller/coreservice/core/datasynchronize/association.go
Labels: demand, inner

#1900 UI: 优化拓扑图展示、交互
  src/ui/.gitignore
  src/ui/src/components/ui/form/bool.vue
  src/ui/src/store/modules/api/global-models.js
  src/ui/src/store/modules/api/object-association.js
  src/ui/src/utils/util.js
  src/ui/src/views/model-topology/children/graphics-association.vue
  src/ui/src/views/model-topology/children/graphics-config.vue
  src/ui/src/views/model-topology/children/graphics-models.vue
  src/ui/src/views/model-topology/children/graphics-options.js
  src/ui/src/views/model-topology/children/graphics-toolbar.vue
  src/ui/src/views/model-topology/children/graphics.js
  src/ui/src/views/model-topology/children/topology-graphics.vue
  src/ui/src/views/model-topology/index.bak.vue
  src/ui/src/views/model-topology/index.vue
Labels: inner, optimization

#1898 Search mainline topo with cores ervice. issue #1897
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/mainline/api.go
  src/apimachinery/coreservice/mainline/mainline.go
  src/common/metadata/core_service.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/mainline/README.md
  src/source_controller/coreservice/core/mainline/instance.go
  src/source_controller/coreservice/core/mainline/mainline.go
  src/source_controller/coreservice/core/mainline/model.go
  src/source_controller/coreservice/service/mainline.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
  version.md
Labels: demand, inner

#1893 host authorization. issue #1834
  src/auth/meta/meta.go
  src/auth/parser/parser.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/app/server.go
  src/scene_server/host_server/authorize/README.md
  src/scene_server/host_server/authorize/authorize.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/auth.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/hostlock.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/service.go
Labels: demand, inner

#1906 向权限中心注册系统，资源类型
  resources/errors/common/default/migrate.json
  resources/errors/english/en/migrate.json
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/perm_sys.go
  src/auth/authcenter/type.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/service/service.go
Labels: bug, demand, inner

#1904 UI optimize
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.eot
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/router/index.js
  src/ui/src/utils/util.js
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/index.old.vue
Labels: inner, optimization

#1910 optimize: add new rules for topo server and authcenter. issue #1891
  src/apiserver/app/server.go
  src/apiserver/core/auth/auth.go
  src/apiserver/service/service.go
  src/auth/authcenter/authcenter.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/core/auth/auth.go
Labels: demand, inner

#1911 注释加载权限的接口，用于测试
  src/ui/src/setup/preload.js
Labels: inner, optimization

#1909 添加事件订阅的权限校验
  src/apiserver/service/service.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/perm_sys.go
  src/auth/authcenter/type.go
  src/auth/meta/resource.go
  src/auth/parser/chain.go
  src/auth/parser/event.go
  src/auth/parser/parser.go
  src/common/util/net.go
  src/common/util/net_test.go
  src/scene_server/event_server/app/server.go
  src/scene_server/event_server/distribution/start.go
  src/scene_server/event_server/service/service.go
Labels: demand, inner

#1905 fixes ignore empty when enum is not require
  src/scene_server/validator/valid_basic.go
Labels: bug, inner

#1913 optimize: test object classification, object, association type,
  src/apiserver/service/service.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/id.go
  src/scene_server/topo_server/core/auth/auth.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/object_classification.go
  src/web_server/app/server.go
  src/web_server/service/index.go
Labels: inner, optimization

#1916 优化 add host 代码逻辑
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/service/host.go
Labels: inner, optimization

#1912 支持动态注册“事件订阅”类型资源到IAM
  src/apiserver/app/server.go
  src/apiserver/service/service.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/id.go
  src/auth/authcenter/permit/permit.go
  src/auth/meta/resource.go
  src/auth/parser/chain.go
  src/auth/parser/event.go
  src/auth/parser/host.go
  src/auth/parser/parser.go
  src/auth/parser/process.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/scene_server/event_server/app/options/options.go
  src/scene_server/event_server/app/server.go
  src/scene_server/event_server/service/service.go
  src/scene_server/event_server/service/subscription.go
  src/source_controller/objectcontroller/service/group_action.go
  src/source_controller/objectcontroller/service/objectcls_action.go
  src/storage/rpc/pool.go
Labels: demand, inner

#1915 Host authorize
  resources/configures/host.conf
  src/apimachinery/coreservice/mainline/api.go
  src/apimachinery/coreservice/mainline/mainline.go
  src/apimachinery/rest/request.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/id.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/auth/parser/parser.go
  src/common/metadata/core_service.go
  src/common/tablenames.go
  src/scene_server/host_server/app/options/options.go
  src/scene_server/host_server/app/server.go
  src/scene_server/host_server/authorize/authorize.go
  src/scene_server/host_server/logics/cloud_synctask.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/instance.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/auth.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/hostlock.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/service.go
  src/scene_server/host_server/service/userapi.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/mainline/class.go
  src/source_controller/coreservice/core/mainline/instance.go
  src/source_controller/coreservice/core/mainline/mainline.go
  src/source_controller/coreservice/core/mainline/manager.go
  src/source_controller/coreservice/core/mainline/model.go
  src/source_controller/coreservice/service/mainline.go
  src/ui/src/setup/preload.js
  src/ui/src/store/modules/api/user-privilege.js
Labels: demand, inner

#1899 cmdb导出实例或主机根据用户自定义column进行优先排序
  src/common/definitions.go
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/resource/index.vue
  src/web_server/logics/excel.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/fields.go
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
  src/web_server/service/host.go
  src/web_server/service/inst.go
Labels: demand, outer

#1903 V3.4.x authcenter process server
  src/auth/authcenter/id.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/logics/logics.go
  src/scene_server/proc_server/logics/util.go
  src/scene_server/proc_server/proc_service/service/process.go
  src/scene_server/proc_server/proc_service/service/service.go
Labels: demand, inner

#1930 修复增加或者删除主线模型关联导致拓扑异常问题
  resources/errors/common/default/common.json
  src/scene_server/topo_server/core/operation/association.go
Labels: bug, inner

#1919 update:ui:修改蓝鲸管理后台导航样式
  src/ui/src/assets/scss/admin-view.scss
  src/ui/src/components/layout/nav.vue
Labels: inner, optimization

#1931 适配权限校验接口
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/permit/permit.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/auth/parser/host.go
  src/auth/parser/process.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/auth/parser/util.go
  src/scene_server/host_server/authorize/authorize.go
  src/scene_server/host_server/service/auth.go
  src/scene_server/host_server/service/host.go
Labels: demand, inner

#1938 修改主机审计日志，变化前后一样
  src/scene_server/host_server/service/host.go
Labels: bug, inner

#1936 审计模块优化
  src/scene_server/host_server/service/host.go
  src/source_controller/auditcontroller/logics/audit.go
  vendor/github.com/google/go-cmp/.travis.yml
  vendor/github.com/google/go-cmp/CONTRIBUTING.md
  vendor/github.com/google/go-cmp/README.md
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/util_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/compare_test.go
  vendor/github.com/google/go-cmp/cmp/example_reporter_test.go
  vendor/github.com/google/go-cmp/cmp/example_test.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff_test.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func_test.go
  vendor/github.com/google/go-cmp/cmp/internal/testprotos/protos.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project1.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project2.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project3.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project4.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/structs.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort_test.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero_test.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/options_test.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/github.com/google/go-cmp/go.mod
Labels: inner, optimization

#1932 V3.3.x host module relation
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  resources/language/default/oplogdesc.json
  resources/language/en/oplogdesc.json
  src/common/errInfo.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
Labels: demand, inner

#1939 fix error code value for mainline operation
  resources/errors/common/default/common.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/topo_server.json
  scripts/Makefile
  src/common/errInfo.go
Labels: inner, optimization

#1941 resolve error code conflict problem
  resources/errors/common/default/common.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
Labels: inner, optimization

#1940 resolve error code conflict problem
  resources/errors/common/default/common.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
Labels: inner, optimization

#1946 fix: solve object instance auth problem. issue #1945
  src/apimachinery/toposerver/inst/inst.go
  src/scene_server/topo_server/core/model/classification.go
  src/source_controller/objectcontroller/service/privilege_action.go
  src/web_server/middleware/auth/auth_util.go
  src/web_server/middleware/auth/public.go
  src/web_server/middleware/login.go
  src/web_server/middleware/types/types.go
Labels: bug, inner

#1947 3.2.x前端调整
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.eot
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.svg
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.ttf
  src/ui/src/assets/icon/cc-icon/fonts/icomoon.woff
  src/ui/src/assets/icon/cc-icon/selection.json
  src/ui/src/assets/icon/cc-icon/style.css
  src/ui/src/assets/json/static-navigation.json
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/src/components/date-picker/date-picker.vue
  src/ui/src/store/modules/api/object-model-classify.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/classify-item.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/permission/role-form.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/topology/children/_node-create.vue
  src/ui/src/views/topology/index.vue
  src/ui/static/svg/cc-basic-resource.svg
Labels: bug, demand, inner, optimization

#1944 主机业务内转移模块，不支持预定义模块
  docs/apidoc/error_code.md
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/service/module.go
Labels: demand, inner

#1950 V3.2.x codecc代码扫描优化
  src/apimachinery/discovery/discovery.go
  src/apimachinery/rest/request.go
  src/common/util/lib_test.go
  src/scene_server/host_server/logics/agent.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/instance.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/topo_server/core/model/object.go
  src/source_controller/hostcontroller/logics/logics.go
  src/source_controller/hostcontroller/service/host.go
Labels: inner, optimization

#1951 fix: delete object instance auth problem.
  src/web_server/middleware/auth/auth_util.go
Labels: bug, inner

#1954 optimize: makefile and version info optimize.
  scripts/Makefile
  src/common/version/version.go
Labels: inner, optimization

#1953 fix codecc warnings
  src/scene_server/topo_server/core/model/object.go
  src/source_controller/objectcontroller/service/inst_action.go
  src/source_controller/objectcontroller/service/objectasst_action.go
Labels: inner, optimization

#1952 fix codecc warnings
  src/scene_server/topo_server/core/model/object.go
  src/source_controller/objectcontroller/service/objectasst_action.go
Labels: inner, optimization

#1948 bugfix for authorization
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/host.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/host.go
  src/scene_server/host_server/service/host.go
Labels: bug, inner

#1970 3.4.x dev
  src/ui/src/App.vue
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/hosts/filter/_collection.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/layout/nav.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/dictionary/menu.js
  src/ui/src/dictionary/nav.js
  src/ui/src/main.js
  src/ui/src/mixins/auth.js
  src/ui/src/router/index.bak.js
  src/ui/src/router/index.js
  src/ui/src/setup/preload.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business-model/router.config.js
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/business/router.config.js
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/custom-query/router.config.js
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/eventpush/router.config.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/history/router.config.js
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/index/children/search-item-host.vue
  src/ui/src/views/index/router.config.js
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-association/router.config.js
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/group.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/property-group.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/process/index.vue
  src/ui/src/views/process/module.vue
  src/ui/src/views/process/router.config.js
  src/ui/src/views/resource/index.vue
  src/ui/src/views/resource/router.config.js
  src/ui/src/views/topology/index.vue
  src/ui/src/views/topology/router.config.js
  src/ui/static/svg/cc-tips.svg
Labels: demand, inner

#1959 优化paser执行效率
  src/auth/authcenter/authcenter.go
  src/auth/parser/chain.go
  src/auth/parser/event.go
  src/auth/parser/host.go
  src/auth/parser/netcollector.go
  src/auth/parser/process.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
Labels: bug, inner, optimization

#1963 add restrict for instance batch update interface, which will update a…
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst.go
Labels: bug, inner

#1968 issue: #1964, issue: #1966
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst.go
Labels: inner, optimization

#1962 style:fix codecc warning issue #1961
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/synchronize_server/logics/background_synchronize.go
  src/scene_server/synchronize_server/logics/exception/file/exception.go
  src/scene_server/synchronize_server/logics/synchronize.go
Labels: inner, optimization

#1971 特殊模型前端路由处理
  src/ui/src/components/layout/nav.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/mixins/auth.js
  src/ui/src/router/index.js
  src/ui/src/setup/preload.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/views/business/index.vue
  src/ui/src/views/business/router.config.js
  src/ui/src/views/custom-query/router.config.js
  src/ui/src/views/eventpush/router.config.js
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/history/router.config.js
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/index/children/classify-item.vue
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/resource/router.config.js
Labels: demand, inner

#1967 enhance parameter validate for batch instance create and update
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst.go
Labels: inner, optimization
