Repository Tencent/bk-cmdb, pull requests merged in 2019-02, with the labels that each got.

#1788 UI: 拓扑组成关系从新建关联下拉列表中移除
  src/ui/src/views/model-manage/children/relation-detail/index.vue
Labels: inner, optimization

#1795 add a clone method for MapStr
  src/common/mapstr/mapstr.go
  src/common/mapstr/mapstr_test.go
  vendor/github.com/mohae/deepcopy/LICENSE
  vendor/github.com/mohae/deepcopy/README.md
  vendor/github.com/mohae/deepcopy/deepcopy.go
  vendor/vendor.json
Labels: demand, inner

#1798 optimize:ui: 人员选择器在仅允许输入系统用户时默认选中第一个匹配的用户
  src/ui/src/components/ui/form/objuser.vue
Labels: inner, optimization

#1805 fixbug: limit the return and deletion of the mainline model association
  src/scene_server/topo_server/core/operation/association.go
Labels: bug, inner

#1801 fix:ui: objuser component update scroller timing
  src/ui/src/components/ui/form/objuser.vue
Labels: inner, optimization

#1803 bugfix: /api/v3/topo/model/0 interface failed into infinite loop when…
  src/scene_server/topo_server/core/operation/association_mainline_object.go
Labels: inner, optimization

#1807 Fix start.sh 注释
  scripts/start.sh
Labels: optimization, outer

#1809 fix:Python脚本在Python3.x环境下失败
  scripts/generate.py
  scripts/init.py
  scripts/ip.py
  scripts/license.py
Labels: optimization, outer

#1811 feature: update issue template issue #1810
  ISSUE_TEMPLATE.md
Labels: inner, optimization

#1794 新加主机，修改主机校验改到coreservice
  src/common/definitions.go
  src/common/metadata/common.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
Labels: demand, inner

#1813 fix:module bind proc, delete module, then delete proc error issue #1812
  src/scene_server/proc_server/proc_service/service/proc2module.go
Labels: bug, inner

#1783 feature:add auth module for supplementary, issue #1774
  src/auth/auth.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/supplementary_auth.go
  src/scene_server/topo_server/core/types/types.go
  src/scene_server/topo_server/core/wrapper/auth.go
  src/scene_server/topo_server/service/service.go
Labels: demand, inner

#1821 feature: add topology auth api filters and optimize authorize interface and data structure.
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/type.go
  src/auth/parser/chain.go
  src/auth/parser/parser.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/auth/resource.go
  src/auth/type.go
Labels: demand, inner, optimization

#1817 add error log when model occurs to have multiple children
  src/scene_server/topo_server/core/model/object.go
Labels: inner, optimization

#1824 fix: should recursively check child while delete a topo layer instance
  src/scene_server/admin_server/command/command.go
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/command/types.go
  src/storage/dal/mongo/mgo_mongo.go
Labels: bug, inner

#1823 fix: ignore import singleasst or multiasst attribute
  src/scene_server/topo_server/core/operation/object.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/remote/mongo.go
Labels: bug, inner

#1832 修复查询关联类型接口分页查询错误
  src/source_controller/objectcontroller/service/association_action.go
Labels: bug, inner

#1833 refactor:delete host query history api issue #1827
  src/scene_server/host_server/service/service.go
Labels: demand, inner

#1829 修复procserver接口缺失问题
  src/common/definitions.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/proc_server/proc_service/service/template.go
  src/scene_server/topo_server/core/operation/association.go
Labels: demand, inner

#1830 feature: disable create mainline assoication in topo model scene and …
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apimachinery/objcontroller/meta/api.go
  src/apimachinery/objcontroller/meta/meta.go
  src/common/errInfo.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/association.go
  src/source_controller/objectcontroller/service/instasst_action.go
  src/source_controller/objectcontroller/service/objectasst_action.go
  src/source_controller/objectcontroller/service/service.go
Labels: inner, optimization

#1839 feature: add all the api filter analyze and abstract, and embeded in api server.
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/apiserver/app/server.go
  src/apiserver/service/service.go
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/type.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/auth/parser/chain.go
  src/auth/parser/host.go
  src/auth/parser/netcollector.go
  src/auth/parser/parser.go
  src/auth/parser/process.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/auth/permit/permit.go
  src/auth/resource.go
  src/common/errInfo.go
Labels: demand, inner
