Repository Tencent/bk-cmdb, pull requests merged in 2019-08, with the labels that each got.

#2840 fix:ui: 修复表单校验错误提示文本超长未处理的问题
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/views/model-manage/index.vue
Labels: bug, inner

#2838 UI：文案及url变更
  src/ui/src/api/middleware/admin-entrance.js
  src/ui/src/components/modal/permission.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/auth.js
Labels: optimization

#2842 新增主机查询页面支持多字符字段模型查询功能
  src/common/definitions.go
  src/common/paraparse/host.go
  src/scene_server/host_server/logics/hostsearch.go
Labels: demand

#2846 demand: resource convert, multiple host search support
  src/apiserver/service/auth.go
  src/apiserver/service/service.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/id.go
  src/auth/meta/meta.go
  src/common/definitions.go
  src/common/paraparse/host.go
  src/scene_server/admin_server/synchronizer/handler/business.go
  src/scene_server/admin_server/synchronizer/handler/core.go
  src/scene_server/admin_server/synchronizer/handler/usergroup.go
  src/scene_server/admin_server/synchronizer/producer.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/service/module.go
Labels: demand

#2848 fix:ui: 修复长短字符长度校验未按byte校验的问题
  src/ui/package.json
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/setup/validate.js
Labels: optimization

#2854 fix:ui: 修改infobox 副标题vnode的使用方法
  src/ui/src/views/resource/index.vue
Labels: bug, inner

#2851 UI： 主机多模糊查询
  src/ui/package.json
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/hosts/filter/_filter-field-operator.vue
  src/ui/src/components/hosts/filter/_filter.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/search-input.vue
  src/ui/src/components/ui/index.js
  src/ui/src/setup/validate.js
  src/ui/src/views/model-manage/index.vue
Labels: bug, demand, inner

#2865 fix: host identifier, assignment to entry in nil map issue #2864
  src/source_controller/coreservice/core/host/identifier/identifier.go
Labels: bug, outer

#2856 update:ui: 优化调整
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/object-main-line-module.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/service-instance-empty.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/model-association/_detail.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/field-detail/enum.vue
  src/ui/src/views/model-manage/children/field-detail/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/process-form.vue
Labels: inner, optimization

#2868 UI:交互优化
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/magicbox/index.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/main.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/history.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/tree/index.vue
  src/ui/src/views/tree/router.config.js
  src/ui/src/views/tree/tree-item.vue
  src/ui/src/views/tree/tree-node.js
  src/ui/src/views/tree/tree.vue
  src/ui/src/views/tree/utils.js
Labels: inner, optimization

#2869 demand: add search host instance property api in apiserver.
  src/auth/parser/host.go
  src/scene_server/host_server/service/host.go
Labels: demand

#2849 feature: tool check snapshot issue #2844
  src/tools/snapshot_check/Makefile
  src/tools/snapshot_check/app/options/options.go
  src/tools/snapshot_check/app/options/options_test.go
  src/tools/snapshot_check/app/server.go
  src/tools/snapshot_check/main.go
  src/tools/snapshot_check/readme.md
  src/tools/snapshot_check/service/check.go
Labels: demand, inner

#2860 业务拓扑树web接口返回结果带上服务模板ID信息 #2853
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
Labels: demand

#2873 update:ui: 优化调整
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-topology/children/edit-label.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-category/router.config.js
  src/ui/src/views/service-template/index.vue
Labels: optimization

#2875 feature: metadata.Time 支持string 反序列化 issue #2833
  src/common/metadata/time.go
Labels: bug, outer

#2876 UI： 体验优化
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/relation/_topology.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/components/ui/other/button-group.vue
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-category/index.vue
Labels: inner, optimization

#2874 feature: metadata.Time 支持string 反序列化 issue #2833
  src/common/metadata/time.go
Labels: bug, outer

#2878 进程实例鉴权调整: 按服务拓扑鉴权
  src/auth/authcenter/adaptor.go
  src/auth/meta/resource.go
  src/auth/parser/processinstance.go
  src/source_controller/coreservice/service/service_template.go
Labels: demand

#2872 fix: host identifier, assignment to entry in nil map issue #2864
  src/source_controller/objectcontroller/service/identifier.go
Labels: bug, inner

#2866 V3.5.x host topo relation
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/metadata/core_service.go
  src/common/metadata/hostcontroller.go
  src/common/metadata/page.go
  src/scene_server/host_server/logics/app.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/compatiblev2/set.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/transfer.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/process/service_instance.go
Labels: demand, in progress

#2885 进程实例鉴权调整: 按服务实例鉴权；禁用模块模板解绑功能 #2867
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  src/auth/parser/processinstance.go
  src/common/errInfo.go
  src/scene_server/proc_server/service/processinstance.go
Labels: demand

#2886 optimize process service topology auth issue
  src/apiserver/service/service.go
  src/auth/authcenter/adaptor.go
  src/auth/parser/chain.go
  src/common/backbone/configcenter/cc.go
Labels: optimization

#2880 UI: 交互优化
  src/ui/package.json
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/hosts/filter/_filter-field-operator.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/ui/form/date-range.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/search-input.vue
  src/ui/src/components/ui/index.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/setup/validate.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/index.vue
Labels: inner, optimization

#2889 迁移主机模块关系接口
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/compatiblev2/set.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/source_controller/coreservice/service/hostmodule.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand

#2890 optimize auth with service topology
  src/common/metadata/core_service.go
  src/scene_server/host_server/service/module.go
  src/scene_server/proc_server/service/servicecategory.go
  src/scene_server/proc_server/service/servicetemplate.go
Labels: optimization

#2888 update:ui: 调整拓扑样式
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: demand

#2884 V3.5.x 云区域操作相关接口
  src/apiserver/service/url.go
  src/common/metadata/hostserver.go
  src/common/metadata/page.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/service.go
  src/source_controller/coreservice/core/model/attribute.go
Labels: demand

#2893 fix: 无权限服务模板不显示问题
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/service-template/router.config.js
Labels: bug

#2892 拆分服务分类接口 #2891
  src/auth/parser/servicecategory.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/servicecategory.go
  src/ui/src/store/modules/api/service-classification.js
Labels: optimization

#2894 fix:ui: 修复切换资源池已分配/未分配主机切换时参数不正确的问题
  src/ui/src/components/hosts/table/index.vue
Labels: bug, inner

#2895 update:ui: 修改权限表现
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-list.vue
Labels: optimization

#2907 V3.4.x 在启动的时候，zk链接不上，多次重试
  src/common/backbone/backbone.go
Labels: optimization

#2906 V3.2.x hostsearch 根据用户指定的字段返回数据
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/service/phpapi.go
Labels: bug, inner

#2901 update:ui: 全量引入magicbox
  src/ui/package.json
  src/ui/src/magicbox/index.js
Labels: optimization

#2900 V3.4.x host bug
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/phpapi.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
Labels: bug, inner

#2899 3.5体验问题优化/修复 #2867
  src/apiserver/service/service.go
  src/auth/authcenter/id.go
  src/auth/authcenter/permit/permit.go
  src/common/metadata/metadata.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/thirdpartyclient/elasticsearch/esclient.go
  src/web_server/logics/host.go
  src/web_server/service/host.go
Labels: optimization

#2896 V3.5.x 优化
  src/storage/tmserver/core/command/find.go
  src/tools/snapshot_check/Makefile
Labels: optimization

#2858 实现一套统一查询语言
  src/common/querybuilder/README.md
  src/common/querybuilder/parser.go
  src/common/querybuilder/parser_test.go
  src/common/querybuilder/types.go
  src/common/querybuilder/types_test.go
  src/common/querybuilder/validate.go
  src/common/selector/selector_test.go
Labels: demand, inner

#2859 主机查询接口拆分/重构
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/auth/parser/host.go
  src/common/definitions.go
  src/common/metadata/hostserver.go
  src/common/querybuilder/README.md
  src/common/querybuilder/parser.go
  src/common/querybuilder/parser_test.go
  src/common/querybuilder/types.go
  src/common/util/array.go
  src/common/util/lib.go
  src/scene_server/host_server/service/findhost.go
  src/scene_server/host_server/service/service.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/searcher.go
  src/source_controller/coreservice/core/host/searcher/searcher.go
  src/source_controller/coreservice/service/hostsearch.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand

#2914 update:ui: 体验优化
  src/ui/src/components/modal/permission.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/history/index.vue
Labels: optimization

#2913 refactor: optimization transfer host to module tips
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/scene_server/host_server/logics/module.go
Labels: optimization

#2909 服务注册依赖事件，不再使用定时的方式
  src/common/registerdiscover/zkregdiscv.go
Labels: inner, optimization

#2863 完善数组操作函数集对边界情况的处理
  src/apimachinery/coreservice/host/api.go
  src/common/selector/selector_test.go
  src/common/util/array.go
  src/common/util/collection.go
  src/common/util/conv.go
  src/common/util/lib.go
  src/common/util/mapbuilder.go
  src/common/util/struti.go
  src/common/util/time.go
  src/scene_server/host_server/service/findhost.go
  src/source_controller/coreservice/core/host/searcher/searcher.go
Labels: optimization

#2903 V3.5.x feature sync 支持多样化的更新操作
  src/storage/dal/mongo/remote/collection.go
  src/storage/mongodb/collection.go
  src/storage/mongodb/driver/collection.go
  src/storage/tmserver/core/command/aggregate.go
  src/storage/tmserver/core/command/count.go
  src/storage/tmserver/core/command/delete.go
  src/storage/tmserver/core/command/find.go
  src/storage/tmserver/core/command/insert.go
  src/storage/tmserver/core/command/update.go
  src/storage/types/message_type.go
Labels: demand, outer

#2916 新增webserver接口：根据主机ID查询相关可监听IP列表
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/auth/parser/serviceinstance.go
  src/common/metadata/common.go
  src/web_server/service/host.go
  src/web_server/service/service.go
Labels: demand

#2904 Feature sync 数据更新操作及日志相关
  src/storage/dal/mongo/remote/collection.go
  src/storage/mongodb/collection.go
  src/storage/mongodb/driver/collection.go
  src/storage/tmserver/core/command/aggregate.go
  src/storage/tmserver/core/command/count.go
  src/storage/tmserver/core/command/delete.go
  src/storage/tmserver/core/command/find.go
  src/storage/tmserver/core/command/insert.go
  src/storage/tmserver/core/command/update.go
  src/storage/types/message_type.go
Labels: bug, outer

#2803 添加eventserver测试用例
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/apimachinery/apiserver/biz.go
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/apimachinery/procserver/process/api.go
  src/apimachinery/procserver/process/instance.go
  src/apimachinery/procserver/process/template.go
  src/apimachinery/procserver/procserver.go
  src/apimachinery/procserver/service/api.go
  src/apimachinery/procserver/service/category.go
  src/apimachinery/procserver/service/instance.go
  src/apimachinery/procserver/service/template.go
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/common.go
  src/apimachinery/toposerver/inst/inst.go
  src/apimachinery/toposerver/object/api.go
  src/apimachinery/toposerver/object/attribute.go
  src/apimachinery/toposerver/object/class.go
  src/apimachinery/toposerver/object/graphic.go
  src/apimachinery/toposerver/object/group.go
  src/apimachinery/toposerver/object/obj.go
  src/apimachinery/toposerver/privilege/api.go
  src/apimachinery/toposerver/privilege/privilege.go
  src/common/mapstr/struct.go
  src/common/metadata/object_controller.go
  src/common/metadata/toposerver.go
  src/scene_server/event_server/service/subscription.go
  src/scene_server/topo_server/core/operation/group.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/object_group.go
  src/source_controller/coreservice/service/model.go
  src/test/business/business_suite_test.go
  src/test/business/business_test.go
  src/test/event_server/event_server_suite_test.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_server_suite_test.go
  src/test/host_server/host_test.go
  src/test/host_server/user_test.go
  src/test/proc_server/no_service_template_test.go
  src/test/proc_server/proc_server_suite_test.go
  src/test/proc_server/service_template_test.go
  src/test/test.go
  src/test/topo_server/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/object_test.go
  src/test/topo_server/privilege_test.go
  src/test/topo_server/topo_server_suite_test.go
Labels: demand

#2928 update:ui: 体验优化
  src/ui/src/components/layout/header.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/selector/input-select.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/store/modules/api/service-instance.js
  src/ui/src/store/modules/view/business-topology.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/edit-label.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/host-details/children/association-property-filter.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/index.vue
Labels: optimization

#2924 3.5体验问题处理
  resources/language/default/property_group.json
  resources/language/en/property_group.json
  src/auth/authcenter/client.go
  src/auth/parser/serviceinstance.go
  src/common/mapstr/struct.go
  src/common/metadata/core_service.go
  src/scene_server/admin_server/common/definitions.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/update_process_property.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
Labels: optimization

#2929 服务模板集成测试 bugfix
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  resources/language/default/property.json
  resources/language/en/property.json
  src/apimachinery/discovery/discovery.go
  src/common/mapping.go
  src/common/metadata/process.go
  src/scene_server/proc_server/app/options/options.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/source_controller/coreservice/core/label/label.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_template.go
  src/storage/dal/mongo/config.go
  src/storage/dal/mongo/remote/mongo.go
Labels: bug, optimization

#2939 remove sync auth in adminserver
  docs/overview/installation.md
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/authsynchronizer/worker.go
  src/web_server/middleware/login.go
Labels: optimization

#2935 feature:write conf fie to config center issue #2933
  src/scene_server/admin_server/configures/conf.go
Labels: demand, inner

#2920 V3.5.x attribute id name duplicate
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  resources/language/default/model_attribute.json
  resources/language/en/model_attribute.json
  src/common/definitions.go
  src/common/errInfo.go
  src/scene_server/topo_server/core/model/valid.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/attribute_private.go
  src/storage/rpc/client.go
Labels: bug

#2940 add: html_reporter to generate html test report
  src/test/event_server/event_server_suite_test.go
  src/test/host_server/host_server_suite_test.go
  src/test/proc_server/proc_server_suite_test.go
  src/test/reporter/html_reporter.go
  src/test/reporter/template.go
  src/test/test.go
  src/test/topo_server/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/object_test.go
  src/test/topo_server/topo_server_suite_test.go
Labels: demand

#2942 optimize error code in full text search
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
Labels: optimization

#2946 update:ui: 体验优化
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/ui/dot-menu/dot-menu.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/model-manage/children/group.vue
  src/ui/src/views/permission/role.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
Labels: optimization

#2941 V3.5.x bugfix
  resources/errors/common/default/core_service.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/core_service.json
  resources/errors/english/en/topo_server.json
  resources/language/default/property.json
  resources/language/en/property.json
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/thirdpartyclient/elasticsearch/esclient.go
Labels: bug

#2945 ui: 交互优化
  src/ui/src/App.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/index.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/resource/index.vue
Labels: optimization

#2947 ui: 修复校验规则翻译不正确的问题
  src/ui/src/setup/validate.js
Labels: optimization

#2948 optimize add new api filter in auth parser.
  src/auth/parser/topology.go
Labels: optimization

#2949 bugfix: 模块变化对比返回的实例信息全部一样
  src/scene_server/proc_server/service/serviceinstance.go
Labels: bug

#2952 V3.5.x topo direct mgo addr create
  src/scene_server/topo_server/app/server.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_private.go
Labels: bug

#2955 demand: add upsert operation for mongo.
  src/storage/dal/interface.go
  src/storage/dal/mongo/local/mock_mongo.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/remote/collection.go
Labels: demand

#2954 update:ui: 优化体验
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/ui/form/float.vue
  src/ui/src/components/ui/form/int.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
Labels: optimization

#2968 feature: support -,+ user sort conditon issue #2967
  src/storage/tmserver/core/command/find.go
Labels: bug, inner

#2958 删除空集群失败 #2957
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/common/util/array.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.08.19.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.08.19.01/remove_proc_fresh_instance.go
  src/scene_server/admin_server/upgrader/x19.08.19.01/update_ip_regex.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_crud.go
  src/source_controller/coreservice/core/process/service_category.go
Labels: bug

#2963 update:ui: 回归优化
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/components/model-manage/_choose-icon.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/components/service/process-form.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/view/business-topology.js
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-graphics.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/index.vue
Labels: bug, optimization

#2974 UI: 体验优化
  src/ui/package.json
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/relation/_update.vue
  src/ui/src/components/ui/form/enum.vue
  src/ui/src/components/ui/form/search-input.vue
  src/ui/src/components/ui/form/timezone.vue
  src/ui/src/filters/formatter.js
  src/ui/src/filters/host.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/main.js
  src/ui/src/router/StatusError.js
  src/ui/src/router/index.js
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/global.js
  src/ui/src/store/modules/view/hosts.js
  src/ui/src/utils/tools.js
  src/ui/src/views/business-model/router.config.js
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/business/router.config.js
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association-list.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/host-details/children/status.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/model-association/router.config.js
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/resource/router.config.js
  src/ui/src/views/status/require-business.vue
Labels: bug, inner, optimization

#2975 update:ui: 修改$tooltips写法
  src/ui/src/components/relation/_update.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/index/children/full-text-search.vue
Labels: optimization

#2979 支持修改自定义模块的服务分类
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/source_controller/coreservice/core/instances/instance_crud.go
  src/source_controller/coreservice/core/instances/instance_validate.go
Labels: demand

#2956 fix and optimize with multiple issues.
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apiserver/service/filter.go
  src/apiserver/service/service.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/perm_initial.go
  src/auth/parser/host.go
  src/auth/parser/topology.go
  src/common/errInfo.go
  src/common/tablenames.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/event_server/app/server.go
  src/scene_server/event_server/service/subscription.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/utils.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/validator/valid_unique.go
Labels: bug, optimization

#2980 fix bug
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.08.20.01/delete_host_plat_association.go
  src/scene_server/admin_server/upgrader/x19.08.20.01/pkg.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/source_controller/coreservice/service/instances_dependence.go
  src/web_server/logics/association.go
  src/web_server/logics/excel.go
Labels: bug, inner

#2981 change error code
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
Labels: bug, inner

#2986 全文索引undefined问题修复
  src/common/metadata/process.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/service/fulltextsearch.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
Labels: bug

#2984 不可以删除在唯一校验中的属性
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/apiserver/service/auth.go
  src/apiserver/service/service.go
  src/common/errInfo.go
  src/source_controller/coreservice/core/model/attribute_curd.go
Labels: bug, inner

#2992 属性相关的校验
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/operation/object.go
  src/source_controller/coreservice/core/model/attribute_curd.go
Labels: demand, inner

#2993 UI交互优化
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/setup/validate.js
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/cloud-discover/create.vue
  src/ui/src/views/cloud-discover/update.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/eventpush/push-detail.vue
  src/ui/src/views/index/children/recently.vue
  src/ui/src/views/model-association/_detail.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/model-topology/children/graphics-association.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/network-config/device.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: bug, inner

#2989 update:ui: 体验优化
  src/ui/src/components/hosts/filter/filter-property-selector.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/ui/form/enum.vue
  src/ui/src/components/ui/form/timezone.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/utils/tools.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/model-manage/children/verification-detail/index.vue
  src/ui/src/views/model-manage/children/verification.vue
Labels: optimization

#2997 全文索引高亮业务ID字段
  src/thirdpartyclient/elasticsearch/esclient.go
Labels: optimization

#2996 批量修改主机，提示信息错误
  src/scene_server/host_server/service/host.go
Labels: bug, inner

#3001 更新procserver测试用例
  src/test/proc_server/no_service_template_test.go
  src/test/proc_server/service_template_test.go
Labels: demand

#2998 fix:ui: 修复编辑主机按钮未去掉鉴权的问题
  src/ui/src/components/hosts/table/index.vue
Labels: bug, inner

#3008 删除模型的数据逻辑转移到coreservice中
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/object.go
  src/source_controller/coreservice/core/model/model_crud.go
Labels: bug, demand, inner

#3005 event server推送订阅事件bugfix: 提前关闭了连接
  src/common/http/httpclient/client.go
Labels: bug

#3000 非标准组件的节点支持IsMaster
  src/apimachinery/discovery/discovery.go
  src/common/types/serverInfo.go
  src/scene_server/admin_server/configures/conf.go
Labels: demand, inner

#3009 optimize: 审计注册与bk_mainline注册优化
  src/scene_server/admin_server/authsynchronizer/meta/types.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/authsynchronizer/worker.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/topo_server/service/association.go
Labels: optimization

#3023 feature:ui: 禁止修改蓝鲸拓扑
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: demand, inner

#3013 注册集群模板新路由格式
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/settemplate/api.go
  src/apimachinery/coreservice/settemplate/process.go
  src/apimachinery/toposerver/settemplate/apis.go
  src/apimachinery/toposerver/settemplate/settemplate.go
  src/apimachinery/toposerver/toposerver.go
  src/apiserver/service/url.go
  src/common/definitions.go
  src/common/metadata/metadata.go
  src/common/metadata/set_template.go
  src/common/metadata/set_template_request.go
  src/common/tablenames.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.08.24.01/add_module_property.go
  src/scene_server/admin_server/upgrader/x19.08.24.01/add_set_property.go
  src/scene_server/admin_server/upgrader/x19.08.24.01/create_table.go
  src/scene_server/admin_server/upgrader/x19.08.24.01/initialize_set_template_field.go
  src/scene_server/admin_server/upgrader/x19.08.24.01/pkg.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/scene_server/topo_server/service/service_settemplate_initfunc.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/coreservice/service/service_set_template_initfunc.go
  src/source_controller/coreservice/service/set_template.go
  src/test/set_template/topo_server/set_template_test.go
  src/test/set_template/topo_server/topo_server_suite_test.go
Labels: demand

#3029 新增: 模型实例数统计接口 #3028
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/model/model.go
  src/scene_server/topo_server/service/object.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand

#3002 V3.2.x 减少FindClassificationWithObjects的for循环层数
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/classification.go
Labels: optimization

#3032 查询模型关联关系panic 问题
  src/scene_server/topo_server/service/association.go
Labels: bug, inner

#3033 apiserver鉴权处理：跳过模型实例数统计接口鉴权 #3028
  src/auth/parser/topology.go
Labels: demand

#3035 create_inst 接口性能优化
  src/apimachinery/objcontroller/inst/api.go
  src/apimachinery/objcontroller/inst/inst.go
  src/common/metadata/object_controller.go
  src/scene_server/topo_server/core/operation/inst.go
  src/source_controller/objectcontroller/service/inst_action.go
  src/source_controller/objectcontroller/service/service.go
  src/source_controller/validator/type.go
  src/source_controller/validator/util.go
  src/source_controller/validator/valid_basic.go
  src/source_controller/validator/valid_unique.go
Labels: optimization

#3044 删除查询关联关系类型，不返回业务主线拓扑模型
  src/scene_server/topo_server/service/association.go
  src/source_controller/coreservice/service/model_attribute_test.go
Labels: inner, optimization

#3046 权限与模型相关调整
  src/auth/authcenter/perm_biz.go
  src/auth/extensions/host.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.08.26.01/bk_set_upgrade.go
  src/scene_server/admin_server/upgrader/x19.08.26.01/pkg.go
  src/scene_server/host_server/service/host.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/topo_server/service/inst.go
  src/source_controller/coreservice/service/instances.go
Labels: demand, optimization

#3039 UI: 批量编辑鉴权优化，拓扑关系异常处理
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/model-topology/index.old.vue
Labels: bug, inner

#3041 服务模板鉴权策略调整
  src/auth/parser/servicecategory.go
  src/scene_server/admin_server/authsynchronizer/handler/servicetemplate.go
  src/scene_server/admin_server/authsynchronizer/meta/types.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/authsynchronizer/worker.go
  src/scene_server/proc_server/service/servicecategory.go
  src/scene_server/topo_server/service/object.go
Labels: demand

#3047 instance权限同步区分mainline资源类型
  src/auth/extensions/instance.go
  src/scene_server/admin_server/authsynchronizer/handler/instance.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/authsynchronizer/worker.go
Labels: demand

#3048 instance权限同步区分mainline资源类型bugfix
  src/auth/extensions/instance.go
  src/scene_server/admin_server/authsynchronizer/handler/instance.go
Labels: demand

#3050 feature: user language use cookie issue #3049
  src/common/definitions.go
  src/web_server/common/httpheader.go
  src/web_server/middleware/login.go
  src/web_server/middleware/user/public.go
  src/web_server/service/host.go
  src/web_server/service/index.go
  src/web_server/service/inst.go
  src/web_server/service/netdevice.go
  src/web_server/service/netproperty.go
  src/web_server/service/object.go
Labels: inner, optimization

#3061 fix:ui: 修改模板模块服务实例进程表单可填项的判断
  src/ui/src/components/service/instance-table.vue
Labels: bug, inner

#3060 optimize: 权限中心资源调整与服务模板校验调整
  src/auth/authcenter/perm_biz.go
  src/common/metadata/process.go
  src/scene_server/admin_server/authsynchronizer/producer.go
Labels: optimization

#3062 【v3.5.x】fix: create_inst批量接口的操作审计全是新增
  src/scene_server/topo_server/core/operation/inst.go
Labels: demand

#3053 修改datacollection的db和redis初始化位置 issue #3051
  src/scene_server/datacollection/app/server.go
  src/scene_server/datacollection/datacollection/datacollection.go
  src/scene_server/datacollection/service/service.go
Labels: optimization

#3058 add package mapstructure
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/vendor.json
Labels: optimization

#3045 添加create_inst接口的操作审计
  src/source_controller/objectcontroller/service/inst_action.go
  src/source_controller/validator/valid_unique.go
Labels: optimization

#3063 优化IP正则 #2964
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.08.30.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.08.30.01/update_ip_regex.go
Labels: optimization
