Repository Tencent/bk-cmdb, pull requests merged in 2019-06, with the labels that each got.

#2477 feature: add process related auth method in api server.
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/permit/permit.go
  src/auth/meta/resource.go
  src/auth/parser/process.go
  src/auth/parser/topolatest.go
  src/common/definitions.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
Labels: demand, inner

#2482 refactor: change import and export excel file name issue #2479
  src/web_server/service/host.go
  src/web_server/service/inst.go
  src/web_server/service/object.go
Labels: demand, inner

#2484 coreservice 删除关联关系改成批量接口 #2483
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/definitions.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/process.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/process_instance_relation.go
  src/source_controller/coreservice/service/process_template.go
  src/source_controller/coreservice/service/service_category.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_template.go
Labels: inner, optimization

#2481 refactor: change import and export excel file name issue #2479
  src/web_server/service/host.go
  src/web_server/service/inst.go
  src/web_server/service/object.go
Labels: demand, inner

#2488 模型实例列表接口返回实例名称字段
  resources/errors/common/default/common.json
  src/apimachinery/coreservice/process/api.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/process_instance_relation.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/source_controller/coreservice/service/service_template.go
Labels: demand, inner

#2491 V3.5.x 新增进程模板相关功能
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/category.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/process_template.go
Labels: demand, inner

#2495 模块模型新增服务分类和服务模版字段
  resources/errors/common/default/common.json
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/add_default_category.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/add_module_property.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/service_category.go
  src/source_controller/coreservice/service/service_process_initfunc.go
Labels: demand, inner

#2502 新增：更新进程实例接口
  resources/errors/common/default/common.json
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/proc_server.json
  resources/language/default/property.json
  resources/language/en/property.json
  src/common/errInfo.go
  src/common/metadata/process.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/process/base.go
Labels: demand, inner

#2499 修复web_server 中网络设备采集接口相关代码
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/web_server/logics/netdevice.go
  src/web_server/logics/netproperty.go
  src/web_server/service/netdevice.go
  src/web_server/service/netproperty.go
  src/web_server/service/service.go
Labels: demand, inner

#2511 optimize: add github doc for store issue and pr template
  .github/ISSUE_TEMPLATE.md
  .github/pull_request_template.md
Labels: inner, optimization

#2515 服务实例相关接口补充
  resources/errors/common/default/common.json
  resources/errors/common/default/core_service.json
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/core_service.json
  resources/errors/english/en/proc_server.json
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/hostserver.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/hostmoduleconfig.go
  src/source_controller/coreservice/core/host/modulehost/hostmodule.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/source_controller/coreservice/service/service_template.go
Labels: demand, inner

#2520 主机转移校验规则及新增获取单个服务模板接口
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/common/errInfo.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/source_controller/coreservice/core/host/modulehost/hostmodule.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
Labels: demand, inner

#2528 进程实例相关接口
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/errInfo.go
  src/common/errors/type.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/host.go
  src/source_controller/coreservice/core/host/modulehost/hostmodule.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
  src/source_controller/coreservice/core/process/base.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/process_instance_relation.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
Labels: demand, inner, optimization

#2531 新增服务模板详情接口 #2530
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/source_controller/coreservice/service/service_template.go
Labels: demand, inner

#2535 update:ui: 全文检索回归
  src/ui/config/index.js
  src/ui/index.html
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/store/index.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/index/router.config.js
Labels: demand, inner

#2538 进程实例唯一校验 #2534
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/common/errInfo.go
  src/common/metadata/inst.go
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/update_process_property.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/host/modulehost/transfer.go
  src/source_controller/coreservice/core/process/base.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/process_instance_relation.go
  src/source_controller/coreservice/service/service_template.go
Labels: demand, inner

#2521 修复唯一性校验提示%s未被替换为字段名
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
Labels: inner, optimization

#2435 fix error nil dereferences and duplicate lines
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
Labels: bug, outer

#2533 权限接口调整
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_sys.go
  src/auth/authcenter/type.go
  src/auth/parser/topolatest.go
  src/auth/parser/util.go
  src/scene_server/datacollection/logics/collector.go
  src/scene_server/datacollection/logics/common.go
  src/scene_server/datacollection/logics/device.go
  src/scene_server/datacollection/logics/property.go
  src/scene_server/datacollection/logics/report.go
Labels: demand, inner

#2536 权限矩阵调整3.5
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/client.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_sys.go
Labels: demand, inner

#2540 进程实例唯一校验
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  resources/language/default/property.json
  src/common/definitions.go
  src/common/errInfo.go
  src/common/errors/errorIf.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/change_process_name.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/update_process_property.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/process/base.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_instance.go
Labels: demand, inner

#2545 进程模板支持排序
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/process/process_template.go
Labels: demand, inner

#2549 UI:修复编辑关联关系时唯一标识显示不正确的问题
  src/ui/src/setup/preload.js
  src/ui/src/views/model-manage/children/relation-detail/index.vue
Labels: bug, inner

#2547 UI: 修复编辑关联关系时唯一标识显示不正确的问题
  src/ui/src/setup/preload.js
  src/ui/src/views/model-manage/children/relation-detail/index.vue
Labels: bug, inner

#2551 进程实例联调
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
Labels: inner, optimization

#2558 服务实例与模板对比/同步 #2557
  src/common/metadata/core_service.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/process/service_instance.go
Labels: inner, optimization

#2562 添加判断管理员入口接口
  src/apiserver/service/auth.go
  src/apiserver/service/service.go
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
Labels: demand, inner

#2565 UI: 无权限交互
  src/ui/src/App.vue
  src/ui/src/api/index.js
  src/ui/src/api/middleware/admin-entrance.js
  src/ui/src/api/middleware/auth.js
  src/ui/src/api/middleware/business.js
  src/ui/src/api/middleware/index.js
  src/ui/src/api/middleware/util.js
  src/ui/src/assets/images/lock-closed.svg
  src/ui/src/assets/images/lock-opened.svg
  src/ui/src/assets/images/lock-opening.svg
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/layout/header.vue
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/directives/cursor.js
  src/ui/src/directives/index.js
  src/ui/src/main.js
  src/ui/src/mixins/auth.js
  src/ui/src/setup/permission.js
  src/ui/src/setup/preload.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/process/index.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/status/403.vue
  src/ui/src/views/topology/index.vue
Labels: demand, inner

#2553 处理全局模型修改名称不生效问题：禁止修改内置模型名称
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/id.go
  src/auth/extensions/instance.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/topo_server/service/inst.go
Labels: inner, optimization

#2566 feature:ui: 将990403状态的请求reject掉
  src/ui/src/api/index.js
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/directives/cursor.js
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/views/model-manage/index.vue
Labels: demand, inner

#2556 feature: 新增无权限管理形态
  src/apiserver/service/service.go
  src/auth/auth.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/type.go
  src/auth/extensions/attribute.go
  src/auth/extensions/attributegroup.go
  src/auth/extensions/audit.go
  src/auth/extensions/base.go
  src/auth/extensions/business.go
  src/auth/extensions/classification.go
  src/auth/extensions/dynamicgroup.go
  src/auth/extensions/host.go
  src/auth/extensions/instance.go
  src/auth/extensions/model.go
  src/auth/extensions/modelunique.go
  src/auth/extensions/module.go
  src/auth/extensions/process.go
  src/auth/meta/meta.go
  src/auth/parser/host.go
  src/auth/parser/parser.go
  src/auth/parser/topolatest.go
  src/common/errInfo.go
  src/common/metadata/common.go
  src/common/metadata/result.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/core/instances/instance.go
  src/storage/mongodb/driver/client.go
Labels: demand, inner

#2569 关联升级需要交换 源<->目标模型
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
Labels: bug, inner

#2568 关联升级需要交换 源<->目标模型
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#2570 update:ui: 进程回归优化
  src/ui/src/components/ui/dot-menu/dot-menu.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/src/components/selector/selector.vue
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/service-cagetory/index.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/index.vue
Labels: inner, optimization

#2573 服务模板/进程优化
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
Labels: inner, optimization

#2567 解决evenserver中redis oom问题
  src/common/eventclient/eventclient.go
  src/scene_server/event_server/distribution/reconclier.go
  src/scene_server/event_server/identifier/identifier.go
Labels: inner, optimization

#2575 update:ui: 添加侧栏关闭提示
  src/ui/src/components/service/instance-table.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/children/process.vue
Labels: inner, optimization

#2576 解决evenserver中redis oom问题
  src/common/eventclient/eventclient.go
  src/scene_server/event_server/identifier/identifier.go
Labels: bug, inner

#2577 fix:ui: 修复拓扑树新增节点插入位置错误的问题
  src/ui/src/components/ui/tree/tree.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: demand, inner

#2574 update:ui: 修改鼠标跟随图标
  src/ui/src/assets/images/lock.svg
  src/ui/src/assets/scss/common.scss
Labels: inner, optimization

#2579 fix： 修复内置”防火墙”模型枚举字段多语言支持问题
  resources/language/default/enum.json
  resources/language/en/enum.json
  src/common/language/language.go
Labels: inner, optimization

#2580 optimize: 修复内置模型的多语言支持问题
  resources/language/default/enum.json
  resources/language/en/enum.json
  src/apiserver/service/auth.go
  src/common/language/language.go
Labels: inner, optimization

#2584 服务模板/进程优化
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/errInfo.go
  src/common/errors/defaultError.go
  src/common/metadata/inst.go
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/update_process_property.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/process/service_category.go
Labels: demand, inner

#2581 update:ui: 回归调整
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/service-category/children/category-input.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-category/router.config.js
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: inner, optimization

#2585 调整权限中心的资源命名
  src/auth/authcenter/adaptor.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: demand, inner

#2591 移除升级到3.2.x时遗留的脏数据
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#2589 update:ui: 回归优化
  src/ui/src/components/ui/form/form.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/mixins/form.js
  src/ui/src/store/modules/api/business-synchronous.js
  src/ui/src/store/modules/api/process-instance.js
  src/ui/src/store/modules/api/process-template.js
  src/ui/src/store/modules/api/service-instance.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/children/process.vue
Labels: bug, demand, inner

#2586 服务模板功能体验问题修复
  resources/errors/common/default/core_service.json
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/core_service.json
  resources/errors/english/en/proc_server.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
Labels: demand, inner

#2597 整理coreservice中host模块代码结构
  src/common/eventclient/eventclient.go
  src/common/metadata/process.go
  src/source_controller/coreservice/core/host/Identifier/identifier.go
  src/source_controller/coreservice/core/host/host.go
  src/source_controller/coreservice/core/host/identifier.go
  src/source_controller/coreservice/core/host/transfer.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/host/transfer/transfer.go
  src/source_controller/coreservice/core/host/util/util.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/ui/src/store/modules/api/process-template.js
Labels: inner, optimization

#2592 fix:ui: 修改判断是否是模板模块节点的条件
  src/ui/src/api/middleware/admin-entrance.js
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
Labels: bug, inner

#2588 V3.2.x 修复创建云区域唯一校验不过的问题
  src/scene_server/topo_server/core/operation/inst.go
Labels: bug, inner

#2590 UI: 去除原有关于管理入口的鉴权
  src/ui/src/api/middleware/admin-entrance.js
  src/ui/src/components/layout/header.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/router/index.js
  src/ui/src/views/permission/router.config.js
Labels: demand, inner

#2608 V3.4.x 权限优化调整
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/client.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_sys.go
  src/auth/authcenter/permit/permit.go
  src/auth/authcenter/type.go
  src/auth/extensions/audit.go
  src/auth/extensions/business.go
  src/auth/extensions/dynamicgroup.go
  src/auth/extensions/host.go
  src/auth/extensions/process.go
  src/auth/meta/resource.go
  src/auth/parser/event.go
  src/auth/parser/host.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/common/errInfo.go
  src/common/eventclient/eventclient.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/unique.go
  src/source_controller/coreservice/core/instances/instance_validate.go
Labels: bug, inner, optimization

#2607 V3.4.x 权限回归
  src/ui/src/api/index.js
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/ui/tree/_tree-layout.js
  src/ui/src/components/ui/tree/_tree-node.vue
  src/ui/src/components/ui/tree/tree.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/directives/cursor.js
  src/ui/src/setup/afterload.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/store/modules/view/host-details.js
  src/ui/src/views/business/archived.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association-list.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/history.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/index.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/topology/index.vue
Labels: bug, demand, inner, optimization

#2605 update:ui: admin-tips添加hover色
  src/ui/src/components/layout/header.vue
Labels: inner, optimization

#2611 UI: 业务选择器提示语优化
  src/ui/src/components/ui/selector/business.vue
Labels: inner, optimization

#2612 optimize: mainline model instance update operation with special logic.
  src/auth/parser/topolatest.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst.go
Labels: inner, optimization

#2598 支持从IAM过滤无权限业务
  .travis.yml
  src/common/eventclient/eventclient.go
  src/common/util/collection.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
  src/scene_server/topo_server/core/operation/inst_business.go
Labels: demand, inner

#2610 修复事件推送前对比数据panic问题
  src/common/eventclient/eventclient.go
Labels: bug, inner

#2594 refactor: improve /api/v3/find/classificationobject performance
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/classification.go
Labels: inner, optimization

#2603 update:ui: 回归优化
  src/ui/src/magicbox/src/components/paging/paging.vue
  src/ui/src/setup/validate.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/service-instances.vue
Labels: inner, optimization

#2504 Feature txn
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/definitions.go
  src/common/errInfo.go
  src/common/util/lib.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/service.go
  src/storage/dal/interface.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/local/wrapper_transcation.go
  src/storage/dal/mongo/remote/collection.go
  src/storage/dal/mongo/remote/find.go
  src/storage/dal/mongo/remote/mongo.go
  src/storage/dal/mongo/remote/mongo_test.go
  src/storage/dal/mongo/remote/pool.go
  src/storage/dal/mongo/remote/transaction.go
  src/storage/dal/mongo/remote/transaction_test.go
  src/storage/dal/mongo/remote/wrapper_transaction.go
  src/storage/rpc/client.go
  src/storage/rpc/pool.go
  src/storage/tmserver/core/command/abort_transaction.go
  src/storage/tmserver/core/command/commit_transaction.go
  src/storage/tmserver/core/command/start_transaction.go
  src/storage/tmserver/core/core.go
  src/storage/tmserver/core/session/manager.go
  src/storage/tmserver/core/session/session.go
  src/storage/tmserver/service/service.go
  src/storage/types/types.go
Labels: demand, inner

#2618 update:ui: 回归优化调整
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/tree/tree-item.vue
  src/ui/src/components/ui/tree/tree-node.js
  src/ui/src/components/ui/tree/tree.vue
  src/ui/src/directives/cursor.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/service-instance/clone.vue
Labels: bug, inner, optimization

#2624 ui: 修改获取有权限业务列表的接口
  src/ui/src/api/middleware/business.js
  src/ui/src/store/modules/api/object-biz.js
Labels: demand, inner

#2623 修复升级到3.2.9+时未更新实例关联的问题
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: bug, inner

#2622 业务拓扑树默认按照名字排序 #2621
  src/scene_server/admin_server/upgrader/x19.05.16.01/add_inner_category.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/service/association.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/web_server/middleware/login.go
  src/web_server/ui.go
Labels: demand, inner

#2616 optimize: add get exactly authorized business list api.
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apiserver/service/auth.go
  src/apiserver/service/service.go
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/type.go
  src/auth/extensions/audit.go
  src/auth/extensions/business.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/common/errInfo.go
  src/common/util/collection.go
  src/common/util/lib.go
  src/scene_server/admin_server/upgrader/x18.12.05.01/addswitchAssociation.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: demand, inner, optimization

#2600 update:ui: 限制搜索长度
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/index/children/search-input.vue
Labels: demand, inner

#2627 服务模板/进程体验优化
  resources/errors/common/default/common.json
  resources/errors/common/default/core_service.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/common.json
  resources/errors/english/en/core_service.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/process_instance_relation.go
Labels: demand, inner, optimization

#2631 feature: skip set module get authorize
  src/auth/authcenter/permit/permit.go
Labels: demand, inner

#2632 fix: 修复API文档链接失效问题
  readme.md
  readme_en.md
Labels: demand, outer

#2633 fix:ui: 修复历史记录详情查看报错的问题
  src/ui/src/components/audit-history/details.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/store/modules/api/host-update.js
  src/ui/src/views/host-details/children/property.vue
Labels: bug, inner

#2650 UI: 修复渲染主机实时状态失败的问题
  src/ui/src/store/modules/api/host-search.js
  src/ui/src/views/host-details/children/status.vue
Labels: bug, inner
