Repository Tencent/bk-cmdb, pull requests merged in 2019-12, with the labels that each got.

#3546 修复版本升级主机bk_state_name被删除后，升级失败
  src/scene_server/admin_server/upgrader/x19.04.16.02/pkg.go
  src/scene_server/admin_server/upgrader/x19.04.16.02/updateFranceName.go
Labels: bug, inner

#3549 UI: 调整查询业务链接
  src/ui/src/store/modules/api/object-biz.js
Labels: optimization, outer

#3524 新增集群模板查询服务模板web接口 及其它体验问题修复
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/auth/auth.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/type.go
  src/auth/extensions/plat.go
  src/auth/parser/settemplate.go
  src/common/errInfo.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/service_settemplate_initfunc.go
  src/scene_server/topo_server/service/set_template.go
Labels: demand

#3544 update:ui: 收藏条件列表更新 / 集群模板名称长度调整为20个字符
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/set-template/children/template-config.vue
Labels: optimization

#3551 主机转移属性自动应用预览
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/host-apply/children/property-confirm-table.vue
  src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue
  src/ui/src/views/host-operation/index.vue
Labels: demand, inner

#3540 集成测试bugfix
  src/scene_server/host_server/logics/app.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/topo_server/core/model/attribute.go
Labels: bug

#3556 UI: 主机详情编辑状态判定
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/host-apply.js
  src/ui/src/views/host-apply/children/search-select-mix.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-details/children/property.vue
Labels: demand, inner

#3558 主机属性自动应用功能完善
  src/ui/src/store/modules/api/host-apply.js
  src/ui/src/store/modules/view/hosts.js
  src/ui/src/views/host-apply/batch-edit.vue
  src/ui/src/views/host-apply/children/apply-status.vue
  src/ui/src/views/host-apply/children/conflict-resolve.vue
  src/ui/src/views/host-apply/children/host-property-modal.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-apply/children/property-confirm-table.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/conflict-list.vue
  src/ui/src/views/host-apply/failed-list.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-apply/property-confirm.vue
  src/ui/src/views/host-apply/router.config.js
Labels: demand, inner

#3564 实例数量优化 / 文件路径调整
  src/ui/src/components/ui/user/user-queue.js
  src/ui/src/components/ui/user/user.vue
  src/ui/src/directives/user.js
  src/ui/src/views/business-synchronous/index.vue
Labels: bug, inner

#3563 update:ui: 实例数量优化
  src/ui/src/views/business-synchronous/index.vue
Labels: bug, inner

#3570 update:ui: 体验优化
  src/ui/src/components/model-manage/field-group/field-detail/enum.vue
  src/ui/src/components/model-manage/field-group/field-detail/list.vue
  src/ui/src/components/ui/form/longchar.vue
  src/ui/src/components/ui/form/search-input.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/info.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-operation/index.vue
Labels: inner, optimization

#3571 主机属性自动应用功能完善
  src/ui/src/dictionary/menu.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/views/host-apply/children/apply-status.vue
  src/ui/src/views/host-apply/children/conflict-resolve.vue
  src/ui/src/views/host-apply/children/host-property-modal.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-apply/children/property-form-element.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-apply/property-confirm.vue
  src/ui/src/views/host-apply/router.config.js
Labels: demand, inner

#3569 feature:ui: 属性应用拓扑筛选完善
  src/ui/src/store/modules/api/host-apply.js
  src/ui/src/views/host-apply/children/search-select-mix.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
Labels: demand, inner

#3572 fix: 属性字段排序
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/store/modules/view/host-details.js
Labels: bug

#3553 主机身份接口添加自定义层级
  src/common/metadata/inst.go
  src/scene_server/event_server/identifier/hostcache.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/topo_server/core/operation/identifier.go
  src/source_controller/coreservice/core/host/identifier/identifier.go
Labels: demand

#3548 云区域作为通用实例注册到权限中心数据结构调整
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/id.go
  src/auth/extensions/plat.go
  src/scene_server/admin_server/authsynchronizer/handler/core.go
  src/scene_server/admin_server/authsynchronizer/handler/instance.go
  src/scene_server/admin_server/authsynchronizer/handler/plat.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/host_server/service/cloudarea.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/mainline/class.go
  src/source_controller/coreservice/core/mainline/instance.go
  src/source_controller/coreservice/core/mainline/manager.go
  src/source_controller/coreservice/core/mainline/model.go
  src/source_controller/coreservice/service/mainline.go
Labels: demand

#3565 list_biz_hosts接口添加set的过滤条件
  src/common/definitions.go
  src/common/metadata/hostserver.go
  src/scene_server/event_server/identifier/hostcache.go
  src/scene_server/host_server/service/findhost.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/test/host_server/host_test.go
Labels: demand

#3541 remove redundant Redis option and client
  scripts/init.py
  src/scene_server/proc_server/app/options/options.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/logics/logics.go
  src/scene_server/proc_server/service/service.go
  src/source_controller/coreservice/service/health.go
  src/source_controller/coreservice/service/host.go
  src/source_controller/coreservice/service/service.go
  src/storage/tmserver/app/options/options.go
  src/storage/tmserver/app/server.go
  src/web_server/app/server.go
Labels: optimization

#3561 修复测试用例错误时提示信息位置错误和实例查询鉴权未关联实例ID的问题
  src/test/util/fail.go
Labels: bug

#3581 修复云区域注册鉴权问题
  src/apimachinery/rest/request.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/topo_server/core/model/attribute.go
Labels: bug

#3584 update:ui: 体验优化
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/field-view.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/components/ui/user/user-queue.js
  src/ui/src/components/ui/user/user.vue
  src/ui/src/directives/overflow-tips.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-set.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
  src/ui/src/views/set-template/children/template-config.vue
  src/ui/src/views/set-template/children/template-tree.vue
Labels: inner, optimization

#3590 主机属性自动应用体验问题修复
  src/ui/package.json
  src/ui/src/components/feature-tips/index.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/dictionary/menu.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/views/host-apply/batch-edit.vue
  src/ui/src/views/host-apply/children/apply-status.vue
  src/ui/src/views/host-apply/children/conflict-resolve.vue
  src/ui/src/views/host-apply/children/host-property-modal.vue
  src/ui/src/views/host-apply/children/multi-edit-copy.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-apply/children/property-confirm-table.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/conflict-list.vue
  src/ui/src/views/host-apply/edit.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-apply/property-confirm.vue
  src/ui/src/views/host-apply/router.config.js
Labels: inner, optimization

#3588 update:ui: 3.7体验优化
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/host-apply/children/conflict-resolve.vue
  src/ui/src/views/host-apply/children/property-confirm-table.vue
  src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue
  src/ui/src/views/host-operation/index.vue
Labels: bug, inner, optimization

#3587 optimize: 查询业务接口，无权限时返回200状态码
  src/scene_server/host_server/service/cloudarea.go
  src/web_server/service/object.go
Labels: optimization

#3585 fix: 修复模型属性更新、删除接口权限解析无layer信息 issue #3493
  src/auth/parser/topology.go
Labels: bug

#3586 listen_ip_options调用list_hosts_without_app时添加page.limit查询条件
  src/web_server/service/host.go
Labels: demand

#3606 fix:ui: 实例数显示问题
  src/ui/src/views/business-synchronous/index.vue
Labels: bug, inner

#3603 主机属性自动应用加权限和体验问题修复
  src/ui/package.json
  src/ui/src/dictionary/auth.js
  src/ui/src/dictionary/menu-symbol.js
  src/ui/src/views/host-apply/children/conflict-resolve.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-apply/children/property-confirm-table.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/conflict-list.vue
  src/ui/src/views/host-apply/failed-list.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-apply/property-confirm.vue
  src/ui/src/views/host-apply/router.config.js
Labels: inner, optimization

#3598 update:ui: 3.7回归优化
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: inner, optimization

#3600 模型实例关联权限bugfix
  src/apiserver/service/filter.go
  src/auth/authcenter/adaptor.go
  src/auth/parser/topolatest.go
  src/auth/parser/util.go
Labels: bug

#3608 update:ui: 样式优化
  src/ui/src/components/ui/selector/business.vue
Labels: optimization

#3610 空闲机可以设置自动应用和体验问题修复
  src/ui/src/store/modules/api/object-main-line-module.js
  src/ui/src/views/host-apply/children/conflict-resolve.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/property-confirm-table.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/edit.vue
  src/ui/src/views/host-apply/property-confirm.vue
Labels: bug, demand, inner, optimization

#3612 fix: 修复资源池bizId获取问题
  src/ui/src/views/host-details/children/info.vue
Labels: bug, inner

#3611 UI: 面包屑调整
  src/ui/src/components/layout/dynamic-breadcrumbs.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-fields/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/host-details/children/info.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/resource-manage/index.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-instance/clone.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-operation/index.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/service-template/template.vue
  src/ui/src/views/set-sync/sync-index.vue
  src/ui/src/views/set-template/index.vue
  src/ui/src/views/set-template/template.vue
Labels: inner

#3599 update:ui: 简化属性自动应用拓扑搜索功能
  src/ui/src/views/host-apply/children/property-confirm-table.vue
  src/ui/src/views/host-apply/children/search-select-mix.vue
Labels: inner, optimization

#3595 添加外网ip唯一校验
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.7.201912121117/add_host_outer_ip_unique.go
  src/scene_server/admin_server/upgrader/y3.7.201912121117/pkg.go
Labels: demand

#3618 主机自动应用翻译补充和组件提取
  src/ui/src/components/host-apply/conflict-resolve.vue
  src/ui/src/components/host-apply/property-confirm-table.vue
  src/ui/src/components/host-apply/property-form-element.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/host-apply/children/host-property-modal.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-apply/children/search-select-mix.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/conflict-list.vue
  src/ui/src/views/host-apply/failed-list.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-apply/property-confirm.vue
  src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue
  src/ui/src/views/host-temp/apply-status.vue
Labels: inner

#3617 添加外网ip唯一校验的upgrader查找属性时添加owner id查询条件
  src/scene_server/admin_server/upgrader/y3.7.201912121117/add_host_outer_ip_unique.go
Labels: demand

#3578 支持按名称排序；规范分页参数校验方式
  scripts/init.py
  src/common/metadata/hostserver.go
  src/common/metadata/page.go
  src/scene_server/admin_server/upgrader/y3.6.201911141516/obj_host_add_field_type_list.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/create_table.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/init_chart.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/upgrader.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/topo_server/service/inst_business.go
Labels: optimization

#3605 主机属性自动应用功能优化及鉴权接入
  scripts/init.py
  src/apimachinery/coreservice/hostapplyrule/api.go
  src/apimachinery/coreservice/hostapplyrule/hostapplyrule.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_initial.go
  src/auth/meta/resource.go
  src/auth/parser/host.go
  src/auth/parser/hostapply.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
  src/common/metadata/attribute.go
  src/common/metadata/host_apply_rule.go
  src/common/metadata/object.go
  src/common/metadata/procserver.go
  src/scene_server/admin_server/upgrader/y3.7.201911141719/init_host_property_apply.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/hostapplyrule.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/host.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/hostapplyrule/plan.go
  src/source_controller/coreservice/core/hostapplyrule/rule.go
  src/source_controller/coreservice/service/host_apply_rule.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_host_apply_rule_initfunc.go
  src/thirdpartyclient/esbserver/user/api.go
  src/thirdpartyclient/esbserver/user/esbserv.go
  src/ui/src/components/host-apply/property-confirm-table.vue
  src/ui/src/store/modules/api/host-apply.js
  src/web_server/middleware/user/plugins/method/self/userinfo.go
Labels: demand

#3574 datacollection问题修复
  resources/language/default/property.json
  resources/language/en/property.json
  src/scene_server/datacollection/datacollection/middleware/discover.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/datacollection/datacollection/middleware/readme.md
  src/source_controller/coreservice/core/model/unique_crud.go
Labels: optimization

#3619 fix: 修复模型关联n-n时，俩实例之间的关联可以重复创建的bug
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/association.go
Labels: bug

#3622 update:ui: 进程模板调整
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
Labels: inner, optimization

#3583 fix: 删除实例bug
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/inst_business.go
Labels: bug

#3625 update:ui: 取消返回查看模式
  src/ui/src/views/service-template/children/operational.vue
Labels: inner

#3628 移除实例查询的鉴权
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/perm_sys.go
  src/auth/authcenter/permit/permit.go
Labels: demand

#3623 V3.7.x集成测试
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/auth/parser/settemplate.go
  src/common/definitions.go
  src/common/metadata/common.go
  src/common/metadata/hostserver.go
  src/common/metadata/inst.go
  src/common/metadata/set_template.go
  src/common/metadata/set_template_request.go
  src/common/querybuilder/types.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.7.201912171427/add_set_template_version.go
  src/scene_server/admin_server/upgrader/y3.7.201912171427/pkg.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/scene_server/topo_server/service/service_settemplate_initfunc.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/test/host_server/host_apply_test.go
  src/test/util/util.go
  vendor/k8s.io/client-go/CHANGELOG.md
  vendor/k8s.io/client-go/CONTRIBUTING.md
  vendor/k8s.io/client-go/INSTALL.md
  vendor/k8s.io/client-go/LICENSE
  vendor/k8s.io/client-go/OWNERS
  vendor/k8s.io/client-go/README.md
  vendor/k8s.io/client-go/SECURITY_CONTACTS
  vendor/k8s.io/client-go/code-of-conduct.md
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/client-go/go.sum
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
  vendor/vendor.json
Labels: demand

#3620 optimize:ui: 属性自动应用添加面包屑回退功能
  src/ui/src/components/host-apply/property-confirm-table.vue
  src/ui/src/components/layout/dynamic-breadcrumbs.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/conflict-list.vue
  src/ui/src/views/host-apply/edit.vue
  src/ui/src/views/host-apply/failed-list.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-apply/property-confirm.vue
  src/ui/src/views/host-apply/router.config.js
Labels: inner, optimization

#3636 云区域查询暂时跳过鉴权
  src/auth/authcenter/permit/permit.go
Labels: optimization

#3640 optimize readme.md with blueking standard.
  LICENSE.txt
  docs/resource/img/BKEN.png
  docs/resource/img/bk-cmdb.png
  readme.md
  readme_en.md
Labels: optimization

#3632 代码检查问题修复
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/serviceinstance.go
Labels: optimization

#3630 v3.6.xbugfix
  src/auth/extensions/association.go
  src/auth/extensions/attribute.go
  src/auth/extensions/attributegroup.go
  src/auth/extensions/audit.go
  src/auth/extensions/base.go
  src/auth/extensions/business.go
  src/auth/extensions/classification.go
  src/auth/extensions/dynamicgroup.go
  src/auth/extensions/host.go
  src/auth/extensions/instance.go
  src/auth/extensions/model.go
  src/auth/extensions/modelunique.go
  src/auth/extensions/module.go
  src/auth/extensions/plat.go
  src/auth/extensions/process.go
  src/auth/extensions/servicecategory.go
  src/auth/extensions/servicetemplate.go
  src/auth/extensions/set.go
  src/auth/extensions/settemplate.go
  src/auth/parser/topology.go
  src/common/metadata/procserver.go
  src/common/querybuilder/parser.go
  src/common/querybuilder/types.go
  src/common/querybuilder/validate.go
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/thirdpartyclient/esbserver/user/api.go
  src/thirdpartyclient/esbserver/user/esbserv.go
  src/web_server/middleware/user/plugins/method/self/userinfo.go
Labels: bug

#3631 代码检查
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/upgrader/compare.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/admin_server/upgrader/util.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/source_controller/coreservice/core/host/lock.go
  src/source_controller/coreservice/core/hostapplyrule/plan.go
  src/source_controller/coreservice/core/hostapplyrule/rule.go
  src/source_controller/coreservice/core/mainline/class.go
  src/source_controller/coreservice/core/mainline/manager.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/core/settemplate/set_template.go
Labels: optimization

#3637 update: 蓝鲸业务编辑判断
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: demand

#3624 3.7 优化调整
  src/ui/src/App.vue
  src/ui/src/components/feature-tips/index.vue
  src/ui/src/components/host-apply/conflict-resolve.vue
  src/ui/src/components/ui/other/tips.vue
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/custom-fields/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/host-operation/children/create-service-instance.vue
  src/ui/src/views/host-operation/children/deleted-service-instance.vue
  src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue
  src/ui/src/views/host-operation/children/move-to-idle-host.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.new.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-operation/children/move-to-idle-host.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-template/index.vue
Labels: optimization

#3647 业务拓扑中tab页disabled改为在内部提示
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/index.vue
Labels: optimization

#3634 允许前端页面修改蓝鲸业务
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/system/api.go
  src/apimachinery/coreservice/system/system.go
  src/apiserver/service/url.go
  src/auth/authcenter/permit/permit.go
  src/auth/meta/resource.go
  src/auth/parser/host.go
  src/common/metadata/adminserver.go
  src/common/paraparse/app.go
  src/scene_server/admin_server/service/flag.go
  src/scene_server/admin_server/service/service.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/logics/special.go
  src/scene_server/host_server/service/service.go
  src/scene_server/host_server/service/special.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/system/system.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/coreservice/service/system.go
Labels: demand, inner

#3642 fix: 饼图横轴数量设置隐藏，主机数量变化趋势图隐藏横轴数量设置
  src/ui/src/views/operation/chart-detail.vue
Labels: bug

#3645 V3.6.x 测试问题修复
  src/common/metadata/process.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/settemplate/set_template.go
Labels: bug

#3646 feature:ui: 添加主机转移/移除确认界面可二次编辑功能
  src/ui/package.json
  src/ui/src/components/ui/dialog/dialog.vue
  src/ui/src/magicbox/index.js
  src/ui/src/views/business-topology/host/host-selector-topology.vue
  src/ui/src/views/business-topology/host/host-selector.vue
  src/ui/src/views/host-operation/index.vue
Labels: demand

#3649 update:ui: 蓝鲸业务可编辑
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: demand

#3660 修复主机属性为bool类型默认值错误问题
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/index.vue
Labels: bug

#3659 fix:ui: 修复属性自动应用搜索结果为空是展示不正确的问题
  src/ui/package.json
  src/ui/src/views/business-topology/host/host-selector-topology.vue
  src/ui/src/views/host-apply/children/search-select-mix.vue
  src/ui/src/views/host-apply/index.vue
Labels: bug

#3657 3.6.x 回归优化
  src/ui/src/components/hosts/table/_quick-search.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/field-detail/int.vue
  src/ui/src/components/model-manage/field-group/field-view.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/relation/_property-filter.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/setup/validate.js
  src/ui/src/utils/tools.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-set.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/module-selector.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
  src/ui/src/views/set-template/sync-history.vue
Labels: bug, inner, optimization

#3650 字段属性排序问题
  src/ui/src/components/model-manage/field-group/index.vue
Labels: bug

#3666 云区域查询暂时跳过鉴权
  src/scene_server/host_server/service/cloudarea.go
Labels: demand

#3672 optimize: 调整权限中心的事件订阅和云区域名称 issue #3671
  resources/language/default/object.json
  src/auth/authcenter/perm_sys.go
Labels: optimization

#3663 feature: delete http header, not support http giz encoding issue #3641
  src/apimachinery/rest/request.go
  src/web_server/common/httpheader.go
  src/web_server/middleware/login.go
  src/web_server/service/user.go
Labels: inner, optimization

#3667 批量检查集群同步状态接口 #3623
  src/auth/parser/settemplate.go
  src/common/metadata/set_template_request.go
  src/scene_server/topo_server/service/service_settemplate_initfunc.go
  src/scene_server/topo_server/service/set_template.go
Labels: demand

#3670 update:ui: 优化体验
  src/ui/src/components/ui/form/search-input.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-operation/index.vue
Labels: optimization

#3677 UI：3.6测试回归
  src/ui/package.json
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/relation/_topology.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/filters/formatter.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/utils/tools.js
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/host-details/children/association-graphics.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/model-topology/children/display-config.vue
  src/ui/src/views/model-topology/children/graphics-association.vue
  src/ui/src/views/model-topology/children/graphics-config.vue
  src/ui/src/views/model-topology/children/graphics-models.vue
  src/ui/src/views/model-topology/children/graphics-options.js
  src/ui/src/views/model-topology/children/graphics-toolbar.vue
  src/ui/src/views/model-topology/children/graphics.js
  src/ui/src/views/model-topology/children/topology-graphics.vue
  src/ui/src/views/model-topology/index.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: bug, inner, optimization

#3680 修复问题：新建实例统计图表模型没有维度又是必填
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/operation/chart-detail.vue
Labels: bug

#3682 3.7体验问题修复
  src/ui/src/components/host-apply/property-confirm-table.vue
  src/ui/src/filters/formatter.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/utils/tools.js
  src/ui/src/views/host-apply/children/apply-status.vue
  src/ui/src/views/host-apply/children/host-property-modal.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-apply/conflict-list.vue
  src/ui/src/views/host-apply/failed-list.vue
  src/ui/src/views/host-apply/property-confirm.vue
Labels: optimization

#3683 cmdb_operation启动失败bugfix
  src/scene_server/operation_server/app/options/options.go
  src/scene_server/operation_server/app/server.go
  src/scene_server/operation_server/service/service.go
Labels: bug

#3684 完善业务私有字段与公有字段key互斥检查条件
  src/common/metadata/metadata.go
  src/source_controller/coreservice/core/model/attribute_private.go
Labels: optimization

#3685 refactor: 清理proc_server中的事务逻辑代码
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
Labels: optimization

#3668 optimization： 属性字段排序
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/model/model.go
  src/auth/parser/topolatest.go
  src/common/errInfo.go
  src/common/metadata/result.go
  src/common/metadata/update.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.6.201911141516/obj_host_add_field_type_list.go
  src/scene_server/admin_server/upgrader/y3.6.201912241627/pkg.go
  src/scene_server/admin_server/upgrader/y3.6.201912241627/sort_bk_property_index.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/web_server/logics/excel.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/fields.go
  src/web_server/logics/netdevice.go
  src/web_server/logics/netproperty.go
Labels: demand

#3692 fix: 创建模型属性接口，返回值修改为最新数据
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/apimachinery/coreservice/model/api.go
  src/common/errInfo.go
  src/scene_server/topo_server/service/object_attribute.go
Labels: demand, outer

#3695 安装的cmdb的时候，放开蓝鲸业务对进程信息的校验
  src/scene_server/admin_server/command/import.go
  src/scene_server/admin_server/command/types.go
Labels: demand, inner

#3696 UI: 修复模块选择器/主机选择器生成模式下显示异常的问题
  src/ui/src/views/business-topology/host/host-selector.vue
  src/ui/src/views/business-topology/host/module-selector.vue
Labels: bug, inner

#3691 部署文档mongodb版本调整为v3.6以上
  docs/overview/installation.md
Labels: demand
