Repository Tencent/bk-cmdb, pull requests merged in 2019-07, with the labels that each got.

#2653 UI: 优化无权限交互提示
  src/ui/src/components/hosts/transfer/index.vue
  src/ui/src/components/modal/permission.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/mixins/auth.js
  src/ui/src/router/index.js
  src/ui/src/router/meta.js
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business-model/router.config.js
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/business/router.config.js
  src/ui/src/views/cloud-confirm/router.config.js
  src/ui/src/views/cloud-discover/router.config.js
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/custom-query/router.config.js
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/eventpush/router.config.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-association/router.config.js
  src/ui/src/views/model-manage/children/field.vue
  src/ui/src/views/model-manage/children/group.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/index.old.vue
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/process/index.vue
  src/ui/src/views/process/module.vue
  src/ui/src/views/process/router.config.js
  src/ui/src/views/resource/index.vue
  src/ui/src/views/resource/router.config.js
  src/ui/src/views/topology/index.vue
  src/ui/src/views/topology/router.config.js
Labels: inner, optimization

#2617 Feature txn
  src/common/metadata/time.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/datacollection/datacollection/datacollection.go
  src/scene_server/event_server/app/server.go
  src/scene_server/topo_server/app/server.go
  src/source_controller/coreservice/app/server.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/hostcontroller/app/server.go
  src/source_controller/objectcontroller/app/server.go
  src/source_controller/proccontroller/app/server.go
  src/storage/dal/mongo/config.go
  src/storage/dal/mongo/remote/collection.go
  src/storage/dal/mongo/remote/find.go
  src/storage/dal/mongo/remote/mongo.go
  src/storage/dal/mongo/remote/mongo_test.go
  src/storage/dal/mongo/remote/transaction.go
  src/storage/dal/mongo/remote/transaction_test.go
  src/storage/mongodb/collection.go
  src/storage/mongodb/driver/collection.go
  src/storage/mongodb/driver/database.go
  src/storage/mongodb/driver/session.go
  src/storage/mongodb/session.go
  src/storage/rpc/client.go
  src/storage/rpc/server.go
  src/storage/rpc/types.go
  src/storage/tmserver/core/command/ddl.go
  src/storage/tmserver/core/command/find.go
  src/storage/tmserver/core/command/insert.go
  src/storage/tmserver/core/command/update.go
  src/storage/tmserver/core/core.go
  src/storage/tmserver/core/session/manager.go
  src/storage/tmserver/core/type.go
  src/storage/tmserver/service/handler.go
  src/storage/types/message_type.go
  src/storage/types/types.go
  src/storage/types/types_test.go
  vendor/github.com/mongodb/mongo-go-driver/bson/bson_test.go
  vendor/github.com/mongodb/mongo-go-driver/bson/bsoncodec/default_value_decoders.go
  vendor/github.com/mongodb/mongo-go-driver/bson/bsoncodec/struct_codec.go
Labels: demand, inner

#2663 optimize: blueking community bk-ci.
  readme.md
Labels: inner, optimization

#2664 update:ui: 回归优化
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/service-template/index.vue
Labels: inner, optimization

#2661 Full text search optimization
  src/scene_server/topo_server/service/find.go
Labels: inner, optimization

#2666 事务相关
  src/storage/dal/mongo/remote/mongo.go
  src/storage/dal/mongo/remote/pool.go
  src/storage/rpc/pool.go
Labels: demand, inner

#2668 修复实例数据关联关系导入，提示唯一健个数失败
  resources/language/default/import_instance.json
  resources/language/en/import_instance.json
  src/common/eventclient/eventclient.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/topo_server/core/operation/import_association.go
Labels: inner

#2671 fixes upgrade
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: inner

#2658 服务实例优化需求
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  resources/language/default/placeholder.json
  resources/language/en/placeholder.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/common/errInfo.go
  src/common/metadata/association.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/pkg.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/update_process_property.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/scene_server/topo_server/core/inst/inst.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_category.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/process_template.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
Labels: demand

#2673 optimize audit log
  src/common/auditoplog/operationlog.go
Labels: inner, optimization

#2680 修复导入主机实例报错问题
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/topo_server/core/operation/import_association.go
Labels: inner, optimization

#2683 ui: 禁止修改模型关联关系的关联类型
  src/ui/src/views/model-manage/children/relation-detail/index.vue
Labels: demand, inner

#2686 add change_asst_id script
  src/scene_server/admin_server/change_asst_id.js
Labels: inner, optimization

#2684 ui: 禁止修改模型关联关系的关联类型
  src/ui/src/views/model-manage/children/relation-detail/index.vue
Labels: demand, inner

#2687 change default association kind's DestinationToSourceNote to "被关联"
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
Labels: inner, optimization

#2681 多租户下主机分配到业务，删除主机的问题
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/service/host.go
Labels: optimization

#2678 服务实例支持label和selector功能 #2674
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/label/api.go
  src/apimachinery/coreservice/label/label.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/common/selector/label.go
  src/common/selector/selector.go
  src/common/selector/selector_test.go
  src/common/util/map.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/label/label.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/label.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand, inner

#2691 用python重写makefile中的配置生成逻辑 #2688
  scripts/Makefile
  scripts/prepare_cfg.py
Labels: demand, inner

#2695 makefile 配置生成 bugfix
  scripts/prepare_cfg.py
Labels: demand, inner

#2698 V3.2.x fix: 系统权限搜索按钮隐藏 && 操作审计业务不可输入搜索 && 操作审计模型和类型选中后不能清除选中
  src/ui/src/views/audit/index.vue
  src/ui/src/views/permission/role.vue
Labels: optimization, outer

#2699 v3.4.x： fix: 操作审计业务不可搜索 && 类型选中后不可清楚选中
  src/ui/src/views/audit/index.vue
Labels: optimization, outer

#2694 修复升级进程的缺陷
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
Labels: inner

#2676 事务提交和取消无效
  src/storage/dal/mongo/remote/transaction.go
  src/storage/dal/mongo/remote/transaction_test.go
  src/storage/tmserver/core/command/commit_transaction.go
Labels: demand, inner

#2703 style:code format issue #2614
  src/storage/dal/mongo/remote/find.go
  src/storage/dal/mongo/remote/wrapper_transaction.go
  src/storage/mongodb/driver/collection.go
Labels: inner

#2692 更进程实例数据结构：绑定IP由枚举类型改成IP串
  scripts/prepare_cfg.py
  src/apiserver/service/service.go
  src/apiserver/service/version.go
  src/common/metadata/process.go
  src/common/selector/selector.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/update_process_property.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/web_server/service/index.go
Labels: inner, optimization

#2707 补充3.4升级的合包遗漏
  src/scene_server/admin_server/change_asst_id.js
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.12.13.01/addswitchAssociation.go
  src/scene_server/admin_server/upgrader/x18.12.13.01/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.13.02/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.13.02/upgrader.go
Labels: demand, inner

#2696 fix: mongodb用户名密码包括特殊字符导致拼接的URI无法连接到mongodb V3.4
  src/scene_server/topo_server/core/operation/classification.go
  src/storage/dal/mongo/config.go
Labels: demand, inner

#2693 fix: mongodb用户名密码包括特殊字符导致拼接的URI无法连接到mongodb issue #2690
  src/storage/dal/mongo/mongo.go
Labels: demand, inner

#2701 update:ui: 进程绑定ip调整
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/children/update.vue
  src/ui/src/views/service-template/index.vue
Labels: inner, optimization

#2665 v3.4.x auth related optimization.
  resources/errors/common/default/host_server.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/host_server.json
  resources/errors/english/en/topo_server.json
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/host.go
  src/auth/meta/meta.go
  src/auth/meta/resource.go
  src/auth/parser/host.go
  src/common/errInfo.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/hostlock.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/service.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/classification.go
  src/scene_server/topo_server/core/model/group.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/privilege/group.go
  src/scene_server/topo_server/service/inst_business.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/association/kind.go
  src/source_controller/coreservice/core/association/model.go
  src/source_controller/coreservice/core/model/classification.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/source_controller/hostcontroller/service/favourite.go
  src/source_controller/hostcontroller/service/user.go
  src/source_controller/objectcontroller/service/object_unique.go
Labels: inner, optimization

#2718 修复自定义层级查询主机错误。修复healthz接口
  src/apimachinery/healthz/healthz.go
  src/apimachinery/rest/request.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/service/service.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/datacollection/service/service.go
  src/scene_server/event_server/app/server.go
  src/scene_server/event_server/service/service.go
  src/scene_server/host_server/app/server.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/auditcontroller/app/server.go
  src/source_controller/auditcontroller/service/service.go
  src/source_controller/hostcontroller/app/server.go
  src/source_controller/hostcontroller/service/service.go
  src/source_controller/objectcontroller/app/server.go
  src/source_controller/objectcontroller/service/service.go
  src/source_controller/proccontroller/app/server.go
  src/source_controller/proccontroller/service/service.go
Labels: inner, optimization

#2729 [v3.5.x] tmserver 支持 Aggregate 方法 issue #2714
  src/storage/dal/mongo/remote/collection.go
  src/storage/mongodb/collection.go
  src/storage/mongodb/driver/collection.go
  src/storage/tmserver/core/command/aggregate.go
Labels: demand, inner

#2725 ui: 优化API配置
  src/ui/src/views/eventpush/pop.vue
  src/ui/src/views/model/details/field.vue
Labels: bug, inner

#2724 feature: 新增服务实例label聚合操作
  src/common/metadata/core_service.go
  src/common/metadata/metadata.go
  src/common/metadata/process.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/source_controller/coreservice/core/host/identifier/identifier.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/core/process/process_template.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/core/process/service_template.go
  src/source_controller/coreservice/service/hostmodule.go
Labels: demand

#2722 服务模板/进程权限接入 #2721
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/auth/extensions/servicecategory.go
  src/auth/extensions/servicetemplate.go
  src/auth/parser/chain.go
  src/auth/parser/framework.go
  src/auth/parser/parser.go
  src/auth/parser/process.go
  src/auth/parser/processinstance.go
  src/auth/parser/processtemplate.go
  src/auth/parser/servicecategory.go
  src/auth/parser/serviceinstance.go
  src/auth/parser/servicetemplate.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/scene_server/proc_server/proc_service/service/service.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/processtemplate.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/servicecategory.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/source_controller/hostcontroller/service/favourite.go
  src/source_controller/hostcontroller/service/user.go
  src/source_controller/objectcontroller/service/object_unique.go
Labels: demand, inner

#2744 privilege接口正常返回格式与默认值格式不一致 #2743
  src/source_controller/objectcontroller/service/role_action.go
Labels: inner, optimization

#2745 privilege接口正常返回格式与默认值格式不一致 #2743
  src/source_controller/objectcontroller/service/role_action.go
Labels: inner, optimization

#2742 修复v3.4.x路由注册与eventserver数据清理
  src/apiserver/service/url.go
  src/scene_server/event_server/distribution/reconclier.go
Labels: inner, optimization

#2746 optimize: optimize delete mainline object problem
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/common/errInfo.go
  src/scene_server/host_server/logics/phpapi.go
  src/scene_server/host_server/service/phpapi.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/classification.go
  src/scene_server/topo_server/core/model/group.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/privilege/group.go
  src/source_controller/hostcontroller/service/favourite.go
  src/source_controller/hostcontroller/service/user.go
  src/source_controller/objectcontroller/service/object_unique.go
Labels: inner, optimization

#2748 业务权限管理保存权限配置没有生效 #2747
  src/source_controller/objectcontroller/service/role_action.go
Labels: inner, optimization

#2751 业务权限管理保存权限配置没有生效 #2747
  src/common/util/ownerutil.go
  src/source_controller/coreservice/service/privilege_role.go
Labels: inner, optimization

#2753 optimize delete mainline object operation.
  src/common/util/flags.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: inner, optimization

#2752 optimize: optimize delete mainline object operation.
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/inst.go
Labels: inner, optimization

#2756 解决字段查询没生效问题
  src/source_controller/coreservice/core/instances/instance_crud.go
Labels: inner, optimization

#2754 V3.4.x 主机相关优化
  resources/language/default/oplogdesc.json
  resources/language/en/oplogdesc.json
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/service/module.go
  src/scene_server/topo_server/core/operation/association.go
Labels: inner

#2758 event-server coding style refactor #2735
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/common/metadata/eventserver.go
  src/scene_server/admin_server/upgrader/x18.10.10.01/procsrv.go
  src/scene_server/event_server/distribution/callback.go
  src/scene_server/event_server/distribution/distribution.go
  src/scene_server/event_server/distribution/handle_event.go
  src/scene_server/event_server/distribution/reconclier.go
  src/scene_server/event_server/distribution/start.go
  src/scene_server/event_server/distribution/transaction.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/event_server/service/service.go
  src/scene_server/event_server/service/subscription.go
  src/scene_server/event_server/types/const.go
  src/scene_server/topo_server/service/fulltextsearch.go
  src/scene_server/topo_server/service/privilege.go
  src/scene_server/topo_server/service/privilege_group.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/core/host/transfer/transfer.go
Labels: inner, optimization

#2766 tmserver metric 和循环引用的问题
  src/apimachinery/rest/request.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/datacollection/datacollection/datacollection.go
  src/scene_server/event_server/app/server.go
  src/scene_server/topo_server/app/server.go
  src/source_controller/coreservice/service/service.go
  src/storage/dal/mongo/remote/mongo.go
  src/storage/dal/mongo/remote/pool.go
Labels: inner

#2770 V3.5.x tmserver aggregate 返回数据重复
  src/storage/mongodb/driver/collection.go
Labels: bug

#2771 服务实例详情列表查询接口
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/apimachinery/coreservice/topographics/graphic.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/perm_biz.go
  src/auth/parser/serviceinstance.go
  src/common/definitions.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/util.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/core/compatiblev2/module.go
  src/scene_server/topo_server/core/compatiblev2/set.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/service/privilege.go
  src/scene_server/topo_server/service/privilege_group.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/mainline/manager.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/hostfavourite.go
  src/source_controller/coreservice/service/hostmodule.go
  src/source_controller/coreservice/service/hostuser.go
  src/source_controller/coreservice/service/privilege_usergroup.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/source_controller/coreservice/service/topographics.go
  src/ui/src/store/modules/api/service-instance.js
Labels: demand

#2781 服务模板/进程权限接入bugfix #2721
  src/apimachinery/rest/request.go
  src/auth/parser/framework.go
  src/auth/parser/process.go
  src/auth/parser/processinstance.go
  src/auth/parser/processtemplate.go
  src/auth/parser/servicetemplate.go
Labels: optimization

#2779 depend: add go-cmp library issue #2778
  vendor/github.com/google/go-cmp/.travis.yml
  vendor/github.com/google/go-cmp/CONTRIBUTING.md
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/README.md
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/util_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/compare_test.go
  vendor/github.com/google/go-cmp/cmp/example_reporter_test.go
  vendor/github.com/google/go-cmp/cmp/example_test.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff_test.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func_test.go
  vendor/github.com/google/go-cmp/cmp/internal/testprotos/protos.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project1.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project2.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project3.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/project4.go
  vendor/github.com/google/go-cmp/cmp/internal/teststructs/structs.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort_test.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero_test.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/options_test.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/github.com/google/go-cmp/go.mod
Labels: inner

#2787 feature: add load test case.
  src/apiserver/service/http.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/remote/find.go
  src/storage/rpc/client.go
  src/storage/rpc/pool.go
  src/test/business/business_suite_test.go
  src/test/business/business_test.go
  src/test/run/color.go
  src/test/run/limiter.go
  src/test/run/run.go
  src/test/run/stats.go
Labels: demand

#2776 V3.5.x tmserver
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/errInfo.go
  src/scene_server/admin_server/upgrader/v3.0.8/addDefauleApp.go
  src/scene_server/admin_server/upgrader/x18.12.12.01/add_aix_property.go
  src/scene_server/admin_server/upgrader/x18.12.12.01/set_tcp_default.go
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
  src/scene_server/validator/util.go
  src/scene_server/validator/valid_basic.go
Labels: inner

#2784 支持根据用户名搜索业务
  src/common/paraparse/app.go
  src/scene_server/topo_server/service/inst_business.go
Labels: inner

#2782 feature: filter operate log duplicate info issue #2778
  src/source_controller/auditcontroller/logics/audit.go
Labels: inner

#2794 fix: sync WiteList 拼写错误改为WhiteList
  src/scene_server/synchronize_server/app/options/options.go
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/synchronize_server/logics/background_synchronize.go
  src/scene_server/synchronize_server/logics/inst.go
Labels: outer

#2790 V3.4.x 支持根据用户搜索业务
  src/common/paraparse/app.go
  src/scene_server/topo_server/service/inst_business.go
Labels: inner

#2810 增强权限同步producer代码可读性
  src/scene_server/admin_server/authsynchronizer/producer.go
Labels: optimization

#2818 style: err code define issue #1780
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/errInfo.go
Labels: inner

#2822 V3.2.x 修复查询指定模型的指定实例关联top报错
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/inst.go
  src/common/metadata/toposerver.go
Labels: optimization

#2827 optimize multi-language issue
  resources/language/en/enum.json
Labels: optimization

#2826 优化收藏名字重复提示
  src/scene_server/host_server/service/favourite.go
  src/source_controller/hostcontroller/service/favourite.go
Labels: inner, optimization

#2823 V3.2.4 修复查询指定模型的指定实例关联top报错
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/inst.go
  src/common/metadata/toposerver.go
Labels: bug

#2811 feature:ui: 无权限跳转
  src/ui/src/api/index.js
  src/ui/src/components/modal/permission.vue
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/auth.js
Labels: demand, inner

#2806 topo server代码规范梳理 #2805
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/compatiblev2.go
  src/scene_server/topo_server/core/operation/graphics.go
  src/scene_server/topo_server/core/operation/health.go
  src/scene_server/topo_server/core/operation/identifier.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/topo_server/core/privilege/privilege.go
  src/scene_server/topo_server/core/privilege/role.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/compatiblev2.go
  src/scene_server/topo_server/service/graphics.go
  src/scene_server/topo_server/service/identifier.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/inst_set.go
  src/scene_server/topo_server/service/object_association.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/object_classification.go
  src/scene_server/topo_server/service/object_group.go
  src/scene_server/topo_server/service/privilege.go
  src/scene_server/topo_server/service/privilege_group.go
  src/scene_server/topo_server/service/privilege_role.go
  src/scene_server/topo_server/service/service.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/scene_server/topo_server/service/types.go
Labels: optimization

#2820 feature: add get skip url from auth center, add sync biz roles from auth center demand.
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/apiserver/service/auth.go
  src/apiserver/service/service.go
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/type.go
  src/auth/extensions/host.go
  src/auth/extensions/types.go
  src/common/errInfo.go
  src/common/metadata/result.go
  src/scene_server/admin_server/synchronizer/handler/process.go
  src/scene_server/admin_server/synchronizer/handler/usergroup.go
  src/scene_server/admin_server/synchronizer/meta/types.go
  src/scene_server/admin_server/synchronizer/producer.go
  src/scene_server/admin_server/synchronizer/worker.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/hostlock.go
  src/scene_server/host_server/service/module.go
Labels: demand

#2836 V3.5.x mainline search
  src/common/metadata/time.go
  src/common/types/serverInfo.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/synchronize_server/logics/background_synchronize.go
  src/scene_server/synchronize_server/logics/model.go
  src/source_controller/coreservice/core/instances/validator_util.go
  src/source_controller/coreservice/core/mainline/manager.go
  src/storage/rpc/types.go
  src/storage/types/types.go
  src/storage/types/types_test.go
Labels: bug, demand, optimization
