Repository Tencent/bk-cmdb, pull requests merged in 2019-09, with the labels that each got.

#3064 fix: previous commit missing one update condition
  src/scene_server/topo_server/core/operation/inst.go
Labels: optimization

#3068 [v3.2.x] find/instassttopo/object/{object_id}/inst/{inst_id} 接口返回关联关系ID
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/types.go
Labels: demand, inner

#3083 根据模块名获取绑定进程信息bugfix
  src/source_controller/objectcontroller/service/process.go
Labels: bug

#3081 权限同步问题处理 #3080
  src/auth/extensions/instance.go
  src/auth/extensions/plat.go
  src/auth/extensions/types.go
  src/scene_server/admin_server/authsynchronizer/handler/instance.go
  src/scene_server/admin_server/authsynchronizer/handler/plat.go
  src/scene_server/admin_server/authsynchronizer/meta/types.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/authsynchronizer/worker.go
Labels: demand

#3071 fix nil map issue in apiserver
  src/api_server/logics/v2/common/converter/converter.go
Labels: bug

#3090 服务实例主键冲突 & 权限中心同步问题修复
  src/auth/extensions/types.go
  src/scene_server/admin_server/authsynchronizer/handler/instance.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.08.26.02/fix_service_instance_max_id.go
  src/scene_server/admin_server/upgrader/x19.08.26.02/pkg.go
  src/scene_server/topo_server/core/inst/inst.go
  src/source_controller/coreservice/core/process/service_instance.go
Labels: demand

#3085 修复当网络，中间件下的模型被删除后，升级失败
  src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
Labels: bug, inner

#3095 修复当网络，中间件下的模型被删除后，升级失败
  src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
Labels: bug, inner

#3093 datacollection模块资源添加时注册到权限中心
  src/auth/extensions/host.go
  src/auth/extensions/types.go
  src/scene_server/datacollection/app/options/options.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/datacollection/datacollection/datacollection.go
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
  src/scene_server/datacollection/datacollection/middleware/discover.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/datacollection/datacollection/netcollect/netdevice.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
Labels: demand

#3096 doc:ui: 翻译文件修改
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
Labels: optimization

#3102 optimize: full text search, snapshot, auth related optimization.
  src/auth/authcenter/perm_biz.go
  src/auth/authcenter/perm_initial.go
  src/scene_server/host_server/logics/agent.go
  src/scene_server/topo_server/service/fulltextsearch.go
  src/scene_server/topo_server/service/object_attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/thirdpartyclient/elasticsearch/esclient.go
Labels: demand, optimization

#3098 调整已注册实例的拉取策略
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/util.go
  src/auth/extensions/host.go
  src/common/errInfo.go
  src/scene_server/admin_server/authsynchronizer/handler/core.go
  src/scene_server/admin_server/authsynchronizer/handler/instance.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.09.03.02/pkg.go
  src/scene_server/admin_server/upgrader/x19.09.03.02/set_module_set_template_field_uneditable.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
Labels: demand, optimization

#3107 UI： 修改权限转换协议
  src/ui/package.json
  src/ui/src/setup/permission.js
Labels: optimization

#3103 refactor: rename
  src/source_controller/coreservice/core/model/attribute_curd.go
Labels: optimization

#3108 update:ui: 界面UI调整
  src/ui/src/components/columns-config/columns-config.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/dictionary/menu.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-synchronous/router.config.js
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.old.vue
Labels: optimization

#3106 调整进程属性分组 #3105
  resources/language/default/property_group.json
  resources/language/en/property_group.json
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.09.03.03/pkg.go
  src/scene_server/admin_server/upgrader/x19.09.03.03/set_module_set_template_field_uneditable.go
Labels: optimization

#3109 optimize: change auth convert protocol.
  src/apiserver/service/auth.go
Labels: optimization

#3111 fix:ui: 修复部分一级导航权限模式设置不正确的问题
  src/ui/src/components/modal/permission.vue
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/views/audit/router.config.js
  src/ui/src/views/business-model/router.config.js
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/business/router.config.js
  src/ui/src/views/cloud-confirm/router.config.js
  src/ui/src/views/cloud-discover/router.config.js
  src/ui/src/views/custom-fields/router.config.js
  src/ui/src/views/custom-query/router.config.js
  src/ui/src/views/eventpush/router.config.js
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/model-association/router.config.js
  src/ui/src/views/model-manage/router.config.js
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/resource/router.config.js
  src/ui/src/views/service-category/router.config.js
  src/ui/src/views/service-instance/router.config.js
  src/ui/src/views/service-template/router.config.js
Labels: optimization

#3115 roll back auth resources
  src/apiserver/service/auth.go
  src/apiserver/service/filter.go
  src/auth/authcenter/perm_biz.go
Labels: optimization

#3114 文案优化：集群名字->集群名
  resources/language/default/property.json
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.09.03.04/pkg.go
  src/scene_server/admin_server/upgrader/x19.09.03.04/set_module_set_template_field_uneditable.go
Labels: optimization

#3119 导入关联关系错误
  src/scene_server/topo_server/core/operation/import_association.go
  src/source_controller/coreservice/core/association/instance.go
  src/web_server/logics/excel.go
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
Labels: bug, outer

#3123 UI: 调整convert auth 参数
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/auth.js
Labels: demand

#3127 fix:import association bug issue #3126
  src/scene_server/topo_server/core/operation/import_association.go
Labels: bug

#3130 权限注册支持分页 #3129
  src/auth/authcenter/authcenter.go
  src/auth/meta/meta.go
  src/scene_server/admin_server/authsynchronizer/handler/core.go
Labels: optimization

#3131 UI：交互体验优化
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/components/ui/form/longchar.vue
  src/ui/src/components/ui/form/objuser.vue
  src/ui/src/components/ui/form/singlechar.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/eventpush/push-detail.vue
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/service-template/children/process-form.vue
Labels: optimization

#3121 fix: solve bug in ParseHostSnap issue #3120
  src/scene_server/host_server/logics/agent.go
  src/scene_server/host_server/logics/agent_test.go
Labels: optimization

#3143 data-collection模块导入实例时记录审计日志
  src/auth/extensions/base.go
  src/scene_server/datacollection/datacollection.go
  src/scene_server/datacollection/datacollection/manager.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/datacollection/datacollection/middleware/util.go
  src/scene_server/datacollection/readme.md
Labels: demand

#3135 去掉BKHostOuterIPField
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
Labels: outer

#3122 获取实例关联关系的列表
  resources/errors/common/default/core_service.json
  resources/errors/english/en/core_service.json
  src/apiserver/service/url.go
  src/common/metadata/query.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/service_initfunc.go
Labels: bug, inner

#3152 optimize: sync auth related optimized
  src/scene_server/admin_server/authsynchronizer/handler/core.go
  src/scene_server/admin_server/authsynchronizer/producer.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/source_controller/coreservice/service/instances.go
Labels: demand, optimization

#3155 feature: 新增清理业务下在IAM中注册的实例和审计资源
  src/apiserver/core/compatiblev2/common/converter/converter.go
  src/apiserver/service/auth.go
  src/apiserver/service/filter.go
  src/auth/auth.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/client.go
  src/auth/authcenter/perm_initial.go
Labels: demand

#3154 ui: 调整服务实例标签key正则
  src/ui/src/setup/validate.js
  src/ui/src/views/business-topology/children/edit-label.vue
Labels: optimization

#3153 调整服务实例的标签key校验规则
  src/common/selector/label.go
Labels: demand

#3164 降低migrate文件版本号 #3163
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.12.12.07/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.07/update_ip_regex.go
Labels: demand

#3167 V3.5.x adminserver 18.12.12.05 bug
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
  src/scene_server/admin_server/upgrader/x18.12.13.01/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.13.02/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.13.02/upgrader.go
Labels: bug

#3166 优化升级卡死的问题
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
Labels: optimization

#3165 UI: 功能更新
  src/ui/src/App.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/components/ui/form/date.vue
  src/ui/src/components/ui/form/time.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/dictionary/menu-symbol.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/router/meta.js
  src/ui/src/setup/validate.js
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/store/modules/global.js
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/custom-query/router.config.js
  src/ui/src/views/history/index.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/index.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/hosts/index.vue
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/index/children/full-text-search.old.vue
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/index/children/search-input.old.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/index/children/search-item-host.vue
  src/ui/src/views/status/403.vue
  src/ui/src/views/status/index.js
  src/ui/src/views/status/permission.vue
Labels: demand

#3162 excel导入配置项实例时，提示某行某个字段校验不通过
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/scene_server/host_server/logics/import.go
  src/scene_server/validator/valid_basic.go
  src/source_controller/coreservice/core/instances/validator_attr.go
Labels: optimization

#3186 读取execel，去除空格 #3180
  src/web_server/logics/excel_util.go
Labels: optimization

#3181 v3.5.x: fix: auth-parser URL error
  src/auth/parser/topology.go
Labels: optimization

#3174 UI: 功能调整
  src/ui/package.json
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/dynamic-breadcrumbs.vue
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/dictionary/menu.js
  src/ui/src/router/index.js
  src/ui/src/router/meta.js
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-synchronous/router.config.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/host-details/index.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/hosts/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-topology/index.new.vue
  src/ui/src/views/model-topology/router.config.js
  src/ui/src/views/service-instance/clone.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: demand, optimization

#3177 调整longchar字段类型最大长度为 15000
  src/common/definitions.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
Labels: optimization

#3173 fix: fix upgrade process in v3.2 to v3.5 service instance problem.
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
Labels: bug

#3171 update:ui: 拓扑树交互调整
  src/ui/package.json
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: optimization

#3170 fix:增加主机导入时的云区域数值校验 issue #3169
  resources/language/default/import_instance.json
  resources/language/en/import_instance.json
  src/common/mapstr/mapstr.go
  src/scene_server/host_server/logics/import.go
  src/test/host_server/host_abnormal_test.go
Labels: optimization

#3185 v3.5.x mapstr的String(key string)函数问题修复
  src/common/mapstr/mapstr.go
  src/common/mapstr/mapstr_test.go
Labels: bug

#3036 集群模板CRUD
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  resources/language/default/property.json
  resources/language/en/property.json
  src/apimachinery/coreservice/settemplate/api.go
  src/apimachinery/coreservice/settemplate/settemplate.go
  src/apimachinery/procserver/process/api.go
  src/apimachinery/procserver/process/process.go
  src/apimachinery/procserver/service/api.go
  src/apimachinery/procserver/service/template.go
  src/apimachinery/toposerver/settemplate/apis.go
  src/apimachinery/toposerver/settemplate/settemplate.go
  src/apiserver/service/url.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/errors/errorIf.go
  src/common/metadata/inst.go
  src/common/metadata/set_template.go
  src/common/metadata/set_template_request.go
  src/common/tablenames.go
  src/common/util/lib.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.09.06.01/add_module_property.go
  src/scene_server/admin_server/upgrader/x19.09.06.01/add_set_property.go
  src/scene_server/admin_server/upgrader/x19.09.06.01/create_table.go
  src/scene_server/admin_server/upgrader/x19.09.06.01/initialize_set_template_field.go
  src/scene_server/admin_server/upgrader/x19.09.06.01/pkg.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/worker.go
  src/scene_server/topo_server/service/service.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/scene_server/topo_server/service/service_settemplate_initfunc.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_set_template_initfunc.go
  src/source_controller/coreservice/service/set_template.go
  src/test/proc_server/proc_server_suite_test.go
  src/test/set_template/topo_server/run_test.go
  src/test/set_template/topo_server/set_template_test.go
  src/test/set_template/topo_server/topo_server_suite_test.go
Labels: demand

#3193 update:ui: 3.5回归
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/status.vue
Labels: optimization

#3192 optimize: optimize update host batch api operation.
  src/apiserver/app/server.go
  src/scene_server/host_server/logics/hostsearch.go
  src/scene_server/host_server/service/host.go
Labels: bug

#3194 optimize: 优化批量修改主机时鉴权提示
  src/auth/authcenter/adaptor.go
  src/auth/extensions/audit.go
  src/auth/extensions/base.go
  src/auth/extensions/business.go
  src/auth/extensions/host.go
  src/auth/extensions/module.go
  src/auth/extensions/process.go
  src/auth/extensions/servicecategory.go
  src/auth/extensions/servicetemplate.go
  src/scene_server/host_server/service/host.go
Labels: optimization

#3191 回归体验优化
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/modal/permission.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/children/service-instance-empty.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/index.vue
Labels: demand, optimization

#3183 optimize: use global variable to control auth center enable status
  src/apiserver/app/options/options.go
  src/apiserver/app/server.go
  src/apiserver/service/service.go
  src/auth/authcenter/authcenter.go
  src/auth/authcenter/type.go
  src/common/auth/auth.go
  src/scene_server/admin_server/app/options/options.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/authsynchronizer/synchronizer.go
  src/scene_server/admin_server/service/authcenter.go
  src/scene_server/datacollection/app/options/options.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/event_server/app/options/options.go
  src/scene_server/event_server/app/server.go
  src/scene_server/host_server/app/options/options.go
  src/scene_server/proc_server/app/options/options.go
  src/scene_server/synchronize_server/app/options/options.go
  src/scene_server/topo_server/app/options/options.go
Labels: optimization

#3195 feature-ui 回归调整
  src/ui/src/views/business-topology/children/edit-label.vue
  src/ui/src/views/business-topology/children/service-instance-empty.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: optimization

#3196 UI: 交互优化
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/magicbox/index.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/history.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
Labels: optimization

#3197 UI： 界面入口调整
  src/ui/package.json
  src/ui/src/dictionary/menu.js
  src/ui/src/views/business-model/index.vue
  src/ui/src/views/business-model/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-topology/router.config.js
Labels: optimization

#3210 业务运维与查询业务拓扑权限调整
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/perm_initial.go
  src/auth/authcenter/permit/permit.go
Labels: optimization

#3208 定制模块重名提示
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/topo_server/core/operation/inst_module.go
Labels: optimization

#3205 模块创建接口兼容无服务分类参数
  src/scene_server/topo_server/core/operation/inst_module.go
Labels: optimization

#3201 从数据初始化移除中间件
  resources/language/default/classification.json
  resources/language/default/object.json
  resources/language/default/property.json
  resources/language/default/property_group.json
  resources/language/en/classification.json
  resources/language/en/object.json
  resources/language/en/property.json
  resources/language/en/property_group.json
  src/scene_server/admin_server/upgrader/v3.0.8/addPresetObjects.go
  src/scene_server/admin_server/upgrader/v3.0.8/objAttDescData.go
  src/scene_server/admin_server/upgrader/x08.09.04.01/pkg.go
  src/scene_server/admin_server/upgrader/x08.09.04.01/updateSystemProperty.go
  src/scene_server/admin_server/upgrader/x18.12.12.06/reconcil_unique.go
Labels: demand

#3198 服务模板优化
  resources/errors/common/default/proc_server.json
  resources/errors/english/en/proc_server.json
  scripts/build.sh
  src/common/errInfo.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/add_default_category.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/add_inner_category.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/servicecategory.go
Labels: bug, optimization

#3211 fix: fix move host from idle to fault or resource pool, but skip auth…
  src/auth/authcenter/permit/permit.go
  src/auth/extensions/host.go
  src/auth/parser/host.go
  src/scene_server/host_server/service/module.go
Labels: bug

#3215 fix：云同步并发读写加锁，ticker可能存在资源泄露
  src/scene_server/host_server/logics/cloud_synctask.go
Labels: bug

#3217 optimize init.py
  docs/overview/installation.md
  scripts/init.py
  scripts/template.sh.start
Labels: demand

#3214 支持批量创建集群
  src/auth/parser/topology.go
  src/scene_server/admin_server/upgrader/x19.09.06.01/pkg.go
  src/scene_server/topo_server/service/inst_set.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/source_controller/coreservice/service/set_template.go
  src/test/set_template/topo_server/run_test.go
  src/test/topo_server/set_template_test.go
  src/test/topo_server/topo_server_suite_test.go
Labels: demand

#3224 optimize: a operator in mongodb can not be empty in search host api.
  src/common/paraparse/host.go
Labels: optimization
