Repository Tencent/bk-cmdb, pull requests merged in 2020-03, with the labels that each got.

#3862 UI: 主机详情云区域样式优化
  src/ui/src/views/host-details/children/info.vue
Labels: demand

#3863 UI: 主机关联列表页面不显示无关联实例表格
  src/ui/src/views/host-details/children/association-list-table.vue
Labels: optimization

#3858 UI: 实例关联页面修改为与主机一致
  src/ui/src/components/model-instance/relation/create.vue
  src/ui/src/components/model-instance/relation/graphics.vue
  src/ui/src/components/model-instance/relation/index.vue
  src/ui/src/components/model-instance/relation/list-table.vue
  src/ui/src/components/model-instance/relation/list.vue
  src/ui/src/components/model-instance/relation/property-filter.vue
  src/ui/src/components/relation/_details.vue
  src/ui/src/components/relation/_tree.vue
  src/ui/src/components/relation/index.vue
  src/ui/src/views/business/details.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/details.vue
  src/ui/src/views/host-details/children/association-graphics.new.vue
  src/ui/src/views/host-details/children/association-list.vue
  src/ui/src/views/host-details/children/association.vue
Labels: optimization

#3868 fix：excel导入更新主机，http method
  src/apimachinery/apiserver/api.go
Labels: bug

#3865 修复删除实例失败时权限中心注册的实例被解注册的问题
  src/scene_server/host_server/service/host.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/inst_set.go
  src/scene_server/topo_server/service/unique.go
Labels: demand

#3870 模型属性枚举类型添加id和name是否为字符串的校验
  src/common/util/valid.go
  src/source_controller/coreservice/core/instances/validator_util.go
  src/source_controller/coreservice/core/model/attribute_curd.go
Labels: optimization

#3877 fix: metadata bson decode error
  src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go
Labels: bug, inner

#3876 fix: code duplicate
  resources/errors/common/default/synchronize.json
  resources/errors/english/en/synchronize.json
  src/common/errInfo.go
Labels: bug, inner

#3879 fix:ui: 修复枚举类型字段枚举列表缺失type的问题
  src/ui/src/components/model-manage/field-group/field-detail/enum.vue
  src/ui/src/views/model-manage/children/field-detail/enum.vue
Labels: bug

#3851 增加云账户接口的具体业务逻辑 issue #3850
  resources/errors/common/default/cloud_server.json
  resources/errors/english/en/cloud_server.json
  src/apimachinery/cloudserver/api.go
  src/apimachinery/cloudserver/cloudserver.go
  src/apimachinery/coreservice/cloud/api.go
  src/apimachinery/coreservice/cloud/cloud.go
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/cloud.go
  src/common/metadata/result.go
  src/scene_server/cloud_server/app/server.go
  src/scene_server/cloud_server/logics/account_verify.go
  src/scene_server/cloud_server/service/account.go
  src/scene_server/cloud_server/service/health.go
  src/scene_server/cloud_server/service/service.go
  src/scene_server/host_server/service/cloudarea.go
  src/source_controller/coreservice/core/cloud/account.go
  src/source_controller/coreservice/core/cloud/validator.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/service/cloudaccount.go
  src/test/cloud_server/cloud_account_test.go
  src/test/cloud_server/cloud_server_suite_test.go
  src/test/host_server/cloudarea_test.go
  src/test/test.go
Labels: demand

#3866 UI: 主机详情/实例详情采用子路由形式查看
  src/ui/src/assets/scss/_vars.scss
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/components/ui/button/link-button.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/other/router-subview.vue
  src/ui/src/components/ui/other/sticky-layout.vue
  src/ui/src/dictionary/menu.js
  src/ui/src/dictionary/navigation.js
  src/ui/src/directives/transfer-dom.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/resource/index.vue
  src/ui/src/views/resource/router.config.js
Labels: demand, inner, optimization

#3886 优化dal mgo类库使用session的方法
  src/storage/dal/mongo/local/mongo.go
Labels: inner, optimization

#3872 rearrange dal code structure and refactor transaction code.
  src/common/util/lib.go
  src/common/util/transaction.go
  src/scene_server/admin_server/upgrader/v3.0.8/createtable.go
  src/scene_server/admin_server/upgrader/x08.09.17.01/create_table_netcollect.go
  src/scene_server/admin_server/upgrader/x18.10.10.01/procsrv.go
  src/scene_server/admin_server/upgrader/x18.10.30.01/association.go
  src/scene_server/admin_server/upgrader/x18.12.12.05/remove_deleted_inst_asst.go
  src/scene_server/admin_server/upgrader/x19.04.16.02/updateFranceName.go
  src/scene_server/admin_server/upgrader/x19.09.03.05/create_inst_name_index.go
  src/scene_server/admin_server/upgrader/x19.09.03.05/create_object_id_index.go
  src/scene_server/admin_server/upgrader/x19.10.22.02/add_host_index.go
  src/scene_server/admin_server/upgrader/y3.6.201909062359/create_table.go
  src/scene_server/admin_server/upgrader/y3.6.201909272359/task.go
  src/scene_server/admin_server/upgrader/y3.6.201910091234/settemplate_sync_status.go
  src/scene_server/admin_server/upgrader/y3.6.201911261109/create_table.go
  src/scene_server/admin_server/upgrader/y3.7.201911141719/init_host_property_apply.go
  src/scene_server/admin_server/upgrader/y3.8.202001172032/create_audit_log_table.go
  src/scene_server/event_server/distribution/transaction.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/core/datasynchronize/identifier.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/storage/dal/dal.go
  src/storage/dal/filter.go
  src/storage/dal/kv.go
  src/storage/dal/mongo/config.go
  src/storage/dal/mongo/local/mock_mongo.go
  src/storage/dal/mongo/local/mock_mongo_test.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/local/mongo_test.go
  src/storage/dal/mongo/local/transaction.go
  src/storage/dal/mongo/local/txn_manager.go
  src/storage/dal/mongo/local/wrapper_transcation.go
  src/storage/dal/tools.go
  src/storage/dal/transaction_test.go
  src/storage/dal/types/types.go
  src/storage/types/types.go
Labels: optimization

#3874 获取公司部门信息从登录组件分离
  src/common/resource/esb/esb.go
  src/web_server/app/server.go
  src/web_server/logics/department.go
  src/web_server/middleware/user/public.go
  src/web_server/middleware/user/user.go
  src/web_server/service/department.go
  src/web_server/service/service.go
  src/web_server/service/user.go
Labels: inner, optimization

#3848 feature: 增加云账户的API鉴权 issue #3846
  src/apiserver/service/url.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/id.go
  src/auth/authcenter/perm_sys.go
  src/auth/meta/resource.go
  src/auth/parser/chain.go
  src/auth/parser/cloud.go
Labels: demand

#3888 新加提供事件服务框架的能力。
  src/storage/dal/dal.go
  src/storage/stream/event/event.go
  src/storage/stream/event/list_watch.go
  src/storage/stream/event/utils.go
  src/storage/stream/event/watch.go
  src/storage/stream/stream.go
  src/storage/stream/types/types.go
  src/storage/types/message_type.go
  src/storage/types/types_test.go
Labels: demand

#3899 fix search biz topo bug
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
Labels: demand

#3902 修复migrate失败的bug
  src/scene_server/admin_server/upgrader/y3.7.202002231026/add_bk_port_enable_property.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_sync_tables.go
Labels: demand

#3867 UI: 统一实例的变更记录页面
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/model-instance/audit-history.vue
  src/ui/src/components/model-instance/relation/list-table.vue
  src/ui/src/components/ui/form/async-objuser.vue
  src/ui/src/views/business/details.vue
  src/ui/src/views/general-model/details.vue
  src/ui/src/views/host-details/index.vue
Labels: demand

#3904 add reflector package and add function in stream.
  src/storage/reflector/reflector.go
  src/storage/reflector/types.go
  src/storage/stream/event/watch.go
  src/storage/stream/types/types.go
Labels: demand

#3909 UI: 添加导入excel更新主机功能
  src/ui/src/components/import/import.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-topology/host/host-list-options.vue
Labels: demand

#3907 ui: 进程表格信息添加协议字段
  src/ui/src/components/service/instance-table.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-template/children/process.vue
  src/ui/src/views/set-template/children/service-template-info.vue
Labels: optimization

#3906 ui: 审计详情变更信息溢出显示优化
  src/ui/src/components/audit-history/details.vue
Labels: optimization

#3911 fix: add json.Number validate in host query builder.
  src/common/querybuilder/validate.go
Labels: bug

#3914 fix：暂时关闭运营统计实例变更统计
  src/source_controller/coreservice/core/operation/inner_chart.go
Labels: optimization

#3893 feature: audit compare support ignore fields issue #3869
  src/source_controller/coreservice/core/auditlog/audit.go
  src/source_controller/coreservice/core/auditlog/audit_test.go
Labels: inner, optimization

#3917 修复权限同步时json序列化错误和判断带父层级资源位置错误的问题
  src/auth/extensions/types.go
  src/scene_server/admin_server/authsynchronizer/handler/core.go
Labels: bug

#3918 feature: audit compare support ignore fields
  src/source_controller/coreservice/core/auditlog/audit.go
Labels: demand

#3919 datacollection map并发读写问题修复
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
Labels: bug

#3913 fix: excel导入更新主机添加错误提示
  resources/language/default/import_instance.json
  resources/language/en/import_instance.json
  src/scene_server/host_server/service/host.go
  src/web_server/logics/excel.go
Labels: demand

#3926 stream watch code optimize
  src/storage/stream/event/list_watch.go
  src/storage/stream/event/watch.go
Labels: optimization

#3927 stream watch code optimize issue #3887
  src/storage/stream/event/watch.go
Labels: optimization

#3925 UI查询集群模板接口返回全量数据
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/settemplate/set_template.go
Labels: demand

#3930 修复list_service_instance_detail无进程信息的问题
  src/source_controller/coreservice/core/process/service_instance.go
Labels: bug

#3924 resource driver
  src/storage/driver/mongodb/mongodb_test.go
  src/storage/driver/mongodb/monogdb.go
  src/storage/driver/redis/redis.go
  src/storage/driver/redis/redis_test.go
Labels: inner, optimization

#3935 修复find_host_by_module接口中的page参数无效的问题
  src/scene_server/host_server/logics/findhost.go
Labels: bug

#3933 list_biz_hosts接口默认按host id排序
  src/source_controller/coreservice/core/host/searcher/searcher.go
Labels: optimization

#3937 删除服务实例中的内网IP字段
  src/common/metadata/process.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/source_controller/coreservice/core/process/service_instance.go
Labels: optimization

#3943 修改补全枚举类型的解析
  src/common/metadata/attribute.go
Labels: optimization

#3944 optimize:ui: 服务分类默认给用户选中default
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: inner, optimization

#3939 统一运营分析url规范化
  src/apimachinery/coreservice/operation/api.go
  src/apimachinery/coreservice/operation/operation.go
  src/auth/parser/operationstatistics.go
  src/scene_server/operation_server/service/operation.go
  src/scene_server/operation_server/service/service.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/operation/operation.go
  src/source_controller/coreservice/service/operation.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/ui/src/store/modules/api/operation-chart.js
Labels: optimization

#3950 修复权限同步时主线实例被注册为模型实例的问题
  src/auth/extensions/instance.go
  src/common/definitions.go
  src/common/metadata/core_service.go
Labels: bug

#3957 在backbone里对无值的registerip设默认值
  src/common/backbone/backbone.go
Labels: bug

#3962 UI：3.7.x BUG修复
  src/ui/src/components/ui/details/details.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/host-operation/index.vue
Labels: bug, inner

#3963 UI：云资源管理
  src/ui/src/api/_cached-promise.js
  src/ui/src/api/index.js
  src/ui/src/components/ui/dialog/dialog.vue
  src/ui/src/components/ui/selector/cloud.vue
  src/ui/src/dictionary/cloud-resource-type.js
  src/ui/src/dictionary/cloud-vendor.js
  src/ui/src/dictionary/menu-symbol.js
  src/ui/src/dictionary/menu.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/router/index.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/cloud-account.js
  src/ui/src/store/modules/api/cloud.js
  src/ui/src/store/modules/api/cloudarea.js
  src/ui/src/store/modules/api/resource.js
  src/ui/src/views/cloud-account/children/account-details.vue
  src/ui/src/views/cloud-account/children/account-form.vue
  src/ui/src/views/cloud-account/children/account-sideslider.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/cloud-account/router.config.js
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/cloud-area/router.config.js
  src/ui/src/views/cloud-resource/children/task-account-selector.vue
  src/ui/src/views/cloud-resource/children/task-details-history-content.vue
  src/ui/src/views/cloud-resource/children/task-details-history.vue
  src/ui/src/views/cloud-resource/children/task-details-info.vue
  src/ui/src/views/cloud-resource/children/task-details.vue
  src/ui/src/views/cloud-resource/children/task-directory-selector.vue
  src/ui/src/views/cloud-resource/children/task-form-table-header.vue
  src/ui/src/views/cloud-resource/children/task-form-table.vue
  src/ui/src/views/cloud-resource/children/task-form.vue
  src/ui/src/views/cloud-resource/children/task-region-selector.vue
  src/ui/src/views/cloud-resource/children/task-resource-selector.vue
  src/ui/src/views/cloud-resource/children/task-sideslider.vue
  src/ui/src/views/cloud-resource/children/task-vpc-selector.vue
  src/ui/src/views/cloud-resource/index.vue
  src/ui/src/views/cloud-resource/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/resource/children/directory.vue
Labels: demand, inner

#3929 fix: 修复excel导入实例与多主机关联失败bug
  src/scene_server/topo_server/core/operation/import_association.go
Labels: bug

#3954 查询云区域返回值可带主机数量&&云区域审计日志
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/common/errInfo.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/service/cloudarea.go
  src/test/host_server/cloudarea_test.go
Labels: demand

#3968 修复zk二次关闭的问题
  src/common/zkclient/zkclient.go
Labels: bug

#3978 操作审计添加业务内主机在模块set间的转移
  src/common/auditlog/util.go
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
Labels: demand

#3981 主机转移性能优化
  src/scene_server/host_server/service/transfer.go
  src/scene_server/host_server/service/userapi.go
  src/source_controller/coreservice/core/process/service_instance.go
Labels: optimization

#3985 主线模型实例的操作审计与模型实例区别开
  src/auth/extensions/audit.go
  src/common/metadata/audit.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/topo_server/service/auditlog.go
Labels: optimization

#3959 主机转移接口删除删除移出模块的服务实例
  src/scene_server/host_server/service/transfer.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/host/transfer/transfer.go
Labels: demand

#3983 调整云同步代码，修复体验问题
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/common/errInfo.go
  src/common/metadata/cloud.go
  src/scene_server/cloud_server/app/server.go
  src/scene_server/cloud_server/cloudsync/cloudsync.go
  src/scene_server/cloud_server/cloudsync/hostsyncor.go
  src/scene_server/cloud_server/cloudsync/taskprocessor.go
  src/scene_server/cloud_server/cloudsync/taskscheduler.go
  src/scene_server/cloud_server/cloudvendor/aws.go
  src/scene_server/cloud_server/cloudvendor/aws_test.go
  src/scene_server/cloud_server/cloudvendor/tencent_cloud.go
  src/scene_server/cloud_server/cloudvendor/tencent_cloud_test.go
  src/scene_server/cloud_server/logics/auditlog.go
  src/scene_server/cloud_server/pid/cloud.pid
  src/scene_server/host_server/service/cloudarea.go
Labels: optimization

#3948 增加云主机的属性和索引
  resources/language/default/enum.json
  resources/language/default/property.json
  resources/language/en/enum.json
  resources/language/en/property.json
  src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_host_attr.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_sync_tables.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/init_plat_attr.go
Labels: demand

#3998 optimize: 调整查询用户管理的用户列表接口
  src/common/metadata/webserver.go
  src/storage/dal/mongo/local/mongo_test.go
  src/storage/dal/tools.go
  src/storage/dal/types/types.go
  src/web_server/logics/user.go
  src/web_server/middleware/user/plugins/method/blueking/userinfo.go
  src/web_server/middleware/user/plugins/method/skip_login/userinfo.go
  src/web_server/middleware/user/public.go
  src/web_server/middleware/user/user.go
  src/web_server/service/user.go
Labels: optimization

#3999 optimize: refactor config discovery.
  src/apiserver/app/server.go
  src/common/backbone/backbone.go
  src/common/backbone/configcenter/cc.go
  src/common/backbone/configcenter/parse.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/event_server/app/server.go
  src/scene_server/host_server/app/server.go
  src/scene_server/operation_server/service/service.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/task_server/app/server.go
  src/scene_server/topo_server/app/server.go
  src/source_controller/coreservice/app/server.go
  src/web_server/app/server.go
  src/web_server/middleware/user/plugins/method/blueking/userinfo.go
Labels: optimization
