Repository Tencent/bk-cmdb, pull requests merged in 2020-11, with the labels that each got.

#4771 feature:add unique index issue #4769
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.9.202011021415/create_unique_index.go
  src/scene_server/admin_server/upgrader/y3.9.202011021415/pkg.go
  src/storage/dal/mongo/local/mongo.go
Labels: inner, optimization

#4827 UI: 权限解析优化/IP选择器优化/操作审计查询优化
  src/ui/src/components/modal/permission.vue
  src/ui/src/dictionary/iam-auth.js
  src/ui/src/setup/permission.js
  src/ui/src/views/audit/children/audit-business-options.vue
  src/ui/src/views/audit/children/audit-host-options.vue
  src/ui/src/views/audit/children/audit-other-options.vue
  src/ui/src/views/audit/children/audit-resource-options.vue
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/host/across-business-module-selector.vue
  src/ui/src/views/business-topology/host/host-selector-new/host-selector-custom.vue
  src/ui/src/views/resource/children/host-options.vue
Labels: bug, optimization

#4733 feature: init cacheservice code issue #4732
  scripts/init.py
  src/apimachinery/cacheservice/cache/host/api.go
  src/apimachinery/cacheservice/cache/host/cache.go
  src/apimachinery/cacheservice/cache/topology/api.go
  src/apimachinery/cacheservice/cache/topology/cache.go
  src/apimachinery/cacheservice/cacheservice.go
  src/apimachinery/clientset.go
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/discovery_mock.go
  src/common/types/serverInfo.go
  src/scene_server/auth_server/logics/fetch_instance_info.go
  src/scene_server/auth_server/logics/list_instance.go
  src/scene_server/datacollection/collections/hostsnap/hostsnap.go
  src/scene_server/event_server/distribution/distributer.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/event_server/service/watch.go
  src/scene_server/event_server/watcher/lua.go
  src/scene_server/event_server/watcher/watch.go
  src/scene_server/topo_server/service/cache.go
  src/source_controller/cacheservice/Makefile
  src/source_controller/cacheservice/app/options/options.go
  src/source_controller/cacheservice/app/server.go
  src/source_controller/cacheservice/cache/business/business.go
  src/source_controller/cacheservice/cache/business/cache.go
  src/source_controller/cacheservice/cache/business/client.go
  src/source_controller/cacheservice/cache/business/client_logic.go
  src/source_controller/cacheservice/cache/business/custom_level.go
  src/source_controller/cacheservice/cache/business/key.go
  src/source_controller/cacheservice/cache/business/logic.go
  src/source_controller/cacheservice/cache/business/module_set.go
  src/source_controller/cacheservice/cache/business/types.go
  src/source_controller/cacheservice/cache/cache.go
  src/source_controller/cacheservice/cache/host/cache.go
  src/source_controller/cacheservice/cache/host/client.go
  src/source_controller/cacheservice/cache/host/client_logic.go
  src/source_controller/cacheservice/cache/host/host.go
  src/source_controller/cacheservice/cache/host/key.go
  src/source_controller/cacheservice/cache/host/lua.go
  src/source_controller/cacheservice/cache/tools/lock.go
  src/source_controller/cacheservice/cache/topo_tree/doc.go
  src/source_controller/cacheservice/cache/topo_tree/path.go
  src/source_controller/cacheservice/cache/topo_tree/topo_tree.go
  src/source_controller/cacheservice/cache/topo_tree/type.go
  src/source_controller/cacheservice/event/event.go
  src/source_controller/cacheservice/event/flow.go
  src/source_controller/cacheservice/event/gc.go
  src/source_controller/cacheservice/event/key.go
  src/source_controller/cacheservice/event/lua.go
  src/source_controller/cacheservice/event/types.go
  src/source_controller/cacheservice/main.go
  src/source_controller/cacheservice/readme.md
  src/source_controller/cacheservice/service/cache.go
  src/source_controller/cacheservice/service/health.go
  src/source_controller/cacheservice/service/service.go
  src/source_controller/cacheservice/service/service_initfunc.go
  src/source_controller/coreservice/core/host/host.go
  src/source_controller/coreservice/core/host/searcher/searcher.go
  src/source_controller/coreservice/service/service.go
Labels: demand, in progress

#4836 fix: 修复转移主机到直接新建的模块下时，会新增两个重复服务实例的问题
  src/source_controller/coreservice/core/process/service_instance.go
  src/storage/stream/event/watch.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_test.go
Labels: bug

#4838 optimize:ui: 优化主机池文案
  src/ui/src/components/layout/header.vue
  src/ui/src/dictionary/iam-auth.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/host-relation.js
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business-topology/host/move-to-resource-confirm.vue
  src/ui/src/views/eventpush/push-detail.vue
  src/ui/src/views/resource/children/directory.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/resource/transfer/transfer-menu.vue
Labels: optimization

#4831 feature: 增加更新服务实例的接口 issue #4830
  src/ac/parser/serviceinstance.go
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/apimachinery/procserver/service/api.go
  src/apimachinery/procserver/service/instance.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/service_instance.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/test/proc_server/no_service_template_test.go
Labels: demand

#4867 fix: import host not custom fields issue #4866
  src/web_server/logics/host.go
  src/web_server/service/host.go
Labels: bug, inner

#4856 feature: 增加查询业务topo树简要信息的接口 issue #4855
  src/ac/parser/topology.go
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/common.go
  src/common/metadata/toposerver.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/test/topo_server/business_test.go
Labels: demand

#4875 fix: cc_PropertyGroup unique index error issue #4769
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.9.202011021415/create_unique_index.go
  src/scene_server/admin_server/upgrader/y3.9.202011192014/change_unique_index.go
  src/scene_server/admin_server/upgrader/y3.9.202011192014/pkg.go
Labels: bug, inner

#4754 feature: 新增点分五位查询进程实例的相关信息接口
  resources/errors/common/default/object_controller.json
  resources/errors/english/en/object_controller.json
  src/ac/parser/processinstance.go
  src/apimachinery/procserver/process/api.go
  src/apimachinery/procserver/process/instance.go
  src/common/errInfo.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/common/metadata/procserver.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/test/proc_server/no_service_template_test.go
Labels: demand

#4886 feature:add unique index issue #4769
  src/scene_server/admin_server/upgrader/y3.9.202011021415/create_unique_index.go
Labels: demand, inner

#4893 V3.9.x topo context
  src/scene_server/topo_server/core/inst/association.go
  src/scene_server/topo_server/core/model/attribute.go
  src/scene_server/topo_server/core/model/classification.go
  src/scene_server/topo_server/core/model/group.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/model/unique.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/graphics.go
  src/scene_server/topo_server/core/operation/group.go
  src/scene_server/topo_server/core/operation/identifier.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/operation/inst_set.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/unique.go
  src/scene_server/topo_server/service/object_association.go
Labels: inner

#4889 feature: 增加批量查询服务模版计数信息的接口 issue #4888
  src/ac/parser/servicetemplate.go
  src/apimachinery/procserver/service/api.go
  src/apimachinery/procserver/service/template.go
  src/common/metadata/core_service.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/servicetemplate.go
  src/source_controller/coreservice/service/count.go
  src/test/proc_server/service_template_test.go
Labels: demand

#4913 refactor: optimization /topo/internal/{owner}/{bk_biz_id}/with_statis…
  src/apimachinery/coreservice/instance/api.go
  src/apimachinery/coreservice/instance/instance.go
  src/common/metadata/instance_struct.go
  src/scene_server/topo_server/core/operation/inst_business.go
Labels: inner, optimization
