Repository Tencent/bk-cmdb, pull requests merged in 2020-08, with the labels that each got.

#4503 UI: 集群模板名称校验规则调整
  src/ui/src/views/set-template/children/template-config.vue
Labels: optimization

#4498 UI: 鉴权BUG修复
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/dictionary/iam-auth.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/mixins/edit-multiple-host.js
  src/ui/src/mixins/permission.js
  src/ui/src/router/meta.js
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business-topology/service-instance/instance/options.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/status/non-exist-business.vue
  src/ui/src/views/status/permission.vue
Labels: bug, inner

#4514 UI: 主机查询跳转错误修复
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/views/host-details/landing.vue
Labels: bug, inner

#4516 UI: 鉴权BUG修复
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/service/form/form.vue
  src/ui/src/components/ui/auth/auth.vue
Labels: bug, inner

#4515 增加用户类型模型属性的正则校验
  src/common/metadata/attribute.go
  src/common/util/struti.go
Labels: optimization

#4529 修复获取redis和mongo的配置产生异常
  src/common/backbone/configcenter/viper.go
Labels: bug

#4538 fix:ui: 修复动态分组对应权限中心视图配置错误的问题
  src/ui/src/dictionary/iam-auth.js
Labels: bug, inner

#4551 UI: 前端前置鉴权优化
  src/ui/src/api/index.js
  src/ui/src/components/model-instance/relation/create.vue
  src/ui/src/components/model-instance/relation/list.vue
  src/ui/src/components/ui/auth/auth-option.vue
  src/ui/src/components/ui/index.js
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/cloud-resource/children/task-region-selector.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-create.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
Labels: inner, optimization

#4542 feature:ui: 不可操作的模型通过model.bk_ishidden判断
  src/ui/src/store/modules/api/global-models.js
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.new.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/resource-manage/index.vue
Labels: demand, inner

#4559 fix:ui: 修复主机详情查询属性参数错误的问题
  src/ui/src/views/host-details/index.vue
Labels: bug, inner

#4576 UI: 前端鉴权问题修复
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/mixins/permission.js
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/operation-chart.js
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/cloud-account/children/account-details.vue
  src/ui/src/views/cloud-account/children/account-form.vue
  src/ui/src/views/cloud-account/children/account-sideslider.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/cloud-resource/children/task-directory-selector.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/model-association/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: bug, inner

#4582 feature: port not support mutli-port issue #4468
  src/scene_server/admin_server/upgrader/y3.8.202007211455/proc_bind_change.go
Labels: demand, inner

#4591 UI: 主机池支持显示业务拓扑、首页搜索优化、资源池交互优化、其他功能优化
  src/ui/package.json
  src/ui/src/components/host-topo-path/host-topo-path.vue
  src/ui/src/components/host-topo-path/proxy.js
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/components/ui/selector/clipboard.vue
  src/ui/src/components/ui/selector/selector.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/store/modules/api/object-model-property.js
  src/ui/src/utils/tools.js
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/host/module-selector.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business-topology/service-instance/common/view-switcher.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/index/children/classify.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/index/children/search-item.vue
  src/ui/src/views/index/children/search.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/model-topology/children/create-relation.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/resource/transfer/host-store.js
  src/ui/src/views/resource/transfer/transfer-menu.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: bug, demand, inner
