Repository Tencent/bk-cmdb, pull requests merged in 2020-06, with the labels that each got.

#4269 增加审计日志page limit的校验
  src/common/definitions.go
  src/common/metadata/common.go
  src/scene_server/topo_server/service/auditlog.go
Labels: optimization

#4270 增加审计日志分页limit参数的校验
  src/common/definitions.go
  src/common/errors/errorIf.go
  src/common/metadata/common.go
  src/scene_server/topo_server/service/auditlog.go
Labels: optimization

#4282 避免一次性获取过多的数据
  src/scene_server/host_server/logics/hostsearch.go
Labels: inner, optimization

#4284 避免一次性获取过多的数据
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/hostsearch.go
Labels: inner, optimization

#4287 控制主机关系返回的字段
  src/common/metadata/core_service.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/hostsearch.go
  src/source_controller/coreservice/core/host/transfer/manager.go
Labels: inner, optimization

#4283 补全进程实例与模版同步中差异对比所缺失的网管代理字段，修正获取进程实例关系的数量返回值
  src/common/definitions.go
  src/scene_server/proc_server/logics/processinstance.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
Labels: bug

#4266 主机IP、维护人从字符串调整为数组
  src/common/definitions.go
  src/common/metadata/host.go
  src/common/metadata/inst.go
  src/common/paraparse/host.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x08.09.18.01/upgrader.go
  src/scene_server/admin_server/upgrader/y3.8.202005251144/change_host_ip_user_to_array.go
  src/scene_server/admin_server/upgrader/y3.8.202005251144/pkg.go
  src/scene_server/event_server/identifier/identifier.go
  src/scene_server/host_server/logics/import.go
  src/source_controller/coreservice/cache/host/host.go
  src/source_controller/coreservice/core/datasynchronize/instance.go
  src/source_controller/coreservice/core/host/cloudarea.go
  src/source_controller/coreservice/core/host/lock.go
  src/source_controller/coreservice/core/host/searcher/searcher.go
  src/source_controller/coreservice/core/host/transfer/transfer.go
  src/source_controller/coreservice/core/hostapplyrule/plan.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
  src/source_controller/coreservice/core/instances/validator_unique.go
  src/source_controller/coreservice/core/process/base.go
  src/source_controller/coreservice/core/process/service_instance.go
  src/source_controller/coreservice/service/host.go
  src/storage/dal/mongo/local/mongo.go
Labels: demand

#4289 修复创建没有附带进程的服务模板失败问题
  src/scene_server/proc_server/service/processtemplate.go
  src/source_controller/coreservice/service/transaction.go
Labels: bug

#4288 UI：性能优化
  src/ui/package.json
  src/ui/src/assets/json/operation_audit_all.json
  src/ui/src/assets/scss/admin-view.scss
  src/ui/src/assets/scss/model-manage.scss
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/model-manage/_create-model.vue
  src/ui/src/components/model-manage/field-group/field-detail/config.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/ui/dialog/leave-confirm.vue
  src/ui/src/i18n/index.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/index.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/main.js
  src/ui/src/mixins/form.js
  src/ui/src/store/modules/api/net-collect-device.js
  src/ui/src/store/modules/api/net-collect-property.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/host/host-selector-topology.vue
  src/ui/src/views/business-topology/host/module-selector.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/property-confirm.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/model-topology/index.new.vue
  src/ui/src/views/operation/index.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
  src/ui/src/views/set-template/children/template-tree.vue
Labels: inner, optimization

#4296 UI: 模型管理搜索优化/拓扑节点编辑UI溢出BUG修复
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/model-manage/index.vue
Labels: bug, inner, optimization

#4301 V3.8.x动态分组缺陷问题修复
  src/ui/src/components/hosts/filter/_filter-field-operator.vue
  src/ui/src/views/custom-query/define.vue
Labels: bug, inner

#4291 V3.8.x hostserver optimize
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/common/metadata/core_service.go
  src/common/metadata/hostcontroller.go
  src/scene_server/host_server/logics/hostsearch.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/transfer.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/service/host.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/local/mongo_test.go
  src/storage/dal/types/types.go
Labels: inner, optimization

#4309 V3.8.x缺陷与体验问题修复
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/edit.vue
  src/ui/src/views/host-apply/index.vue
Labels: bug, inner

#4321 UI: 拓扑服务实例视图展示调整
  src/ui/package.json
  src/ui/src/assets/scss/_vars.scss
  src/ui/src/components/ui/auth/auth.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/dot-menu/dot-menu.vue
  src/ui/src/components/ui/form/longchar.vue
  src/ui/src/components/ui/form/singlechar.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/router/index.js
  src/ui/src/store/modules/api/process-template.js
  src/ui/src/store/modules/api/service-instance.js
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business-topology/service-instance/common/bus.js
  src/ui/src/views/business-topology/service-instance/common/form-multiple.js
  src/ui/src/views/business-topology/service-instance/common/form-multiple.vue
  src/ui/src/views/business-topology/service-instance/common/form.js
  src/ui/src/views/business-topology/service-instance/common/form.vue
  src/ui/src/views/business-topology/service-instance/common/process-form-tips-render.js
  src/ui/src/views/business-topology/service-instance/common/process-form-tips.vue
  src/ui/src/views/business-topology/service-instance/common/symbol.js
  src/ui/src/views/business-topology/service-instance/common/view-switcher.vue
  src/ui/src/views/business-topology/service-instance/instance/create-process-mixin.js
  src/ui/src/views/business-topology/service-instance/instance/dialog/label-batch-dialog-content.vue
  src/ui/src/views/business-topology/service-instance/instance/dialog/label-batch-dialog.js
  src/ui/src/views/business-topology/service-instance/instance/dialog/label-batch-dialog.vue
  src/ui/src/views/business-topology/service-instance/instance/dialog/label-dialog-content.vue
  src/ui/src/views/business-topology/service-instance/instance/dialog/label-dialog.js
  src/ui/src/views/business-topology/service-instance/instance/dialog/label-dialog.vue
  src/ui/src/views/business-topology/service-instance/instance/expand-list.vue
  src/ui/src/views/business-topology/service-instance/instance/list-cell-count.vue
  src/ui/src/views/business-topology/service-instance/instance/list-cell-name.vue
  src/ui/src/views/business-topology/service-instance/instance/list-cell-operation.vue
  src/ui/src/views/business-topology/service-instance/instance/list-cell-tag.vue
  src/ui/src/views/business-topology/service-instance/instance/list-sticky-row.vue
  src/ui/src/views/business-topology/service-instance/instance/list.vue
  src/ui/src/views/business-topology/service-instance/instance/options.vue
  src/ui/src/views/business-topology/service-instance/instance/view.vue
  src/ui/src/views/business-topology/service-instance/process/expand-list.vue
  src/ui/src/views/business-topology/service-instance/process/list.vue
  src/ui/src/views/business-topology/service-instance/process/options.vue
  src/ui/src/views/business-topology/service-instance/process/view.vue
  src/ui/src/views/business-topology/service-instance/view.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: demand, inner

#4328 模型实例侧滑详情标题溢出显示优化
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
Labels: inner, optimization

#4325 全文检索适配主机IP等数据调整为数组及高亮搜索词显示优化
  src/ui/src/filters/formatter.js
  src/ui/src/views/index/children/full-text-search.vue
  src/ui/src/views/index/children/search-input.vue
Labels: inner, optimization

#4332 增加查询服务模板下的主机和查询集群模板下的主机接口
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/auth/parser/host.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/service/findhost.go
  src/scene_server/host_server/service/service.go
Labels: demand

#4281 增加批量编辑进程的接口
  src/apimachinery/procserver/process/api.go
  src/apimachinery/procserver/process/instance.go
  src/auth/parser/processinstance.go
  src/common/metadata/process.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/util.go
  src/scene_server/admin_server/upgrader/y3.8.202006021120/add_service_instance_index.go
  src/scene_server/admin_server/upgrader/y3.8.202006021120/pkg.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/test/proc_server/no_service_template_test.go
Labels: demand

#4320 增加批量查询主机快照的接口，快照数据里增加ip、mac地址
  resources/errors/common/default/host_controller.json
  resources/errors/english/en/host_controller.json
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/module.go
  src/apimachinery/toposerver/inst/set.go
  src/auth/parser/host.go
  src/common/errInfo.go
  src/common/metadata/common.go
  src/common/metadata/hostcontroller.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/agent.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/service.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/inst_set.go
  src/source_controller/coreservice/service/host.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/test/topo_server/object_test.go
Labels: demand

#4366 UI: 切换人员选择器
  src/ui/build/utils.js
  src/ui/config/index.js
  src/ui/index.html
  src/ui/package.json
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/model-instance/property.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/form/async-objuser.vue
  src/ui/src/components/ui/form/objuser.vue
  src/ui/src/components/ui/form/user.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/other/property-value.vue
  src/ui/src/components/ui/other/user-value.vue
  src/ui/src/components/ui/user/user-queue.js
  src/ui/src/components/ui/user/user.vue
  src/ui/src/directives/index.js
  src/ui/src/directives/overflow-tips.js
  src/ui/src/directives/user.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/business-topology/service-instance/instance/list-cell-operation.vue
  src/ui/src/views/host-details/children/property.vue
Labels: inner, optimization

#4360 UI: 其他板块操作审计和缺陷问题修复
  src/ui/src/assets/json/operation_audit.json
  src/ui/src/components/ui/dialog/dialog.vue
  src/ui/src/setup/validate.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/service-instance/instance/dialog/label-dialog-content.vue
Labels: demand, inner, optimization

#4312 UI: 新增系统配置管理功能
  src/ui/config/index.js
  src/ui/index.html
  src/ui/src/App.vue
  src/ui/src/api/index.js
  src/ui/src/components/hosts/status/status.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/components/ui/auth/auth.vue
  src/ui/src/dictionary/auth.js
  src/ui/src/dictionary/menu-symbol.js
  src/ui/src/i18n/index.js
  src/ui/src/main.js
  src/ui/src/router/index.js
  src/ui/src/setup/afterload.js
  src/ui/src/setup/preload.js
  src/ui/src/setup/validate.js
  src/ui/src/store/modules/api/auth.js
  src/ui/src/store/modules/global.js
  src/ui/src/views/admin/config.vue
  src/ui/src/views/admin/router.config.js
  src/ui/src/views/host-details/children/status.vue
  src/ui/src/views/index.js
  src/ui/src/views/index/children/footer.config.js
  src/ui/src/views/index/children/footer.vue
  src/ui/src/views/index/router.config.js
  src/ui/src/views/resource/index.vue
Labels: demand, inner

#4162 hostserver的所有写接口支持事务
  src/scene_server/host_server/app/options/options.go
  src/scene_server/host_server/app/server.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/favourite.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/hostapplyrule.go
  src/scene_server/host_server/service/hostlock.go
  src/scene_server/host_server/service/module.go
  src/scene_server/host_server/service/service.go
  src/scene_server/host_server/service/special.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/host_server/service/userapi.go
  src/scene_server/host_server/service/usercustom.go
  src/test/host_server/host_abnormal_test.go
Labels: demand

#4379 feature: streamline asynchronous task header issue #4377
  src/common/metadata/set_template_request.go
  src/scene_server/task_server/logics/task.go
  src/scene_server/task_server/service/queue.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/service/internal_task.go
Labels: inner, optimization

#3921 下线auth parser里在topolatest有替换接口的接口
  src/auth/parser/host.go
  src/auth/parser/topolatest.go
  src/auth/parser/topology.go
Labels: optimization

#4382 UI: 缺陷与体验问题修复
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/router/index.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/eventpush/pop.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/service-instance/children/clone-to-other.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-instance/clone.vue
  src/ui/src/views/service-instance/create.vue
Labels: bug, optimization

#4393 UI：云资源管理
  src/ui/package.json
  src/ui/src/api/_cached-promise.js
  src/ui/src/api/index.js
  src/ui/src/api/middleware/admin-entrance.js
  src/ui/src/api/middleware/auth.js
  src/ui/src/api/middleware/business.js
  src/ui/src/api/middleware/index.js
  src/ui/src/api/middleware/util.js
  src/ui/src/assets/json/class-icon.json
  src/ui/src/assets/json/static-navigation.json
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/model-instance/property.vue
  src/ui/src/components/ui/other/tips.vue
  src/ui/src/components/ui/other/vendor.vue
  src/ui/src/components/ui/vendor/index.vue
  src/ui/src/components/ui/vendor/vendor-icon.js
  src/ui/src/dictionary/cloud-vendor.js
  src/ui/src/dictionary/menu.js
  src/ui/src/dictionary/request-symbol.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/main.js
  src/ui/src/router/index.js
  src/ui/src/store/modules/api/cloud-account.js
  src/ui/src/store/modules/api/cloud.js
  src/ui/src/store/modules/api/resource.js
  src/ui/src/store/modules/view/resource-host.js
  src/ui/src/utils/tools.js
  src/ui/src/views/cloud-account/children/account-details.vue
  src/ui/src/views/cloud-account/children/account-form.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/cloud-resource/children/task-account-selector.vue
  src/ui/src/views/cloud-resource/children/task-cloud-area-input.vue
  src/ui/src/views/cloud-resource/children/task-details-history.vue
  src/ui/src/views/cloud-resource/children/task-directory-selector.vue
  src/ui/src/views/cloud-resource/children/task-form-table-header.vue
  src/ui/src/views/cloud-resource/children/task-form-table.vue
  src/ui/src/views/cloud-resource/children/task-form.vue
  src/ui/src/views/cloud-resource/children/task-region-selector.vue
  src/ui/src/views/cloud-resource/children/task-sideslider.vue
  src/ui/src/views/cloud-resource/children/task-vpc-selector.vue
  src/ui/src/views/cloud-resource/common/symbol.js
  src/ui/src/views/cloud-resource/index.vue
  src/ui/src/views/general-model/router.config.js
  src/ui/src/views/resource/children/directory.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/resource/router.config.js
Labels: demand

#4381 UI: 服务实例批量编辑BUG修复及交互优化
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/service/form/form-multiple.js
  src/ui/src/components/service/form/form-multiple.vue
  src/ui/src/components/service/form/form.js
  src/ui/src/components/service/form/form.vue
  src/ui/src/components/service/form/process-form-tips-render.js
  src/ui/src/components/service/form/process-form-tips.vue
  src/ui/src/components/service/form/symbol.js
  src/ui/src/components/service/instance-table.vue
  src/ui/src/components/ui/other/sticky-layout.vue
  src/ui/src/dictionary/regexp.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/service-instance/instance/create-process-mixin.js
  src/ui/src/views/business-topology/service-instance/instance/expand-list.vue
  src/ui/src/views/business-topology/service-instance/instance/list-cell-name.vue
  src/ui/src/views/business-topology/service-instance/instance/list.vue
  src/ui/src/views/business-topology/service-instance/instance/options.vue
  src/ui/src/views/business-topology/service-instance/process/expand-list.vue
  src/ui/src/views/business-topology/service-instance/process/options.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/children/process.vue
  src/ui/src/views/service-template/children/template-instance.vue
  src/ui/src/views/service-template/template.vue
Labels: bug, inner, optimization
