Repository Tencent/bk-cmdb, pull requests merged in 2020-07, with the labels that each got.

#4396 集群同步相关问题修改
  src/apimachinery/coreservice/settemplate/api.go
  src/apimachinery/coreservice/settemplate/settemplate.go
  src/common/http/rest/contexts.go
  src/common/lock/lock_key.go
  src/common/util/lib.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/settemplate/sync_status.go
  src/source_controller/coreservice/service/service_set_template_initfunc.go
  src/source_controller/coreservice/service/set_template.go
Labels: bug, inner

#4399 feature:set biz and set association is pre issue #4398
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.8.202007011748/change_bk_mainlin_set_biz_asst.go
  src/scene_server/admin_server/upgrader/y3.8.202007011748/pkg.go
Labels: inner, optimization

#4389 查询资源池目录接口支持排序和指定返回字段
  src/common/metadata/toposerver.go
  src/scene_server/topo_server/service/resource_directory.go
Labels: demand

#4411 UI： 优化人员选择器使用场景
  src/ui/index.html
  src/ui/src/components/ui/form/user.vue
Labels: inner, optimization

#4418 UI: 修复类型错误的实例字段值对应的表单组件无法渲染的问题
  src/ui/index.html
  src/ui/src/components/ui/form/async-objuser.vue
  src/ui/src/components/ui/form/bool.vue
  src/ui/src/components/ui/form/date.vue
  src/ui/src/components/ui/form/list.vue
  src/ui/src/components/ui/form/time.vue
  src/ui/src/components/ui/form/timezone.vue
  src/ui/src/components/ui/form/user.vue
Labels: inner, optimization

#4425 fix:ui: 修复服务模板进程无法操作的问题
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process.vue
Labels: bug, inner

#4428 V3.5.x host cloudarea type
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/service/host.go
  src/test/host_server/host_abnormal_test.go
Labels: inner, optimization

#4437 UI：业务拓扑下的功能bug修复
  src/ui/src/components/service/instance-table.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: bug, inner

#4433 UI: 云资源相关功能添加关联检测
  src/ui/package.json
  src/ui/src/components/ui/button/link-button.vue
  src/ui/src/components/ui/other/tips.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/store/modules/api/cloud.js
  src/ui/src/views/cloud-account/children/account-details.vue
  src/ui/src/views/cloud-account/children/account-form.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/cloud-resource/children/task-cloud-area-input.vue
  src/ui/src/views/cloud-resource/children/task-details-info.vue
  src/ui/src/views/cloud-resource/children/task-details.vue
  src/ui/src/views/cloud-resource/children/task-form-table.vue
  src/ui/src/views/cloud-resource/children/task-form.vue
  src/ui/src/views/cloud-resource/children/task-region-selector.vue
  src/ui/src/views/cloud-resource/children/task-sideslider.vue
  src/ui/src/views/cloud-resource/children/task-vpc-selector.vue
  src/ui/src/views/cloud-resource/index.vue
Labels: demand, inner, optimization

#4446 修改主机实例属性api 无法修改运区域
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/service/host.go
  src/test/host_server/host_abnormal_test.go
Labels: bug, inner

#4450 云资源管理写DB操作接入分布式事务
  src/scene_server/cloud_server/app/options/options.go
  src/scene_server/cloud_server/app/server.go
  src/scene_server/cloud_server/service/account.go
  src/scene_server/cloud_server/service/service.go
  src/scene_server/cloud_server/service/synctask.go
  src/test/cloud_server/cloud_sync_task_test.go
Labels: demand

#4020 云资源被销毁后的同步
  resources/errors/common/default/cloud_server.json
  resources/errors/common/default/host_server.json
  resources/errors/english/en/cloud_server.json
  resources/errors/english/en/host_server.json
  resources/language/default/enum.json
  resources/language/en/enum.json
  src/ac/parser/cloud.go
  src/apimachinery/coreservice/cloud/api.go
  src/apimachinery/coreservice/cloud/cloud.go
  src/auth/parser/cloud.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/eventoperator/eventoperator.go
  src/common/metadata/audit.go
  src/common/metadata/cloud.go
  src/common/metadata/hostserver.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_host_attr.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_host_unique.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/init_plat_attr.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/pkg.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/update_plat_unique_key.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/upgrade_cloud_area.go
  src/scene_server/cloud_server/app/server.go
  src/scene_server/cloud_server/cloudsync/cloudsync.go
  src/scene_server/cloud_server/cloudsync/hostsyncor.go
  src/scene_server/cloud_server/cloudvendor/aws.go
  src/scene_server/cloud_server/cloudvendor/aws_test.go
  src/scene_server/cloud_server/cloudvendor/tencent_cloud.go
  src/scene_server/cloud_server/cloudvendor/tencent_cloud_test.go
  src/scene_server/cloud_server/cloudvendor/vendorclient.go
  src/scene_server/cloud_server/common/types.go
  src/scene_server/cloud_server/common/util.go
  src/scene_server/cloud_server/logics/auditlog.go
  src/scene_server/cloud_server/logics/cloud.go
  src/scene_server/cloud_server/logics/synctask.go
  src/scene_server/cloud_server/service/account.go
  src/scene_server/cloud_server/service/service.go
  src/scene_server/host_server/service/cloudarea.go
  src/source_controller/coreservice/core/cloud/account.go
  src/source_controller/coreservice/core/cloud/cloud.go
  src/source_controller/coreservice/core/cloud/synctask.go
  src/source_controller/coreservice/core/cloud/validator.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/service/cloudsynctask.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/test/cloud_server/cloud_account_test.go
  src/test/cloud_server/cloud_server_suite_test.go
  src/test/cloud_server/cloud_sync_task_test.go
  src/test/host_server/cloudarea_test.go
Labels: demand

#4486 UI: 鉴权参数读取与配置调整
  src/ui/package.json
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/import/import.vue
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/ui/auth/auth-queue.js
  src/ui/src/components/ui/auth/auth.vue
  src/ui/src/dictionary/iam-auth.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/setup/permission.js
  src/ui/src/store/modules/api/cloud.js
  src/ui/src/store/modules/api/operation-chart.js
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/cloud-account/children/account-form.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/cloud-resource/children/task-account-selector.vue
  src/ui/src/views/cloud-resource/children/task-details-history.vue
  src/ui/src/views/cloud-resource/children/task-directory-selector.vue
  src/ui/src/views/cloud-resource/children/task-region-selector.vue
  src/ui/src/views/cloud-resource/index.vue
  src/ui/src/views/eventpush/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/resource/children/directory.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/status/permission.vue
Labels: bug, inner, optimization

#4487 update:ui: 调整主机操作相关的权限设置
  src/ui/src/dictionary/iam-auth.js
  src/ui/src/setup/permission.js
  src/ui/src/views/host-operation/index.vue
Labels: optimization

#4488 demand: add list business, set, module, host with id list cache api
  src/apimachinery/coreservice/cache/api.go
  src/apimachinery/coreservice/cache/cache.go
  src/apimachinery/rest/request.go
  src/apiserver/service/limiter.go
  src/common/http/rest/contexts.go
  src/common/metadata/cache.go
  src/common/metadata/result.go
  src/scene_server/event_server/service/lua.go
  src/source_controller/coreservice/cache/business/client.go
  src/source_controller/coreservice/cache/business/client_logic.go
  src/source_controller/coreservice/cache/host/client.go
  src/source_controller/coreservice/cache/host/client_logic.go
  src/source_controller/coreservice/cache/host/host.go
  src/source_controller/coreservice/cache/host/key.go
  src/source_controller/coreservice/cache/host/lua.go
  src/source_controller/coreservice/service/cache.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand

#4495 fix: fix stream watch problem which will cause a high cpu of process
  src/storage/stream/event/watch.go
Labels: bug

#4496 optimize:ui: UI交互细节优化
  src/ui/src/App.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/router/index.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/host-details/landing.vue
  src/ui/src/views/host-details/router.config.js
  src/ui/src/views/index.js
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/set-template/children/template-config.vue
Labels: inner, optimization
