Repository Tencent/bk-cmdb, pull requests merged in 2020-10, with the labels that each got.

#4722 V3.9.x bugfix
  src/common/definitions.go
  src/common/http/rest/contexts.go
  src/common/util/lib.go
  src/scene_server/cloud_server/app/server.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/source_controller/coreservice/cache/topo_tree/path.go
  src/source_controller/coreservice/service/service.go
  src/test/txn/txn_test.go
Labels: bug, inner

#4735 UI: 小优化
  src/ui/package.json
  src/ui/src/utils/tools.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/status/404.vue
Labels: optimization

#4740 ui: 限制操作审计最大查询数量为200
  src/ui/src/utils/tools.js
  src/ui/src/views/audit/index.vue
Labels: optimization

#4742 增加获取各云区域下主机数量的接口
  src/ac/parser/topology.go
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/common/metadata/hostserver.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.9.202010151650/add_cloudid_index.go
  src/scene_server/admin_server/upgrader/y3.9.202010151650/pkg.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/service_initfunc.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/cloudarea.go
  src/source_controller/coreservice/service/cloudarea.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/storage/dal/mongo/local/mongo.go
  src/test/host_server/host_test.go
Labels: demand

#4744 fix: 修改原先的依照模型实例删除关联关系的接口，改为按照id批量删除关联关系
  src/apimachinery/coreservice/association/api.go
  src/apimachinery/coreservice/association/association.go
  src/auth/parser/topology.go
  src/common/metadata/association.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/coreservice/service/association.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: outer

#4762 UI: bug修复与动态分组优化
  src/ui/src/components/host-topo-path/host-topo-path.vue
  src/ui/src/components/search/enum.vue
  src/ui/src/components/search/list.vue
  src/ui/src/components/search/longchar.vue
  src/ui/src/components/search/singlechar.vue
  src/ui/src/components/search/timezone.vue
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/store/modules/api/object-model-property.js
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/cloud-resource/children/task-account-selector.vue
  src/ui/src/views/dynamic-group/form/form-property-selector.vue
  src/ui/src/views/dynamic-group/form/form.vue
  src/ui/src/views/dynamic-group/index.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/index.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
Labels: bug, inner

#4767 优化从URL中匹配bizID的方式,使其匹配更精准
  src/ac/parser/framework.go
  src/ac/parser/host.go
  src/ac/parser/hostapply.go
  src/ac/parser/settemplate.go
Labels: optimization

#4776 UI: 动态分组支持服务模板查询、云区域主机数量异步获取
  src/ui/src/components/loading/loading.vue
  src/ui/src/components/search/index.js
  src/ui/src/components/search/service-template.vue
  src/ui/src/store/modules/api/cloud.js
  src/ui/src/store/modules/api/service-template.js
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/dynamic-group/form/form-operator-selector.vue
  src/ui/src/views/dynamic-group/form/form-property-list.vue
  src/ui/src/views/dynamic-group/form/form.vue
Labels: demand, inner

#4763 主机更新创建时对bk_cloud_id做校验，必须为数值型
  src/scene_server/host_server/service/host.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/instances/instance_validate.go
Labels: optimization

#4758 feature: execute migrate specify version issue #4757
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/service/service.go
  src/scene_server/admin_server/upgrader/register.go
Labels: demand, inner

#4780 fix: make error issue #4688
  src/scene_server/admin_server/upgrader/register.go
Labels: bug, inner

#4774 feature: 新增查询某业务下进程ID对应进程详情的接口
  src/ac/parser/processinstance.go
  src/apimachinery/procserver/process/api.go
  src/apimachinery/procserver/process/instance.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/test/proc_server/no_service_template_test.go
Labels: demand

#4790 fix: redis driver default client bug issue #4789
  src/storage/driver/redis/redis.go
Labels: bug, inner, optimization

#4804 fix: 修复flow watch内存泄漏的问题
  src/common/backbone/configcenter/cc.go
  src/common/backbone/configcenter/viper.go
  src/source_controller/coreservice/app/server.go
  src/source_controller/coreservice/event/flow.go
  src/storage/stream/event/utils.go
  src/storage/stream/event/watch.go
Labels: bug
