Repository Tencent/bk-cmdb, pull requests merged in 2020-02, with the labels that each got.

#3790 UI: 云资源管理相关页面静态页面
  src/common/metadata/audit.go
  src/common/metadata/log.go
  src/ui/src/assets/scss/_vars.scss
  src/ui/src/components/ui/button/link-button.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/other/sticky-layout.vue
  src/ui/src/dictionary/menu-symbol.js
  src/ui/src/dictionary/menu.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/cloud-account/children/account-details.vue
  src/ui/src/views/cloud-account/children/account-form.vue
  src/ui/src/views/cloud-account/children/account-sideslider.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/cloud-account/router.config.js
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/cloud-area/router.config.js
  src/ui/src/views/cloud-resource/children/resource-details-history-content.vue
  src/ui/src/views/cloud-resource/children/resource-details-history.vue
  src/ui/src/views/cloud-resource/children/resource-details-info.vue
  src/ui/src/views/cloud-resource/children/resource-details-sideslider.vue
  src/ui/src/views/cloud-resource/children/resource-folder-selector.vue
  src/ui/src/views/cloud-resource/children/resource-form-all.vue
  src/ui/src/views/cloud-resource/children/resource-form-custom-header.vue
  src/ui/src/views/cloud-resource/children/resource-form-custom.vue
  src/ui/src/views/cloud-resource/children/resource-form.vue
  src/ui/src/views/cloud-resource/children/resource-sideslider.vue
  src/ui/src/views/cloud-resource/index.vue
  src/ui/src/views/cloud-resource/router.config.js
  src/ui/src/views/index.js
Labels: demand, inner

#3797 更新cmdb的英文logo
  docs/resource/img/bk-cmdb-en.png
  readme_en.md
  src/scene_server/validator/valid_basic.go
  src/source_controller/coreservice/core/association/mock_test.go
Labels: optimization

#3799 fix event server migrate instance id bug
  src/scene_server/event_server/distribution/start.go
  src/storage/dal/mongo/local/mongo.go
Labels: bug

#3800 code optimize with benchmark
  src/apiserver/service/http.go
  src/apiserver/service/url.go
  src/common/rdapi/rdfunc.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/model_private.go
  src/storage/dal/mongo/local/mongo.go
Labels: optimization

#3801 修复get_biz_internal_module接口bson的tag缺双引号导致json序列化ModuleName错误的问题
  src/common/metadata/object.go
Labels: bug

#3804 fix:ui: V3.7体验问题优化
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/host-apply/children/search-select-mix.vue
  src/ui/src/views/host-apply/conflict-list.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-apply/property-confirm.vue
Labels: inner, optimization

#3803 feature: 资源池目录
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/ui/other/button-group.vue
  src/ui/src/views/resource/children/directory.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/resource/index.vue
Labels: demand, inner

#3813 optimize owner id query condition
  src/scene_server/host_server/logics/app.go
  src/source_controller/coreservice/core/mainline/class.go
Labels: optimization

#3814 fix response code 406 issue.
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/service/service.go
Labels: bug

#3815 调整coreservice中ownerid的使用方式
  src/source_controller/coreservice/core/mainline/manager.go
  src/web_server/logics/host.go
Labels: optimization

#3808 UI: 3.7 bug修复
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/model-association/_detail.vue
  src/ui/src/views/model-association/index.vue
Labels: bug, inner, optimization

#3805 仅内置模型等进行国际化
  src/source_controller/coreservice/service/association.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/translate.go
Labels: optimization

#3823 update:ui: 操作审计功能细化
  src/ui/src/assets/json/operation_audit.json
  src/ui/src/assets/json/operation_audit_all.json
  src/ui/src/components/audit-history/audit-history.vue
  src/ui/src/components/audit-history/details-json.vue
  src/ui/src/components/audit-history/details.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/operation-audit.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/history.vue
Labels: demand

#3817 UI: 主机转移的变更确认badge优化
  src/ui/src/views/host-operation/index.vue
Labels: optimization

#3810 UI：3.6 bug 修复
  src/ui/src/router/index.js
  src/ui/src/setup/validate.js
  src/ui/src/store/modules/global.js
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/host-details/children/info.vue
Labels: bug, inner

#3807 UI: 3.8优化
  src/ui/src/components/model-manage/field-group/field-view.vue
  src/ui/src/filters/formatter.js
  src/ui/src/views/model-manage/index.vue
Labels: inner, optimization

#3826 update:ui: 删除服务拓扑中无用的鉴权
  src/ui/src/views/business-topology/router.config.js
Labels: optimization

#3827 update:ui: 删除业务拓扑中无用的鉴权
  src/ui/src/views/business-topology/router.config.js
Labels: optimization

#3811 修复添加业务字段时与全局字段名相同时可添加成功的问题
  src/source_controller/coreservice/core/model/attribute_curd.go
Labels: bug

#3816 bk_supplier_account调整
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/datacollection/logics/common.go
  src/scene_server/host_server/logics/app.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/topo_server/core/inst/association.go
  src/scene_server/topo_server/core/model/group.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/auditlog.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/object_attribute.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/auditlog/audit.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_crud.go
  src/source_controller/coreservice/core/model/model_private.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/source_controller/coreservice/service/instances_dependence.go
  src/source_controller/coreservice/service/topographics.go
  src/web_server/logics/fields.go
  src/web_server/logics/inst.go
  src/web_server/middleware/user/owner.go
Labels: optimization

#3830 change FieldTypeLongCharRegexp, add '=' char support.
  src/common/definitions.go
Labels: demand

#3829 ui: 主机详情云区域信息展示优化
  src/ui/src/views/host-details/children/info.vue
Labels: inner, optimization

#3822 fix: process template name and function name empty bug issue #3821
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/scene_server/admin_server/upgrader/x20.02.17.01/fix_proctemp_procname.go
  src/scene_server/admin_server/upgrader/x20.02.17.01/pkg.go
Labels: bug, inner

#3802 event server 事件id使用upgrader迁移
  scripts/init.py
  src/scene_server/admin_server/app/options/options.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/service/service.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/admin_server/upgrader/y3.8.202002101113/migrate_event_id.go
  src/scene_server/admin_server/upgrader/y3.8.202002101113/pkg.go
  src/scene_server/event_server/distribution/start.go
Labels: demand

#3833 增加cloud server的coreservice层框架代码和apiclient接口
  src/apimachinery/clientset.go
  src/apimachinery/cloudserver/api.go
  src/apimachinery/cloudserver/cloudserver.go
  src/apimachinery/coreservice/cloud/api.go
  src/apimachinery/coreservice/cloud/cloud.go
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/discovery_mock.go
  src/apimachinery/healthz/healthz.go
  src/apiserver/service/filter.go
  src/apiserver/service/url.go
  src/common/definitions.go
  src/common/metadata/cloud.go
  src/common/metadata/core_service.go
  src/common/types/serverInfo.go
  src/source_controller/coreservice/core/cloud/account.go
  src/source_controller/coreservice/core/cloud/cloud.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/service/cloudaccount.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: demand

#3825 add: 添加cloudserver的基础框架代码 issue #3824
  scripts/init.py
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/cloud_server/Makefile
  src/scene_server/cloud_server/app/options/options.go
  src/scene_server/cloud_server/app/server.go
  src/scene_server/cloud_server/cloud.go
  src/scene_server/cloud_server/logics/logics.go
  src/scene_server/cloud_server/readme.md
  src/scene_server/cloud_server/service/account.go
  src/scene_server/cloud_server/service/health.go
  src/scene_server/cloud_server/service/service.go
Labels: demand

#3839 V3.6.x: 添加主机当前状态字段英文翻译
  resources/language/default/property.json
  resources/language/en/property.json
Labels: demand

#3834 调整mongodb连接数配置项生效
  scripts/init.py
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/command/command.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/event_server/app/server.go
  src/scene_server/topo_server/app/server.go
  src/source_controller/coreservice/service/service.go
  src/storage/dal/mongo/config.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/local/mongo_test.go
  src/storage/dal/mongo/local/transaction_test.go
  src/test/load/db_load_test.go
  src/test/test.go
  src/tools/cmdb_ctl/app/config/config.go
Labels: demand

#3844 修复datacollection更新主机信息失败的问题
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
Labels: bug

#3853 fix task_server TARGET_PORT
  src/scene_server/task_server/Makefile
Labels: bug

#3854 add access control pkg.
  src/ac/auth.go
  src/ac/iam/client.go
  src/ac/iam/iam.go
  src/ac/iam/initial_actions.go
  src/ac/iam/initial_resources.go
  src/ac/iam/types.go
  src/apimachinery/rest/request.go
Labels: demand

#3847 通用json反序列化去除科学记数法
  src/apimachinery/rest/request.go
  src/common/json/json.go
  src/common/mapstr/convert.go
  src/common/mapstr/mapstr.go
  src/common/mapstr/to_value.go
  src/common/util/conv.go
  src/scene_server/admin_server/authsynchronizer/handler/host.go
  src/scene_server/topo_server/service/inst_business.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_test.go
  src/test/host_server/user_test.go
  src/test/proc_server/no_service_template_test.go
  src/test/proc_server/proc_server_suite_test.go
  src/test/proc_server/service_template_test.go
  src/test/topo_server/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/object_test.go
Labels: demand

#3852 修复3.2 datacollection空指针异常和连接未关闭的问题
  src/scene_server/datacollection/datacollection/discover.go
  src/scene_server/datacollection/datacollection/hostsnap.go
Labels: bug

#3840 添加查询业务下的主机和进程信息接口及测试用例
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/process/process.go
  src/apimachinery/procserver/process/api.go
  src/apimachinery/procserver/process/instance.go
  src/auth/parser/processinstance.go
  src/common/metadata/core_service.go
  src/common/metadata/process.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/service.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/process/process_instance_relation.go
  src/source_controller/coreservice/service/process_instance_relation.go
  src/source_controller/coreservice/service/service_process_initfunc.go
  src/test/proc_server/no_service_template_test.go
Labels: demand

#3843 fix: RespAutoError data 从""修改为nil
  src/common/http/rest/contexts.go
Labels: optimization

#3819 V3.8.x： Excel导出导入，增加一列字段标识前三行是不允许删除的
  resources/language/default/fieldtype.json
  resources/language/en/fieldtype.json
  src/apiserver/service/http.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/attribute.go
  src/common/metadata/audit.go
  src/common/metadata/procserver.go
  src/common/types/serverInfo.go
  src/common/util/lib.go
  src/scene_server/admin_server/upgrader/v3.0.8/createtable.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/datacollection/logics/common.go
  src/scene_server/event_server/app/server.go
  src/scene_server/host_server/logics/app.go
  src/scene_server/proc_server/logics/processinstance.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/service/auditlog.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/association/kind.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/mainline/class.go
  src/source_controller/coreservice/core/mainline/manager.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_private.go
  src/source_controller/coreservice/core/operation/inner_chart.go
  src/source_controller/coreservice/core/settemplate/set_template.go
  src/source_controller/coreservice/service/association.go
  src/source_controller/coreservice/service/host.go
  src/source_controller/coreservice/service/instances.go
  src/source_controller/coreservice/service/topographics.go
  src/source_controller/coreservice/service/translate.go
  src/storage/dal/mongo/config.go
  src/storage/dal/mongo/local/transaction_test.go
  src/storage/dal/mongo/local/txn_manager.go
  src/storage/types/types.go
  src/storage/types/types_test.go
  src/test/load/db_load_test.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/fields.go
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
  src/web_server/middleware/user/owner.go
  src/web_server/middleware/user/plugins/method/blueking/userinfo.go
  src/web_server/middleware/user/plugins/method/skip_login/userinfo.go
Labels: demand

#3855 修复datacollection连接未关闭的问题
  src/scene_server/datacollection/datacollection/porter.go
Labels: bug

#3818 v3.8.x：新加excel导入更新主机功能
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/auth/parser/host.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/service.go
  src/web_server/logics/host.go
  src/web_server/service/host.go
  src/web_server/service/service.go
Labels: demand

#3857 update:ui: 配置返回按钮
  src/ui/src/views/host-details/router.config.js
Labels: optimization

#3849 update:ui: tab样式调整
  src/ui/src/views/host-operation/index.vue
Labels: optimization

#3836 update:ui: 模型bool字段可设置默认值
  src/ui/src/components/model-manage/field-group/field-detail/bool.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/utils/tools.js
  src/ui/src/views/service-template/children/operational.vue
Labels: demand, inner

#3837 新增添加主机到资源池接口
  src/apimachinery/hostserver/apis.go
  src/apimachinery/hostserver/hostserver.go
  src/auth/parser/host.go
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/service.go
  src/test/host_server/host_test.go
Labels: demand

#3796 操作审计调整 #3787
  docs/apidoc/v3.1/operation_audit.md
  docs/apidoc/v3.2/operation_audit.md
  docs/overview/installation.md
  resources/language/default/oplogdesc.json
  resources/language/en/oplogdesc.json
  src/apimachinery/coreservice/auditlog/api.go
  src/apimachinery/coreservice/auditlog/auditlog.go
  src/auth/extensions/audit.go
  src/common/auditlog/util.go
  src/common/auditoplog/operationlog.go
  src/common/auditoplog/operationlog_test.go
  src/common/definitions.go
  src/common/metadata/association.go
  src/common/metadata/audit.go
  src/common/metadata/log.go
  src/common/metadata/operation.go
  src/common/tablenames.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/v3.0.8/addDefauleApp.go
  src/scene_server/admin_server/upgrader/v3.0.8/addPlatData.go
  src/scene_server/admin_server/upgrader/v3.0.8/addSystemData.go
  src/scene_server/admin_server/upgrader/v3.0.8/createtable.go
  src/scene_server/admin_server/upgrader/v3.0.8/upgradeBKBiz.go
  src/scene_server/admin_server/upgrader/v3.0.9-beta.1/fixes_supplier_account.go
  src/scene_server/admin_server/upgrader/x08.09.11.01/upgrader.go
  src/scene_server/admin_server/upgrader/x08.09.13.01/addOperationLogIndex.go
  src/scene_server/admin_server/upgrader/x08.09.13.01/pkg.go
  src/scene_server/admin_server/upgrader/y3.7.201912171427/add_set_template_version.go
  src/scene_server/admin_server/upgrader/y3.8.202001172032/create_audit_log_table.go
  src/scene_server/admin_server/upgrader/y3.8.202001172032/pkg.go
  src/scene_server/datacollection/datacollection/hostsnap/hostsnap.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/scene_server/datacollection/datacollection/middleware/util.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/module.go
  src/scene_server/topo_server/core/core.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/audit.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/topo_server/service/auditlog.go
  src/source_controller/coreservice/core/auditlog/audit.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/operation/chart_operation.go
  src/source_controller/coreservice/core/operation/inner_chart.go
  src/source_controller/coreservice/core/operation/operation.go
  src/source_controller/coreservice/service/auditlog.go
Labels: optimization
