Repository Tencent/bk-cmdb, pull requests merged in 2020-09, with the labels that each got.

#4599 优化主机快照存储逻辑，减少快照存储大小
  src/scene_server/datacollection/collections/hostsnap/hostsnap.go
  src/scene_server/datacollection/collections/hostsnap/parse.go
  src/scene_server/host_server/logics/agent.go
  src/scene_server/host_server/service/host.go
Labels: optimization

#4606 refactor: list all host with cache issue #4605
  src/common/json/json.go
  src/source_controller/coreservice/core/host/host.go
  src/source_controller/coreservice/core/host/searcher/searcher.go
  src/source_controller/coreservice/service/service.go
Labels: inner, optimization

#4607 feature: sub attribute support group name issue #4468
  src/common/metadata/attribute.go
  src/scene_server/admin_server/upgrader/y3.8.202007211455/proc_bind_change.go
Labels: inner, optimization

#4609 feature: list host without biz fixed sort field(bk_host_id). issue…
  agent/readme.md
  src/scene_server/host_server/service/findhost.go
Labels: demand, inner, optimization

#4615 feature: bind info sub attribute is require issue #4468
  src/scene_server/admin_server/upgrader/y3.8.202007211455/proc_bind_change.go
Labels: demand, inner

#4626 ui: 服务模板绑定IP增加选项/ bug修复
  src/ui/package.json
  src/ui/src/components/model-instance/relation/list.vue
  src/ui/src/components/service/process-bind-info-value.vue
  src/ui/src/components/ui/form/table.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/host-operation/children/create-service-instance.vue
  src/ui/src/views/index/children/search-input.vue
  src/ui/src/views/resource/transfer/host-store.js
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-template/children/process-form-property-ip.vue
  src/ui/src/views/service-template/children/process-form-property-table.vue
Labels: demand, inner

#4628 feature:ui: 资源池显示主机拓扑路径及支持主机转移模块
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/resource/transfer/host-store.js
  src/ui/src/views/resource/transfer/transfer-menu.vue
Labels: inner, optimization

#4634 refactor: change resource to driver method issue #4570
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/process/service_instance.go
Labels: inner, optimization

#4625 UI： 操作审计优化
  src/ui/src/assets/json/operation_audit.json
  src/ui/src/assets/json/operation_audit_all.json
  src/ui/src/components/audit-history/audit-business-selector.vue
  src/ui/src/components/audit-history/details-json.vue
  src/ui/src/components/audit-history/details-slider.vue
  src/ui/src/components/audit-history/details-table.vue
  src/ui/src/components/audit-history/details.js
  src/ui/src/components/audit-history/details.vue
  src/ui/src/components/model-instance/audit-history.vue
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/audit.js
  src/ui/src/store/modules/api/operation-audit.js
  src/ui/src/views/audit/children/audit-action-selector.vue
  src/ui/src/views/audit/children/audit-business-options.vue
  src/ui/src/views/audit/children/audit-host-options.vue
  src/ui/src/views/audit/children/audit-other-options.vue
  src/ui/src/views/audit/children/audit-resource-options.vue
  src/ui/src/views/audit/children/audit-target-selector.vue
  src/ui/src/views/audit/index.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/host-details/index.vue
Labels: inner, optimization

#4641 refactor: change migrate version issue #4468
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.8.202009101702/pkg.go
  src/scene_server/admin_server/upgrader/y3.8.202009101702/proc_bind_change.go
Labels: inner

#4645 feature:ui: 编译时自动注入当前的commit id
  src/ui/config/prod.env.js
  src/ui/src/main.js
Labels: demand, inner

#4647 fix: sync proc bind info and diff bind info not equal issue #4468
  src/common/metadata/process_bind_info.go
Labels: bug, in progress

#4654 修复当主机没有安装agent时，快照实时页面显示不对的问题
  src/scene_server/host_server/service/host.go
Labels: bug, inner

#4655 UI: 修复收藏条件应用无效及运营统计新增图表UI异常的问题
  src/ui/src/views/audit/children/audit-business-options.vue
  src/ui/src/views/audit/children/audit-host-options.vue
  src/ui/src/views/audit/children/audit-other-options.vue
  src/ui/src/views/audit/children/audit-resource-options.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/service-category/index.vue
Labels: bug, inner

#4664 feature: send query command to secondary nodes by scenario issue #4663
  src/common/definitions.go
  src/common/http/rest/contexts.go
  src/common/http/rest/rest.go
  src/common/util/lib.go
  src/scene_server/auth_server/service/service.go
  src/scene_server/host_server/service/findhost.go
  src/storage/dal/mongo/local/mongo.go
Labels: demand, in progress, inner

#4661 UI: 动态分组支持查询主机与集群
  src/ui/src/components/search/bool.vue
  src/ui/src/components/search/date.vue
  src/ui/src/components/search/enum.vue
  src/ui/src/components/search/float.vue
  src/ui/src/components/search/index.js
  src/ui/src/components/search/int.vue
  src/ui/src/components/search/list.vue
  src/ui/src/components/search/longchar.vue
  src/ui/src/components/search/objuser.vue
  src/ui/src/components/search/organization.vue
  src/ui/src/components/search/singlechar.vue
  src/ui/src/components/search/time.vue
  src/ui/src/components/search/timezone.vue
  src/ui/src/main.js
  src/ui/src/store/index.js
  src/ui/src/store/modules/api/dynamic-group.js
  src/ui/src/store/modules/api/host-custom-api.js
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/index.vue
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/custom-query/query-property-seletor.vue
  src/ui/src/views/dynamic-group/form/form-fields-selector.vue
  src/ui/src/views/dynamic-group/form/form-operator-selector.vue
  src/ui/src/views/dynamic-group/form/form-property-list.vue
  src/ui/src/views/dynamic-group/form/form-property-selector.js
  src/ui/src/views/dynamic-group/form/form-property-selector.vue
  src/ui/src/views/dynamic-group/form/form.js
  src/ui/src/views/dynamic-group/form/form.vue
  src/ui/src/views/dynamic-group/index.vue
  src/ui/src/views/dynamic-group/preview/preview.js
  src/ui/src/views/dynamic-group/preview/preview.vue
  src/ui/src/views/dynamic-group/router.config.js
  src/ui/src/views/index.js
Labels: demand, inner

#4674 refactor: --version output service name info issue #4673
  src/common/identification.go
  src/common/types/serverInfo.go
  src/common/version/version.go
Labels: inner, optimization

#4684 datacollection变更字段可以根据环境配置
  src/scene_server/datacollection/collections/hostsnap/hostsnap.go
Labels: in progress, inner

#4699 UI：交互优化
  src/ui/src/components/audit-history/details-table.vue
  src/ui/src/components/host-apply/property-confirm-table.vue
  src/ui/src/components/model-instance/property.vue
  src/ui/src/components/model-manage/field-group/field-detail/bool.vue
  src/ui/src/components/model-manage/field-group/field-detail/enum.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/other/property-value.vue
  src/ui/src/components/ui/other/table-value.vue
  src/ui/src/components/ui/other/user-value.vue
  src/ui/src/components/ui/selector/selector.vue
  src/ui/src/router/query.js
  src/ui/src/views/business-synchronous/children/details.vue
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/business-topology/service-instance/instance/expand-list.vue
  src/ui/src/views/business-topology/service-instance/process/expand-list.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/cloud-resource/index.vue
  src/ui/src/views/custom-fields/index.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/index.vue
  src/ui/src/views/host-operation/children/create-service-instance.vue
  src/ui/src/views/model-manage/children/index.vue
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
  src/ui/src/views/model-topology/children/relation-detail.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-template/children/process.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/service-template/template.vue
  src/ui/src/views/set-template/children/service-template-info.vue
  src/ui/src/views/set-template/index.vue
  src/ui/src/views/set-template/template.vue
Labels: bug, optimization

#4676 feature: add dynamic service discoery issue #4675
  src/apimachinery/discovery/discovery.go
  src/common/types/manager.go
Labels: inner, optimization

#4707 UI：交互优化
  src/ui/src/components/modal/permission.vue
  src/ui/src/components/model-manage/field-group/field-view.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business/index.vue
  src/ui/src/views/cloud-account/index.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/service-template/index.vue
Labels: inner, optimization
