Repository Tencent/bk-cmdb, pull requests merged in 2020-01, with the labels that each got.

#3702 fix: 模型属性分组为none或“”时，migrate设置为default，更新模型属性不可更新分组
  src/scene_server/admin_server/upgrader/y3.6.201912241627/sort_bk_property_index.go
  src/scene_server/topo_server/service/object_attribute.go
Labels: demand

#3716 fix:ui: 修复业务主机业务选择器UI层级不正确的问题
  src/ui/src/views/hosts/index.vue
Labels: bug

#3713 feature: add http transport support proxy issue #3712
  src/apimachinery/util/client.go
Labels: demand, inner

#3710 全文检索连接es支持配置https与auth认证
  scripts/init.py
  src/scene_server/topo_server/app/options/options.go
  src/scene_server/topo_server/app/server.go
  src/thirdpartyclient/elasticsearch/esclient.go
Labels: demand

#3706 主机支持设置业务自定义属性
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/errInfo.go
  src/common/metadata/hostserver.go
  src/source_controller/coreservice/core/host/transfer/manager.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/service/instances_dependence.go
Labels: demand

#3697 主机删除未判断关联bugfix
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/scene_server/host_server/service/host.go
  src/scene_server/topo_server/core/operation/association.go
  src/source_controller/coreservice/core/host/transfer/transfer.go
Labels: bug

#3717 全文检索连接es支持配置https与auth认证
  scripts/init.py
  src/scene_server/topo_server/app/options/options.go
  src/scene_server/topo_server/app/server.go
  src/thirdpartyclient/elasticsearch/esclient.go
Labels: demand

#3714 查询模型属性接口性能优化
  src/scene_server/topo_server/core/operation/attribute.go
Labels: optimization

#3687 批量服务实例删除支持预览发生主机转移时的属性自动应用信息预览 #3686
  src/common/metadata/attribute.go
  src/common/metadata/process_request.go
  src/scene_server/proc_server/service/processinstance.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/service/object_attribute.go
  src/source_controller/coreservice/core/hostapplyrule/plan.go
Labels: demand

#3723 fix: 修复url有参数拼接时，metrics会采集多个不同url的问题 issue #3722
  src/apimachinery/adminserver/api.go
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/biz.go
  src/apimachinery/coreservice/association/api.go
  src/apimachinery/coreservice/auditlog/api.go
  src/apimachinery/coreservice/cloudsync/api.go
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/instance/api.go
  src/apimachinery/coreservice/label/api.go
  src/apimachinery/coreservice/mainline/api.go
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/operation/api.go
  src/apimachinery/coreservice/process/api.go
  src/apimachinery/coreservice/settemplate/api.go
  src/apimachinery/coreservice/synchronize/api.go
  src/apimachinery/coreservice/system/api.go
  src/apimachinery/coreservice/topographics/graphic.go
  src/apimachinery/eventserver/api.go
  src/apimachinery/healthz/healthz.go
  src/apimachinery/hostserver/apis.go
  src/apimachinery/procserver/openapi/openapi.go
  src/apimachinery/procserver/process/instance.go
  src/apimachinery/procserver/process/template.go
  src/apimachinery/procserver/service/category.go
  src/apimachinery/procserver/service/instance.go
  src/apimachinery/procserver/service/template.go
  src/apimachinery/rest/request.go
  src/apimachinery/synchronize/synchronizeserver/syncrhonize.go
  src/apimachinery/taskserver/queue/queue.go
  src/apimachinery/taskserver/task/task.go
  src/apimachinery/toposerver/association/association.go
  src/apimachinery/toposerver/inst/app.go
  src/apimachinery/toposerver/inst/common.go
  src/apimachinery/toposerver/inst/inst.go
  src/apimachinery/toposerver/inst/module.go
  src/apimachinery/toposerver/inst/set.go
  src/apimachinery/toposerver/object/action.go
  src/apimachinery/toposerver/object/attribute.go
  src/apimachinery/toposerver/object/class.go
  src/apimachinery/toposerver/object/graphic.go
  src/apimachinery/toposerver/object/group.go
  src/apimachinery/toposerver/object/obj.go
  src/apimachinery/toposerver/object/unique.go
  src/apimachinery/toposerver/settemplate/settemplate.go
  src/auth/authcenter/client.go
  src/thirdpartyclient/esbserver/gse/api.go
  src/thirdpartyclient/esbserver/nodeman/nodeman.go
  src/thirdpartyclient/esbserver/user/api.go
Labels: optimization

#3732 feature:ui: 查看集群模板tab添加同步提示
  src/ui/src/views/set-template/template.vue
Labels: optimization

#3728 修复并发场景下，属性和字段属性重复的问题
  resources/errors/common/default/common.json
  resources/errors/common/default/core_service.json
  resources/errors/english/en/common.json
  resources/errors/english/en/core_service.json
  src/apimachinery/toposerver/object/api.go
  src/apimachinery/toposerver/object/obj.go
  src/common/errInfo.go
  src/common/lock/lock.go
  src/common/lock/lock_key.go
  src/common/lock/lock_test.go
  src/scene_server/datacollection/datacollection/middleware/handler.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/service/service.go
Labels: bug, inner

#3727 SetQueryOwner 优化
  src/common/util/ownerutil.go
  src/common/util/ownerutil_test.go
  src/source_controller/coreservice/core/host/searcher/searcher.go
  src/source_controller/coreservice/service/host.go
Labels: optimization

#3725 新增资源池主机查询接口
  src/scene_server/host_server/service/findhost.go
  src/scene_server/host_server/service/service.go
Labels: demand

#3699 模型名其及字段名增加符合mongo表名及其字段名的限制
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/validator_util.go
Labels: demand

#3708 调整业务归档策略 #3707
  src/common/metadata/toposerver.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/inst_business.go
Labels: demand

#3738 fix: 模型属性排序，index获取bug修复
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/web_server/logics/fields.go
Labels: bug

#3733 update:ui: 内部体验优化
  src/ui/src/components/service/instance-table.vue
  src/ui/src/views/business-synchronous/router.config.js
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/host/module-selector.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue
  src/ui/src/views/set-sync/router.config.js
  src/ui/src/views/set-sync/sync-index.vue
Labels: optimization

#3739 update:ui: 模型字段排序调整
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/store/modules/api/object-model-field-group.js
Labels: optimization

#3734 3.8优化调整
  src/ui/src/components/columns-config/columns-config.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/permission/embed-permission.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/preload.js
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/store/modules/api/user-custom.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business/archived.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/set-template/children/service-template-selector.vue
Labels: demand

#3690 去除UpdateModelInstances中多余的count操作
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
Labels: optimization

#3748 优化 /api/v3/find/classificationobject 接口
  src/common/metadata/object_controller.go
  src/scene_server/topo_server/core/operation/classification.go
Labels: inner, optimization

#3745 导出excel模型字段排序
  src/web_server/logics/fields.go
Labels: demand

#3736 fix: 运营统计主机数量变化趋势图，定时器不生效bug
  src/common/metadata/operation.go
  src/scene_server/operation_server/logics/logics.go
  src/scene_server/operation_server/service/service.go
  src/source_controller/coreservice/core/operation/inner_chart.go
  src/source_controller/coreservice/core/operation/operation.go
  src/source_controller/coreservice/service/operation.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_initfunc.go
Labels: bug

#3764 fix: 修复查询不存在的模型属性报错的问题 issue #3763
  src/scene_server/topo_server/core/operation/attribute.go
Labels: optimization

#3720 取消长短字符字段的特殊字符正则校验
  src/common/definitions.go
  src/common/metadata/attribute.go
  src/common/metadata/process.go
  src/scene_server/topo_server/core/model/valid.go
  src/source_controller/coreservice/core/hostapplyrule/plan.go
  src/source_controller/coreservice/core/hostapplyrule/rule.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator_attr.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/test/topo_server/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/object_test.go
Labels: demand

#3741 常用数据库管理/修复脚本
  src/tools/mongo_script/.DS_Store
  src/tools/mongo_script/clear_redundancy_servicetemplate.js
  src/tools/mongo_script/fix_duplicated_service_instance_id.js
  src/tools/mongo_script/fix_inner_model.js
  src/tools/mongo_script/fix_max_primary_id.js
  src/tools/mongo_script/fix_module_missed_fields.js
  src/tools/mongo_script/fix_service_category_field.js
  src/tools/mongo_script/migrate_time_field.js
Labels: optimization

#3744 update:ui: 体验优化
  src/ui/src/components/model-manage/field-group/field-detail/enum.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/field-detail/list.vue
  src/ui/src/components/model-manage/field-group/preview-field.vue
  src/ui/src/components/ui/selector/selector.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-synchronous/router.config.js
  src/ui/src/views/business-topology/children/create-set.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/host-details/children/info.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/model-manage/children/relation-detail/index.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/service-instance/children/clone-to-other.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-instance/create.vue
  src/ui/src/views/service-instance/router.config.js
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/service-template/router.config.js
  src/ui/src/views/set-template/router.config.js
Labels: inner, optimization

#3750 /read/model/{bk_obj_id}/instances接口优化
  src/auth/extensions/classification.go
  src/auth/extensions/host.go
  src/auth/extensions/model.go
  src/auth/extensions/module.go
  src/auth/extensions/set.go
  src/common/metadata/query.go
  src/scene_server/host_server/logics/app.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/instance.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/logics/module.go
  src/scene_server/host_server/logics/object.go
  src/scene_server/host_server/logics/plat.go
  src/scene_server/host_server/logics/set.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/host_server/service/host.go
  src/scene_server/host_server/service/hostapplyrule.go
  src/scene_server/host_server/service/transfer.go
  src/scene_server/synchronize_server/logics/find.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/identifier.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/core/operation/inst_module.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/inst_set.go
  src/scene_server/topo_server/service/set_template.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/association/kind_crud.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/source_controller/coreservice/service/model_classification_test.go
  src/storage/dal/mongo/local/mongo.go
  src/web_server/logics/fields.go
Labels: optimization

#3753 fix: export host not topolgy info issue #3753
  src/web_server/logics/excel_util.go
Labels: bug, inner

#3756 内置服务分类添加翻译
  resources/language/default/service_category.json
  resources/language/en/service_category.json
  src/source_controller/coreservice/service/service_category.go
  src/source_controller/coreservice/service/translate.go
Labels: demand

#3758 已赋值的实例日期和时间类型字段允许置空
  src/common/metadata/attribute.go
  src/source_controller/coreservice/core/instances/validator_attr.go
Labels: bug

#3746 optimize:ui: 显示字段单位和树搜索为空提示文案位置
  src/ui/package.json
  src/ui/src/components/host-apply/property-confirm-table.vue
  src/ui/src/components/host-apply/property-form-element.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/_quick-search.vue
  src/ui/src/components/model-manage/field-group/preview-field.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/store/modules/api/host-apply.js
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/host-apply/children/host-property-modal.vue
  src/ui/src/views/host-apply/children/search-select-mix.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
  src/ui/src/views/host-apply/index.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/children/template-instance.vue
Labels: inner, optimization

#3766 fix: 更新主机报"根据主机ID获取业务ID失败"
  src/source_controller/coreservice/core/instances/instance_validate.go
Labels: bug

#3767 db数据升级文档
  docs/wiki/db_upgrade.md
  readme.md
Labels: optimization

#3761 进程启动监听地址支持IPV6，zk注册发现地址支持域名
  docs/overview/installation.md
  scripts/init.py
  scripts/init_db.sh
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/server.go
  src/apiserver/app/options/options.go
  src/apiserver/app/server.go
  src/common/backbone/backbone.go
  src/common/backbone/register.go
  src/common/core/cc/config/config.go
  src/common/types/serverInfo.go
  src/scene_server/admin_server/app/options/options.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/datacollection/app/options/options.go
  src/scene_server/datacollection/app/server.go
  src/scene_server/event_server/app/options/options.go
  src/scene_server/event_server/app/server.go
  src/scene_server/host_server/app/options/options.go
  src/scene_server/host_server/app/server.go
  src/scene_server/operation_server/app/options/options.go
  src/scene_server/operation_server/app/server.go
  src/scene_server/proc_server/app/options/options.go
  src/scene_server/proc_server/app/server.go
  src/scene_server/synchronize_server/app/options/options.go
  src/scene_server/synchronize_server/app/server.go
  src/scene_server/task_server/app/options/options.go
  src/scene_server/task_server/app/server.go
  src/scene_server/topo_server/app/options/options.go
  src/scene_server/topo_server/app/server.go
  src/source_controller/coreservice/app/options/options.go
  src/source_controller/coreservice/app/server.go
  src/storage/tmserver/app/options/options.go
  src/storage/tmserver/app/run.go
  src/storage/tmserver/app/server.go
  src/web_server/app/options/options.go
  src/web_server/app/server.go
Labels: demand

#3770 fix: excel导入实例与主机关联失败，报错主机不存在
  src/scene_server/topo_server/core/operation/import_association.go
Labels: demand

#3773 fix:ui: V3.7问题修复
  src/ui/src/components/model-manage/field-group/preview-field.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/longchar.vue
  src/ui/src/components/ui/table-empty/table-empty.vue
  src/ui/src/views/host-apply/router.config.js
  src/ui/src/views/service-template/children/process-form.vue
Labels: bug, optimization

#3769 蓝鲸业务下编辑/删除
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/store/modules/view/business-host.js
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
Labels: demand

#3771 模型属性bk_property_group为none的改为default
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x20.01.13.01/pkg.go
  src/scene_server/admin_server/upgrader/x20.01.13.01/update_none_property_group.go
Labels: bug

#3762 1s未收到服务变更事件时从zk读server数据并做对比
  src/common/registerdiscover/zkregdiscv.go
Labels: optimization

#3774 UI: 功能优化
  src/ui/src/api/_request-queue.js
  src/ui/src/api/index.js
  src/ui/src/components/ui/form/async-objuser.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/user/user-queue.js
  src/ui/src/views/host-apply/children/search-select-mix.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-template/index.vue
Labels: inner, optimization

#3772 fix:ui: 修复运营统计图表创建/编辑时发起错误请求的问题
  src/ui/src/views/operation/chart-detail.vue
  src/ui/src/views/operation/index.vue
Labels: bug

#3775 code optimize with mongo about tcp connections
  src/storage/dal/mongo/local/mongo.go
Labels: optimization

#3749 delete: V3.8.x 删除云同步代码
  resources/errors/common/default/host_server.json
  resources/errors/english/en/host_server.json
  src/apimachinery/coreservice/cloudsync/api.go
  src/apimachinery/coreservice/cloudsync/cloud.go
  src/apimachinery/coreservice/coreservice.go
  src/apiserver/app/options/options.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/hostcontroller.go
  src/common/metadata/hostserver.go
  src/common/tablenames.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/x18.12.13.02/pkg.go
  src/scene_server/admin_server/upgrader/x18.12.13.02/upgrader.go
  src/scene_server/host_server/app/server.go
  src/scene_server/host_server/logics/cloud_synctask.go
  src/scene_server/host_server/logics/instance.go
  src/scene_server/host_server/service/cloudtask.go
  src/scene_server/host_server/service/service.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/host/cloud_sync.go
  src/source_controller/coreservice/service/cloud_sync.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/storage/tmserver/app/server.go
  src/tools/mongo_script/.DS_Store
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/cloud-confirm/history.vue
  src/ui/src/views/cloud-confirm/index.vue
  src/ui/src/views/cloud-confirm/router.config.js
  src/ui/src/views/cloud-discover/create.vue
  src/ui/src/views/cloud-discover/index.vue
  src/ui/src/views/cloud-discover/router.config.js
  src/ui/src/views/cloud-discover/sync-history.vue
  src/ui/src/views/cloud-discover/task-details.vue
  src/ui/src/views/cloud-discover/update.vue
  src/web_server/app/server.go
  src/web_server/logics/fields.go
Labels: demand

#3777 fix: 修复url有参数拼接时，metrics会采集多个不同url的问题 #3722
  src/apimachinery/coreservice/hostapplyrule/api.go
  src/test/host_server/host_apply_test.go
Labels: demand

#3776 fix:ui: 修复首页搜索跳转主机详情404的问题
  src/ui/src/store/modules/view/host-details.js
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/host-details/index.vue
  src/ui/src/views/index/children/full-text-search.vue
Labels: bug, inner

#3731 code refactor: 迁移实例字段的校验到属性描述
  scripts/init.py
  src/common/metadata/attribute.go
  src/common/metadata/core_service.go
  src/common/metadata/webserver.go
  src/scene_server/topo_server/core/model/object.go
  src/scene_server/topo_server/core/operation/association_mainline_inst.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/object_attribute.go
  src/source_controller/coreservice/core/instances/instance_validate.go
  src/source_controller/coreservice/core/instances/validator_attr.go
  src/test/host_server/host_apply_test.go
  src/thirdpartyclient/esbserver/user/api.go
  src/thirdpartyclient/esbserver/user/esbserv.go
  src/web_server/middleware/user/plugins/method/self/userinfo.go
  src/web_server/middleware/user/public.go
  src/web_server/service/service.go
  src/web_server/service/user.go
Labels: optimization

#3779 3.5.x init owner
  src/auth/parser/topology.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/web_server/middleware/user/owner.go
  src/web_server/middleware/user/public.go
  src/web_server/service/user.go
Labels: demand

#3781 fix: 服务在zk注册时增加uuid字段，用来区分master, issue #3780
  scripts/init_db.sh
  src/apimachinery/discovery/discovery.go
  src/apimachinery/discovery/server.go
  src/common/types/serverInfo.go
Labels: demand

#3643 模型属性增加组织部门字段类型，提供查询部门列表和部门人员信息的接口
  src/apimachinery/rest/request.go
  src/common/definitions.go
  src/common/metadata/attribute.go
  src/common/metadata/procserver.go
  src/common/metadata/webserver.go
  src/source_controller/coreservice/core/instances/validator_util.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/thirdpartyclient/esbserver/user/api.go
  src/thirdpartyclient/esbserver/user/esbserv.go
  src/web_server/logics/fields.go
  src/web_server/middleware/user/plugins/method/blueking/userinfo.go
  src/web_server/middleware/user/plugins/method/skip_login/userinfo.go
  src/web_server/middleware/user/public.go
  src/web_server/middleware/user/user.go
  src/web_server/service/service.go
  src/web_server/service/user.go
Labels: demand

#3782 操作审计错误信息调整
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/common/errInfo.go
  src/scene_server/host_server/service/host.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/audit.go
  src/scene_server/topo_server/core/operation/supplementary_audit.go
  src/scene_server/topo_server/core/operation/types.go
  src/source_controller/coreservice/service/auditlog.go
Labels: optimization

#3784 fix: 增加模型关联类型的英文翻译 issue #3783
  src/common/metadata/result.go
  src/source_controller/coreservice/core/association/kind.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/service/association.go
  src/source_controller/coreservice/service/translate.go
Labels: demand

#3786 修复操作审计数据库字段错误问题
  src/common/metadata/log.go
Labels: bug

#3789 修复操作审计数据库字段错误问题
  src/common/metadata/log.go
  src/scene_server/admin_server/upgrader/v3.0.8/upgradeBKBiz.go
Labels: bug

#3788 add new audit log struct definination.
  src/common/metadata/audit.go
Labels: demand

#3792 optimize find business api performance.
  src/apimachinery/rest/request.go
  src/common/definitions.go
  src/common/http/rest/contexts.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/inst_business.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
  src/source_controller/coreservice/service/host.go
  src/source_controller/coreservice/service/instances.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/operation.go
  src/source_controller/coreservice/service/service.go
  src/source_controller/coreservice/service/service_category.go
Labels: optimization

#3794 optimize http rest api performance.
  src/apimachinery/util/client.go
  src/common/metrics/metrics.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/service/service.go
Labels: optimization
