Repository Tencent/bk-cmdb, pull requests merged in 2020-05, with the labels that each got.

#4143 修复excel导入模型属性无效的问题
  src/scene_server/topo_server/service/object.go
Labels: bug

#4140 cc_ServiceTemplate、cc_ProcessTemplate、cc_ServiceInstance表联合索引拆开
  src/scene_server/admin_server/upgrader/y3.8.202004291536/add_index.go
  src/storage/dal/mongo/local/mongo.go
Labels: demand

#4139 ui: opensource login
  src/ui/build/webpack.base.conf.js
  src/ui/build/webpack.dev.conf.js
  src/ui/build/webpack.prod.conf.js
  src/ui/config/index.js
  src/ui/login.html
  src/ui/src/login/assets/blueking_cn.svg
  src/ui/src/login/assets/login_bg.png
  src/ui/src/login/assets/login_bg_1280.png
  src/ui/src/login/assets/password.svg
  src/ui/src/login/assets/user.svg
  src/ui/src/login/index.js
  src/ui/src/login/index.vue
Labels: demand, inner

#4148 find_host_by_module接口支持传入host 的字段列表，只返回列表里的字段数
  src/common/metadata/hostserver.go
  src/scene_server/host_server/logics/findhost.go
Labels: optimization

#4167 修复从zookeeper 获取服务配置文件panic的问题
  src/common/backbone/configcenter/cc.go
Labels: bug, inner

#4160 healthz依赖组件更新
  src/apimachinery/healthz/healthz.go
  src/apiserver/service/healthz.go
  src/scene_server/admin_server/service/service.go
  src/scene_server/host_server/service/service.go
  src/scene_server/proc_server/service/service.go
  src/source_controller/coreservice/service/health.go
Labels: demand

#4157 ui: 优化跳转至业务拓扑界面的性能
  src/ui/src/App.vue
  src/ui/src/assets/scss/common.scss
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/dictionary/menu-symbol.js
  src/ui/src/router/business-interceptor.js
  src/ui/src/router/index.js
  src/ui/src/router/query.js
  src/ui/src/setup/preload.js
  src/ui/src/store/modules/api/object-biz.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/index/index.vue
  src/ui/src/views/index/router.config.js
  src/ui/src/views/set-template/children/template-tree.vue
Labels: inner, optimization

#4152 V3.8.x redis driver
  src/scene_server/admin_server/service/flag.go
  src/storage/driver/mongodb/monogdb.go
  src/storage/driver/redis/redis.go
Labels: bug, inner

#4054 增加操作审计部分模型类后端代码
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  src/common/errInfo.go
  src/common/metadata/audit.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/core/operation/classification.go
  src/scene_server/topo_server/core/operation/group.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/object_attr_audit.go
  src/scene_server/topo_server/core/operation/object_attrgroup_audit.go
  src/scene_server/topo_server/core/operation/object_audit.go
  src/scene_server/topo_server/core/operation/object_cls_audit.go
  src/scene_server/topo_server/service/object.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/object_classification.go
  src/scene_server/topo_server/service/object_group.go
  src/ui/src/assets/json/operation_audit_all.json
  src/ui/src/store/modules/api/operation-audit.js
Labels: demand

#4176 修复无法通过redis 在配置文件的前缀获取对应redis 实例的问题
  src/storage/driver/redis/redis.go
Labels: bug, inner

#4171 修复因类型转换失败导致的Excel更新模型实例不全的问题
  src/source_controller/objectcontroller/service/inst_action.go
Labels: bug

#4177 optimize:ui: 优化确认转移主机的loading显示效果
  src/ui/src/views/host-operation/index.vue
Labels: inner, optimization

#4183 fix:ui: 修复login组件引起在safari假死的问题
  src/ui/package.json
Labels: bug, inner

#4185 UI: 业务菜单下的页面问题修复
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/layout/dynamic-navigation.vue
  src/ui/src/router/query.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/business-topology/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/footer.config.js
  src/ui/src/views/index/children/footer.vue
  src/ui/src/views/index/index.vue
Labels: bug, inner

#4187 UI： 添加desktop配置项
  src/ui/config/index.js
  src/ui/index.html
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/index/index.vue
Labels: demand, inner

#4192 优化主机与动态分组多集群多模块搜索
  src/ui/src/components/hosts/filter/_filter-field-operator.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/views/custom-query/define.vue
Labels: inner, optimization

#4191 ui: 主机详情鉴权精细化
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/association.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-list.vue
  src/ui/src/views/host-details/mixin-auth.js
Labels: inner, optimization

#4194 ui: 添加自定义字段审计字典
  src/ui/src/assets/json/operation_audit.json
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/api/operation-audit.js
  src/ui/src/views/audit/index.vue
Labels: demand, inner

#4189 coreservice flow事件流优化
  src/auth/authcenter/adaptor.go
  src/common/http/rest/contexts.go
  src/source_controller/coreservice/cache/host/host.go
  src/source_controller/coreservice/core/mainline/class.go
  src/source_controller/coreservice/core/mainline/instance.go
  src/source_controller/coreservice/event/flow.go
  src/source_controller/coreservice/event/gc.go
  src/source_controller/coreservice/event/key.go
  src/source_controller/coreservice/service/mainline.go
Labels: optimization

#4199 optimize：主机缓存逻辑中，去掉去oid key 的操作与管理
  src/source_controller/coreservice/cache/host/host.go
  src/source_controller/coreservice/cache/host/key.go
  src/source_controller/coreservice/event/flow.go
Labels: optimization

#4203 补充业务拓扑节点信息编辑中的集群和模块名称校验
  src/ui/src/components/ui/form/form.vue
Labels: inner, optimization

#4204 ui: 修复query为空时不会调用立即执行的RouterQuery.watch的问题
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/router/query.js
  src/ui/src/views/business-topology/index.vue
Labels: bug, inner

#4211 fix:not return rid in http header issue #4146
  src/common/http/rest/contexts.go
  src/common/rdapi/rdfunc.go
  src/web_server/middleware/requestid.go
Labels: inner, optimization

#4217 apiserver入口处增加请求信息日志
  src/apiserver/service/service.go
  src/common/rdapi/rdfunc.go
  src/scene_server/synchronize_server/service/service.go
Labels: optimization

#4220 optimize: optimize event watch logics.
  src/apimachinery/eventserver/api.go
  src/apimachinery/eventserver/eventserver.go
  src/auth/authcenter/adaptor.go
  src/auth/authcenter/id.go
  src/auth/parser/event.go
  src/common/types/serverInfo.go
  src/common/watch/watch.go
  src/scene_server/event_server/service/lua.go
  src/scene_server/event_server/service/watch.go
  src/source_controller/coreservice/cache/business/custom_level.go
  src/source_controller/coreservice/cache/business/key.go
  src/source_controller/coreservice/event/flow.go
  src/source_controller/coreservice/event/gc.go
  src/source_controller/coreservice/event/lua.go
  src/tools/cmdb_ctl/cmd/watch.go
  src/tools/cmdb_ctl/cmd/zk.go
Labels: demand

#4219 V3.8.x driver
  src/common/blog/blog.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/local/mongo_test.go
  src/storage/dal/redis/redis.go
  src/storage/dal/types/types.go
Labels: demand

#4233 fix: fix cache refresh concurrent read map.
  src/source_controller/coreservice/cache/tools/lock.go
Labels: bug

#4235 主机属性增加docker版本字段
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.8.202005201015/add_host_attr.go
  src/scene_server/admin_server/upgrader/y3.8.202005201015/pkg.go
Labels: demand

#4238 V3.8.x缺陷与体验问题修复
  src/ui/src/components/import/import.vue
  src/ui/src/components/layout/dynamic-breadcrumbs.vue
  src/ui/src/filters/formatter.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/utils/host.js
  src/ui/src/views/custom-query/define.vue
  src/ui/src/views/custom-query/preview.vue
  src/ui/src/views/custom-query/query-property-seletor.vue
  src/ui/src/views/host-apply/children/multi-module-config.vue
  src/ui/src/views/host-apply/children/single-module-config.vue
  src/ui/src/views/host-apply/index.vue
Labels: bug, inner, optimization

#4237 UI: 交互显示优化/导航bug修复
  src/ui/src/components/layout/dynamic-router-view.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/utils/tools.js
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/index/children/footer.vue
  src/ui/src/views/resource/index.vue
  src/ui/src/views/set-template/index.vue
Labels: bug, inner, optimization

#4240 fix:ui: 修复主机详情服务列表未注入权限数据的问题
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-details/children/service-list.vue
Labels: bug, inner

#4119 toposerver的所有写接口支持事务
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/graphics.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/inst_set.go
  src/scene_server/topo_server/service/object.go
  src/scene_server/topo_server/service/object_association.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/object_classification.go
  src/scene_server/topo_server/service/object_group.go
  src/scene_server/topo_server/service/service_test.go
  src/scene_server/topo_server/service/set_template.go
  src/scene_server/topo_server/service/unique.go
  src/source_controller/coreservice/core/instances/instance.go
  src/storage/dal/mongo/local/txn_manager.go
Labels: demand

#4244 apiserver新增服务降级能力
  src/apiserver/app/server.go
  src/apiserver/service/filter.go
  src/apiserver/service/limiter.go
  src/apiserver/service/service.go
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/apilimiter.go
  src/common/types/serverInfo.go
  src/common/util/struti.go
  src/tools/cmdb_ctl/cmd/limiter.go
  src/tools/cmdb_ctl/readme.md
Labels: demand

#4258 UI: 首页主机搜索支持固资编号
  src/ui/src/assets/scss/_mixins.scss
  src/ui/src/components/hosts/filter/_filter-field-operator.vue
  src/ui/src/components/hosts/filter/filter-property-selector.vue
  src/ui/src/components/hosts/filter/index.vue
  src/ui/src/components/hosts/table/index.vue
  src/ui/src/components/ui/selector/business.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/store/modules/api/user-custom.js
  src/ui/src/store/modules/view/hosts.js
  src/ui/src/utils/host.js
  src/ui/src/views/business-topology/host/host-list.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/resource/index.vue
Labels: demand, inner

#4222 修复开源版本登录和跳过登录方式下拉取用户列表报错的问题
  resources/errors/common/default/web.json
  resources/errors/english/en/web.json
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/webserver.go
  src/web_server/logics/department.go
  src/web_server/logics/user.go
  src/web_server/middleware/user/plugins/mananger.go
  src/web_server/middleware/user/plugins/method/blueking/userinfo.go
  src/web_server/middleware/user/plugins/method/open_source/userinfo.go
  src/web_server/middleware/user/plugins/method/skip_login/userinfo.go
  src/web_server/middleware/user/public.go
  src/web_server/middleware/user/user.go
  src/web_server/service/department.go
  src/web_server/service/login.go
  src/web_server/service/user.go
Labels: bug

#4230 增加批量查询某业务下集群和模块的接口
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/module.go
  src/apimachinery/toposerver/inst/set.go
  src/auth/parser/topology.go
  src/common/metadata/common.go
  src/common/metadata/page.go
  src/scene_server/topo_server/service/inst_module.go
  src/scene_server/topo_server/service/inst_set.go
  src/scene_server/topo_server/service/service_initfunc.go
  src/test/topo_server/object_test.go
Labels: demand

#4268 审计日志只记录模型的公共属性，不记录业务下的私有属性
  src/common/condition/condition.go
  src/common/condition/field.go
  src/scene_server/host_server/logics/host.go
  src/scene_server/host_server/logics/import.go
  src/scene_server/host_server/logics/log.go
  src/scene_server/host_server/service/host.go
  src/scene_server/topo_server/core/model/object.go
Labels: optimization
