Repository Tencent/bk-cmdb, pull requests merged in 2020-04, with the labels that each got.

#4006 修复列表属性校验出错的问题
  src/common/metadata/attribute.go
Labels: bug

#4007 修复page的空指针异常
  src/scene_server/topo_server/service/inst_module.go
Labels: bug

#3996 云同步问题修复，代码调整
  resources/errors/common/default/cloud_server.json
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/cloud_server.json
  resources/errors/english/en/topo_server.json
  src/common/definitions.go
  src/common/errInfo.go
  src/common/metadata/cloud.go
  src/scene_server/cloud_server/cloudsync/cloudsync.go
  src/scene_server/cloud_server/cloudsync/hostsyncor.go
  src/scene_server/cloud_server/cloudsync/taskscheduler.go
  src/scene_server/cloud_server/common/util.go
  src/scene_server/cloud_server/logics/cloud.go
  src/scene_server/cloud_server/logics/synctask.go
  src/scene_server/cloud_server/service/account.go
  src/scene_server/cloud_server/service/synctask.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/topo_server/service/resource_directory.go
  src/source_controller/coreservice/core/cloud/account.go
  src/source_controller/coreservice/core/cloud/synctask.go
  src/source_controller/coreservice/core/cloud/validator.go
  src/storage/stream/event/list_watch.go
  src/test/cloud_server/cloud_sync_task_test.go
Labels: optimization

#4011 UI: bug及优化
  src/ui/package.json
  src/ui/src/components/audit-history/details.vue
  src/ui/src/components/host-apply/property-confirm-table.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/form/form-tips.js
  src/ui/src/components/ui/form/form.vue
  src/ui/src/directives/transfer-dom.js
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/setup/validate.js
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/process-form-tips-render.js
  src/ui/src/views/business-topology/children/process-form-tips.vue
  src/ui/src/views/business-topology/children/service-instance-table.vue
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/business-topology/host/host-selector-topology.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-details/children/association-list-table.vue
  src/ui/src/views/host-details/children/property.vue
  src/ui/src/views/host-details/children/service-instance-table.vue
  src/ui/src/views/host-operation/children/create-service-instance.vue
  src/ui/src/views/host-operation/children/host-attrs-auto-apply.vue
  src/ui/src/views/host-operation/index.vue
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/service-instance/children/clone-to-source.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process.vue
  src/ui/src/views/set-template/children/service-template-info.vue
Labels: bug, optimization

#4008 fix:ui: 修复模型关系分组名称溢出的问题
  src/ui/src/views/model-topology/index.new.vue
Labels: bug, inner

#3993 查询模型属性接口输入输出支持bk_biz_id
  src/auth/parser/topolatest.go
  src/common/metadata/attribute.go
  src/scene_server/topo_server/core/operation/attribute.go
  src/scene_server/topo_server/service/object_attribute.go
  src/scene_server/topo_server/service/service_business_initfunc.go
Labels: demand

#4013 UI: 服务模板功能更新
  src/ui/src/views/business-synchronous/children/details.vue
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-synchronous/router.config.js
  src/ui/src/views/business-topology/children/service-instances.vue
  src/ui/src/views/service-template/children/template-instance.vue
Labels: demand, inner

#4017 UI: 服务模板、拓扑节点BUG修复
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/template-instance.vue
Labels: bug, inner

#4018 UI: 字段创建、拓扑节点创建BUG
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/views/business-topology/children/create-node.vue
  src/ui/src/views/model-manage/children/field-detail/char.vue
  src/ui/src/views/model-manage/children/field-detail/config.vue
  src/ui/src/views/model-manage/children/field-detail/enum.vue
  src/ui/src/views/model-manage/children/field-detail/float.vue
  src/ui/src/views/model-manage/children/field-detail/index.vue
  src/ui/src/views/model-manage/children/field-detail/int.vue
Labels: bug, inner

#4026 UI: 3.8 bug修复
  src/ui/src/components/import/import.vue
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/host-details/children/association-list.vue
  src/ui/src/views/host-details/children/association.vue
Labels: bug, inner

#4029 fix search host identifer with null array issue
  src/source_controller/coreservice/core/host/identifier/identifier.go
Labels: bug

#4030 refactor: add mongodb ping , product session mastersocket issue #3884
  src/storage/dal/mongo/local/mongo.go
Labels: bug, inner, optimization

#4031 event client bugfix
  src/common/eventclient/eventclient.go
Labels: optimization

#4032 修复同步服务模版时的异常
  src/common/metadata/process.go
Labels: bug

#4047 UI： 3.7 缺陷修复
  src/ui/src/components/model-manage/field-group/field-view.vue
  src/ui/src/components/relation/_details.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/form/longchar.vue
  src/ui/src/components/ui/form/search-input.vue
  src/ui/src/views/business-synchronous/children/details.vue
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/service-node-info.vue
  src/ui/src/views/set-template/children/template-config.vue
  src/ui/src/views/set-template/index.vue
Labels: bug, inner

#4042 UI: 修复鉴权组件校验结果不严谨的问题
  src/ui/src/components/ui/auth/auth-queue.js
Labels: bug, inner

#4039 修复业务主机操作实例关联时提示无全局主机编辑权限的问题
  src/auth/parser/topolatest.go
  src/auth/parser/util.go
Labels: bug

#4053 修正获取组织接口的返回数据
  src/web_server/service/department.go
Labels: bug

#4072 进程管理增加网关相关配置
  resources/language/default/property.json
  resources/language/default/property_group.json
  resources/language/en/property.json
  resources/language/en/property_group.json
  src/common/metadata/process.go
  src/scene_server/admin_server/common/definitions.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.8.202004151435/add_proc_gateway_attr.go
  src/scene_server/admin_server/upgrader/y3.8.202004151435/pkg.go
Labels: demand

#4076 UI: 3.5.x 问题修复
  src/ui/src/components/model-manage/field-group/field-detail/config.vue
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
  src/ui/src/components/model-manage/field-group/field-view.vue
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/views/model-manage/children/relation.vue
  src/ui/src/views/model-manage/children/verification.vue
Labels: bug, inner

#4063 查找主机的高级筛选里支持集群、模块等模型属性值忽略大小写的模糊匹配
  src/common/definitions.go
  src/common/paraparse/app.go
  src/scene_server/topo_server/service/inst_business.go
  src/web_server/service/object.go
Labels: demand

#4057 redis调整
  scripts/init.py
  src/storage/dal/mongo/config.go
  src/storage/dal/redis/redis.go
  src/web_server/app/options/options.go
  src/web_server/app/server.go
  vendor/github.com/holmeswang/redistore/redistore.go
Labels: demand

#4084 fix:ui: 内置字段更新不提交名称字段
  src/ui/src/components/model-manage/field-group/field-detail/index.vue
Labels: bug, inner

#4086 fix:ui: 修复主机详情删除主机所属模块可以重新选择主机的问题
  src/ui/src/views/business-topology/router.config.js
  src/ui/src/views/host-details/children/info.vue
  src/ui/src/views/host-operation/index.vue
Labels: bug, inner

#4085 UI: bugfix
  src/ui/src/setup/validate.js
  src/ui/src/utils/tools.js
  src/ui/src/views/service-category/index.vue
  src/ui/src/views/set-template/children/template-intance.vue
Labels: bug, inner

#4088 UI: 审计日志数据读取调整/属性自动应用交互优化
  src/ui/src/components/audit-history/details.vue
  src/ui/src/views/audit/index.vue
  src/ui/src/views/host-apply/children/sidebar.vue
  src/ui/src/views/host-apply/children/topology-tree.vue
Labels: inner, optimization

#4070 feature: add transaction support based on mongodb distributed transaction
  src/apimachinery/coreservice/coreservice.go
  src/apimachinery/coreservice/transaction/api.go
  src/apimachinery/coreservice/transaction/client.go
  src/common/backbone/configcenter/cc.go
  src/common/definitions.go
  src/common/eventclient/eventclient.go
  src/common/eventclient/eventclient_test.go
  src/common/http/rest/rest.go
  src/common/metadata/transaction.go
  src/common/util/lib.go
  src/scene_server/proc_server/service/service.go
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/app/options/options.go
  src/scene_server/topo_server/app/server.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst_business.go
  src/scene_server/topo_server/service/service.go
  src/source_controller/coreservice/core/model/classification_private.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/source_controller/coreservice/service/transaction.go
  src/storage/dal/dal.go
  src/storage/dal/mongo/config.go
  src/storage/dal/mongo/local/mongo.go
  src/storage/dal/mongo/local/mongo_test.go
  src/storage/dal/mongo/local/transaction.go
  src/storage/dal/mongo/local/txn_manager.go
  src/storage/dal/mongo/local/wrapper_transcation.go
  src/storage/dal/types/types.go
  src/test/test.go
  src/test/topo_server/business_test.go
  src/test/topo_server/inst_test.go
  src/test/topo_server/object_test.go
  src/test/txn/txn_suite_test.go
  src/test/txn/txn_test.go
  vendor/go.mongodb.org/mongo-driver/mongo/session_exposer.go
Labels: demand

#4102 V3.8.x问题修复与功能完善
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/store/modules/view/business-host.js
  src/ui/src/utils/tools.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/host-operation/index.vue
Labels: demand, inner, optimization

#4104 优化事件回调方法和修复已发送事件的过期删除
  src/scene_server/event_server/distribution/callback.go
  src/scene_server/event_server/distribution/distribution.go
  src/scene_server/event_server/distribution/handle_event.go
  src/scene_server/event_server/distribution/reconclier.go
  src/scene_server/event_server/service/subscription.go
Labels: optimization

#4099 事件推送支持事务
  src/apimachinery/coreservice/transaction/client.go
  src/common/definitions.go
  src/common/eventclient/eventclient.go
  src/scene_server/event_server/distribution/start.go
  src/scene_server/event_server/distribution/transaction.go
  src/source_controller/coreservice/service/transaction.go
  src/test/txn/txn_test.go
Labels: demand

#4116 fix: v3.8.x缺陷问题修复
  src/ui/src/components/ui/other/property-value.vue
  src/ui/src/store/modules/view/service-process.js
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/children/process-form.vue
  src/ui/src/views/service-template/children/process.vue
Labels: bug, inner

#4114 UI: 修复部分文本显示不正确的问题
  src/ui/src/components/model-manage/field-group/index.vue
  src/ui/src/components/ui/other/property-value.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/host-apply/children/property-config-table.vue
Labels: bug, inner

#4125 删除主机查询时的重复操作，调整集成测试用例
  src/scene_server/host_server/logics/hostsearch.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_test.go
Labels: bug

#4128 增加查询模型实例关系的api路由
  src/api_server/service/v3/uri.go
Labels: demand

#4130 UI: 审计/服务模板bugfix
  src/ui/src/assets/json/operation_audit.json
  src/ui/src/components/model-instance/audit-history.vue
  src/ui/src/components/ui/selector/selector.vue
  src/ui/src/dictionary/audit.js
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-synchronous/index.vue
  src/ui/src/views/business-topology/children/create-module.vue
  src/ui/src/views/business-topology/children/create-set.vue
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/service-template/children/operational.vue
  src/ui/src/views/service-template/template.vue
Labels: bug, inner, optimization

#4134 cc_ServiceTemplate、cc_ProcessTemplate、cc_ServiceInstance表添加索引
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/y3.8.202004291536/add_index.go
  src/scene_server/admin_server/upgrader/y3.8.202004291536/pkg.go
Labels: demand

#4138 ui: 修复创建通用模型实例/业务时传递了自定id的问题
  src/ui/src/views/business/index.vue
  src/ui/src/views/general-model/index.vue
Labels: bug, inner

#4137 查询主机列表的接口支持传入host 的字段列表，只返回列表里的字段数
  src/apimachinery/coreservice/host/api.go
  src/apimachinery/coreservice/host/host.go
  src/common/metadata/hostserver.go
  src/common/metadata/page.go
  src/common/querybuilder/types.go
  src/scene_server/host_server/service/findhost.go
  src/source_controller/coreservice/core/host/searcher/searcher.go
  src/test/host_server/host_abnormal_test.go
  src/test/host_server/host_test.go
Labels: optimization
