Repository Tencent/bk-cmdb, pull requests merged in 2020-12, with the labels that each got.

#4915 优化toposerver
  src/scene_server/topo_server/service/set_template.go
Labels: inner, optimization

#4925 UI: bug修复
  src/ui/src/components/filters/filter-form.vue
  src/ui/src/components/filters/store.js
  src/ui/src/components/search/service-template.vue
  src/ui/src/components/ui/other/property-value.vue
  src/ui/src/views/business/index.vue
  src/ui/src/views/dynamic-group/form/form.vue
  src/ui/src/views/general-model/index.vue
  src/ui/src/views/index/children/host-search.vue
  src/ui/src/views/service-template/index.vue
  src/ui/src/views/set-template/children/template-config.vue
Labels: bug

#4919 优化集群模板对比和同步接口
  src/scene_server/topo_server/core/settemplate/settemplate.go
Labels: inner, optimization

#4928 refactor: error code topo issue #4912
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
Labels: bug, inner

#4929 style: topo issue #4912
  src/scene_server/topo_server/core/operation/association_mainline_object.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/set_template.go
Labels: inner, optimization

#4947 feature: 增加刷新配置的api，在不重启adminserver的情况下更新配置中心的配置 issue #4946
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/configures/conf.go
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/service/service.go
Labels: demand

#4977 fix: v3.2.21 upgrade v3.9.11 process template bind info not upgrade
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
  src/storage/driver/mongodb/table.go
Labels: bug

#4976 fix: v3.2.21 upgrade v3.9.11 process template bind info not upgrade …
  src/scene_server/admin_server/upgrader/x19.05.16.01/upgrade_service_template.go
Labels: bug

#4933 feature: 增加异常数据监控采集上报组件 issue #4932
  scripts/init.py
  src/common/backbone/backbone.go
  src/common/backbone/configcenter/viper.go
  src/common/definitions.go
  src/scene_server/admin_server/configures/checkconf.go
  src/thirdparty/monitor/README.md
  src/thirdparty/monitor/config/config.go
  src/thirdparty/monitor/meta/content.go
  src/thirdparty/monitor/meta/type.go
  src/thirdparty/monitor/monitor.go
  src/thirdparty/monitor/plugins/blueking/blueking.go
  src/thirdparty/monitor/plugins/blueking/gsecmdline.go
  src/thirdparty/monitor/plugins/noop/noop.go
  src/thirdparty/monitor/plugins/plugin.go
Labels: demand

#4992 UI: 修复主机表格数据显示错误&小优化
  src/ui/package.json
  src/ui/src/components/audit-history/audit-business-selector.vue
  src/ui/src/components/filters/store.js
  src/ui/src/components/filters/utils.js
  src/ui/src/components/search/foreignkey.vue
  src/ui/src/components/service/instance-table.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/utils/tools.js
  src/ui/src/views/business-topology/children/topology-tree.vue
  src/ui/src/views/business-topology/host/across-business-module-selector.vue
  src/ui/src/views/business-topology/host/host-selector-new/host-selector-topology.vue
  src/ui/src/views/business-topology/host/host-selector-topology.vue
  src/ui/src/views/business-topology/host/module-selector.vue
  src/ui/src/views/cloud-area/index.vue
  src/ui/src/views/host-details/children/status.vue
  src/ui/src/views/resource/children/host-list.vue
  src/ui/src/views/resource/children/host-options.vue
  src/ui/src/views/resource/transfer/transfer-menu.vue
Labels: optimization

#4991 feature:ui: 主机批量导出
  src/ui/src/api/index.js
  src/ui/src/components/batch-export/content.vue
  src/ui/src/components/batch-export/index.js
  src/ui/src/components/export-fields/export-fields.vue
  src/ui/src/i18n/lang/cn.json
  src/ui/src/i18n/lang/en.json
  src/ui/src/magicbox/index.js
  src/ui/src/magicbox/magicbox.scss
  src/ui/src/views/business-topology/host/host-list-options.vue
  src/ui/src/views/resource/children/host-options.vue
Labels: demand
