Repository Tencent/bk-cmdb, pull requests merged in 2021-06, with the labels that each got.

#5318 删除唯一索引中must_check 字段 #5250
  resources/errors/common/default/topo_server.json
  resources/errors/english/en/topo_server.json
  resources/language/default/import_instance.json
  resources/language/en/import_instance.json
  src/ac/parser/topolatest.go
  src/apimachinery/apiserver/api.go
  src/apimachinery/apiserver/apiserver.go
  src/common/errInfo.go
  src/common/metadata/association.go
  src/common/metadata/object_controller.go
  src/common/metadata/unique.go
  src/common/metadata/webserver.go
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/upgrader/history/x18.11.19.01/reconcil_unique.go
  src/scene_server/admin_server/upgrader/history/x18.12.12.01/reconcil_unique.go
  src/scene_server/admin_server/upgrader/history/x18.12.12.06/reconcil_unique.go
  src/scene_server/admin_server/upgrader/history/y3.7.201912121117/add_host_outer_ip_unique.go
  src/scene_server/admin_server/upgrader/y3.10.202105251041/pkg.go
  src/scene_server/admin_server/upgrader/y3.10.202105251041/unqiue_index_delete_must_check.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/add_cloud_host_unique.go
  src/scene_server/admin_server/upgrader/y3.9.202002131522/add_plat_unique_key.go
  src/scene_server/topo_server/core/model/unique.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/core/operation/unique.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/object_association.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/scene_server/topo_server/service/unique.go
  src/source_controller/coreservice/core/instances/validator_unique.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/test/topo_server/inst_test.go
  src/tools/cmdb_ctl/cmd/unique.go
  src/web_server/logics/association.go
  src/web_server/logics/excel.go
  src/web_server/logics/excel_util.go
  src/web_server/logics/fields.go
  src/web_server/logics/host.go
  src/web_server/logics/inst.go
  src/web_server/logics/object.go
  src/web_server/service/host.go
  src/web_server/service/inst.go
  src/web_server/service/object.go
  src/web_server/service/service.go
Labels: demand, inner

#5306 refactor: sync index and table issue #5292
  src/common/backbone/backbone.go
  src/common/backbone/configcenter/viper.go
  src/common/index/index.go
  src/scene_server/admin_server/app/options/options.go
  src/scene_server/admin_server/app/server.go
  src/scene_server/admin_server/logics/index.go
  src/scene_server/admin_server/service/index.go
  src/scene_server/admin_server/upgrader/register.go
  src/scene_server/topo_server/service/object.go
  src/thirdparty/monitor/monitor.go
Labels: inner

#5326 update monstache doc
  docs/overview/installation.md
Labels: inner, optimization

#5330 fix: blog output log panic
  src/scene_server/admin_server/logics/index.go
Labels: bug

#5332 fix:ui: 修复表单/表单详情按钮组在部分分辨率下抖动的问题
  src/ui/src/components/ui/details/details.vue
  src/ui/src/components/ui/form/form-multiple.vue
  src/ui/src/components/ui/form/form.vue
  src/ui/src/components/ui/index.js
  src/ui/src/components/ui/other/sticky-layout.vue
  src/ui/src/views/service-template/children/process-form.vue
Labels: bug

#5340 UI: 去除业务拓扑服务实例表格的行吸顶效果, 修复缺陷
  src/ui/package.json
  src/ui/src/views/audit/index.vue
  src/ui/src/views/business-topology/children/node-extra-info-set-template.vue
  src/ui/src/views/business-topology/service-instance/instance/list.vue
  src/ui/src/views/dynamic-group/preview/preview.vue
  src/ui/src/views/service-template/children/operational.vue
Labels: bug, inner

#5342 fix: new instance api auth parser
  src/ac/parser/topolatest.go
Labels: bug

#5345 UI: 修复操作审计详情未显示业务自定义字段的问题
  src/ui/src/components/audit-history/details-table.vue
  src/ui/src/mixins/edit-multiple-host.js
Labels: inner

#5348 refactor: change ObjectBase mapping table index
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/upgrader/y3.10.202104221702/mapping.go
  src/scene_server/admin_server/upgrader/y3.10.202104221702/split_inst_table.go
Labels: inner, optimization

#5353 Fix instance api about new limits policies
  src/common/metadata/common.go
  src/common/metadata/page.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst.go
  src/test/topo_server/asst_test.go
  src/test/topo_server/inst_test.go
Labels: optimization

#5354 feature: import/export not invalid
  src/scene_server/topo_server/service/inst.go
  src/web_server/logics/association.go
  src/web_server/logics/excel.go
  src/web_server/logics/excel_util.go
Labels: inner, optimization

#5355 fix: instance association object limit
  src/scene_server/topo_server/core/operation/association.go
Labels: optimization

#5359 导入模型属性的时候提示未知错误
  src/scene_server/proc_server/service/serviceinstance.go
  src/scene_server/topo_server/service/object.go
Labels: bug, inner

#5315 fix: change instance association relation by excel import not effect …
  src/ac/parser/topolatest.go
  src/common/metadata/association.go
  src/common/metadata/webserver.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/import_association.go
  src/web_server/logics/excel.go
Labels: bug, in progress, inner

#5382 feature 添加批量创建通用模型实例接口以及批量创建模型实例关联关系接口
  resources/errors/common/default/common.json
  resources/errors/english/en/common.json
  src/ac/parser/topolatest.go
  src/apimachinery/coreservice/association/api.go
  src/apimachinery/coreservice/association/association.go
  src/apimachinery/toposerver/association/apis.go
  src/apimachinery/toposerver/association/association.go
  src/apimachinery/toposerver/inst/api.go
  src/apimachinery/toposerver/inst/inst.go
  src/common/errInfo.go
  src/common/metadata/association.go
  src/common/metadata/inst.go
  src/scene_server/host_server/service/cloudarea.go
  src/scene_server/topo_server/core/operation/association.go
  src/scene_server/topo_server/core/operation/inst.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/inst.go
  src/scene_server/topo_server/service/service_business_initfunc.go
  src/source_controller/coreservice/core/association/instance.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/service/instances.go
  src/test/topo_server/asst_test.go
  src/test/topo_server/inst_test.go
Labels: demand

#5407 style: add log issue #5223
  src/scene_server/admin_server/logics/index.go
Labels: inner, optimization

#5410 refactor: doc monstache
  docs/overview/installation.md
Labels: inner, optimization

#5412 更新服务实例，主机和拓扑关系表的的索引
  src/scene_server/admin_server/imports.go
  src/scene_server/admin_server/service/migrate.go
  src/scene_server/admin_server/upgrader/y3.9.202106291420/index.go
  src/scene_server/admin_server/upgrader/y3.9.202106291420/pkg.go
Labels: inner, optimization
