Repository Tencent/bk-cmdb, pull requests merged in 2021-03, with the labels that each got.

#5075 删除多余的条件
  src/scene_server/host_server/service/module.go
Labels: inner, optimization

#5068 UI: bugfix
  src/ui/src/components/ui/dialog/leave-confirm.vue
  src/ui/src/views/history/index.vue
  src/ui/src/views/host-details/children/property.vue
Labels: bug

#5125 feature: add instance objectID mapping handle issue #5085
  src/storage/driver/mongodb/instancemapping/inst_mapping.go
Labels: demand, inner

#5143 docs: update monstache doc issue #5085
  docs/overview/installation.md
Labels: demand, inner

#5150 V3.9.x feature instasst migrate
  src/apimachinery/coreservice/model/api.go
  src/apimachinery/coreservice/model/model.go
  src/common/index/instance.go
  src/common/metadata/core_service.go
  src/scene_server/admin_server/logics/index.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/object.go
  src/source_controller/coreservice/core/core.go
  src/source_controller/coreservice/core/model/model.go
  src/source_controller/coreservice/core/model/model_tables.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/source_controller/coreservice/service/model.go
  src/source_controller/coreservice/service/service_initfunc.go
  src/storage/dal/types/types.go
  src/test/test.go
Labels: demand, inner

#5158 V3.9.x feature instasst migrate
  src/common/index/collections/applicationbase.go
  src/common/index/instance.go
  src/common/metadata/core_service.go
  src/scene_server/admin_server/upgrader/y3.9.202103241156/inner_object_index.go
  src/scene_server/admin_server/upgrader/y3.9.202103241156/mapping.go
  src/scene_server/admin_server/upgrader/y3.9.202103241156/split_inst_table.go
  src/scene_server/topo_server/core/operation/object.go
  src/scene_server/topo_server/service/association.go
  src/scene_server/topo_server/service/object.go
  src/source_controller/coreservice/core/instances/instance.go
  src/source_controller/coreservice/core/instances/instance_crud.go
  src/source_controller/coreservice/core/model/attribute_curd.go
  src/source_controller/coreservice/core/model/model_crud.go
  src/source_controller/coreservice/core/model/model_tables.go
  src/source_controller/coreservice/core/model/unique_crud.go
  src/test/topo_server/resource_dir_test.go
Labels: bug, inner
