Repository Tencent/bk-cmdb, pull requests merged in 2021-05, with the labels that each got.

#5219 [typo] 单词拼写错误, looked, 应为locked
  src/common/lock/lock.go
  src/source_controller/coreservice/core/model/attribute.go
  src/source_controller/coreservice/core/model/model.go
Labels: demand, outer

#5230 use `url.QueryEscape` to escape some special characters; fix misspel…
  src/storage/dal/mongo/config.go
  src/storage/dal/mongo/local/mongo_test.go
Labels: optimization, outer

#5239 fix: 修服务集群模板实例展示问题
  src/apimachinery/rest/request.go
  src/scene_server/topo_server/core/settemplate/settemplate.go
  src/scene_server/topo_server/core/settemplate/sync_status.go
  src/scene_server/topo_server/service/set_template.go
Labels: bug, inner

#5281 feature: style code issue #5085
  src/scene_server/admin_server/upgrader/history/x18.12.12.05/remove_deleted_inst_asst.go
  src/scene_server/admin_server/upgrader/y3.10.202104221702/pkg.go
  src/scene_server/admin_server/upgrader/y3.9.202010281615/update_inst_time_val.go
  src/scene_server/admin_server/upgrader/y3.9.202011172152/remove_field.go
  src/test/host_server/host_ip_array_test.go
Labels: inner, optimization
